### ISSUE TITLE
Emory Login Service Request(Shibboleth): Implementation 

### ISSUE THREAD

**Issue by tmiles2** [emory-libraries/blacklight-catalog#10]
> Acceptance Criteria: _Fill in by Product Owner_. 

> Tasks: _Fill in by Middleware_.

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/blacklight-catalog/pull/36

No screenshots necessary.

**Comment by bwatson78** [comment]
@mprefer got the environment working and helped me to identify an error in my code. Have pulled this back into "In Progress" and will focus on this tomorrow (11/24/2020).

**Comment by bwatson78** [comment]
@bwatson78 New PR made: https://github.com/emory-libraries/blacklight-catalog/pull/54

Corrects the omission of needed columns for `:trackable` for Devise.

**Comment by bwatson78** [comment]
After deploy, the login is successful, but there is no OmniAuth user information being passed through (including `uid`). At the moment, all users who attempt to login will go to the same account (`User.where(uid: nil)`).

**Comment by tmiles2** [comment]
Emory Login request form: [https://emory.app.box.com/file/710176312172](url) @mprefer 

Service Request INC03495097 @bwatson78

**Comment by bwatson78** [comment]
[ ] Contact Gerry about lack of user metadata through ServiceNow.
[ ] Receive communication from Gerry about the issue.
[ ] Post here the ETA for the issue to be resolved.

**Comment by bwatson78** [comment]
Confirmed that Gerry has completed his requirements. Have worked with @SolomonHD to get the attributes mapped to the info hash and that works. Am now seeing an error tied to `ActionView::Template::Error (undefined local variable or method `edit_user_registration_path' for #<#<Class:0x000000000632a2c0>:0x0000000006ea8a48>)` that I will access and correct.

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/blacklight-catalog/pull/71

**Comment by tmiles2** [comment]
@lovinscari Can you test and close out this issue? The behavior is modeled after Lux, so your name should appear and the only option for the user is to logout matches Lux.

**Comment by lovinscari** [comment]
I was able to successfully login using Shibboleth account.
