### ISSUE TITLE
SPIKE: Ensure Romanization Search - Diacritics is working

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#100]
As an end user, I want the ability to search certain words that have variant forms based on the presence or absence of diacritics including words with and without umlauts in German, so that it searches all forms of the word. So I get all results without having to know about the variants and search each variant. Because it is unclear how this works in Solr and Blacklight, this ticket will be to examine how it works and determine if any customizations are needed. 

User Acceptance Criteria and Examples - 

- [ ] It is assumed Field 15 from the Metadata Model [https://docs.google.com/spreadsheets/d/1jSqgNd6HnVJdJMrrShAofkmK8uGgHGdlKODmZOL5NfY/edit?usp=sharing](url) is linked to Field 14 when conducting a rominization search

- [ ] search terms "anfänge" or "anfange" or "anfaenge" -- (German) anfänge means "beginnings". anfange is not a different word but could appear without the umlaut in records. anfaenge is another way of spelling the umlauted form. (The 2 dots diacritic in German represents an umlaut which is a vowel shift in a word.)

Advanced search: Title contains: anfange Subject contains: Jews
Advanced search: Title contains: anfänge Subject contains: Jews
Same Results: 11 records

MMSID: 990012571310302486 Beiträge zur Zeitgeschichte der Anfänge Israels : dokumente, materialien, notizen -- has umlaut
MMS ID: 990019351240302486 Alphabetische Liste aller gelehrten Juden und Jüdinnen, Patriarchen, Propheten und berühmten Rabbinen vom Anfange der Welt bis auf unsere Zeiten, nebst einer kurzen Beschreibung ihres Lebens und ihrer Werke -- no umlaut

**Comment by lovinscari** [comment]
@laura-ake Can you provide examples as identified in the body of the issue?

**Comment by laura-ake** [comment]
search terms "anfänge" or "anfange" or "anfaenge" --   (German)  anfänge means "beginnings".  anfange is not a different word but could appear without the umlaut in records.  anfaenge is another way of spelling the umlauted form.  

I can write a book about the enhancement request we had that Ex Libris could not fulfill - to have words like anfaenge in German also retrieve the umlauted form.  Perhaps "didyoumean" could help... 

Took some digging to find this example:

Advanced search:  Title contains: anfange    Subject contains: Jews
Advanced search:  Title contains: anfänge    Subject  contains: Jews
Same Results:  11 records
MMSID: 990012571310302486  Beiträge zur Zeitgeschichte der Anfänge Israels : dokumente, materialien, notizen -- has umlaut
MMS ID: 990019351240302486  Alphabetische Liste aller gelehrten Juden und Jüdinnen, Patriarchen, Propheten und berühmten Rabbinen vom Anfange der Welt bis auf unsere Zeiten, nebst einer kurzen Beschreibung ihres Lebens und ihrer Werke  -- no umlaut (probably an input mistake since other umlauts are present, but leave it be!).

More examples to follow.

**Comment by bwatson78** [comment]
This is blocked until we can clear Solr and ingest the production OAI set, which contains these expected records.

**Comment by bwatson78** [comment]
Test on Production Data in the Test Environment:

- `anfange` under the Title option: 757 items

![Screen Shot 2021-02-22 at 2.59.07 PM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/202bd401-bcdd-4723-9cf7-f835ed532d42)

![Screen Shot 2021-02-22 at 3.09.54 PM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/17ce40a6-a008-45be-8128-e8ecb4f43740)

- `anfänge` under the Title option: 757 items

![Screen Shot 2021-02-22 at 3.12.37 PM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/432a9ad4-2887-4e41-bebf-35e3779e4a37)

![Screen Shot 2021-02-22 at 3.15.24 PM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/62d1f109-bffd-48c6-a94c-458e6b078c2c)

- `anfaenge` under the Title option: 2 items

![Screen Shot 2021-02-22 at 3.16.47 PM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/4d07c99c-adff-4dff-a6be-37b8210b1159)

**Comment by laura-ake** [comment]
Hi Brad, I did some poking around:

Search on
Blackcat-test results count
Includes
Primo Production count
Includes
anfange
452
anfänge, anfange
861
anfange, anfänge
anfänge
453
anfange, anfänge
857
anfänge, anfange
anfaenge
2
Anfaenge only
2







Odd that Primo results are so much larger.  I guessed they padded out results to things including “anfang” (singular, like, stemming) but I haven’t caught an example.  However...

Found one example search in Primo where there are 4 results in Primo, but only one (different one) in BL test:  Schillers anfange .  Was looking for Schillers Werke in zwei Bänden 9936508508702486.   It’s in BL test.  Word anfange is in the 505 Contents note – maybe that’s not keyword indexed yet?  Any other insights?

Both places:
Most anfange results had an umlaut
An un-umlauted anfange word I found in the anfänge results:  990009891230302486 (assumed from searching Johann Adam Hensels anfänge )

The 2 anfaenge results in blackcat-test:

[cid:image003.jpg@01D70946.2F54DB50]

Searched Die anfange der Literaturtheorie bei den Serben  Got zero results
Searched Die anfänge der Literaturtheorie bei den Serben  Got zero results

Next trick, could we get those searches to capture the diphthong version...  (I was told Primo can’t handle more than 2).  Maybe Phase 2?  Would make the Theology Library director happy.

I also searched a few more words with and without diacritics with good results, and was able to find 990008691710302486 with search on “thidriks saga” so multi-indexing of diacritics and special chars. seems to be coming nicely.
(DidYouMean is weird.  Infants?)

Hope this helps.  Let me know if you have questions.

Laura

**Comment by eporter23** [comment]
Discussed in standup 2/23/21: we can accommodate the same characters with or without diacritics ("anfänge" = "anfange"), but transliterations that change the spelling of a word ("anfaenge") are not necessarily feasible in this phase.

**Comment by eporter23** [comment]
Additional comments from @mark-dce: 

> Re: Ticket 100 - Romanization - we should be able to accommodate diacritic matching relatively easily - i.e. 'a' == 'ä',  we will not be able to accommodate transliteration without a significant amount of effort - i.e. 'a' == 'ae' (and this needs to be configured and tested per language basis)

**Comment by eporter23** [comment]
@lovinscari I think from what has been identified, we can close this and incorporate findings into search tips/help. As noted above, transliteration support won't be feasible without addressing support for multiple languages.

**Comment by rotated8** [comment]
I think there's a little more nuance than that. Solr appears to use the [ICU Folding filter](https://lucene.apache.org/solr/guide/7_7/filter-descriptions.html#icu-folding-filter) for both [text](https://github.com/emory-libraries/blacklight-catalog/blob/main/solr/conf/schema.xml#L284) and [english-text](https://github.com/emory-libraries/blacklight-catalog/blob/main/solr/conf/schema.xml#L310) fields. The filter should do Unicode [NFKC normalization](https://unicode.org/reports/tr15/) and [folding](https://www.unicode.org/reports/tr30/tr30-4.html) (including case folding and diacritic removal). We can see the diacritic removal working in this ticket. Normalization and folding should take care of some transliteration (like ligatures and equivalent letterforms), but language specific transliteration is beyond the pale.

**Comment by lovinscari** [comment]
I am going to accept this based on our conversations but also expect we will need to address some customizations with this once functional testing begins.
