### ISSUE TITLE
Review/refine hover behavior in certain items appearing in Services Page

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#1006]
Doug Goans reported strange hover behavior with the following record

https://emory.primo.exlibrisgroup.com/discovery/openurl?institution=01GALI_EMORY&vid=01GALI_EMORY:services&rft.mms_id=990027482770302486&loginId=13311193710002486_o4soRG99kFkKfF2

In reviewing the record, Collin found different formatting with the table of this record. We are not sure if this is specific to the record or bound with's or multiple holdings of an item. 

- [ ] Research what is happening with this record and determine if a change is needed within the CSS

- [ ] Implement the changes to the CSS for Primo VE

**Comment by CB987** [comment]
tooltips appearing on the items locations list:
![Screen Shot 2021-11-03 at 2.12.21 PM.png](https://images.zenhubusercontent.com/5d379c9d5221e52414fca85c/358c3261-89d0-4320-bdda-b60206d898b8)
![Screen Shot 2021-11-03 at 2.12.26 PM.png](https://images.zenhubusercontent.com/5d379c9d5221e52414fca85c/f8423c61-74fa-495c-a421-8a1eb30add43)
![Screen Shot 2021-11-03 at 2.12.30 PM.png](https://images.zenhubusercontent.com/5d379c9d5221e52414fca85c/261b5e4b-3093-4d30-b113-b388fd1a1c4a)

**Comment by lovinscari** [comment]
This cannot be fixed with CSS. Closing for now.
