### ISSUE TITLE
TASK: continuing ExL views style fixes

### ISSUE THREAD

**Issue by CB987** [emory-libraries/blacklight-catalog#1007]

**Comment by CB987** [comment]
exl23 ready for testing:
![Screen Shot 2021-11-03 at 11.23.34 AM.png](https://images.zenhubusercontent.com/5d379c9d5221e52414fca85c/031e53a0-45fa-40de-81d9-615378b4c329)
exl25  ready for testing:
![Screen Shot 2021-11-03 at 11.31.50 AM.png](https://images.zenhubusercontent.com/5d379c9d5221e52414fca85c/c1d72378-7025-45fb-a35d-1e8d3096fc4b)

**Comment by CB987** [comment]
continuing work on [exl28](https://docs.google.com/document/d/1XZLBPYxfDtHiiamdN5hA4iinskDKrxUi9hP2JZzUgMI/edit?usp=sharing):
fixed most hover styles on services to be dark blue text on light blue. now moving those styles to articles view. 
![Screen Shot 2021-11-16 at 9.20.28 PM.png](https://images.zenhubusercontent.com/5d379c9d5221e52414fca85c/c25ca333-97dc-47a0-8d14-e79519e0d75b)
![Screen Shot 2021-11-18 at 7.22.26 AM.png](https://images.zenhubusercontent.com/5d379c9d5221e52414fca85c/860a89c8-f1e4-415c-8850-03f616267c15)

**Comment by lovinscari** [comment]
@CB987 - This looks good. I am moving this to To Deploy to Prod as perhaps we should deploy Primo VE changes to sandbox as we incorporate into production first?
