### ISSUE TITLE
SPIKE: Determine if Services Page View and Articles + View pages can navigate back to search results

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#1015]
Feedback from the last User Acceptance Test indicates some confusion with the expected behavior when selecting "Return to Library Search" link from the top of the pages 
![ExLibris_ReturntoLibSearchNav.jpg](https://images.zenhubusercontent.com/5c4a1fe1e9b5fb46bcedb9fc/e1c86051-f509-4a07-b87d-a957cab9746c)

When meeting with Emily and Clare this morning to discuss possibly changing the wording of the link "Return to Library Search" we decided we should first determine if any improvements can be made with the functionality. Specifically, I would like to know the link from the ExLibris page views can be modified to return the user to the page they were at before navigating to the ExLibris page (Services Page or Articles+).

For example, if I performed a search on Pizza and was viewing the search results and selected the Locate/Request option with one of the items in search results, I would be directed to the Services Page view for that item. If I selected Return to Library Search, I would like to be returned to my search results for Pizza. 

Findings of the research, including estimate of the work involved to implement, should be documented within this ticket.

**Comment by alexBLR** [comment]
Here is the process of making it happen:

**In PrimoVE** we need to add an id="return-to-blackcat" to the anchor tag:
<div id="emory-util-nav"><a href="https://search.libraries.emory.edu" **id="return-to-blackcat"** class="md-primoExplore-theme">← Return to Library Search</a></div>

After adding an id we need to pass a url parameter with javascript to the href of the anchor tag.
<script>
const qString = window.location.search;
const urlParams = new URLSearchParams(qString);
const newUrl = urlParams.get('url')
var changeTarget = document.getElementById('return-to-blackcat');
var _href = changeTarget.href;
if(newUrl){
changeTarget.href = newUrl;
}else{
changeTarget.href = _href;
}
</script>

In **blacklight application**: we need to a similar thing with javascript

<script>
const fullPath = window.location.href;
var changeTarget = document.getElementById('articles-plus-url');
var _href = changeTarget.href;
var newUrl = '&url=' + fullPath
if(newUrl){
changeTarget.href =  _href + newUrl;
}else{
changeTarget.href = _href;
}
</script>
