### ISSUE TITLE
Preliminary Item Level Display

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#102]
_As an end user, I want to preview information about a individual resource selected from search results query, so that I can determine if that is the item I would like to request or access online_

Scope Notes:

- These requirements are still in review for final approval, so iterations may be needed.
- Additional tickets will specify additional preview components beyond the metadata fields.

Metadata fields to display in the item level display include the following. As a general display and spacing pattern:
- Prefix each output with the label (in bold); some are further grouped under a heading. 
- Add a space after each MARC tag. 
- Add a space after each indicator if displayed.
- Separate multiple subfields with spaces.

From [Laura's document which includes additional details](https://app.zenhub.com/files/295449627/3e475c7e-40ce-4087-8fe8-731286465472/download), 
"_ _" (underscore) means any accompanying indicator value is okay to display.
$ means subfields

**Title:**  `245 _ _ $a, $b, $f, $g, $n, $p, $s  `

**Author/Creator:** `100 _ _ $a, $b, $c, $d, $e, $j, $q, $u` [note: Laura provided 3 options, not sure how many we need?]

**Publisher:** 
`264 _ _ $b `
`260 _ _ $b`
`260 _ _ $f `

**Creation Date:** `008`  [see additional notes below]

**Language:** ` 008` [bytes 35-37; this outputs a coded value. to discuss: transform this to the label as a later ticket?]  

**ISBN:** `020 _ _ $a`

**ISSN:** `022 _ _ $a`  

**Call Number:** `090` or `050` (depending on what is mapped)

**MMS ID:** `001`

**Summary:** `520 _ _ $a, $b  `

**Table of Contents**: `505 _ _  $a,  $g, $ t, $r  `

**Access**: `marc_resource` [SOLR field] (for initial testing purposes - indicates if an item is Electronic or Physical: see comments in ticket #87)

Laura's notes for dates:
note that fixed field starts with byte 0
Take Date1 bytes 7-10, separate by / or dash or spaces or something, then take Date2 bytes 11-14.   EXCEPT:
Take nothing (leave blank) if either Date1 or Date2 is 0000, #### (blanks), //// (fill characters), 9999,  or uuuu.   

Deferred after discussion:
Headings/groupings of related fields: **Identifiers** (heading only for multiple fields); **Description** (heading only for multiple fields)
Field groupings and headings will added later as requirements are finalized.

**Comment by lovinscari** [comment]
@laura-ake - Do you think you can provide high level Marc mappings for the fields identified above?

**Comment by laura-ake** [comment]
@lovinscari I will focus on getting these mappings first (this afternoon) and then look at other ticket requests.  This may also be useful for  #87

**Comment by laura-ake** [comment]
[https://app.zenhub.com/files/295449627/f16d9504-bc3d-445e-b50c-b5980a5e7a93/download](https://app.zenhub.com/files/295449627/f16d9504-bc3d-445e-b50c-b5980a5e7a93/download)

**Comment by eporter23** [comment]
Discussed in sprint planning - not focusing on filling in missing mappings if they are not yet present, but identifying them if there are gaps.

**Comment by eporter23** [comment]
Related to work that @bwatson78 did in ticket #87, we proposed adding a temporary display field for "Access" both in the search results and item detail views that indicate if an item is physical or electronic, to help with testing other work in progress.

**Comment by bwatson78** [comment]
@eporter23 Not mapped at the moment:

- Publisher (discussed in #87)
- ISSN
- Call Number (there is a mapping called `lc_callnum_display` that points to subfield tagged `050ab`, not `090`)
- Summary
- Table of Contents

Please advise whether mapping these requested fields are a requirement for this ticket.

**Comment by eporter23** [comment]
@bwatson78 yes, please use whatever is already mapped for `lc_callnum_display`.

**Comment by bwatson78** [comment]
Will do.

**Comment by eporter23** [comment]
Discussed with @bwatson78 that the headings for Identifiers and Description will be added later as this involves overriding default Blacklight behavior (better addressed once requirements finalized).

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/blacklight-catalog/pull/112

![Screen Shot 2020-12-21 at 10.18.20 AM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/a84882d3-714a-44b3-8031-763027bc7250)

![Screen Shot 2020-12-21 at 10.19.23 AM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/5a2c2168-aa72-47d7-b342-1917bad127c3)

**Comment by bwatson78** [comment]
Arch site is live again and above changes are evident. @mprefer believes the schema was going into the wrong directory and has decided to script the procedure to update the the schema so that it works correctly every time.

Note: `Access:` will not be populate on any record until we reingest with the changed mappings.
