### ISSUE TITLE
Add hyperlinked search option for (Primary) Author in Single Item View

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/blacklight-catalog#1020]
Based on user feedback, we should consider adding a hyperlinked search option to let users find more items for an author, once a user has navigated to a record matching the author they are looking for.

We provide this functionality for additional (non-primary) authors already, but the hyperlinked search option was not originally requested for the Primary Author field in the brief display of the Single Item View, so we haven't implemented it yet. See prior work in #314 and #385.

Example for William Butler Yeats:

Add a hyperlink to the Author/Creator field value that runs a faceted search matching on that author:
![Screen Shot 2021-10-28 at 4.55.11 PM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/78f3a652-272f-4bdd-8d4a-b86e848e0dce)

![Screen Shot 2021-10-28 at 4.55.26 PM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/dd807ca3-d8a2-47db-adea-c72422200b61)!

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/blacklight-catalog/pull/1046

![Screen Shot 2021-11-15 at 11.30.36 AM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/aaffeca7-bc70-4844-bacd-49e7bf2098b1)
![Screen Shot 2021-11-15 at 11.31.03 AM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/a2f0d5ad-3d4c-49da-992d-c42b9f920c0f)

**Comment by eporter23** [comment]
Looks good! I think by showing this in the search results also that helps with author searching.

**Comment by lovinscari** [comment]
Looks great!
