### ISSUE TITLE
SPIKE - Review possible revisions to full item display in Articles Plus 

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#1021]
Jenny Vitti is reporting the full item displays for items in Articles Plus does not include certain information used as part of ILL workflows. Specifically, page is lacking the identifiers (ISSN, DOI, PMID). Jenny's full report is included below including links from Articles Plus and the comparison record in discovereE.

Within this ticket, please provide information on the following:

- [x] Is it possible to refine the single item view in Articles Plus to include  identifiers (ISSN, DOI, PMID).

- [x] If it is possible, how much effort (time) is involved with making the change. 

Depending on the information provided, I might seek input from SEND Team on other changes needed with the display.

Feedback from Jenny Vitti - 
What is the page you want to tell us about?: 
Articles+: https://emory-psb.primo.exlibrisgroup.com/permalink/01GALI_EMORY/1da8jbm/cdi_scopus_primary_28036088

What do we need to know?: 
This page is lacking the identifiers (ISSN, DOI, PMID). See the corresponding page in Primo: http://discovere.emory.edu/discovere:Combined:TN_cdi_scopus_primary_28036088. I currently use the Combined Search in discoverE for every article request I receive in ILLiad that's lacking an ISSN -- I quickly grab the ISSN/DOI/PMID and insert it/them into ILLiad to help with automation and statistical tracking (Chris Palazzolo & the SLs use the statistical data to make collection decisions, and the ILL team uses it for copyright tracking and payments). I start in discoverE/Articles+ rather than Google Scholar/Google because that lets me see quickly if Emory already has access in print or online, in case I can get the article to the user more quickly than a traditional ILL request. (By the way, aside from the missing identifiers, the layout and usability of the Articles+ page is SO MUCH EASIER TO USE than the Combined Search results in discoverE. Thank you!)

**Comment by libah** [comment]
It is possible to add the identifiers to the record display in Articles +. You can see it in the sandbox now. https://emory-psb.primo.exlibrisgroup.com/permalink/01GALI_EMORY/1da8jbm/cdi_swepub_primary_oai_gup_ub_gu_se_252662

It will take about 1 hour to add to production.

**Comment by libah** [comment]
Added the identifiers to the production instance of Articles+
