### ISSUE TITLE
Bug: Blacklight retains application name in Rails cache.

### ISSUE THREAD

**Issue by bwatson78** [emory-libraries/blacklight-catalog#1023]
PR made: https://github.com/emory-libraries/blacklight-catalog/pull/1022

**Comment by bwatson78** [comment]
Closed the above PR, because I just needed to run `Rails.cache.delete('blacklight/application_name')` from Rails console.

**Comment by lovinscari** [comment]
@bwatson78 - Not sure there is anything for me to accept? Go ahead and move to To Deploy to Prod if applicable.
