### ISSUE TITLE
TASK BL item #16 alignment of facet headings and page title on homepagealignment of facet headings and page title on homepage

### ISSUE THREAD

**Issue by CB987** [emory-libraries/blacklight-catalog#1024]

**Comment by CB987** [comment]
![Screen Shot 2021-11-02 at 12.00.04 PM.png](https://images.zenhubusercontent.com/5d379c9d5221e52414fca85c/97b3a22e-ac94-431e-80f6-7edf0eed5663)

**Comment by lovinscari** [comment]
Looks good @CB987
