### ISSUE TITLE
Confirm search parsers used in different search modes, and use of wildcards

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/blacklight-catalog#1027]
Following up on prior documentation (#789) and the presentation to the SEND team, team members have identified some behavior that indicates wildcard support may be enabled in Basic Search.

In initial investigations and looking at logs, we also see references to edismax from Basic Search which we previously thought was using dismax

In order to accurately document search modifiers for end users, we need to re-confirm which query parsers are used for:

- [x] Basic Search (Keyword, Title, Author, Subject) - edismax
- [x] eJournals Search - edismax
- [x] Advanced Search - edismax, with a fallback to lucene

**Comment by bwatson78** [comment]
After an impromptu meeting between Emily, Collin and I, we have come to the conclusion that all three scopes of searches are using the eDisMax parser. There was some confusion about Advanced and eJournals because the blacklight_advanced_search gem adds parameters like `{!edismax+qf%3Dtitle_main_display_ssim+pf%3D}walden"&defType=lucene` to its queries. After some researching and discussion, we have interpreted that parameter to be a protective clause that operates only when older Solr versions are utilized (those that cannot process eDisMax queries stably using the gems parsed queries).

By default, per our `solr/conf/solrconfig.xml` file, eDisMax is the parser that is used in all of our searches. Basic Search queries carry the explicit defining of the parser in each of its queries (taken from my local environment's traceback):
```
Solr query: get select {"qt"=>nil, "facet.field"=>["title_main_first_char_ssim", "marc_resource_ssim", "library_ssim", "format_ssim", "language_ssim", "pub_date_isim", "author_ssim", "subject_ssim", "collection_ssim", "lc_1letter_ssim", "subject_geo_ssim", "subject_era_ssim", "genre_ssim"], "facet.query"=>[], "facet.pivot"=>[], "fq"=>[], "hl.fl"=>[], "rows"=>10, "qf"=>"subject_tesim", "pf"=>"", "q"=>"Bob", "facet"=>true, "f.title_main_first_char_ssim.facet.limit"=>6, "f.marc_resource_ssim.facet.limit"=>6, "f.library_ssim.facet.limit"=>26, "f.format_ssim.facet.limit"=>26, "f.language_ssim.facet.limit"=>6, "f.author_ssim.facet.limit"=>6, "f.subject_ssim.facet.limit"=>6, "f.collection_ssim.facet.limit"=>6, "f.lc_1letter_ssim.facet.limit"=>6, "f.subject_geo_ssim.facet.limit"=>6, "f.subject_era_ssim.facet.limit"=>6, "f.genre_ssim.facet.limit"=>6, "sort"=>"score desc, pub_date_isim desc, title_si asc", "stats"=>"true", "stats.field"=>["pub_date_isim"], "defType"=>"edismax"}
```
Advanced (and, by extension, eJournals, since it's scoped to the advanced search path) outputs a different search query that seemingly calls the `lucene` search type (which would also support wildcards and boolean):
```
Solr query: get select {"qt"=>nil, "facet.field"=>["title_main_first_char_ssim", "marc_resource_ssim", "library_ssim", "format_ssim", "language_ssim", "pub_date_isim", "author_ssim", "subject_ssim", "collection_ssim", "lc_1letter_ssim", "subject_geo_ssim", "subject_era_ssim", "genre_ssim"], "facet.query"=>[], "facet.pivot"=>[], "fq"=>["marc_resource_ssim:(\"Online\")", "format_ssim:(\"Journal, Newspaper or Serial\")"], "hl.fl"=>[], "rows"=>10, "facet"=>true, "f.title_main_first_char_ssim.facet.limit"=>6, "f.marc_resource_ssim.facet.limit"=>6, "f.library_ssim.facet.limit"=>26, "f.format_ssim.facet.limit"=>26, "f.language_ssim.facet.limit"=>6, "f.author_ssim.facet.limit"=>6, "f.subject_ssim.facet.limit"=>6, "f.collection_ssim.facet.limit"=>6, "f.lc_1letter_ssim.facet.limit"=>6, "f.subject_geo_ssim.facet.limit"=>6, "f.subject_era_ssim.facet.limit"=>6, "f.genre_ssim.facet.limit"=>6, "sort"=>"score desc, pub_date_isim desc, title_si asc", "stats"=>"true", "stats.field"=>["pub_date_isim"], "q"=>"_query_:\"{!edismax qf=title_precise_tesim pf=}Journal\"", "defType"=>"lucene"}
```

**Comment by eporter23** [comment]
@bwatson78 @rotated8 do either of you know which English language stemmer we are currently using in SOLR (or how we can find out)? Trying to get some more detail for SEND team questions.

**Comment by bwatson78** [comment]
From our schema: 
```
<!-- A text field with defaults appropriate for English -->
    <fieldType name="text_en" class="solr.TextField" positionIncrementGap="100">
      <analyzer>
        <tokenizer class="solr.ICUTokenizerFactory"/>
        <filter class="solr.ICUFoldingFilterFactory"/>  <!-- NFKC, case folding, diacritics removed -->
        <filter class="solr.EnglishPossessiveFilterFactory"/>
        <!-- EnglishMinimalStemFilterFactory is less aggressive than PorterStemFilterFactory: -->
        <filter class="solr.EnglishMinimalStemFilterFactory"/>
        <!--
        <filter class="solr.PorterStemFilterFactory"/>
        -->
        <filter class="solr.TrimFilterFactory"/>
      </analyzer>
    </fieldType>
    ```

this applies to all all of our `*_te*` fields.

**Comment by bwatson78** [comment]
In short: `solr.EnglishMinimalStemFilterFactory`

**Comment by lovinscari** [comment]
@eporter23 - Please review and accept if meeting your approval by moving to To Deploy to Prod. Thanks!

**Comment by eporter23** [comment]
@lovinscari I think we can close this, it was mainly research and documentation which has been updated and shared with the SEND team this week.
