### ISSUE TITLE
Add the word "journals" to home page of Library Search

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#1029]
SEND Team members indicate we should include the word "journals" in our description of Library Search. Please update text above search box on home page to read, 

"Search books, eBooks, journals, videos and more" with the difference being adding the word "journals" after eBooks.

**Comment by bwatson78** [comment]
Work for this in PR https://github.com/emory-libraries/blacklight-catalog/pull/1030

**Comment by eporter23** [comment]
Looks good to me.

**Comment by lovinscari** [comment]
Looks good to me.
