### ISSUE TITLE
Adjust direct link feature to resolve to the right environment/domain

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/blacklight-catalog#1032]
As reported from a user, when using the Direct Link option for a record in the production search.libraries.emory.edu domain, the URL generated points to our old base domain name of https://blackcat.library.emory.edu/catalog/

Current behavior:

![Screen Shot 2021-11-08 at 9.16.24 AM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/e697072d-d938-49ca-bf02-16c6b69f2ad3)

Desired behavior:

- [x] Production direct links point to https://search.libraries.emory.edu/catalog/ + MMSID
- [x] Test environment direct links point to https://blackcat-test.library.emory.edu/catalog/ + MMSID
- [x] Arch environment direct links point to https://blackcat-arch.library.emory.edu/catalog/ + MMSID

**Comment by eporter23** [comment]
@lovinscari I saw this in the feedback and thought it'd be good to fix, especially if people start creating direct links soon.

**Comment by bwatson78** [comment]
All that's required for this fix is to update the `ENV['BLACKLIGHT_BASE_URL']` variable and redeploy.

**Comment by lovinscari** [comment]
Thanks @eporter23 for putting this in and for the team for turning this around so quickly. Looks good.
