### ISSUE TITLE
Add and boost Precise Title field within Basic > Title search

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/blacklight-catalog#1035]
Add and boost the Precise Title field (245 ab) for known-item Title searches in our Basic Search by Title option. 

- [x] Add title_precise_tesim to the Basic Search > Title set
- [x] Boost the relevancy scoring of this field over the Title search fields

To discuss: what boost multiplier should we assign?

**Comment by lovinscari** [comment]
Boost precise title to a 5.

**Comment by bwatson78** [comment]
PR: https://github.com/emory-libraries/blacklight-catalog/pull/1053

**Comment by eporter23** [comment]
Very interesting - see [testing notes here](https://docs.google.com/document/d/1Rh98bQJmii1bi1VeajkBTvphPI8gUB5nFTkzkh7TTpU/edit?usp=sharing)

**Comment by lovinscari** [comment]
I will work with @eporter23 to see how we can add this to UAT #4 and have SEND Team test. I have a few concerns based on Emily's testing but will refrain from making any changes until after SEND Team tests and provides feedback.

**Comment by eporter23** [comment]
@bwatson78 can you confirm if title_precise_tesim is actually being boosted within Basic Search > Title search? @lovinscari and I were responding to an example sent by a SEND Team member and it isn't behaving as expected.

**Comment by eporter23** [comment]
@lovinscari I confirmed with @bwatson78 that Precise Title is boosted x5 within the Title set. It is boosted x100 in the Keyword set, however, so we may want to review.
