### ISSUE TITLE
Look at other possible modifications to improve performance of the home page load times

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#1037]
Some previous attempts were made to improve performance of the application load time based on suggestions and outcomes from [Ticket 931](https://app.zenhub.com/workspaces/blacklight-catalog-5f5f84a8a6d29939a0bc5d78/issues/emory-libraries/blacklight-catalog/931) and another ticket I am not finding where @bwatson78 provided a report that showed how long it takes to load the various components on the page and where we could possibly make improvements. Because I have not had time to further investigate this and make suggestions, @rotated8 has suggested and turn this back over to the application development team who has some ideas. Needless to say, we are getting feedback from stakeholders that suggests we need to improve the load time of the home page. I would like to suggest we look at improving to a load time of 3 seconds if possible.

**Comment by abelemlih** [comment]
@lovinscari some promising results regarding performance of the Blacklight catalog. After upgrading the Ruby version from 2.5.7 to 2.7.4, which I did based on various articles praising the massive performance gains in Ruby 2.6.0, the performance of a basic search on my local improved from 3.20s page load to around 800ms, around 75% decrease in load time. We will need to verify how this performance improvement holds up in production, but it will likely impact performance positively. Here are the flamegraphs to see the difference in performance between Ruby 2.5.7 and 2.7.4, and you can use [speedscope](https://www.speedscope.app/) to visualize the flamegraphs:

[https://app.zenhub.com/files/295449627/e3d9e943-8c28-4746-a783-695f1c4045b1/download](https://app.zenhub.com/files/295449627/e3d9e943-8c28-4746-a783-695f1c4045b1/download)

**Comment by abelemlih** [comment]
PR: https://github.com/emory-libraries/blacklight-catalog/pull/1044

**Comment by lovinscari** [comment]
@abelemlih and @bwatson78 - Thanks for your work on this. I see a slight improvement on blackcat-test but not to the degree reported on the local instance. @rotated8 has submitted a new Spike ticket to continue with this work.
