### ISSUE TITLE
Preliminary Search - Ability to start a new search

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#104]
As an end user, I would like the ability to see what the preliminary (Blacklight out of the Box) option is to start a new search in the event my current search is not providing the results I expected and I would like to start a new search from the page I am on instead of having to figure out how to navigate to the home page.

**Comment by eporter23** [comment]
@lovinscari I believe this is already functional in our blackcap-arch instance. If I enter a search, a Start Over button always appears. Screenshots below:

![Screen Shot 2020-12-18 at 9.56.27 AM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/ecfca32f-5018-4a4e-b821-391e0c098b17)

From this results page, if I click on Start Over, it will take me back to the homepage:

![Screen Shot 2020-12-18 at 9.56.34 AM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/ea94c600-fc3d-4307-ab36-fa49b3ba4828)
