### ISSUE TITLE
Refactor Emory login link

### ISSUE THREAD

**Issue by abelemlih** [emory-libraries/blacklight-catalog#1040]
In `_links.html.erb`, the logic that renders the Emory login link is confusing, and checks for `provider == "Shibboleth"`, even though the provider name in the system is not capitalized (`shibboleth` instead of `Shibboleth`).

We need to look into how the following code renders the login link, and refactor it:

```erb
<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <% if provider == "Shibboleth" %>
      <%= link_to "Emory Users Login", new_user_shib_session_path %><br />
    <% else %>
      <%= link_to "Emory Users Login", omniauth_authorize_path(resource_name, provider) %><br />
    <% end %>
  <% end %>
  <%= link_to "Affiliate login", alma_social_login_url(redirect_to: session[:requested_page]) %>
<% end %>
```

**Comment by abelemlih** [comment]
@lovinscari @eporter23 To test this ticket, we just need to confirm that Emory login through Shibboleth still works as expected, and that the code changes did not impact any login functionality.

**Comment by eporter23** [comment]
Logged into test successfully via Shibboleth.
