### ISSUE TITLE
A-Z menu shows up in Bookmarks if you sort results

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/blacklight-catalog#1042]
Current behavior: when viewing the bookmarks page, we offer the same sort options as used in search results. If you re-sort the list by something other than relevance, the A-Z menu unexpectedly appears.

![Screen Shot 2021-11-11 at 10.54.22 AM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/e8c65672-2a3d-47f3-9759-d9a88c47806a)

If you click on a letter that doesn't match your titles, it can then return a blank screen with "no bookmarks".

![Screen Shot 2021-11-11 at 11.27.59 AM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/da294d0f-1e4a-413a-8066-b8df2ba99f03)

Desired behavior:

Suppress the A-Z menu from Bookmarks.

**Comment by lovinscari** [comment]
Looks good.
