### ISSUE TITLE
SPIKE: Search Assistance - Predictive Results

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#105]
Investigate the feasibility of incorporating predictive search assistance to satisfy the user stories below.
 

- [x] As an end user, I want suggestions from a search to find an item even if I have the title or author a little bit off so I can have more confidence in the results I see. An example of a search would be searching by author/creator and entering "hemmingw" when I could not remember the author/creator "hemmingway." There would likely not be any results for the author "hemmingw" but I would like the search results returned to include a statement "Did you mean Hemmingway?" 

- [x] As an end user, I would like for Blacklight to interpret my search request for a title if I did not enter all words of the title. For example, if I enter "Harry Potter Stone" in the global search bar as a Title Search, I would like the results to include either the title of "Harry Potter and the sorcerer's stone" in the results or a suggestion of what I might have meant similar to Google "Did you mean - Harry Potter's and the sorcerer's stone?"

**Comment by rotated8** [comment]
- Are title and author the only fields to predict?
- Does the "Did you mean ..." result show up as a user is typing their search term, or on the results page?
- Do we show spelling suggestions?
- Do we show related searches? How do we define related searches?

**Comment by rotated8** [comment]
Timeboxing to two days

**Comment by alexBLR** [comment]
**Current Behavior in Alma**
	Alma provides only a direct search match
	No instant search on key strokes
	No suggestions when misspelling the title
	When the title is misspelled you get a blank search result, unless a direct match exists

**Answers To Collin's Questions**

* Are title and author the only fields to predict? (Not currently available in Alma)
* Does the "Did you mean ..." result show up as a user is typing their search term, or on the results page? (Not currently available in Alma)
* Do we show spelling suggestions? (Not currently available in Alma)
* Do we show related searches? How do we define related searches? (Not currently available in Alma)


Investigate the feasibility of incorporating predictive search assistance to satisfy the user stories below.
1) As an end user, I want suggestions from a search to find an item even if I have the title or author a little bit off so I can have more confidence in the results I see. An example of a search would be searching by author/creator and entering "hemmingw" when I could not remember the author/creator "hemmingway." There would likely not be any results for the author "hemmingw" but I would like the search results returned to include a statement "Did you mean Hemmingway?"

The default search functionality of blacklight addresses this problem with instant search feedback even if you misspelled the the title or author. There is no need in "Did you mean...." Attached is the screenshot from the blacklight demo.
![Screen Shot 2021-01-05 at 9.29.51 AM.png](https://images.zenhubusercontent.com/5c488275c10ae96cd915967b/8412b93d-f60b-491b-935e-ed564d8623e9)

2) As an end user, I would like for Blacklight to interpret my search request for a title if I did not enter all words of the title. For example, if I enter "Harry Potter Stone" in the global search bar as a Title Search, I would like the results to include either the title of "Harry Potter and the sorcerer's stone" in the results or a suggestion of what I might have meant similar to Google "Did you mean - Harry Potter's and the sorcerer's stone?"

The default search functionality also addresses this story by using search proximity. Attached is the screenshot below:
![Screen Shot 2021-01-05 at 9.27.44 AM.png](https://images.zenhubusercontent.com/5c488275c10ae96cd915967b/2d6a8472-357f-4d1f-b06f-0d2c085386d6)
