### ISSUE TITLE
Update availability display logic for Alma API response of "check holdings"

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/blacklight-catalog#1051]
Example record: https://search.libraries.emory.edu/catalog/990014642750302486

Our previous understanding of Alma availability API responses for print (AVA) holdings is that the status code was either Available or Not Available.

In discussions with the SEND team, however, we have learned that there is a third AVA $e code that is occasionally returned.

Right now our logic for the availability badge shows "Not Available" in cases where the Alma availability status code is actually "check holdings". For cases like this, availability may vary per volume or copy, and we should provide a different message. 
See this mockup: https://codepen.io/eporter23/pen/vYZOJeq for a "Check Holdings" message. Note that we may need to revise these availability outputs further in the near future.

API response returned for holdings:

```<datafield ind1=" " ind2=" " tag="AVA">
<subfield code="0">990014642750302486</subfield>
<subfield code="8">22330735880002486</subfield>
<subfield code="a">01GALI_EMORY</subfield>
<subfield code="b">LSC</subfield>
<subfield code="c">- Non-Circulating</subfield>
<subfield code="d">MICFILM 3021</subfield>
<subfield code="e">check_holdings</subfield>
<subfield code="v">from:4-8 1937-1941 until:82 2015</subfield>
<subfield code="j">USTORNC</subfield>
<subfield code="k">4</subfield>
<subfield code="p">1</subfield>
<subfield code="q">Library Service Center</subfield>
</datafield>```

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/blacklight-catalog/pull/1093

![Screen Shot 2021-11-29 at 1.08.37 PM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/1d475e76-ad95-4389-9c97-dd8cbfe338d1)
![Screen Shot 2021-11-29 at 1.09.06 PM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/ef34bcd1-f231-4774-a167-239e7fd11c80)

**Comment by eporter23** [comment]
@bwatson78 looks good, thanks!

**Comment by lovinscari** [comment]
Looks great!
