### ISSUE TITLE
Add content to Services view homepage

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/blacklight-catalog#1057]
Because we will point discoverE redirects to the Services view, we need to use the "homepage" of that view to assist users who may have been redirected.

[Mockup](https://docs.google.com/drawings/d/1zby9ZCj5wfbmYMNS_TcvP1-CCmQ1xMbXl8uyTru5928/edit)

- [x] Add update your bookmarks banner
- [x] Add overview text and links
- [x] Add 4 search tool cards

**Comment by eporter23** [comment]
@lovinscari screenshot - currently in sandbox and production. 

![Screen Shot 2021-11-22 at 2.19.24 PM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/28ef6aa2-ff22-46d3-b15b-770f3ef542eb)

**Comment by lovinscari** [comment]
@eporter23 - This looks great.
