### ISSUE TITLE
Add the CDI Search Scope to the Services Page View

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#1058]
After the meeting with ExLibris, we should add the search scope of CDI to the services view in case of misc. redirects, saved searches, bookmarks etc. I suspect this will require PrimoVE configuration and CSS Styling to add the link?

**Comment by libah** [comment]
I added the CDI scope to the services view. You can see that both a book from the catalog and article from CDI are returned in the search results with the following link. 
https://emory.primo.exlibrisgroup.com/discovery/search?query=any,contains,miranda%20pollard&tab=&search_scope=MyInst_and_CI&vid=01GALI_EMORY:services&offset=0

**Comment by eporter23** [comment]
Thanks @libah. I will do some more review on this to see which additional aspects of the services view that will need styling to support redirected saved searches and eshelf items.
