### ISSUE TITLE
Initiate message/alert banner on home page stating this is a beta product

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#1059]
In an effort to test the process for creating/initiating a banner on the home page to communicate matters/issues pertaining to Library Search to end users (e.g., application down time, planned maintenance, etc.), I would like to implement a banner similar to that when a user logs in
![Banner_HomePage.png](https://images.zenhubusercontent.com/5c4a1fe1e9b5fb46bcedb9fc/3b194dd0-5a85-4410-b7e8-2efa638ce144)

- [ ] The banner should appear on the home page below the hero image and above the search box. Please consult with @eporter and @CB987 to determine if the message/alert banner should be different colors than the action/confirmation banner (successfully logged in). 

- [ ] The banner in this case should read, "Welcome to the beta version of Library Search. Questions or concerns about the product can be sent to librarysearch@emory.edu. The production launch is scheduled for January 6, 2022. Until then, you can use Library Search or discovere.emory.edu to search and find items from the catalog and Articles Plus."

**Comment by bwatson78** [comment]
PR made:https://github.com/emory-libraries/blacklight-catalog/pull/1075

![Screen Shot 2021-11-19 at 12.13.01 PM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/d2bca90c-3b1d-4e64-99d3-2bb32d5c0257)

**Comment by lovinscari** [comment]
Looks good.
