### ISSUE TITLE
Update references to ebook to e-book

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#1061]
As reported by Colin Bragg, "Our library style sheet (https://emory-my.sharepoint.com/:x:/g/personal/lwingat_emory_edu/Ecmqf4_WvxpGj-nTSZ56SboBiwMkshytqkEkhF-zHam20w?e=a7fRy3) notes that "eBook" should be written as "e-book." The prompt above the search box states "Search books, eBooks, videos and more."

Please update all instances of ebook to e-book including the reference on the home page below the hero image. 

UPDATE: Please look at code to determine if ebook is contained elsewhere in the application and update all references of ebook to e-book. Thanks!

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/blacklight-catalog/pull/1078

![Screen Shot 2021-11-22 at 9.38.55 AM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/8c690be0-ea29-471a-bf3a-54b002609d84)

**Comment by lovinscari** [comment]
Looks good.
