### ISSUE TITLE
Follow up with ExLibris on report of users who have favorites and saved searches in discoverE

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#1062]
Please follow up with Efi in Basecamp to acquire a report on the number of users of discoverE who have saved searches or favorites so we can determine the impact of not having those moved over from discoverE to Library Search. We might also want to explore a targeted communication to those users with how they can export the information from discoverE.

**Comment by libah** [comment]
I have written to Efi in Basecamp asking about the report.

**Comment by libdgg** [comment]
Efi responded on basecamp and provided a spreadsheet.
https://3.basecamp.com/3765443/buckets/23697781/messages/4370964754

**Comment by lovinscari** [comment]
Closing this ticket as the requirement has been met.
