### ISSUE TITLE
Create a ticket with ExLibris support to copy certificates from discoverE to Primo VE

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#1063]
Create a ticket with ExLibris support to copy certificates from discoverE to Primo VE. Per our last meeting with Efi, this is rather urgent as it could take a bit to initiate this change. Once the ticket is created, send the ticket number to Efi via Basecamp. I am not sure if changes are needed to the certificates (i.e., we should have more secure certificates for Primo VE?)

**Comment by libah** [comment]
I created a salesforce ticke (06042224) with Ex Libris and posted a note and ticket number to Efi via Basecamp.

**Comment by libah** [comment]
Created a SalesForce ticket with ExLibris and then posted a message in Basecamp for Efi, 11/19/01

**Comment by libah** [comment]
Sent a message to Efi in Basecamp asking for an update. 11/30/21

**Comment by libah** [comment]
Received the CSR from Ex LIbris, generated a certificate which I sent back to Ex Libris and notified Efi.

**Comment by libah** [comment]
Efi has confirmed that the certificate will be copied or in place on January 6th.

**Comment by libah** [comment]
Paul from Ex Libris,  sent the CSR and requested a new certificate be sent back to him, Dec 28th. I did this and he confirmed it was fine. So they should be able to install the certificate.
