### ISSUE TITLE
Determine tasks and timeline needed for redirecting discovere.emory.edu

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#1064]
In our last meeting with ExLibris, I believe we established the majority of the redirects from discoverE would be managed by ExLibris with the exception of the high level domain of discovere.emory.edu that should redirect to search.libraries.emory.edu on January 6, 2022. In advance of implementing the change, I would like to understand the tasks associated with the change and the estimated timeline so we can properly plan that work. Please document tasks and estimated timeline within this ticket.

**Comment by jcrompton42** [comment]
Currently discovere.emory.edu is an alias for primofe1.library.emory.edu
discovere.emory.edu.	600	IN	CNAME	primofe1.library.emory.edu.

so we need to request it be changed via this form on service now - estimated but not guaranteed delivery time is 1 day. 

https://emory.service-now.com/sp?id=sc_cat_item&sys_id=fe7b2ff1132d1740ed14be322244b03
![Screen Shot 2021-11-18 at 9 59 23 AM (2)](https://user-images.githubusercontent.com/88731056/142442723-9a37e48d-82a6-491f-8e51-d85dbad79110.png)
6
