### ISSUE TITLE
Determine uptime and availability benchmark of AWS @ Emory

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#1066]

**Comment by jcrompton42** [comment]
SLAs from AWS: uptime per instance per billing cycle for services Blacklight relies on 

- Ec2 & EBS 95.5 %   
- ELBs 99.99 %  
- RDS 99.95% 
- Networking (VPCs, subnets) 99.9% 

 AWS @Emory support  
Emory contracts with AWS Enterprise support which is available 24/7/365 with a response time of less than 15 minutes by a Senior Cloud Support Engineer. 

 Note that while Emory does not provide any different availability guarantees from AWS, _access_ to AWS @ Emory is dependent on Emory’s Big IP F5 loadbalancers, which is critical Emory infrastructure.
