### ISSUE TITLE
Determine uptime and availability benchmark of Primo VE by ExLibris

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#1067]

**Comment by libah** [comment]
Uptime and performance report for 2021 3rd quarter: 

https://knowledge.exlibrisgroup.com/Cross-Product/Higher-Ed_Platform_Uptime_Reports/North_America/2021/Higher-Ed-Platform_Performance_and_Uptime_Report_for_NA03_Instance_(North_America)_-_Q3_2021
