### ISSUE TITLE
Determine if Solr should have different benchmarks for availability and uptime from that of the Blacklight application

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#1068]

**Comment by jcrompton42** [comment]
In my opinion, solr should not be considered separately from blacklight. There isn't enough work involved in restoring a catastrophic solr failure to really gain anything from separate consideration.  I see 2 scenarios for catastrophic solr failure:

1) the index is corrupted somehow. We have daily backups made, and restoring the most recent one will take less than 5 minutes.

2) The infrastructure (ec2 or loadbalancers instances) fail. There are 3 ec2 instances for the solr cluster. It is unlikely that all 3 go down at once unless there is an AWS wide failure. Even if that somehow happened, we can restore a backup of the prod solr cluster to the test cluster and point the application there instead. If something happens to the loadbalancer, spinning up a new loadbalancer in AWS is quick.
