### ISSUE TITLE
Determine method, including timeline, for restoring Blacklight application

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#1069]
Update - This ticket assumes that a major incident has occurred affecting the application and restoration would be needed using Circle CI.

**Comment by jcrompton42** [comment]
I have added ansible instructions to my disaster recovery wiki document, but need to meet with Solomon about the terraform piece. 
https://wiki.emory.edu/display/BDL/Disaster+Recovery

**Comment by jcrompton42** [comment]
Terraform has been fixed and instructions for running plus a time estimate have been added to disaster recovery document
