### ISSUE TITLE
Mapping first pass

### ISSUE THREAD

**Issue by devanshu-m** [emory-libraries/blacklight-catalog#107]
We are attempting to map alma marc fields to solr fields from Josh Weisman's initial mapping and changing that to meet our needs. The sample set we are working from is here: https://app.zenhub.com/files/295449627/4c678507-9cc4-4396-8e11-dff824e231f6/download

Google doc is here: https://docs.google.com/spreadsheets/d/1CJam4gusBdY4w1SBgjhegoTjCUUcfjWKVNvfvV7C1sE/edit?usp=sharing

Branch: https://github.com/emory-libraries/blacklight-catalog/tree/resource-segregation

**Comment by devanshu-m** [comment]
Running the rake task has the dependency of updating solr schema on arch.

**Comment by devanshu-m** [comment]
We are somewhat ready for a first pass and the branch has been updated. We will submit a PR for the work tomorrow morning and after review and merge into main, we can start the import process.

Some important issues that we will be tackling in the next iteration include:
* The SolrMarc version we are using is outdated and we will need to update that and also use solrj jar files as those are required with the new SolrMarc version (solrmarc devs have tried to break out the bigger SolrMarc jar files into smaller jar files).
* The above will mean that some of our functions in the mapping, for example, `getLinkedField` for title will not work. There are a few other functions that will also not work according to solrmarc documentation. We will need to update those.
* Currently, we are able to distinguish between physical and electronic items for the larger part, but this theory can quickly fail once we start seeing more items. For example, we are only looking at 007 controlfield tag to determine if a record is electronic; however @lisahamlett and @alexBLR pointed that is not true. 006 controlfield tag can also sometimes be an electronic item. We will also need to consider 856 tag datafield when making that decision.
* All of the above will be possible by using solrmarc's conditional specifications, however, this is unable to us at this time because of outdated solrmarc version. Once we update to the latest jar, and add smaller helper jars, we should be able to use conditional specifications and other functions.

**Comment by devanshu-m** [comment]
Ticket for documenting new first pass mappings: https://app.zenhub.com/workspaces/blacklight-catalog-5f5f84a8a6d29939a0bc5d78/issues/emory-libraries/blacklight-catalog/109

New ticket for second pass of mappings: https://app.zenhub.com/workspaces/blacklight-catalog-5f5f84a8a6d29939a0bc5d78/issues/emory-libraries/blacklight-catalog/110

**Comment by tmiles2** [comment]
Pending the completion of the production import.
