### ISSUE TITLE
Replace current hero image with an Emory stacks photo

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/blacklight-catalog#1081]
Replace the current homepage feature image with the following, which was part of a paid photo shoot of the Libraries in 2019. Contact @eporter23 if this uploaded attachment isn't the right size.

![stacks-eul.jpg](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/f1e0ddb4-6d6c-4093-b7a7-c0f4aa838dd1)

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/blacklight-catalog/pull/1084

![Screen Shot 2021-11-22 at 3.56.58 PM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/d0776888-df81-46dc-8e93-cee367047d35)
