### ISSUE TITLE
Reduce font size of search results' title links

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/blacklight-catalog#1085]
In response to some user feedback regarding the amount of scrolling required to see search results, we want to slightly reduce the font size of the title links (h3), which can take up a lot of screen space.

Suggested revision: reduce to 1.2 rem

Current output
![Screen Shot 2021-11-23 at 9.31.53 AM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/05ad57da-fc98-4005-ae87-8144b75463f8)

Desired output

![Results smaller heading font 2021-11-16 at 12.14.40 PM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/aa6b9cd2-b9b5-4732-87ca-9a30cf3556d8)

**Comment by eporter23** [comment]
@lovinscari @CB987 adding this ticket after our wireframes discussion last week.

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/blacklight-catalog/pull/1086

![Screen Shot 2021-11-23 at 10.14.03 AM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/2411f021-fe85-4d75-b6f6-8c1510d4e899)

**Comment by eporter23** [comment]
@bwatson78 @lovinscari Looks great!
