### ISSUE TITLE
Request Primo Classic UI Analytics be copied and transferred to Primo VE analytics

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#1089]
Per our previous conversations with ExLibris, they stated they can copy the analytics and reports currently saved in discoverE (Primo Classic UI) to Primo VE. This work should be completed on or shortly after 1/6/22.

**Comment by lisahamlett** [comment]
I'd actually prefer to rebuild these in analytics because Primo Classic analytics doesn't have nearly the functionality and abilities that the Alma/PrimoVE analytics does...

**Comment by lovinscari** [comment]
@lisahamlett - I don't mind if these are rebuilt moving forward but would like to retain any analytics we had from discoverE

**Comment by lisahamlett** [comment]
Okie dokie

**Comment by tmiles2** [comment]
Cari will reach out to Ex Libris

**Comment by libah** [comment]
The analytics have been moved. Lisa verified.
