### ISSUE TITLE
Investigate and resolve why deactivated portfolios are showing in Library Search

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#1091]
Per the email from Sofia below, I would like the team to investigate and resolve why deactivated portfolios are showing in Library Search

*********
DiscoverE is set up not to display electronic resources with portfolios that are deactivated, but it is not the case in Blacklight
 
Here are some examples of e-resources that are no longer available, but still display in Blacklight (the portfolios are deactivated in ALMA)
990007090070302486
9936579826202486
 
We have thousands of these records as we often just deactivate the portfolio, but not suppress the bib record. I believe this needs to be addressed before going live.
 
Also I have a question about records for print resources that don’t have inventory (these are usually approval books that we already received, but have not cataloged yet). In DiscoverE, there is at least a message that reads Physical resource may be available at other libraries. It would be nice if there is also some sort of message in Blacklight. Otherwise I think it is very confusing for patrons. Here is an example
 
9937381125702486
 
Please let me know if you need additional clarification or more examples.
 
Thank you very much for considering!
 
Best,
________________________________________________________
Sofia Slutskaya
Head, Resource Description
Woodruff Library | Emory University
404.727.0123 | sofia.slutskaya@emory.edu

**Comment by lisahamlett** [comment]
I made 998e "Activation Status"
```
<datafield tag="998" ind1=" " ind2=" ">
  <subfield code="a">53297729050002486</subfield>
  <subfield code="e">Not Available</subfield>
  <subfield code="c">UNIV</subfield>
  <subfield code="b">BOOK</subfield>
  <subfield code="8">53297729050002486</subfield>
</datafield>
```
For electronic records only, If all 998s on the record have a 998e of "Not Available," the record should not show.
There are two examples in the blacklighttest OAI.  We can start with those.

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/blacklight-catalog/pull/1094

**Comment by lovinscari** [comment]
I tested the two examples and neither appears in Library Search. I notified Sofia of the change.
