### ISSUE TITLE
Restore submitting hold requests using the ALMA API

### ISSUE THREAD

**Issue by abelemlih** [emory-libraries/blacklight-catalog#1095]
Currently, in file `catalog/_show_request_options.html.erb`, the API hold request functionality is commented out. We need to uncomment the hold request functionality and ensure it is working properly.

The API hold request functionality is behind the feature flag `enable_requesting_using_api`.

**Comment by abelemlih** [comment]
Refer to PR: https://github.com/emory-libraries/blacklight-catalog/pull/1101

@rotated8 @lovinscari  To test the feature, you need to enable the "Enable requesting using api" feature toggle by following these steps:
- Sign in, and ensure your NetID is in the list of LTDS NetIDs allowed to access admin features (env variable `LTDS_ADMIN_NET_ID_LIST`)
- Access `/features` page
- Select "on" under "Cookie". This will enable the feature for your user session only.

Once the feature is enabled, you can access the page of any document and see the request button restored in this ticket.

**Comment by lovinscari** [comment]
@abelemlih and I will meet to discuss after standup on 12/7.

**Comment by lovinscari** [comment]
This looks great!
