### ISSUE TITLE
Update search results, bookmarks, and single item view holdings information to include call numbers and locations

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#1096]
Update holding level details within search results, single item view and bookmarks based on wireframes below and associated instructions within wireframes mockup.

- [x]  For search results, please see [wireframe 4B](https://docs.google.com/drawings/d/1cCdbtg5YaN3YwfTdPmzQjzTeKKu2dMHBHs0_583MkUo/edit)

- [x] For single item view, please see wireframe [4F Single Item View](https://docs.google.com/drawings/d/1nqBczuNhRimOBVcjxzykjWV6LbNGO6zI7eL2SeKrK5k/edit)

- [x] For bookmarks, please see wireframe [4F Bookmarks](https://docs.google.com/drawings/d/1M9b98ffpqdl1b4WZ7fbfTAUEzM3RixOJMmyNAPNwvok/edit)

Please coordinate with @eporter23 if there are questions about the wireframe or technical specifications contained in wireframe.

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/blacklight-catalog/pull/1107

See PR for MOV of code in action.

**Comment by eporter23** [comment]
@bwatson78 great turnaround on this! Here are a few things missing from the original wireframe details:

Search results, bookmarks:
When Show Locations is clicked, it toggles a blank table underneath Online-only items. This table should not be shown for online access.

![Screen Shot 2021-12-09 at 12.17.14 PM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/8d04a43b-53db-43b8-8642-20b64c8375d0)

Table layout general styling

Please make the LOCATE/REQUEST THIS ITEM button font consistent with other buttons (~11px, bold)

![Screen Shot 2021-12-09 at 12.37.34 PM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/563deaf7-9300-488a-8074-ae41a1fd1109)

Please make the three table columns more equal width as shown in the wireframe. In particular, we don't want the Call Number heading to wrap to a second line.

![Screen Shot 2021-12-09 at 12.36.34 PM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/352e3596-197e-4af1-b78a-228fbc19491d)

For the single item view, the Locate table should be expanded by default (it is currently hidden by default).

Bookmarks
In the print view, the locations table should be expanded by default. It is currently collapsed.

![Screen Shot 2021-12-09 at 12.39.32 PM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/9a829d77-0892-405e-b2a0-6de9a2285c14)

**Comment by eporter23** [comment]
@lovinscari in the original wireframes you'd requested we not show the availability column when bookmarks printed. Does this mean we need to hide the overall availability badge for the whole table as well as the individual table rows?

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/blacklight-catalog/pull/1133
![Screen Shot 2021-12-10 at 9.26.38 AM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/5ff0544f-e913-4826-9ce6-d3f38ed7d644)

https://images.zenhubusercontent.com/295449627/aa544015-b8a9-4ed1-80f2-8c289de31fd0/screen_recording_2021_12_10_at_9_28_26_am.mov

![Screen Shot 2021-12-10 at 9.29.17 AM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/69c1a2ae-7618-4ea7-a216-2d04798dff56)

**Comment by lovinscari** [comment]
@bwatson78 and @eporter23 - I think this looks good and sorry I did not see your message/questions from last week.

**Comment by eporter23** [comment]
After testing again, we are still missing the following:

Locations table should be expanded by default on the Single Item View page. Currently it is collapsed by default.

The locations table should have equal columns wide enough to contain the headings as shown in the wireframe. The Call Number heading <th> should not wrap to a new line.  ![Screen Shot 2021-12-14 at 2.22.44 PM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/669c6cff-9323-4176-8779-cc447686f774)

**Comment by eporter23** [comment]
@bwatson78 the table column width looks good in your recording, so I guess maybe this is a browser-specific quirk. I'm seeing the same issue as reported earlier in (Mac) Safari 15.2 but Chrome 96.x and Firefox 95 looks good.

**Comment by bwatson78** [comment]
@eporter23 The javascript expanding the collapse on show page was mistakenly added to the Blacklight gem code and not our application--my apologies. Making a small PR to fix this.

**Comment by eporter23** [comment]
Thanks for the fixes @bwatson78 !
