### ISSUE TITLE
Provide holdings access to child records in bound-with situations

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#1097]
For bound-with situations where a child title has been bound together with other titles (multiple "records" but a single physical item with only one barcode), we need to implement options for users to access the parent record in order to see the physical item's availability.

See [additional record examples](https://docs.google.com/spreadsheets/d/1WOk514GDbGbFspv_oOW7fwy0pKjr_ubgaFT2lHP6bTM/edit#gid=2085736995) here.

**Wireframes**
Single item view (example [1](https://docs.google.com/drawings/d/1C1mhctyjvfYvrhU85hYJuEu0YOVApxtmq_ez6eZ-YVQ/edit) | [2](https://docs.google.com/drawings/d/17MD9WaqZp2YgCnk5_9AfzPoOTkDIZ3TaTuzbk76atTg/edit) | [3](https://docs.google.com/drawings/d/1Pu54Y_zh3kAav9S8P0CNH-069yefXmNTNhljrbpIb44/edit))
[Search results](https://docs.google.com/drawings/d/1AR6m8MgIhTYQZxdhR_QkeoqJEDcb8rzKCoL3W6DdOSU/edit) 
Bookmarks (should follow the same pattern as search results)

**SOLR/Indexing**
Create a new display field comprised of the 773 $w and $t.
Only store those 773s which contain an Alma MMSID in $w: these always start with 99 and end with 2486.
When displayed, the field label should be "Is Part Of". The value should be hyperlinked, using the contents of $t as the link text and the href should be /catalog/{$w}

**Comment by bwatson78** [comment]
PRs made: https://github.com/emory-libraries/blacklight-catalog/pull/1108 and https://github.com/emory-libraries/blacklight-catalog/pull/1109

**Comment by eporter23** [comment]
@bwatson78 looks great! I've spot checked quite a few examples. I did find one that isn't quite working, but I wonder if this is a reindexing problem. This MMSID exists in prod but seems to be missing in test.https://blackcat-test.library.emory.edu/catalog/990016850440302486 - parent record for https://blackcat-test.library.emory.edu/catalog/990017278030302486

**Comment by lovinscari** [comment]
@eporter23 - I would like to review with you during our 1-2-1 meeting today as I am a little confused by the behavior of the parent record on the services view page.

**Comment by lovinscari** [comment]
@eporter23 - I am ready to accept this but would like you to confirm the issue you reported last week has been resolved based on our conversation/review yesterday. Please move to To Deploy to Prod once reviewed.

**Comment by eporter23** [comment]
@lovinscari @bwatson78 looks good! But please see my comments on #1098. I am not sure, but I think the new Contact us status is conflicting with bound withs (which should show Check Holdings).

**Comment by bwatson78** [comment]
@eporter23 I will swing this back into In Progress and refine that logic delivering the Contact Us message.

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/blacklight-catalog/pull/1149

![Screen Shot 2021-12-16 at 12.50.58 PM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/87225101-8cf2-4374-9d1d-ef29929b4292)

**Comment by lovinscari** [comment]
@eporter23 - please review this on 12/20/21. If acceptable, please move to To Deploy to Prod

**Comment by eporter23** [comment]
Looks good @bwatson78 , thanks!
