### ISSUE TITLE
Indexing

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#11]
As the product owner of the Blacklight Catalog for Emory University Libraries, I want to ensure that the Solr Index for Blacklight is designed and developed in the most effective manner in an effort to improve the usability of the catalog for Emory University Libraries in the areas of 

- [ ] Basic Search
- [ ] Advanced Search
- [ ] Search Relevancy
- [ ] Ability to boost catalog items by age

Specific usability acceptance criteria for search and relevancy will be identified in the respective epic but the high-level acceptance criteria will be added to each issue attached to this Epic.

**Comment by tmiles2** [comment]
@lovinscari Can we close this epic?
