### ISSUE TITLE
Mapping second pass

### ISSUE THREAD

**Issue by devanshu-m** [emory-libraries/blacklight-catalog#110]
We need to improve alma marc to solr mappings and some important issues that we will be tackling in the next iteration:

* The SolrMarc version we are using is outdated and we will need to update that and also use solrj jar files as those are required with the new SolrMarc version (solrmarc devs have tried to break out the bigger SolrMarc jar files into smaller jar files).
* The above will mean that some of our functions in the mapping, for example, getLinkedField for title will not work. There are a few other functions that will also not work according to solrmarc documentation. We will need to update those.
* Currently, we are able to distinguish between physical and electronic items for the most part (judging from the sample set), but the logic we have in place right now can quickly fail once we start seeing more items. For example, we are only looking at 007 controlfield tag to determine if a record is electronic; however @lisahamlett and @alexBLR pointed that may not be true. 006 controlfield tag can also sometimes be an electronic item. We will also need to consider 856 tag datafield when making that decision.
* All of the above will be possible by using solrmarc's conditional specifications, however, this is unavailable to us at this time because of outdated solrmarc version. Once we update to the latest jar, and add helper jars, we should be able to use conditional specifications and other functions.

Related to the the second pass at mapping, please refer to the Metadata Model (to be provided by @lovinscari on 1/14/21) in the event any data is needed from the metadata model for the mapping.

**Comment by tmiles2** [comment]
Related to #133

**Comment by lisahamlett** [comment]
The test Devanshu did on friday is correct.  We just need to test it with a larger data sample.
