### ISSUE TITLE
Remove deprecated route for ALMA availability

### ISSUE THREAD

**Issue by abelemlih** [emory-libraries/blacklight-catalog#1102]
Route `/alma_availability/:id` is currently not used anywhere in the app, and the method it references, `ApplicationController#alma_availability` is deprecated. The method references a method in the `AlmaAvailabilityService` that no longer exists. We should delete this route and any associated code.

In the future, if we do need routes and helper methods to retrieve ALMA availability, we should create a dedicated controller, and avoid adding this functionality to the Application Controller.

**Comment by lovinscari** [comment]
Nothing for me to test.
