### ISSUE TITLE
Availability indicators not loading correctly in the bookmarks page

### ISSUE THREAD

**Issue by abelemlih** [emory-libraries/blacklight-catalog#1104]
@lovinscari @eporter23 

I noticed that on the bookmarks page, the availability indicators are never displaying the availability values for documents bookmarked. We need to restore that functionality and ensure the AJAX call to retrieve availability data is processed correctly.

**Comment by eporter23** [comment]
@abelemlih looks good, thanks for fixing this!

**Comment by lovinscari** [comment]
Looks good.
