### ISSUE TITLE
Change HTML page title for Advanced Search 

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/blacklight-catalog#1105]
In order to make Analytics more interpretable, we should change the HTML <title> for the advanced search page as follows:

Current output:
More Search Options

Desired output:
Advanced Search

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/blacklight-catalog/pull/1110

![Screen Shot 2021-12-07 at 10.32.20 AM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/d6f43092-5645-4e92-93f3-8f693ee30bab)

**Comment by eporter23** [comment]
Looks good, thanks!
