### ISSUE TITLE
Add MARC 940 to Staff View

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/blacklight-catalog#1115]
This example was reported by Chris Palazzolo on the SEND team. The MARC 940 note field displays in discovere's staff view, but not in Blacklight's Staff View. 

Question: Do we need to provide field by field mappings for Staff View, or does it contain all MARC data from the record?

https://search.libraries.emory.edu/catalog/9937344454402486

Looking at our MARC data inventory, we seem to have ~2,728,008 records with 940 so it's a pretty common field in our catalog.

Note: at the time this ticket is being written, this bib is not currently loading in discovere's Staff View, but here is a screenshot that was submitted.

![discoverE_Screen Shot 2021-12-06 at 6.50.43 PM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/bf45a6d0-26e6-47e4-a47b-49457bfe9f18)

Other examples of 940s:
990033370580302486
990033372550302486
990029401690302486

**Comment by lovinscari** [comment]
From Chris Pallazolo - "In Primo (discoverE), the staff view includes the 940 local field, but I do not see this in the staff view in Blacklight. See attached. This is an important field for staff as it indicates in many cases local sets or provenance (for example, our approval records from GOBI have a YBPAPP 940 designation and our JSTOR DDA have a JSTOR DDA CANDIDATE designation) and can impact CM decision making."

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/blacklight-catalog/pull/1128

![Screen Shot 2021-12-08 at 3.47.17 PM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/d9f648b6-d808-4660-89b9-015cff66a137)

**Comment by lovinscari** [comment]
Tested on the examples provided. Looks good.
