### ISSUE TITLE
SPIKE: Determine fix of issue with script that identifies newly acquired items in Alma

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#1116]
Stakeholders have noticed the newly acquired function is not working as it should in Library Search. Alex has previously developed a python script that is supposed to look at the acquisition date of an item and flag it as newly acquired. The script is no longer working as it should as it appears the flag is not being removed within a certain period of time. I am unsure if this should be fixed with the python script in Alma and the subsequent OAI harvest of Alma data or if this is something that could be resolved within Blacklight and Solr Data. 

The idea is for an item to appear within the newly acquired facet within 90 days of acquisition from the date being searched. For example, if an item was purchased on or around 9/15/21 - 11/15/21, it would appear in the newly acquired facet. If an item was purchased beyond 90 days from today's date (e.g., 1/5/21), it would no longer appear in the newly acquired facet. 

I would like for a member of the application development team to work with @AGCooper and @lisahamlett to determine the best path forward for resolving this issue. Please document the recommendation within this ticket and create a new ticket for the work to be completed ideally before 12/15/21.

**Comment by lisahamlett** [comment]
@lovinscari We're trying to diagnose the problem.  Do you have example MMSIDs?

**Comment by lisahamlett** [comment]
I have requested examples from the SEND team.
If they do not get them to us by the time Alex leaves for vacation, this will have to wait until he returns, as it is his script that is broken (if anything is actually even broken).

**Comment by lisahamlett** [comment]
The script isn't removing the NEW tag from the 940 when the item is no longer new.
I don't know how to fix this, as it is Alex's script and I don't know how he wrote it.  So it will have to wait until he comes back from Germany.

**Comment by lisahamlett** [comment]
I set up an analytics report to collect these items by date: %2Fshared%2FEmory%20University%20Libraries%2FReports%2FLHAMLET%2FPRIMO_NEW_598

Here are a few examples:
9936618306002486
9936626417402486
9936626417502486
9936626417602486
9936626417702486
9936626417802486
9936626417902486
9936626418002486

**Comment by lisahamlett** [comment]
Until Alex has the time to work on this, I am manually running a job to remove the NEW tags from the marc records.

**Comment by lovinscari** [comment]
Changing the scope of this ticket to accept work completed by @lisahamlett. Two new tickets will be issued to have Lisa document the process for updating the newly acquired items. Additionally, a ticket will be created to look at automating the process as part of Phase 2.
