### ISSUE TITLE
Refine generic images for thumbnails to be implemented post-production

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#1117]
As discussed during one of our previous meetings, I would like you to complete the work to refine the generic images for the various resources types in the event thumbnail artwork is not available.

**Comment by eporter23** [comment]
@lovinscari I no longer have access to Adobe Illustrator, so re-drawing the icons we recently discussed will be difficult. As a second idea, I reviewed the icon set we have as part of our pattern library and generated these icons from that source. The good news is, some of these are in use on the library website already. I can do some basic refinements on these as needed (size and color).  ![Format Icons v2.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/fb471300-8fe8-47bb-989a-454652e1e41b)

**Comment by lovinscari** [comment]
@eporter23 - This looks good. If not already done, can you please complete the ticket for application developers to implement the previous solution for thumbnail artwork documented in ticket [#69](https://app.zenhub.com/workspaces/blacklight-catalog-5f5f84a8a6d29939a0bc5d78/issues/emory-libraries/blacklight-catalog/69). Thanks!
