### ISSUE TITLE
Update wireframes for search results and full item view to include thumbnail images

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#1118]
Stakeholders have expressed their desire to see thumbnails with each item record in search results and full item view. I thought there was a mockup for this in Figma but I am not finding it. The idea is for the thumbnail artwork to appear to the left of the item record as it currently does in discoverE with the thumbnail large enough to distinguish what it is but not so large that the size of the item record in search results increases dramatically. If artwork is available for the specific item then that is what will display as the thumbnail. Otherwise, one of the generic images for the resource type will be displayed. Layouts to show both artwork and generic image is desired. Once wireframes are completed, and refinements to generic images are finalized, please submit a new ticket for application developers to implement the changes.

****************
Working notes:
[Generic icons: Search Results - right-side](https://docs.google.com/drawings/d/1LuiU-Ca0Lu082988ERXw4zjPXpNfeqeCVgoXe4ftpNY/edit)
[Generic icons: Search Results - left-side](https://docs.google.com/drawings/d/13fdNcE6tMPmwArlPTkm5GjbGFAwTX0Pmf32TG7Cn72Y/edit)
[Real and generic icons: Search Results - right side](https://docs.google.com/drawings/d/18ALJST3AuYN121lZN_9jKj7qcKQt0vpsWkYdp6ycC34/edit)

Preferred layouts:
[Real and generic icons: Search Results - left side](https://docs.google.com/drawings/d/1o0emQAtT-4fJPX5vmXRIir03B4256xPQFU0UOZYZeJ0/edit)
[Single Item View (left aligned)](https://docs.google.com/drawings/d/1p2E52h4PLtqrpkKELgzsHJhbz4Ak0vMYBXmmymPIuUw/edit)

**Comment by eporter23** [comment]
@lovinscari I've added some mockups here for search results views. Let me know which you prefer (left or right-oriented) and I will begin working on the single item view layout.

**Comment by eporter23** [comment]
I discussed with @lovinscari and the left-aligned options are preferred. These are indicated in the description above.
