### ISSUE TITLE
SPIKE: Determine if "did you mean" can be disabled in Blacklight and identify any possible risks with disabling (if it is possible to do so)

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#1119]
Stakeholders have provided feedback that suggests they are annoyed with how the "did you mean" feature operates in Blacklight. Often the results returned with suggestions with the "did you mean" have no relevance to the search entered. I would like to see if it is possible to turn off this feature in Blacklight. If it is possible, I would also like to understand the possible risks with doing so. It is assumed if the "did you mean" is disabled then users would be presented with alternative language such as "your search provided no results. Please enter a new search or contact someone for help." Much nicer wording of course, but I would like to confirm this is also possible if disabling the feature.

Please document any findings within this ticket. I am suggesting all work within this SPIKE should be 5 points (one day) or less.

**Comment by abelemlih** [comment]
@lovinscari could you please provide an example of a search that triggers the "did you mean" feature? I am unable to recreate the issue

**Comment by lovinscari** [comment]
@abelemlih - From Paige Crowl in Health Sciences Library - Stealth Research: Is Biomedical Innovation Happening Outside the Peer-Reviewed Literature ![blacklightdidyoumeanexample.PNG](https://images.zenhubusercontent.com/5c4a1fe1e9b5fb46bcedb9fc/5a31f3b7-8dc2-41c0-a5be-64ca2058d33f)

**Comment by lovinscari** [comment]
@abelemlih - It looks like you have made the change on test? I wasn't sure if you found this to be possible to disable. I am assuming there are no negative effects for disabling this for now?

**Comment by abelemlih** [comment]
@lovinscari I will refer to @bwatson78, he worked on this ticket.
