### ISSUE TITLE
Please implement changes on Cascade to update the search box on Emory Libraries Home Page

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#1120]
Please implement the changes identified in ticket [#615](https://app.zenhub.com/workspaces/blacklight-catalog-5f5f84a8a6d29939a0bc5d78/issues/emory-libraries/blacklight-catalog/615) to update the search box on Emory Libraries home page within the Cascade CMS. The change should be implemented no earlier than 1/4/22 and no later than 1/5/22 as we will test this with our production launch test plan on 1/6/22. I am adding to the current sprint so you are aware of the requirements and will leave it up to you when to actually schedule the work and implement the changes for test and production.

**Comment by CB987** [comment]
search block updates applied to staging:
staging.libraries.emory.edu/about (must be on vpn to access)
![Screen Shot 2022-01-04 at 9.35.27 AM.png](https://images.zenhubusercontent.com/5d379c9d5221e52414fca85c/3a75e321-462f-4e8f-a8d4-5ff713c1bf1f)

**Comment by lovinscari** [comment]
@CB987 - Everything is working correctly. I am not sure if this is a big deal but when selecting any of the other search sources (Library Search or eJournals), the item selected turns gold and a down arrow appears beneath the item selected. This does not happen with Articles +. I don't consider this to be a big deal, but wanted you to know. Thanks!
