### ISSUE TITLE
Please update the search box on Emory Libraries home page within Drupal

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#1121]
Please implement the changes identified in ticket [#615](https://app.zenhub.com/workspaces/blacklight-catalog-5f5f84a8a6d29939a0bc5d78/issues/emory-libraries/blacklight-catalog/615) to update the search box on Emory Libraries home page within the Drupal CMS. The change should be implemented no earlier than 1/4/22 and no later than 1/6/22 for the Oxford site. All other sites in Drupal should be ready prior to their respective launch dates. I am adding to the current sprint so you are aware of the requirements and will leave it up to you when to actually schedule the work and implement the changes for test and production.

**Comment by CB987** [comment]
updates are applied and functional to drupal dev(test) sites. oxford:
![Screen Shot 2022-01-04 at 11.55.43 AM.png](https://images.zenhubusercontent.com/5d379c9d5221e52414fca85c/3166104d-4678-4c09-8c9c-62a50e8dab93)
main (both dropdown block and front page hero search block):
![Screen Shot 2022-01-04 at 11.56.05 AM.png](https://images.zenhubusercontent.com/5d379c9d5221e52414fca85c/6065aa01-6909-42dc-b996-8f779df1a803)

**Comment by lovinscari** [comment]
@clare - I tested the Oxford dev site (Drupal) and everything looks really good! Thank you!
