### ISSUE TITLE
STORY: Create a launch readiness checklist to review with Scrum team and gain input on prior to launch

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#1122]
We should create a launch readiness checklist for our production launch on 1/6/22 to ensure we have thought of everything needed for production launch. This [Launch Readiness Checklist](https://docs.google.com/document/d/1Q8akvnkFcen0gEihQGVaf-aIhK2MBAEA9xF2Y5ZoY30/edit?usp=sharing) will include input from the Scrum Team which will result in the completion of tasks prior to 1/6/22. Many of the items will result in the reference of existing tickets or creation of new tickets all of which will be completed according the specific instructions within the individual tickets. As such, the estimate for this Story will be the small amount of work to brainstorm tasks and the creation of new tickets. All members of the team are assigned to this ticket and are responsible for identifying tasks, referencing existing tickets, or creating new tickets. Because Zenhub only allows 10 assignees, I will assign the leads of each area to work with their respective teams and we will also review during mid-sprint checkin.

**Comment by libdgg** [comment]
@lovinscari all tickets for this story/epic have closed and we are past the launch date. i'm closing this epic/story. -DG
