### ISSUE TITLE
Discover DNS Redirection

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#1123]
From our operations meeting on 12/6/21, this is a placeholder to complete the work necessary for the DNS redirection from discoverE.emory.edu which will redirect to https://emory.primo.exlibrisgroup.com/discovery/search?vid=01GALI_EMORY:services. ExLibris will take care of all redirects possible from the Primo Classic UI to Primo VE views. According to @rotated8, the following tasks should be completed as part of this work. However, I am simply putting this ticket in as a placeholder in order to capture other tasks needed. Please update the ticket and complete the work as required.

- [x] Reach out to DNS team now as a heads up of work to be done explaining the changes should not be made with the redirects until 1/4/22 and no later than 1/5/22. 

- [ ] Similar to the website – we will have to reduce the TTL (how long you can cache an entry) to 1 hour or 6 hours – this requires enough time so it propagates out to those with a 3 day value.  

- [ ] Put in ticket for DNS team to make the change to redirect discovere.emory.edu to home page of service page view in Primo VE (CL to create ticket and ask Ann to put in details about URL).  - [INC03725417](https://emory.service-now.com/nav_to.do?uri=%2Fincident.do%3Fsys_id%3Df829d6204764895458f20923846d439a%26sysparm_record_target%3Dincident%26sysparm_record_row%3D1%26sysparm_record_rows%3D1%26sysparm_record_list%3Dactive%253Dtrue%255E123TEXTQUERY321%253DDNS%255Ecaller_id.user_nameSTARTSWITHjcromp%255EORDERBYDESCzztextsearchyy)

**Comment by jcrompton42** [comment]
OIT has responded with a contact number and scheduled the dns change for 10am on 1/6

**Comment by jcrompton42** [comment]
Change has happened.
