### ISSUE TITLE
Change banner on Library Search to reflect switch to production

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#1124]
On 1/4/22, please update the banner on Library Search with the following text. We can update the banner on test at any point prior to 12/15/21 but will not move this to production until 1/4/22. 

"Welcome to the new catalog search tool -  Library Search. Questions or concerns about the product can be sent to librarysearch@emory.edu. Please also visit our [help page](https://search.libraries.emory.edu/help) to view the user guide, help articles, and answers to frequently asked questions."

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/blacklight-catalog/pull/1130

![Screen Shot 2021-12-09 at 9.42.19 AM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/84044abf-2551-4dc0-9fe4-6f77e47b98e0)

**Comment by lovinscari** [comment]
Looks good.
