### ISSUE TITLE
Ensure metrics are in place to look at click through articles plus gem

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#1126]
Set up reporting in Google Analytics to track clicks on the Articles+  gem.

Tasks:
- [x] Create this report in GA4: Report name is Outbound Links - Primo Only. The outbound URL indicating use of the for the Articles+ gem is: "https://emory.primo.exlibrisgroup.com/discovery/search?vid=01GALI_EMORY:articles&query=any,contains,".  Data is available as of early March 2023.

- [ ] As currently configured, this data does not appear to be available in UA. Verify necessary configurations: Looks like it's a bit of a project to set up UA for this, and even then the data may not be retrospective. Not really worth it considering we now have the data going forward.

**Comment by tclayton33** [comment]
Closing this since the data is now available in GA4 as of March 2023, and that is sufficient for our needs. Therefore, it isn't really necessary (or worth the effort) to configure UA for this data and extract it.
