### ISSUE TITLE
Possible bug - author search + Title Starts with behavior

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/blacklight-catalog#1127]
To reproduce:

Do a keyword search for William Gibson
Locate a record where William Gibson is the author, and click on the hyperlinked author name (https://blackcat-test.library.emory.edu/?f%5Bauthor_display_ssim%5D%5B%5D=Gibson%2C+William%2C+1948-&sort=title_ssort+asc%2C+pub_date_isim+desc)
After those results load, click on Title Starts With > N 
1 record is found, but the results do not display.

![Screen Shot 2021-12-08 at 3.06.13 PM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/1e846278-b21f-40c8-bc32-dbc051c5f1c3)

This also occurred on the same search when I tried to limit it to Title Starts with Z (2 records, none display)

**Comment by bwatson78** [comment]
@eporter23 Tried to reproduce this bug, but am not seeing the `1 record found` response--just the no results page. Can you confirm?
