### ISSUE TITLE
Rebuild Primo Addon in Ares Client for Blacklight

### ISSUE THREAD

**Issue by lisahamlett** [emory-libraries/blacklight-catalog#1131]
The Course Reserves team pointed out that Bernardo built an integration that allows the staff to pull in data from primo to Ares for incomplete records faculty submit.  He worked with Atlas to build this where he wrote the server-side scripts to pull in data and Atlas built the integration, which is written in Lua.

His Readme is here: (ZenHub won'te let me upload an html file, so I converted it to text.)
[https://app.zenhub.com/files/295449627/8c6b7dcf-1e44-48f7-9785-849238ea61d3/download](https://app.zenhub.com/files/295449627/8c6b7dcf-1e44-48f7-9785-849238ea61d3/download)

Here is my documentation on how the addon works:
[https://app.zenhub.com/files/295449627/1d1bee57-214b-4eff-8ad2-5894b4739b96/download](https://app.zenhub.com/files/295449627/1d1bee57-214b-4eff-8ad2-5894b4739b96/download)

This only applies to Ares and addons are local, so they can be built and worked on locally or on Ares Test.
Additionally, Atlas is willing to work with us to build the addon and ILL is willing to pay for it if there is a cost, which Margaret seemed to think there was before.

**Comment by lovinscari** [comment]
Thanks @lisahamlett for drafting this. @libdgg  and @lisahamlett and @AGCooper - I am going to schedule a meeting for us after Alex returns in January to discuss this work.

**Comment by lovinscari** [comment]
Meeting conducted on 1/24/21. Actions for the meeting are @lisahamlett will contact ILL to confirm scope (just PrimoVE or Articles Plus). She will also reach out to Atlas to start the process of scheduling a meeting. Funding of the work by Atlas will happen once we know the cost estimate based on Statement of Work. Moving this ticket back to Ready until meeting with Atlas happens.

**Comment by lisahamlett** [comment]
We had the meeting with Atlas on 2/9.  Our contact, Sara Juel, is going to take the information back to their developer team to try to estimate the work that will need to be done for this.  She is also going to reach out to Ex Libris and let them know they are going to work on this.

**Comment by lisahamlett** [comment]
We have received confirmation from Ex Libris that they are going to keep the Primo Classic UI operational until the end of March so we have time to try to build the Ares/Blacklight addon.  At that point, the current addon will no longer work and there is nothing I can do about that.

I have not heard from Atlas with their timeline.  I will continue to stress that they need to get with our developers and set something up by the end of March.

I have no other information at this time.

**Comment by lisahamlett** [comment]
Atlas representative responded with this on March 1:

> Thank you for the responses. I'm going to meet with our more technical folks to talk about the responses. Afterward, I'll schedule a meeting to gather technical requirements and make sure our developers have all the info they need to understand the changes.

**Comment by lisahamlett** [comment]
Still waiting on Atlas, so I'm moving this to blocked and I will follow up with them.

**Comment by lisahamlett** [comment]
From Atlas:

> Hello Lisa,
 
I hope all is well. We talked to the product team and have some good news. They are happy to develop this addon as a public addon without any charge to you. The only thing that we ask is you document any work you have to set up on your end or how it's done so we can show other institutions how to configure the information required for importing. 
 
 
Before we can get started on the work, we also ask that you update the XML data (https://search.libraries.emory.edu/catalog/990022009440302486.xml) with any additional fields you would like to search a search/import for. For example, here are the fields Cornell used (but in JSON format):
 
 
Barcode 
Title 
Author 
Call Number 
Copy number 
Permanent location 
Edition 
Publisher 
Publication date 
Volume/Issue 
ISxN
 
{"HOLDING ID":[
  {"id":1,
   "copy":1,
   "enum":"v.1",
   "chron":"1991",
   "barcode":"123456789123",
   "call":"Oversize AB123.5 R11 1990",
   "location":{ CURRENT LOCATION DATA HASH },
   "permLocation":"DISPLAYABLE LOCATION NAME",
   OTHER FIELDS}]}
Thanks,
Access Services Product Manager

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/blacklight-catalog/pull/1259

```
<?xml version="1.0" encoding="UTF-8"?>
<document>
  <title>Arntz-Bulletin; : Dokumentation der Kunst des 20. Jahrhunderts. Bibliographie, Werk-Kataloge ...</title>
  <author/>
  <edition/>
  <publisher>[Distributed in U.S. by Wittenborn, Verlag G. Arntz-Winter]</publisher>
  <publication_date>1968</publication_date>
  <isbn/>
  <issn/>
  <holdings>
    <holding>
      <barcodes type="multi-value" delim="|">010000712412|010000712414</barcodes>
      <volumes_issues type="multi-value" delim="|">V.1|V.2 PT.1-6</volumes_issues>
      <call_number>Z5935 .A762</call_number>
      <copy_number>2</copy_number>
      <library>Library Service Center</library>
      <location/>
    </holding>
  </holdings>
</document>
```

**Comment by bwatson78** [comment]
There is a Markdown document detailing the values of the XML and how they are processed: https://github.com/emory-libraries/blacklight-catalog/blob/main/app/views/catalog/SHOW_XML_README.md

**Comment by AGCooper** [comment]
The add on has been deployed and is in production use. Any further configurations should be possible via the Ares application. If any further development on the Blackcat side is needed we'll create new tickets.
