### ISSUE TITLE
Replace author filter label when viewing results for a specific author

### ISSUE THREAD

**Issue by abelemlih** [emory-libraries/blacklight-catalog#1134]
Currently, when we search by keyword, a user can click on the author associated with a search result, and lookup documents associated with that specific author. The app then displays results with filter "AUTHOR DISPLAY SSIM > AUTHOR_NAME" instead of "AUTHOR > AUTHOR_NAME", as seen in the screenshot below:

![Screen Shot 2021-12-13 at 2.22.15 PM.png](https://images.zenhubusercontent.com/6151f04e7e6954612001d8f9/3c4de324-47a6-499a-8346-dcb3b30459b7)

We need to edit the filter label on the results page to display "AUTHOR > AUTHOR_NAME" instead.

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/blacklight-catalog/pull/1138

![Screen Shot 2021-12-14 at 10.23.14 AM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/3a4f7ada-107e-4157-ab7a-0758840091e8)
