### ISSUE TITLE
Update link in Search Tips on Advanced Search Page

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#1144]
Please update the link to the Search Guide in the last bullet of the Search Tips box on the [Advanced Search page ](https://search.libraries.emory.edu/advanced) to https://guides.libraries.emory.edu/LibrarySearchUserGuide

**Comment by abelemlih** [comment]
PR: https://github.com/emory-libraries/blacklight-catalog/pull/1148
