### ISSUE TITLE
Update page layout if no results

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#1146]
Since removing the "Did you mean" option from Library Search, the page that displays if there are no results is missing the facets. Additionally it has been suggested that we include a Tool Tip to search Articles Plus. 
![ScreenShot_NoResults.png](https://images.zenhubusercontent.com/5c4a1fe1e9b5fb46bcedb9fc/6c6fbf72-6e5b-40df-be0f-08533beb1646)

- [x] Please update the text to include the sentences "Please also try your search in [Articles + ](https://emory.primo.exlibrisgroup.com/discovery/search?vid=01GALI_EMORY:articles). Please [Ask A Librarian](https://emory.libanswers.com/) if additional assistance is needed."

- [x] Please reformat the page to include facets on the left side as referenced in the text. 

![Facets.png](https://images.zenhubusercontent.com/5c4a1fe1e9b5fb46bcedb9fc/9daea4d8-3806-495d-b733-d62e1f622b4d)

**Comment by bwatson78** [comment]
@lovinscari There is an issue with delivering facets when searches produce no results--as far as out-of-the-box Blacklight behavior is concerned. Solr builds the list of facets to deliver to the results page from the resulting list of documents a successful search produces. If there is not a successful search, Solr delivers no facet values to build the facet table with.
Thinking outside of the box, there could be a potential workaround. In the same fashion that the homepage is just an empty search, producing all records and, therefore, all available facets, we could redirect the user to an empty results page if the search they performed returned no documents. This would be a redirect, which means that their landing page would have no evidence of the previous search, but we could still control the elements, such as the Tool Tip, that you want to display. If this is the direction that you'd like to move in, I'd estimate the work to be at least a 5.

**Comment by lovinscari** [comment]
@bwatson78 - Thanks for the explanation. I believe we discussed before break, but just want to confirm the verbiage on the page if no results has been adjusted so that users are not encouraged to view the facets to the left?

**Comment by bwatson78** [comment]
@lovinscari After some discussion with @rotated8, we felt that the possible errant behavior caused by redirecting to a blank search page when no results were found wasn't something we were comfortable releasing to production. I've reverted the code that performed the redirect and have updated the verbiage with the Articles + recommendation. So we're back to the standard Blacklight behavior of no facets because we have no results to build them from.
