### ISSUE TITLE
Shibboleth lost our configuration

### ISSUE THREAD

**Issue by rotated8** [emory-libraries/blacklight-catalog#1154]
To reproduce:
- Visit search.libraries.emory.edu in an incognito window
- Click the Login button at the top right
- Click the Emory Users Login link
- Shibboleth says "The application you have accessed is not registered for use with this service."

Please contact Gerry (our contact with the Shibboleth team) for resolution.

**Comment by jcrompton42** [comment]
Fixed. While futzing with ansible to fix the ruby issue the shibboleth ID was overwrriten from blackcat-arch. Will also look into maybe some thousand eyes monitoring to detect this issue in future.
