### ISSUE TITLE
Possible bug with Articles Plus

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#1158]
Jenny Vitti has reported the following issue when searching Articles Plus - "I noticed an odd bug today in Articles+ that I don't remember seeing last week or earlier. I searched Articles+ with the terms: butler change. All of the results show "No Online Access," but when I click on each item, many of them do have online access. When I close the article view to go back to the search results, the items I have clicked now show "Online Access" appropriately (when access really is available), but I have to click into each item individually and go back to the results page to have all the results show up properly. This is happening in both Firefox & Chrome on a Windows 10 PC, in normal browser sessions and incognito/private sessions, for at least the first two pages of results (I stopped after the second page)."

**Comment by libah** [comment]
I put in a salesforce ticket to Ex Libris. Case number: 06222081

**Comment by libah** [comment]
Wrote back to Ex Libris 12/22/21. Have not heard back yet. will escalate if I don't hear anything today.

**Comment by libah** [comment]
I've tested this today and no longer see the issue. I wil test again tomorrow.

**Comment by libah** [comment]
Ex Libris could not duplicate the issue and now neither can I, it seems to have resolved itself.

**Comment by lovinscari** [comment]
Jenny confirmed she is also no longer seeing the issue.
