### ISSUE TITLE
Update Advanced Search page: sidebar tips

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/blacklight-catalog#1159]
On the [Advanced Search page](https://blackcat-test.library.emory.edu/advanced?q=on+the+river+with+lewis+and+clark&search_field=keyword&utf8=✓), please revise this bullet:

> Truncation and wildcards are not supported unless specifically noted. Word-stemming is done automatically.

as follows:

`Truncation and wildcards are supported using * (asterisk) or ? (question mark). Word-stemming is done automatically.`

**Comment by eporter23** [comment]
@lovinscari added this ticket while I was reviewing the libguide for this page.

**Comment by lovinscari** [comment]
@eporter23 - This looks good to me. Please move to To Deploy to Prod if you accept the work completed. Thanks.
