### ISSUE TITLE
Differentiate "Locate" and "Connect" availability buttons with CSS classes.

### ISSUE THREAD

**Issue by rotated8** [emory-libraries/blacklight-catalog#1168]
Right now, both the "Locate" and "Connect" availability buttons have a class of `avail-link-el`, but there is no way apart from reading the text of the button to see which is which. I propose we add different classes to the buttons depending on which availability it is connected to. Perhaps `avail-physical` for the "Locate" button, and `avail-digital` for the "Connect" button?

**Comment by abelemlih** [comment]
Ready for review: https://github.com/emory-libraries/blacklight-catalog/pull/1169

**Comment by lovinscari** [comment]
@rotated8 - can you take a look and make sure this meets your requirements?
