### ISSUE TITLE
SPIKE: Determine issue with electronic version of Chronicle of Higher Education not appearing in Blacklight

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#1170]
Rosalyn reported an issue this morning:
"I was looking for The Chronicle of Higher Education in library search and I noticed that all of the services that appear in DiscoverE’s Access Online Tab do not appear on the Services Page – mainly the link to the Chronicle’s website.  Quick sleuthing determined it’s because the record (MMSID 9936501806902486) that includes the link directly to the website isn’t showing up in Library Search.
 
Any ideas on why?  I can imagine that every administrator is going to search for that first….."

From Lisa Hamlett - This is most likely associated with deduping rules in Primo. The MMS ID is appearing in the Alma OAI Publishing Job but is not appearing in Blacklight for some reason. We believe if we find the answer to this we might see other anomalies. 

@rotated8 - has suggested we might want to take a look at the rules we have for indexing by developing a tool we can enter an MMSID to see what would happen in Library Search based on indexing rules.

**Comment by bwatson78** [comment]
This was a bug in the deactivated portfolio logic. I will have a pr shortly.

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/blacklight-catalog/pull/1175

No screenshots necessary.

**Comment by lovinscari** [comment]
@bwatson78 - thanks for resolving this so quickly. I tested 9936505354102486, 9936496113402486, 9937364954302486 and all are now appearing.
