### ISSUE TITLE
CSS refinements for "Locate" table

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/blacklight-catalog#1177]
Please make the following revisions to more closely align with the wireframe:

- [x] The font size on the table rows is slightly larger than on the wireframe; we want it to be more consistent with the font sizes used in the Availability badge. Suggested revision: make font size 0.875rem.
- [x] The Availability badge is showing up as centered, but should be left aligned in its column.
- [x] The table heading borders should be our standard light gray. It is currently showing a mix of blue and gray borders. Please remove the extraneous blue border.

![Screen Shot 2022-01-07 at 12.23.49 PM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/ee83eef4-b87b-43c4-b309-6606aad32136)

**Comment by abelemlih** [comment]
PR ready for review: https://github.com/emory-libraries/blacklight-catalog/pull/1183

**Comment by eporter23** [comment]
@abelemlih looks great! One revision: can you please make sure the <th> cells also get the smaller font size of .875rem? This will help with the mobile layout also.

**Comment by abelemlih** [comment]
Add more refinements per @eporter23's suggestions. PR ready for review: https://github.com/emory-libraries/blacklight-catalog/pull/1205
