### ISSUE TITLE
Refine mobile layout of "Locate" table

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/blacklight-catalog#1178]
At mobile sized view, the table data cells become disassociated from their headings. 

- [ ] Please revise the table so that the headings display as column headings vertically above their data cells. If possible, reduce the width of the columns for or reduce the overall width of the table to fit in narrower displays.
col 1 and col 2: 30% width; col 3: 40% width
- [ ] If needed, adjust the width of the availability badge in the table so that it fits in the new column size (~110px). Please leave the width of the badge above the table at the same width it is now.
- [x] If not addressed in separate tickets, please revise the `th` borders to be 1px light gray and remove the extraneous blue borders.
- [x] If not addressed in separate tickets, please  reduce the font size of the `th` and `td` so they are ~.875 rem.
- [ ] Related issue: please adjust the metadata field labels so that they are left-aligned in the mobile view for search results/bookmarks.
- [ ] Related issue: please add a bottom margin below the metadata field value so there is some spacing between the field/value entries.

Current output:

![Screen Shot 2022-01-07 at 12.29.22 PM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/7aaf75c0-0967-485b-beb9-99cd8ea37969)

Desired output:
![Screen Shot 2022-01-07 at 12.59.04 PM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/58ddcfb3-c68b-4fec-aca0-fe90c672f2ff)

**Comment by abelemlih** [comment]
PR ready for review: https://github.com/emory-libraries/blacklight-catalog/pull/1188

**Comment by eporter23** [comment]
@abelemlih looks great! Can you please make sure the <th> cells also get the smaller font size of .875rem? This will help with very small screens. Thanks!

**Comment by eporter23** [comment]
Looks great, @abelemlih, thanks!
