### ISSUE TITLE
BUG: Issue reported with affiliate login

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#1179]
The following issue has been reported with the affiliate login...

Mark, happy new year and thank you very much for this information. 

I did try to log in with the new system as you described, but I received the following error when clicking on the link sent to my email. 
User reported this 10:54 pm on 1/6/22
I’m not sure if this means there is a problem with the credentials for the email I am entering (dcossyleon@gmail.com) or if this is a bug that IT would need to handle. Screenshot attached.

Desiree

![affiliateerror.png](https://images.zenhubusercontent.com/5c4a1fe1e9b5fb46bcedb9fc/c6c403ec-2cc3-4cd9-8f6b-963fc4cbf37d)

**Comment by lisahamlett** [comment]
I have tried multiple times to replicate the error and was unable to do so.
I was even able to make this instruction packet.  No problem whatsoever: [https://app.zenhub.com/files/295449627/5327c76d-f1fd-4b99-891c-b53d28ea858f/download](https://app.zenhub.com/files/295449627/5327c76d-f1fd-4b99-891c-b53d28ea858f/download)

I see nothing wrong with the user's account in Alma either.

Perhaps ask them if they're still having trouble?

**Comment by eporter23** [comment]
I haven't heard anything, but will wait for @lovinscari. Moving into To Accept for now.

**Comment by lovinscari** [comment]
@rotated8 - we have not had any other errors but the same user continues to get the same error. I have forwarded you her email with the specific errors she is getting from the browser to see if you have any ideas before I suggest she get a new account. I don't know that it will make a difference if using the same email address.

**Comment by lisahamlett** [comment]
@lovinscari @rotated8 It looks like she's having issues before she gets to the email login screen by her screenshot.  Is she actually getting there?  Because if so, I can ask Ex Libris, but that Json error is on Library Search, not the services page.

**Comment by abelemlih** [comment]
@lisahamlett this issue is now resolved in production

**Comment by lovinscari** [comment]
User who reported the issue has been contacted and asked to verify she is now able to login.

**Comment by lovinscari** [comment]
User who initially reported issue confirms the issue has been resolved. Library Service Desk notified.
