### ISSUE TITLE
Replace banner on search.libraries.emory.edu

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#1181]
Because we need to reindex production in order for some electronic resources, please change the banner on prod with the following:

"Emergency maintenance is currently underway to resolve issues with the availability of some electronic resources. The reindex of the solr index will result in occasional abnormalities with search results. We apologize for this inconvenience. This maintenance is expected to complete by 5 pm on 1/11/22."

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/blacklight-catalog/pull/1182
