### ISSUE TITLE
Tabletop Support Exercise - Final Round of Support Model Development

### ISSUE THREAD

**Issue by libdgg** [emory-libraries/blacklight-catalog#1184]
- [ ] Recommended to then run second round of tabletop exercises using updated information to validate the model. Note any edits or changes. Alternatively, the LTDS support team can schedule weekly operational check-ins for the first 3 to 6 months after launch of the product or application to refine the support model and documentation over time and proceed with the remaining steps below.
- [ ]  Confirm any final access, permissions and setup for technicians needed for ongoing support and enhancement

**Comment by lovinscari** [comment]
Moving this under leadership responsibilities and out of backlog for the product.
