### ISSUE TITLE
Finalize Support Process Flow Diagram

### ISSUE THREAD

**Issue by libdgg** [emory-libraries/blacklight-catalog#1185]
- [ ] [Finalize the support process flow diagram](https://lucid.app/lucidchart/invitations/accept/inv_c3a1cae6-a58e-4584-8678-0d17b87601e2) (will be used for the OLA)

**Comment by lovinscari** [comment]
I am going to close this ticket as we will need to address how we are going to finish the operational work for Library Search and DLP (and other products) in a different forum.
