### ISSUE TITLE
Operating Level Agreement

### ISSUE THREAD

**Issue by libdgg** [emory-libraries/blacklight-catalog#1186]
- [x] Draft OLA
- [x] Review OLA with LTDS team supporting the product for input and review.
- [ ] Any agreement with Ex Libris that talks about support that we need to document in our support plans.
- [ ] Any Primo VE metrics - identify and document access and how they will be used for operations
- [ ] Review OLA with any team external to LTDS for input and revise.
- [ ] Final review of OLA with LTDS team to submit for approval.
- [ ] Review OLA with LTDS-L for approval. Include approval dates on the signature lines and update metadata. Make PDF of approved copy. Next scheduled review should be no more than 6 months for any new product or application.
- [ ] Post OLA in the approved folder of the [LTDS Technology Agreements OneDrive space](https://emory-my.sharepoint.com/:f:/r/personal/rmetz_emory_edu/Documents/LTDS%20Shared%20Documentation/LTDS-Technology%20Agreements?csf=1&web=1&e=ztshG4). A word copy should be placed in the Drafts folder for any revisions for the next version. All copies in the Approved folder should be PDF with all signatures, dates, version and metadata complete.

[Working Draft of OLA i](https://emory-my.sharepoint.com/:w:/r/personal/rmetz_emory_edu/Documents/LTDS%20Shared%20Documentation/LTDS-Technology%20Agreements/Drafts/OLA-Library-Search/OLA-LIBRARY-SEARCH-DRAFT-2022.docx?d=w662f03cffec845c4a6148f362c46456e&csf=1&web=1&e=dEVTBY)s in OneDrive in the LTDS Technology Agreements Folder.

**Comment by lovinscari** [comment]
I am going to close this ticket as we will need to address how we are going to finish the operational work for Library Search and DLP (and other products) in a different forum.
