### ISSUE TITLE
Indexing Tooling, part one.

### ISSUE THREAD

**Issue by rotated8** [emory-libraries/blacklight-catalog#1191]
- [ ] Create a rake task that takes one MMSID...
- [ ] ... gets the MARC xml for that MMSID from OAI-PMH ...
- [ ] ... runs the current indexing deletion and suppression rules ...
- [ ] ... and outputs whether the MMSID should show up in the index.

**Comment by abelemlih** [comment]
PR ready for review: https://github.com/emory-libraries/blacklight-catalog/pull/1195
