### ISSUE TITLE
Indexing Tooling, part two

### ISSUE THREAD

**Issue by rotated8** [emory-libraries/blacklight-catalog#1192]
- [ ] Split current indexing deletion/suppression rules into individual rules
- [ ] Allow a rule to describe itself, and why an MMSID triggers it.
- [ ] Update the commandline tool to use the new rules
- [ ] Update the commandline tool to report which rule prevents an MMSID from entering the index
- [ ] Update the incremental indexer and full reindexer to use the new rules, but without outputting the explanations.

**Comment by abelemlih** [comment]
PR ready for review: https://github.com/emory-libraries/blacklight-catalog/pull/1209

**Comment by lovinscari** [comment]
@abelemlih - Once you have confirmed the work is accepted, please move to To Deploy to Prod if applicable or please close. Thanks!

**Comment by abelemlih** [comment]
@rotated8 @lovinscari Reindexing in Test was successful, and I retested the tool for valid and invalid records, and everything works as expected. These changes are ready to deploy to production.
