### ISSUE TITLE
Change banner on landing page of search.libraries.emory.edu

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#1193]
Please remove the current banner on search.libraries.emory.edu regarding the emergency maintenance and replace with "As we continue to improve the NEW Library Search tool, please send any questions or feedback to librarysearch@emory.edu, consult with your [subject liaison ](https://libraries.emory.edu/contact/subject-librarian-directory.html), or [Ask a Librarian](https://emory.libanswers.com/). Thank you."

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/blacklight-catalog/pull/1206
![Screen Shot 2022-01-13 at 5.13.45 PM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/ed4aef3d-5398-4301-8397-d018ae124910)
