### ISSUE TITLE
BUG: Additional issues with electronic records - inventory type = collection in Alma

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#1194]
Sofia had reported this issue on 12/20/21 while I was out and I overlooked this with the chaos of trying to get everything ready for the production launch. Please let me know if there are any questions.

Sofia notes that the type of inventory for these in Alma is collection. These are all electronic collections  - both local and community zone.

While testing Kat and I discovered that electronic inventory type of collection/database doesn’t display in Blacklight. These are records are in ALMA and are not suppressed.  The record either displays with no inventory at all (CZ) or pulls electronic inventory from 856 link (local records). It worked correctly in DiscoverE.
Here are examples
`9937393300202486` (CZ record, electronic access doesn’t display at all in Blacklight)
`9937181020302486` (CZ record, electronic access doesn’t display at all in Blacklight)
`9937323316602486` (local record, electronic access comes from 856 link, not e-inventory)
`9937202715602486` (local record, electronic access comes from 856 link, not e-inventory)

**Comment by bwatson78** [comment]
For `9937393300202486`, no 856 or AVE in API response:
![Screen Shot 2022-01-13 at 4.57.53 PM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/667f72eb-e079-4735-8e9f-5c78d16c08c5)

**Comment by bwatson78** [comment]
Same as above for `9937181020302486`:
![Screen Shot 2022-01-13 at 4.59.15 PM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/208eb728-eee8-4e0c-850c-2ebb50c5454d)

**Comment by bwatson78** [comment]
For `9937323316602486`, there is no AVE to override the 856:
![Screen Shot 2022-01-13 at 5.02.05 PM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/82f8fbda-1745-4e66-9a0c-bba203f31a4d)

**Comment by bwatson78** [comment]
And the same goes for `9937202715602486`:
![Screen Shot 2022-01-13 at 5.03.25 PM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/e33ac1ca-5dad-417b-b3ec-1f36897e590d)

**Comment by eporter23** [comment]
This is deployed to prod but I am waiting for the next incremental index to kick in to do testing.

**Comment by bwatson78** [comment]
@eporter23 I haven't created code for this issue. Above, I pointed out that the fields that availability code would scrape to deliver the right badges are missing. I'm not sure if @lisahamlett or cataloging has examined and/or changed the listed records so that the fields will show, but the availability logic is working as expected.

**Comment by lovinscari** [comment]
@lisahamlett - Sofia inquired about this work again in an email on Friday, 1/28/22. I believe it is all the same information originally reported but I am copying the details below just to make sure...

"It appears that there are still issues with records with deactivated portfolios showing up in the library search.
 
Here are some example of records that should not be showing in library search, but do.
9937206359302486
9937173819902486
9936579826202486
 
I know that it was fixed at some point, but perhaps when you were fixing multiple portfolios issue, it got broken again.
 
What needs to happen is this: if all portfolios are NOT active, the bibliographic record should NOT be visible in the Library search at all. If at least one portfolio is active, the record should be visible like in examples below that work correctly.
9936505354102486
9936496113402486
9937364954302486"

**Comment by lovinscari** [comment]
@lisahamlett and @bwatson78 - Is there any way to move this ticket forward? I'm not sure if there are additional examples needed or what we need to do to try and resolve this. Thanks!

**Comment by lisahamlett** [comment]
Using this Link, I was able to see the OAI: `https://na03.alma.exlibrisgroup.com/view/oai/01GALI_EMORY/request?verb=GetRecord&identifier=oai:alma.01GALI_EMORY:[MMSID]&metadataPrefix=marc21`

9937206359302486 is  showing "not available" in the OAI.  I do not know why it is not being processed properly in Library Search.

`<datafield tag="998" ind1=" " ind2=" ">
  <subfield code="a">53440423970002486</subfield>
  <subfield code="e">Not Available</subfield>
  <subfield code="c">UNIV</subfield>
  <subfield code="b">BOOK</subfield>
  <subfield code="8">53440423970002486</subfield>
</datafield>`

9937173819902486 is  showing "not available" in the OAI.  I do not know why it is not being processed properly in Library Search.

`<datafield tag="998" ind1=" " ind2=" ">
  <subfield code="a">53433856730002486</subfield>
  <subfield code="e">Not Available</subfield>
  <subfield code="c">UNIV</subfield>
  <subfield code="b">STREAMINGV</subfield>
  <subfield code="8">53433856730002486</subfield>
</datafield>`

9936579826202486 is showing as "deleted" in the OAI.  I do not know why it is not being processed properly in Library Search.

`<header status="deleted">
  <identifier>oai:alma.01GALI_EMORY:9936579826202486</identifier>
  <datestamp>2021-12-16T19:15:06Z</datestamp>
  <setSpec>blacklighttest</setSpec>
  <setSpec>blacklight</setSpec>
</header>`

9936505354102486 is showing one "available" and one "not available" portfolio in the OAI.

`<datafield tag="998" ind1=" " ind2=" ">
  <subfield code="a">53300100950002486</subfield>
  <subfield code="e">Available</subfield>
  <subfield code="b">JOURNAL</subfield>
  <subfield code="8">53300100950002486</subfield>
</datafield>
<datafield tag="998" ind1=" " ind2=" ">
  <subfield code="a">53469465540002486</subfield>
  <subfield code="e">Not Available</subfield>
  <subfield code="c">UNIV</subfield>
  <subfield code="b">JOURNAL</subfield>
  <subfield code="8">53469465540002486</subfield>
</datafield>`

9936496113402486 does not have a 997 or a 998.  Availability is in the 9459s.

`<datafield tag="949" ind1=" " ind2=" ">
  <subfield code="c">Wiley Online Library</subfield>
  <subfield code="a">Wiley Online Library Backfiles Complete</subfield>
  <subfield code="u">http://emory-primoprod.hosted.exlibrisgroup.com/openurl/01EMORY/01EMORY_services_page?u.ignore_date_coverage=true&rft.mms_id=9936496113402486</subfield>
  <subfield code="e"> Available from 1987 volume: 1 issue: 1 until 1996 volume: 10 issue: 14.</subfield>
  <subfield code="f">611000000000002554</subfield>
  <subfield code="8">53469106880002486</subfield>
</datafield>
<datafield tag="999" ind1=" " ind2=" ">
  <subfield code="a">53469106880002486</subfield>
</datafield>
<datafield tag="949" ind1=" " ind2=" ">
  <subfield code="c">Wiley Online Library</subfield>
  <subfield code="b">HLTH</subfield>
  <subfield code="a">Wiley Online Library All Journals</subfield>
  <subfield code="u">http://emory-primoprod.hosted.exlibrisgroup.com/openurl/01EMORY/01EMORY_services_page?u.ignore_date_coverage=true&rft.mms_id=9936496113402486</subfield>
  <subfield code="e"> Available from 1997 volume: 11 issue: 1.</subfield>
  <subfield code="d">Transferred from Federation of American Societies for Experimental Biology to Wiley after 2019.</subfield>
  <subfield code="f">61110974475362507</subfield>
  <subfield code="8">53392055350002486</subfield>
</datafield>
<datafield tag="999" ind1=" " ind2=" ">
  <subfield code="a">53392055350002486</subfield>
</datafield>
<datafield tag="949" ind1=" " ind2=" ">
  <subfield code="c">Single Journals</subfield>
  <subfield code="a">Single Journals</subfield>
  <subfield code="u">http://emory-primoprod.hosted.exlibrisgroup.com/openurl/01EMORY/01EMORY_services_page?u.ignore_date_coverage=true&rft.mms_id=9936496113402486</subfield>
  <subfield code="e"> Available from 1987 volume: 1 issue: 1.</subfield>
  <subfield code="f">613780000000001486</subfield>
  <subfield code="8">53469106900002486</subfield>
</datafield>
<datafield tag="999" ind1=" " ind2=" ">
  <subfield code="a">53469106900002486</subfield>
</datafield>
<datafield tag="949" ind1=" " ind2=" ">
  <subfield code="c">Ovid</subfield>
  <subfield code="a">Journals@Ovid</subfield>
  <subfield code="u">http://emory-primoprod.hosted.exlibrisgroup.com/openurl/01EMORY/01EMORY_services_page?u.ignore_date_coverage=true&rft.mms_id=9936496113402486</subfield>
  <subfield code="e"> Available from 01/01/1999 volume: 13 issue: 1 until 02/28/2001 volume: 15 issue: 2.</subfield>
  <subfield code="f">61110992297990000</subfield>
  <subfield code="8">53469106920002486</subfield>
</datafield>
<datafield tag="999" ind1=" " ind2=" ">
  <subfield code="a">53469106920002486</subfield>
</datafield>
<datafield tag="949" ind1=" " ind2=" ">
  <subfield code="c">Federation of American Societies for Experimental Biology</subfield>
  <subfield code="b">HLTH</subfield>
  <subfield code="a">Federation of American Societies for Experimental Biology</subfield>
  <subfield code="u">http://emory-primoprod.hosted.exlibrisgroup.com/openurl/01EMORY/01EMORY_services_page?u.ignore_date_coverage=true&rft.mms_id=9936496113402486</subfield>
  <subfield code="e"> Available from 1987 volume: 1 issue: 1 until 2019 volume: 33 issue: 12.</subfield>
  <subfield code="d">Transferred to Wiley after 2019.</subfield>
  <subfield code="f">611000000000000097</subfield>
  <subfield code="8">53272241220002486</subfield>
</datafield>
<datafield tag="999" ind1=" " ind2=" ">
  <subfield code="a">53272241220002486</subfield>`

9937364954302486 is showing one "available" and one "not available" portfolio in the OAI.

`<datafield tag="998" ind1=" " ind2=" ">
  <subfield code="a">53464336860002486</subfield>
  <subfield code="e">Not Available</subfield>
  <subfield code="c">OXFD</subfield>
  <subfield code="8">53464336860002486</subfield>
</datafield>
<datafield tag="998" ind1=" " ind2=" ">
  <subfield code="a">53464644150002486</subfield>
  <subfield code="e">Available</subfield>
  <subfield code="c">OXFD</subfield>
  <subfield code="b">BOOK</subfield>
  <subfield code="8">53464644150002486</subfield>
</datafield>`

**Comment by lisahamlett** [comment]
Stupid ZenHub keeps trying to format my answer.

Here is the summary what I'm seeing:

[https://app.zenhub.com/files/295449627/120f8bc0-c475-4152-976f-4dd52f6724ed/download](https://app.zenhub.com/files/295449627/120f8bc0-c475-4152-976f-4dd52f6724ed/download)

@lovinscari

**Comment by lisahamlett** [comment]
If something is missing in the MARC record, that's up to Cataloging to fix.  I am not going to go modify their electronic resources.

**Comment by bwatson78** [comment]
For `9937206359302486` we are showing online availability because an 856 datafield is present. If you click on the connect button, a modal pops up--that only happens when the only online item available is a link pulled from an 856.

**Comment by bwatson78** [comment]
`9936579826202486` has been removed via single record indexing on both Test and Prod.

**Comment by lisahamlett** [comment]
From Ex Libris:

> I have investigated the question regarding dedup for the records 9936499081602486 and 990002643860302486 “Global divas [electronic resource] : Filipino gay men in the diaspora / Martin F. Manalansan.”
> 
> I confirmed that these two records are being deduped. However, the missing link to EBSCOhost LGBTQ+ Source is not due to the dedup process but instead because of the format of the URL.
> 
> The URL is an OpenURL for a local Alma record, and Primo expects that the URL parameter u.ignore_date_coverage=true should be added to OpenURLs for all local Alma records. If we add that parameter to the OpenURL, the electronic service will display properly:
> https://emory.primo.exlibrisgroup.com/discovery/openurl?institution=01GALI_EMORY&vid=01GALI_EMORY:services&rft.mms_id=9936499081602486&u.ignore_date_coverage=true

**Comment by lisahamlett** [comment]
I created a set of Sofia’s examples and published a new OAI called blacklightlisa which is supposed to publish collection information to a 996.  It's not pulling anything for collection: https://na03.alma.exlibrisgroup.com/view/oai/01GALI_EMORY/request?verb=ListRecords&set=blacklightlisa&metadataPrefix=marc21

I can't see anything consistent across these records.  I'll keep looking and reach out to Ex Libris.

**Comment by lisahamlett** [comment]
Case 06294466 opened with Ex Libris.
https://support.proquest.com/s/case/5003r00001SolguAAB/oai-publishing-collection-information

**Comment by lovinscari** [comment]
@lisahamlett - should we move this into blocked until ExLibris responds?

**Comment by lisahamlett** [comment]
@lovinscari I'd say yes, as there's not much else I can do.

**Comment by eporter23** [comment]
@lisahamlett Sofia sent this info and I'm passing along in case it is something to look into? 

```
Kat and I discovered some publishing information in ALMA for each record including database type records. I am not sure if it would help, but sharing just in case
 
Below is for MMSid 990003350960302486
It is accessible through Other details – Publishing information for electronic inventory
 
I am only pasting the part that is relevant to the inventory
 
<datafield tag="INT" ind1=" " ind2=" ">
            <subfield code="a">E</subfield>
          </datafield>
          <datafield tag="INST" ind1=" " ind2=" ">
            <subfield code="a">01GALI_EMORY</subfield>
          </datafield>
          <datafield tag="ECT" ind1=" " ind2=" ">
            <subfield code="a">database</subfield>
          </datafield>
          <datafield tag="CAT" ind1=" " ind2=" ">
            <subfield code="a">Arts_Architecture_Applied_Arts</subfield>
            <subfield code="b">Visual_Arts</subfield>
            <subfield code="c">Visual_Arts_General</subfield>
          </datafield>
```

**Comment by lisahamlett** [comment]
@eporter23 If you and Sofia want to use that, it can be done.  Just be aware that it doesn't fix the issue for things like this record, which I submitted the ticket about: https://na03.alma.exlibrisgroup.com/view/oai/01GALI_EMORY/request?verb=GetRecord&identifier=oai:alma.01GALI_EMORY:9936505354102486&metadataPrefix=marc21
You can't use the INT field for it because there is no INT field.  Nothing is being published in the electronic information because there is no attached portfolio, which was why I submitted the ticket in the first place.

Here's the full text of the ticket for your reference:

> Good Afternoon,
> 
> I'm hoping you all can help me figure out how to publish collection information to an OAI that doesn't have an attached item... For instance, MMSID 9937181020302486 has an electronic collection "Social Science Electronic Data Library (SSEDL)". This is also the resource's title, but there's nothing in the OAI to indicate its collection:
> https://na03.alma.exlibrisgroup.com/view/oai/01GALI_EMORY/request?verb=ListRecords&set=blacklightlisa&metadataPrefix=marc21
> https://na03.alma.exlibrisgroup.com/view/oai/01GALI_EMORY/request?verb=GetRecord&identifier=oai:alma.01GALI_EMORY:9937181020302486&metadataPrefix=marc21
> 
> Likewise, MMSID 9937389195302486 has a collection in Alma of "National Theatre Collections 1 & 2" but that doesn't show in the OAI at all:
> https://na03.alma.exlibrisgroup.com/view/oai/01GALI_EMORY/request?verb=ListRecords&set=blacklightlisa&metadataPrefix=marc21
> https://na03.alma.exlibrisgroup.com/view/oai/01GALI_EMORY/request?verb=GetRecord&identifier=oai:alma.01GALI_EMORY:9937389195302486&metadataPrefix=marc21
> 
> I am using the Publishing Profile "BlacklightLisa" which publishes from a set also called "BlacklightLisa." I have it publishing portfolio information including collection name, but these items don't have portfolios, so Alma isn't publishing anything to the OAI. I also have Collection Enrichment turned on and publishing to a 996, but that isn't collecting anything either.
> 
> How can I get the OAI to publish collection information for these records?
> 
> Thanks!!!
> Lisa

**Comment by lisahamlett** [comment]
To reiterate, it doesn't matter what is in the collection information.  The OAI isn't publishing it if there's no portfolio attached.  You can give it all the collections you like, but if it doesn't get into the OAI, it doesn't get into Blacklight.

**Comment by lisahamlett** [comment]
However, while I was out there was a comment from Ex Libris that no one responded to, so I will respond to the ticket now and see if I can make Ex Libris understand what we're asking, as they don't see to know or think it's an issue.

**Comment by lisahamlett** [comment]
From Ex Libris on 3/31:

> I believe I need a bit more clarification on what you believe the expected behavior is. Looking at the following OAI URL you provided for (MMS ID: 9937181020302486):
> 
> https://na03.alma.exlibrisgroup.com/view/oai/01GALI_EMORY/request?verb=GetRecord&identifier=oai:alma.01GALI_EMORY:9937181020302486&metadataPrefix=marc21
> 
> You mentioned that "For instance, MMSID 9937181020302486... there's nothing in the OAI to indicate its collection". Could you please clarify what you expect to see in the OAI that you are not seeing?

My response today:

> I am looking at that record (https://na03.alma.exlibrisgroup.com/view/oai/01GALI_EMORY/request?verb=GetRecord&identifier=oai:alma.01GALI_EMORY:9937181020302486&metadataPrefix=marc21) and all it has is standard MARC fields.
> 
> However, in Alma, the MMSID 9937181020302486 is tied to collection Social Science Electronic Data Library (SSEDL). For this record, the collection is the same as the title, but that is not the case in every instance.
> 
> For instance, for MMSID 9937389195302486, the collection name is "National Theatre Collections 1 & 2" (Collection ID: 61472108490002486) which doesn't show in the OAI at all: https://na03.alma.exlibrisgroup.com/view/oai/01GALI_EMORY/request?verb=GetRecord&identifier=oai:alma.01GALI_EMORY:9937389195302486&metadataPrefix=marc21
> 
> If these records had portfolios attached, I could publish the collection info to the OAI. But without the item attached, it won't publish the info. Is there any way to change that?

**Comment by lisahamlett** [comment]
Bad news from Ex Libris:
`Thank you so much for the additional details, this helped clarify the situation for me. It is very possible that this will require an enhancement request, because the publishing profile does not seem to include a way to enrich records with electronic collection information if the portfolios do not exist. This type of enrichment would normally occur in the "Electronic Inventory Enrichment section" of the publishing profile. 

The "Collection Enrichment" section will be irrelevant here because I believe that is enrichment for Alma (Digital) collections as opposed to electronic collections. 

All that said, I want to transfer this case to my colleagues on the Tier 2 team to confirm whether this is an enhancement or if it is possible. My colleagues will be in touch next!`

I suggest Kat and Sofia add dummy inactive portfolios to those records to force them to push to the OAI.  Other than that, I have no solution.  Alma will not do what they are asking.

**Comment by lisahamlett** [comment]
Confirming that Ex Libris is not going to make this information available via the OAI and Kat and Sofia will need to find another solution:

> The publishing is designed to publish the BIB record plus the enrichment fields. The Collection enrichment in the profile is for the Digital Collection, not Electronic collection. The descriptive BIB record does not have Electronic collection as its inventory, the inventory is only Physical/Electronic/Digital. 
> Adding Electronic Collection to the descriptive BIBs would be an enhancement request.

**Comment by eporter23** [comment]
Thanks @lisahamlett - I'll move this into To Accept for Cari to review and then I assume we'll close it.

**Comment by lovinscari** [comment]
I am going to close this ticket since this is not something we can resolve at this point.
