### ISSUE TITLE
Look at any refinements to be made for Bookmarks page layout in order to improve printing of booksmarks

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#1199]
Bo Adams reported issues with printing bookmarks, which is a common practice of those assisting patrons at the service desk. Per our discussion, there are a possible of changes that can be made to the layout of the bookmarks page that would improve the printing including removing availability information. This ticket to is identify possible changes and develop a new wireframe. Once the wireframe is completed, please submit a new ticket for application developers to implement the changes. 

Work notes:
[Draft wireframe](https://docs.google.com/drawings/d/1Ai-x8wdnHRiMNclZJvJVZ5epOtwjidMgNz_EVTbzTOQ/edit)

**Comment by eporter23** [comment]
@lovinscari I added a wireframe to the description above if you want to discuss it before I submit a implementation ticket.

**Comment by lovinscari** [comment]
@eporter23 - I think the wireframe looks good if you want to go ahead and submit for app dev. We can also review during our 1-2-1 meeting on 1/25/22 if needed. Thanks!

**Comment by eporter23** [comment]
New ticket created: #1216
