### ISSUE TITLE
Build a Solr Index with representative sample data from Alma

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#12]
As a member of the Blacklight Discovery Layer Technology Team, I would like to see sample data from Alma loaded into a Solr Index to begin to understand the XML Schema for Solr. 

Acceptance Criteria:

- [x] Run a sample publishing profile with test data from Alma based on a set number and type of records identified by the Alma Analyst (Lisa Hamlett) in coordination with members from the BDL1 SEND Team Members.
- [x] Developers should determine the best way to harvest the data from the Alma publishing profile (e.g., SolrMarc) to read MARC records and extract data from those records to build an Apache Solr Index.
- [x] Once the Solr Index is populated, document the fields and the types for future acceptance criteria associated with searching and indexing
- [x] Developers document specifics of Solr Index used for test in an effort to use as a benchmark against changes needed with publishing profile and/or data harvesting method.

**Comment by rotated8** [comment]
https://github.com/solrmarc/solrmarc

**Comment by devanshu-m** [comment]
PR: https://github.com/emory-libraries/blacklight-catalog/pull/32/

Changes/additions to get solr configured locally (and schema for production):
* Added instance and download directories for solr and also set `persist` to true, all of this in solr_wrapper. This is to make sure solr config is saved correctly and that indexed data persists in between builds, locally.
* Modified the schema to declare all fields (available so far) coming alma url. (more in the `solr/schema.xml` file in the repo)

Run rake task after `db:migrate`:
`RAILS_ENV=development bundle exec rails oai_harvest`
Here, we will get a from and to time. From time will be nil if starting import for the first time. These times are necessary to keep a track of last import and resume from that point to import new data. Once records are retrieved, java runs the `solrmarc` jar file using the config and index properties defined. This will start an index in solr and we can see this by sending a global params select query (*.*)

**Comment by tmiles2** [comment]
Once deployed, additional testing will be needed.

**Comment by wulman16** [comment]
I successfully ran the rake task and got sample data into my local Solr instance:

![Screen Shot 2020-11-12 at 12.16.14 PM.png](https://images.zenhubusercontent.com/5d653d8e0845ad5f24bad9f8/8c9b8409-f56b-4a3a-b244-2f074f4a57ef)
