### ISSUE TITLE
Make labels consistent between Resource Type facet and label on search results, single item view, and bookmarks

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#1200]
Stakeholder feedback indicates there is some confusion between the label "Resource Type" (facet) and "Type" display labels used in brief results.

Please change the display label for this field to "Resource Type" in:

- [x] search results
- [ ] single item view
- [x] bookmarks

Desired output:

![Screen Shot 2022-01-13 at 1.48.03 PM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/c690bcb4-9145-4589-8bbe-1b6fa47e739b)

**Comment by eporter23** [comment]
@lovinscari added a quick mockup to this ticket.

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/blacklight-catalog/pull/1204
![Screen Shot 2022-01-13 at 4.49.51 PM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/724ef8b5-c7ac-4119-a1e1-aca8a34959b2)
