### ISSUE TITLE
Scripts that are dependencies - identify and document for operational support

### ISSUE THREAD

**Issue by libdgg** [emory-libraries/blacklight-catalog#1202]
- [ ] Identify any scripts (e.g. [newly acquired items ticket](https://app.zenhub.com/workspaces/blacklight-catalog-5f5f84a8a6d29939a0bc5d78/issues/emory-libraries/blacklight-catalog/1116)) that Library Search is dependent on
- [ ] add this [information to the wiki](https://wiki.emory.edu/pages/viewpage.action?pageId=180229771)
- [ ] in the wiki documentation, please indicate the names/roles of people in LTDS that have the permissions/access to support them going forward

**Comment by AGCooper** [comment]
On turing.library.emory.edu
Newly acquired:

- crontjobs:
/alma/bin/newly_acquired.sh
/alma/bin/new_ebooks_process.sh

- Scripts (all in /alma/bin/):
new_items_analytics_list.py
new_items_create_xml.py
new_and_pending.py
new_and_pending.sh
new_check_pending.py
new_pending_items_process.sh
new_items_put.py
old_items.sh (probably broken)

**Comment by AGCooper** [comment]
On kleene.library.emory.edu
Aeon integration:

cgi-bin:

/usr/local/cgi-bin/process_booking_primo_new

Sccripts:
/sirsi/webserver/bin/process_primo_request.py
/sirsi/webserver/config/process_booking_primo_new.cfg
/sirsi/webserver/docs/process_booking_request.html

**Comment by AGCooper** [comment]
Not sure how much more detailed we can get without explaining programming.

**Comment by libdgg** [comment]
@AGCooper I added the checklist of steps to the description of this ticket to complete this work.

**Comment by lovinscari** [comment]
I am going to close this ticket as we will need to address how we are going to finish the operational work for Library Search and DLP (and other products) in a different forum.
