### ISSUE TITLE
Refine Keyword Basic Search

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#121]
As the product owner, I would like to refine the basic search for "keywords" based on work completed in Issue #95 to satisfy the following use case -

As an end-user, I would like to enter any keyword into the general search bar and because keyword is selected, the keyword search will search all fields including title, author, and subject.

- [ ] The metadata model https://docs.google.com/spreadsheets/d/1jSqgNd6HnVJdJMrrShAofkmK8uGgHGdlKODmZOL5NfY/edit?usp=sharing should be referenced when looking at all fields associated with keyword search including the MARC fields and subfields that should be mapped to each Solr field associated with keyword search. 

Use Case Example - When searching the catalog and entering the phrase Six Sigma, I should see approximately 1.420 records based on results when performing a similar search in discoverE (see screen shot below). It is assumed this example is primarily utilizing words in the Title Field but could also be included in subject.  

![AllFieldsSearch__SixSigma.png](https://images.zenhubusercontent.com/5c4a1fe1e9b5fb46bcedb9fc/b30d1432-597c-47d0-8cfb-427a2e578cf3)

**Comment by alexBLR** [comment]
@lovinscari do we have an updated metadata model for me to start this ticket?

**Comment by lovinscari** [comment]
@alexBLR - I just updated the ticket with the metadata model. I also added a new task (#134) to the In Sprint pipeline with a link to the Read Me file associated with the metadata model. Please slack me if you have any questions about this. Thanks!

**Comment by lovinscari** [comment]
Based on previous discussions, we agreed to limit the search to test data (Harry Potter related) currently indexed. I performed the search using the word Harry with the keyword context and received 150 results, which I am assuming to be inline with the test data set. I am accepting this story based on this context.
