### ISSUE TITLE
Deleted record removed from test but not prod

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/blacklight-catalog#1210]
A user reported this record having no holdings and was deleted by Sofia. It has been successfully removed from the test index:
https://blackcat-test.library.emory.edu/catalog/9937353743302486

but still appears in production:
https://search.libraries.emory.edu/catalog/9937353743302486

Report from the rake task is:
```
I, [2022-01-20T21:28:35.267567 #17176]  INFO -- : Setting 'from' time: 2022-01-20T20:11:07Z
I, [2022-01-20T21:28:35.274478 #17176]  INFO -- : Calling OAI with query string: ?verb=GetRecord&identifier=oai:alma.01GALI_EMORY:9937353743302486&metadataPrefix=marc21
E, [2022-01-20T21:28:35.701325 #17176] ERROR -- : Record #9937353743302486 is not valid for indexing for the following reason: Record #9937353743302486 is listed under deleted records.
```

**Comment by eporter23** [comment]
Update: @abelemlih manually reindexed this ID and it got deleted. So the short term issue is resolved but we may need to check why it failed to be removed during normal processes.

**Comment by bwatson78** [comment]
@eporter23 This would be a situation with two options that have been brought up in a previous standups. The first one is available to us now (reindexing individual MMSIDs, like @abelemlih did), and the secondis  doing a full reindex like the emergency maintenance one we did about a week ago. For incremental indexes, the deletion MMSIDs seem to only appear for a little over a day, then disappear. For full reindexes, those MMSIDs are a permanent fixture, and would eliminate the item(s) from the catalog.
@rotated8 mentioned previously the idea of having a backup Solr that we can kick off a reindex on silently, then switch to when complete. That's a brilliant idea, would love to code the solution for it, but I'm not sure where it stands in the priority list.

**Comment by eporter23** [comment]
Thanks for that info @bwatson78. We'll keep an eye on it. Sofia is doing some work to identify records with no holdings and delete them, so I'm sure there will be more examples coming in that we can monitor.
