### ISSUE TITLE
Update Search Tips link on homepage to point to correct pages

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/blacklight-catalog#1215]
The search tips link under the search box on the homepage is still pointing to the Blacklight wiki; we should update it to point to our new libguides location:

https://guides.libraries.emory.edu/LibrarySearchUserGuide

![Screen Shot 2022-01-25 at 9.30.19 AM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/d96756df-d151-4569-85c2-6e51ac52852f)

**Comment by eporter23** [comment]
@lovinscari this came up in the SEND team chat comments today so I wrote up this ticket. Please correct the description if that is not the correct URL to link to.

**Comment by lovinscari** [comment]
looks good.
