### ISSUE TITLE
Implement SOLR filters for ISBN, ISSN, LCCN

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/blacklight-catalog#1226]
This ticket follows the investigation from ticket #1208.

**Implement filters for searching and create new fields needed for:** 
- [ ] ISBN (isbn_t) - values should be based on `isbn_ssim`
- [ ] ISSN (issn_t) - values should be based on `issn_ssim`
- [ ] LCCN (lccn_t) - see additional notes below. Values should be based on `lccn_ssim`

Library of Congress call numbers have a specific format which includes spaces and punctuation. Example as entered in a catalog record: 

> DS51 .K7 K883

A user copying the call number from the spine of a book may see it presented as

> DS51
> .K7
> K883
> 

Some users may forget to add the period or don't use the correct spacing between call number elements. For Advanced Search, this can sometimes result in no matches. In Keyword Search, this can also be problematic because a user's search may match partially on the contents of the text_tesi field.

**Adjust search configurations to use the new fields:**

- [ ] Adjust Keyword Search to include new fields for ISBN, ISSN, LCCN
- [ ] Adjust Advanced Search > Identifiers to include new ISBN, ISSN fields 
- [ ] Adjust Advanced Search > Local Call Number to include the new LCCN field in addition to `local_callnumber_tesim`. 

**Update metadata and indexing documentation**
- [ ] Contact Emily to update the worksheet with new fieldnames

**To confirm:** 
- [x] can we use the LCCN filter on our existing `local_call_number_tesim` mapping? It includes multiple call number types, not just LCCN. If this doesn't seem like it will work, we can just add the new LCCN-specific field since most of our call numbers are LC. [no, we should create a new field as we are doing for the other filtered fields]
- [x] Confirm that we will keep the original fields in cause that we need them as display fields or for citation exports: `lccn_ssim`, `isbn_ssim`, `isbn_ssim`

**Comment by eporter23** [comment]
@lovinscari placeholder ticket here for ISBN enhanced searching

**Comment by lovinscari** [comment]
@abelemlih - I am assigning this to you since you worked on the spike ticket. I know it may not be able to move forward immediately since it requires working with @jcrompton42 but this ticket is ready whenever the two of you can work on it.

**Comment by eporter23** [comment]
@abelemlih thanks for the awesome demo today! I added some notes around library of congress call numbers (LCCN) but please let me know if you need more information about this use case.
