### ISSUE TITLE
Refine Single Item View: Add Staff View Link

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#123]
As the product owner I would like to refine the Single Item Display based on the answers provided in issue #102 to include a link to a MARC XML File similar to that found in the Staff View within discoverE which utilizes kleene.library.emory.edu. Moving forward, it will be necessary to have this XML file from the SOLR index as opposed to how the data is handled with kleene.emory (Core Systems Web Server). Having the link available within the single item view will provide information to the Scrum and/or SEND Teams when testing or troubleshooting issues with a particular record.  Alex Cooper or Laura Akerman can be consulted if there are questions about how kleene.library.emory.edu is configured with Primo. 

- [ ] This will be a hyperlink titled Staff View and placed at the bottom of the single item view record   
- [ ] When the link is selected, the record should open in a new tab within the browser.
- [ ] The output should contain the MARC Record associated with the item similar to the screenshot below but coming directly from the SOLR Index.

![MARCRecord_StaffView_DiscoverE.png](https://images.zenhubusercontent.com/5c4a1fe1e9b5fb46bcedb9fc/61e1f928-705c-4126-86be-080fd77460a2)

**Comment by AGCooper** [comment]
A different example (from Primo) would be the ExLibris way of displaying the record as it live in the Primo index:

http://discovere.emory.edu/primo_library/libweb/action/display.do?tabs=detailsTab&ct=display&fn=search&doc=01EMORY_ALMA21222867960002486&indx=4&recIds=01EMORY_ALMA21222867960002486&recIdxs=3&elementId=3&renderMode=poppedOut&displayMode=full&frbrVersion=&frbg=&&dscnt=0&scp.scps=scope%3A(repo)%2Cscope%3A(01EMORY_ALMA)%2CEmory_PrimoThirdNode&tb=t&vid=discovere&mode=Basic&srt=rank&tab=emory_catalog&vl(341573392UI1)=all_items&dum=true&vl(freeText0)=hello&dstmp=1611177814335&showPnx=true

The "&showPnx=true" is the key to getting that raw data.

**Comment by alexBLR** [comment]
@lovinscari and @AGCooper currently we have a **Librarian View** that accomplished the same functionality with the popup in tools. See attached screenshots.

![Screen Shot 2021-01-21 at 8.09.47 AM.png](https://images.zenhubusercontent.com/5c488275c10ae96cd915967b/b9b728b5-00bf-4029-8819-75638d3f2aea)

![Screen Shot 2021-01-21 at 8.10.02 AM.png](https://images.zenhubusercontent.com/5c488275c10ae96cd915967b/7ff9fb78-d450-4d02-9a8b-bb88d65d115d)


Do you still want to proceed with his ticket?

**Comment by lovinscari** [comment]
@alexBLR - I would like to talk about this during standup today to ensure this popup satisfies @mark-dce requirements from a troubleshooting perspective. Thanks!
