### ISSUE TITLE
Test possible resolution to suppress records that ONLY have unavailable electronic holdings

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#1230]
Per our discussion on 2/28/22, I would like to test the logic presented by @lisahamlett to not show any records that (1) has no 997, (2) has at least one 998, and (3) all 998s are "Not Available" regardless of 856
Aka “suppress records that ONLY have unavailable electronic holdings”

@bwatson78 - I am assigning this ticket to you since you were in the meeting yesterday. Please reach out to @lisahamlett if there are any questions about the logic presented. Once deployed to Test, I will ask Sofia and Kat to test. If this seems to resolve the issue they presented, I will ask a few others to test to ensure no adverse behavior.

**Comment by bwatson78** [comment]
PR: https://github.com/emory-libraries/blacklight-catalog/pull/1231

I attempted to test this code with the `blacklightemily` set, but it's 998e field equals `Available`, while it's individual record XML states it as `Not Available`.

**Comment by lovinscari** [comment]
Need to revisit how the OAI configured to determine how print and online is determined.

**Comment by bwatson78** [comment]
Just to summarize what's currently in Production: after a discussion awhile back with @lisahamlett, we reviewed our current logic in place and determined that the only missing ruling was that we allowed records with only deactivated portfolios that also had 856s to be indexed. The solution was to remove the 856 field blocker--now, the logic doesn't analyze whether the records in question even have 856s.

**Comment by tclayton33** [comment]
Consulted w/ Emily. Closing this issue - we can create a new ticket to do additional work if new information is discovered, or there are new reports of problems.
