### ISSUE TITLE
Revise content for Help page to enhance operational support

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/blacklight-catalog#1232]
After monitoring the feedback form submissions since launch, we are finding that most submissions are requests for search help, ordering items, or cataloging issues.

In order to make it easier for users to report problems vs. submitting user interface feedback, we want to reorganize the existing Help page to include additional service point contacts. 

We will essentially combine the content from the Help and Contact pages, and also make some updates for how to report problems.

- [x] Implement [changes noted in this wireframe](https://docs.google.com/drawings/d/1S6Dju5kitL3XQz9fkimqeyTgsTEhzj0hRtio96U2em8/edit?usp=sharing)
- [x] Update the link in the footer with link text "Help & Contacts"; link to` /help` 
- [ ] Remove the Contact page or redirect it to /help

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/blacklight-catalog/pull/1247

**Comment by eporter23** [comment]
Looks great @bwatson78! One thing I noted is that the homepage seems to be linking to https://search.libraries.emory.edu/help which threw me for a moment. But the relative link elsewhere to /help on test is looking good.
