### ISSUE TITLE
Revise Single Item View for problem reporting needs 

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/blacklight-catalog#1233]
In order to streamline problem reporting for users, we want to revise the sidebar items on the single item view. This work includes updating and moving some links from "Tools" into a new "Help" block. 

- [ ] Implement [changes noted in this wireframe](https://docs.google.com/drawings/d/1bYv7ShhJCBJFA10UoaLM0AXgOPvtVkmAQY8JSCAqtfs/edit)

**Comment by eporter23** [comment]
Looks great @bwatson78 !

**Comment by eporter23** [comment]
@bwatson78 got a request from Sofia to change "Harmful Language" to "Report Harmful Language". If you don't mind making that change before we deploy to prod that'd be great.

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/blacklight-catalog/pull/1256

![Screen Shot 2022-04-06 at 9.46.38 AM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/9c7f5632-0ab0-42c5-ab93-e216bf6e720a)

**Comment by eporter23** [comment]
Thanks @bwatson78 !
