### ISSUE TITLE
Revise availability badge text for no holdings state

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/blacklight-catalog#1234]
In order to better assist users who encounter a record with no holdings attached and see the message "Contact Us", we want to revise the text to make it more clear that there are no holdings for the item. We have received numerous submissions regarding this state, but users don't always understand what they are contacting us about.

Current output: Contact Us | CONTACT

![Screen Shot 2022-03-02 at 9.31.09 AM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/53c08012-8f2e-414a-aa67-e25d37083cd7)

Desired output: No Holdings | CONTACT US

![Screen Shot 2022-03-02 at 9.29.52 AM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/835e7e73-a1c6-4900-b5ce-3e263dbf7693)

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/blacklight-catalog/pull/1236

![Screen Shot 2022-03-02 at 10.37.27 AM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/4f4eb45a-9860-4446-b7be-87fad97878de)

**Comment by eporter23** [comment]
@bwatson78 looks good on the screenshot! At the moment I am having a hard time finding examples to check because we have done so much work on suppression and removing deleted records, etc. @lovinscari I think this should be good to go.
