### ISSUE TITLE
Revise homepage for post-launch operations

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/blacklight-catalog#1235]
As we have been live for nearly 2 months, we want to revise the homepage to better guide users for support, which includes removing the feedback form as the primary contact mechanism.

Implement the [changes noted in this wireframe](https://docs.google.com/drawings/d/1IWeIh7986IVUN7K7YbsozXBIXOsDcffXjQKpAZ-70rQ/edit):

- [ ] Remove or disable the current launch banner; we no longer want a banner to display (unless there is an issue to report in the future)
- [ ] Revise the text and links of the block of text beneath the searchbox

**Comment by abelemlih** [comment]
Ready for review: https://github.com/emory-libraries/blacklight-catalog/pull/1239

**Comment by eporter23** [comment]
Moving this into Accept because it's not yet deployed to production.

**Comment by eporter23** [comment]
Thanks @abelemlih! One thing I noticed is the Help link is absolutely linking to https://search.libraries.emory.edu/help - might be helpful to make it a relative link to /help?
