### ISSUE TITLE
Refine logic for "Online" status in Access facet

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/blacklight-catalog#1237]
The search reported below restricts results to Online access, but only one of the items is truly online. 

We revised our 856 mappings recently so that incorrectly coded 856s that do not actually provide full text access (e.g. Table of Contents only, etc) are mapped as related links instead. If we use the presence of an 856 to indicate online access, we should refine the logic so it is more precise to align with our `url_fulltext_ssm` field.

From feedback form submission on 3/2:

https://search.libraries.emory.edu/?f%5Blanguage_ssim%5D%5B%5D=English&f%5Bmarc_resource_ssim%5D%5B%5D=Online&page=1&q=Lu%2C+Xun%2C+1881-1936&search_field=author

What do we need to know?: 
I searched for Chinese author : Lu, Xun, 1881-1936 using author/creator simple search, and limited the results to Language: English. When I further limited the results to Online Access, I got 2 results. The first result did not show any online access that I could see (https://search.libraries.emory.edu/catalog/990007044760302486) so I'm wondering if this is indicating a problem with the facet.

**Comment by eporter23** [comment]
@bwatson78 when I repeat the original search in blackcat-test, it still shows a print resource with the Online facet toggled. Other examples I have spot checked are now working correctly, but can you take a look at [this search](https://blackcat-test.library.emory.edu/?f%5Blanguage_ssim%5D%5B%5D=English&f%5Bmarc_resource_ssim%5D%5B%5D=Online&q=Lu%2C+Xun%2C+1881-1936&search_field=author) to see why 990007044760302486 is being treated as "online" when it doesn't have a url_fulltext_ssm populated?

**Comment by bwatson78** [comment]
@eporter23 I'm attempting a reindex on just this record to see if it got passed by during that last full reindex.

**Comment by bwatson78** [comment]
@eporter23 When attempting a reindex, signs of an interrupted full reindex appeared. Reindexing just that record did fix the issue. Investigating the interrupted full reindex.

**Comment by bwatson78** [comment]
@eporter23 OAI stopped responding: 
```
I, [2022-03-17T08:47:54.518017 #23805]  INFO -- : Batch #4629, query string: ?verb=ListRecords&resumptionToken=all@all@blacklight@marc21@43081342950002486
I, [2022-03-17T08:47:54.518336 #23805]  INFO -- : Calling OAI with query string: ?verb=ListRecords&resumptionToken=all@all@blacklight@marc21@43081342950002486
F, [2022-03-17T08:48:01.120535 #23805] FATAL -- : Communication with the OAI Service failed.
F, [2022-03-17T08:48:01.120646 #23805] FATAL -- : end of file reached (Faraday::ConnectionFailed)
```

**Comment by eporter23** [comment]
@bwatson78 can you take a look at this search result where one of the items is showing up as online but it's a table of contents only? Is this a reindexing issue? https://search.libraries.emory.edu/?f%5Blanguage_ssim%5D%5B%5D=English&f%5Bmarc_resource_ssim%5D%5B%5D=Online&page=1&q=Lu%2C+Xun%2C+1881-1936&search_field=author

**Comment by bwatson78** [comment]
Looking now...

**Comment by eporter23** [comment]
Thanks @bwatson78 my bad - thought it had been deployed to prod. I'll move this into Blocked and note the dependency.

**Comment by lovinscari** [comment]
@bwatson78  Is there any way to pull this work out since we're not able to move forward with the work on other ticket blocking this one?

**Comment by eporter23** [comment]
This is now part of the current version which is deployed to test.

**Comment by eporter23** [comment]
@bwatson78 @lovinscari this looks good. I also spot checked some other oddball 856 examples (table of contents only, etc.) and they are also not showing up as Online in the Access facet.
