### ISSUE TITLE
Pass URL from Library Search to the Report Harmful Language LibWizard form

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#1243]
Sofia has asked if we can pass the URL of the page when a user reports harmful language in the catalog. I believe this will be the same process as the Feedback Form setup in ticket [#544](https://app.zenhub.com/workspaces/blacklight-catalog-5f5f84a8a6d29939a0bc5d78/issues/emory-libraries/blacklight-catalog/544). As @bwatson78 - any app developers will need to have admin access for the [Report Harmful Language LibWizard Form](https://emory.libwizard.com/f/harmful_language_catalog).

**Comment by bwatson78** [comment]
This has been done with the work in PR https://github.com/emory-libraries/blacklight-catalog/pull/1246

**Comment by eporter23** [comment]
Looks great, thanks!
