### ISSUE TITLE
What do we call this service when linking to it?

### ISSUE THREAD

**Issue by rotated8** [emory-libraries/blacklight-catalog#1244]
On the [Library website](https://libraries.emory.edu/), we say both "Library Search" and "Search the Emory Library Catalog"
![website.png](https://images.zenhubusercontent.com/544fb8857c6ccc6277a5b44e/df69931d-d7f8-47ff-a7d1-07d1de96ac3f)

On the [homepage](https://search.libraries.emory.edu/), we say "Welcome To Emory University Library Catalog"
![homepage.png](https://images.zenhubusercontent.com/544fb8857c6ccc6277a5b44e/24a4c344-e5dc-4618-9bb5-73b0ea0dbf6f)

And on the [About page](https://search.libraries.emory.edu/about), we see both "Library Search" and "Emory Library Search Tool"
![about.png](https://images.zenhubusercontent.com/544fb8857c6ccc6277a5b44e/79c076e9-88f3-4316-ad73-c78680750f34)

The [Help page](https://search.libraries.emory.edu/help) consistently says "Library Search"
![help.png](https://images.zenhubusercontent.com/544fb8857c6ccc6277a5b44e/c0c5b1ab-eb4a-4a95-8d35-b88ee517df6c)

The motivation for this ticket is a request to change the links and language on the [ETD application](https://etd.library.emory.edu/).
![etd.png](https://images.zenhubusercontent.com/544fb8857c6ccc6277a5b44e/3d2c795d-105c-4979-a707-708f75676163)

**Comment by lovinscari** [comment]
@rotated8 - where non-Library Search pages are concerned, let's follow the standard currently in place for the Libraries Website "Search the Emory Library Catalog"
