### ISSUE TITLE
Spike: identify options to create a link from the Services Page to the Library Search record view page

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/blacklight-catalog#1251]
We have received feedback from some users that they want a way to open the Library Search record page when viewing the Services Page for a particular MMSID if they have not arrived on the Services Page from Library Search directly. 

Examples:
- A user goes to My Library Card and wants to do things such as Cite or Bookmark something they have checked out. We don't provide "tools" in this view because ExLibris' options are different than ours.
- A user follows a FindIt@Emory link and ends up on the Services Page directly. They want to bookmark, print or cite it but cannot (for the same reason noted above).
- In both cases, to utilize Tools for the record, the user has to copy and paste the title and start a new Library Search session to get to the Blacklight record detail page.  

**Spike Question:** using Javascript and the services page URL parameters or other "Links" options in PrimoVE, can we construct a link from the Services Page to the record detail page for a given MMSID?

**Desired output for URL (link could be added to the Links menu or the header of the Services Page):**
https://search.libraries.emory.edu/catalog/990011894030302486

**Example Services Page url, which includes the MMSID:**
https://emory.primo.exlibrisgroup.com/discovery/openurl?institution=01GALI_EMORY&vid=01GALI_EMORY:services&rft.mms_id=990011894030302486

See also prior investigations about creating a "back link" from the Services Page back to Library Search. Prior work assumed users wanted to get back to search results or other pages from their browser history, however. For this ticket, we simply want to create a consistent link to the record detail in Library Search.

**Comment by eporter23** [comment]
@bwatson78 was able to generate a link to the catalog record and add it to the breadcrumbs trail. Preview in the sandbox here: https://emory-psb.primo.exlibrisgroup.com/discovery/openurl?institution=01GALI_EMORY&vid=01GALI_EMORY:services&rft.mms_id=990001636530302486

**Comment by lovinscari** [comment]
Work around Spike is completed. @lovinscari to determine when (and if) this work should move forward.
