### ISSUE TITLE
Spike: investigate workarounds for unexpected URL parameters sent to Library Search

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/blacklight-catalog#1255]
During the migration to Drupal, we uncovered a problem where the Google Analytics configuration for the Library sites are using cross-domain tracking. The links from libraries.emory.edu to search.libraries.emory.edu are receiving "link decoration" to help analytics join the sessions. See related ticket on [d9 repository](https://github.com/emory-libraries/d9-emory-libraries/issues/471).

Example of link decoration added by Drupal when a user creates a link to the Library Search homepage:
https://search.libraries.emory.edu/?_ga=2.254463560.1947920273.1649182547-1700922359.1649079393

_ga= will be consistent, but the other numeric portions are dynamic.

Problem: Blacklight thinks the `?_ga...` parameter is a query, which fails. This means trying to link to the Library Search homepage will always load what looks like a failed search results view for a user. 

![Screen Shot 2022-04-06 at 9.30.35 AM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/842c66e5-bed3-4565-8aae-96df4252419c)

This could also occur if users create other links with unexpected parameters.

We are continuing to explore options with Drupal's analytics settings, but want to investigate from the Blacklight side as well.

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/blacklight-catalog/pull/1257

![Screen Shot 2022-04-06 at 2.30.10 PM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/2399647e-1b0c-4fd5-9c59-c56ad432e2ee)
![Screen Shot 2022-04-06 at 2.30.38 PM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/a28f3def-5834-465e-8d72-68efb68cdd16)
![Screen Shot 2022-04-06 at 2.31.25 PM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/9d284965-6eb5-4414-8b19-3ff55831ace7)

**Comment by eporter23** [comment]
@lovinscari closing this because it is up and running on prod and working great.
