### ISSUE TITLE
Revisions for ISSN and ISBN searches

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/blacklight-catalog#1260]
This ticket follows work done in #1226 to enhance ISBN and ISSN searches. After deployment to production, the ILL team has reported a few anomalies related to ISSN searches specifically:

**0048671X** vs. **0048-671X**
In this case, I suspect the inclusion of "X" may be breaking the pattern we expected. The [ISSN specification does allow X in addition to numbers and hyphens](https://www.issn.org/understanding-the-issn/what-is-an-issn/).

NOTE: "X" is a valid character in the [ISBN specification also](https://www.isbn.org/faqs_general_questions#isbn_faq5).

**11417161** vs. **1141-7161**
In this case, our current metadata mapping for the 022 field includes both $a and $y which resulted in this record's ISSN being stored as `1141-7161 0008-0020`

```
022    a| 1141-7161 l| 1141-7161 y| 0008-0020 2| 7 0| (uri) http://worldcat.org/issn/1141-7161
```

For better formatting, we should revise the mapping to be 022a AND 022y so that each value is a separate entry such as follows:
`1141-7161`
`0008-0020`

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/blacklight-catalog/pull/1263

**Comment by bwatson78** [comment]
PR addressing X anomaly: https://github.com/emory-libraries/blacklight-catalog/pull/1265

**Comment by eporter23** [comment]
@bwatson78 @lovinscari looks great! This is ready to go to prod whenever that is next scheduled.
