### ISSUE TITLE
Allow "X" as a valid character for ISSN, ISBN optimized search filters

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/blacklight-catalog#1264]
This ticket follows work done in #1226 to enhance ISBN and ISSN searches. After deployment to production, the ILL team has reported a few anomalies related to ISSN searches specifically, but this could also apply to ISBNs:

0048671X vs. 0048-671X
In this case, I suspect the inclusion of "X" may be breaking the pattern we expected. The ISSN specification does allow X in addition to numbers and hyphens.

NOTE: "X" is a valid character in the ISBN specification also.

Fields to modify for the SOLR search filters:

issn_t

isbn_t

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/blacklight-catalog/pull/1265

**Comment by eporter23** [comment]
@bwatson78 @lovinscari looks great! This is ready to go to prod whenever that is next scheduled.
