### ISSUE TITLE
Revise mappings for subject fields (CATACOM request)

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/blacklight-catalog#1274]
At the request of CATACOM, we want to revise the subject field mappings used for search, display and facets. This change will build on our prior work to only include subject terms coded for certain controlled vocabularies.

General acceptance criteria from CATACOM:
- CATACOM would like ALL subject terms (6XX marc fields) to be included in indexing for search 
- CATACOM wants facets and display fields related to subjects/genres to only include terms from specified vocabularies (noted in mapping details)
- CATACOM would also like the discovery team to investigate suppressing terms if they are exact duplicates to prevent duplicate terms from different vocabularies to display multiple times.
- We should also maintain any other current functionality assigned to these fields, such as hyperlinking them to a search if applicable on the single item view page.

Mapping to revise for subject search:

- [ ] subject_tesim

Mappings to revise for facets and single item view:

- [ ] subject_era_ssim
- [ ] subject_geo_ssim
- [ ] subject_ssim
- [ ] genre_ssim
- [ ] subject_display_ssim

See the [metadata and indexing worksheet: filtered for subject fields](https://docs.google.com/spreadsheets/d/1jSqgNd6HnVJdJMrrShAofkmK8uGgHGdlKODmZOL5NfY/edit#gid=1979033236&fvid=848783766) for details

**Comment by abelemlih** [comment]
@eporter23 I have PR #1291 ready for this ticket. One last question: for field `subject_tesim`, we have the following requirements in the spreadsheet:

```
"Revised mapping for search field:

tag=600, code=[a-z]
tag=610, code=[a-z]
tag=611, code=[a-z]
tag=630, code=[a-z]
tag=650, code=[a-z]
tag=651, code=[az]
tag=653, code=[az]
tag=654, code=[az]
tag=655, code=[az]

REVISION 6/22: include all 6xx fields. Please include the above plus these:

656 a-z
657 a-z
658 a-z
662 a-z
688 a-z
690 a-z
691 a-z
692 a-z
693 a-z
694 a-z
695 a-z
696 a-z
697 a-z
698 a-z
699 a-z

Exclude exact duplicates. "
```

For fields 651, 653, 654, and 655, does `code[az]` mean all subfields a to z or just subfields a and z? I just wanted to confirm before submitting the PR for review.

**Comment by eporter23** [comment]
@abelemlih it means a-z, sorry for that being unclear. I'll update the mapping sheet.

**Comment by abelemlih** [comment]
This ticket should be ready for testing once a full reindex is complete on the testing instance.

**Comment by eporter23** [comment]
@abelemlih thanks for your work on this! Sofia and her team have tested this and reported that everything is looking great. They did, however, realize in testing that they omitted some subject headings from their mapping. @lovinscari and I asked them to submit those as a separate request.
