### ISSUE TITLE
Add admin role group using CanCanCan

### ISSUE THREAD

**Issue by abelemlih** [emory-libraries/blacklight-catalog#1275]
- [x] Add `CanCanCan` gem and add a new admin role group
- [x] Add admin ability to access the flipper features dashboard and enable/disable features on the site
- [x] Add admin ability to edit front page banner
- [x] Add admin dashboard with links to features above (flipper dashboard, banner editing page)
- [x] Add link to admin dashboard to homepage

Look into the banner editing feature in Hyrax as an example.

**Comment by eporter23** [comment]
@lovinscari closing this since it is in production now.
