### ISSUE TITLE
Improve Basic Search Behavior when using Text Strings

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#128]
Based on the demonstration provided on 1/12/21, it appears there is something not working correctly with the behavior in basic search when using text strings. This issue indicates the desired behavior and does not address the possibility of other behaviors described with text strings. 

As an end user, I want to use the search function to recognize a string of text as one search in the Blacklight Catalog much like the behavior in the current discoverE catalog. For example, I would like to enter a search phrase in the search box such as harry potter and the sorcerer stone and select Title in the search, and without quotation marks around the phrase. When entering this phrase, I expect the search results to return a list of records with Harry Potter and the Sorcerer's Stone in the title.

User Acceptance Criteria:

- [ ] Perform the test as described above in the example using title search (default) and entering harry potter and the sorcerer's stone in the search box without quotation marks. The returned items should include books and media with harry potter and the sorcerer's stone in the title or somehow related to harry potter and the sorcerer's stone.

**Comment by bwatson78** [comment]
![Screen Shot 2021-01-19 at 9.06.25 AM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/75c29c2b-da83-46e4-a421-90ce575700a4)

Have merged this into `main`. Before POs can test this, we have to wipe the Solr records and re-harvest.

**Comment by devanshu-m** [comment]
@lovinscari From blacklight arch:

![image.png](https://images.zenhubusercontent.com/5c12bc2dd3542818d52aa3a0/3a1a3eb6-3ea4-413b-9285-8677abbd9add)

![image.png](https://images.zenhubusercontent.com/5c12bc2dd3542818d52aa3a0/9eb63a77-1900-4892-a9a0-666c05e190ec)
