### ISSUE TITLE
SPIKE: Determine if there are any other options for sending records via SMS or text

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#1286]
A new enhancement request has been received to add a tool in Blacklight to send a record or call number information to my phone via text or SMS. Often when users are trying to reference a catalog record and/or if a subject librarian is working with a patron and wants to send an item record to a patron, there is not an easy way to do this without copy/pasting and then emailing the patron (or themselves). A librarian has also provided the following use case, "Text messaging is essential for stacks retrieval. Since my text app and my laptop are synched and I can copy and paste the call number and title and text it to myself. If not, I have to take a picture of the laptop screen with the call number and bring up the photo on my phone when I am in the stacks. " This use case was based on functionality that existed DiscoverE.

Some initial research by @rotated8 "Research from @rotated8: Sending text messages from an application hosted in AWS@Emory requires use of the following AWS services: SNS and Pinpoint, as well as a dedicated phone line. These do seem to be enabled, but having the sender phone number will require additional costs including one time setup fees estimated at $650 to set up, then $995/month plus ~$0.009/message"

I would like for this group to revisit this conversation once more to include research by others in the Blacklight community to see if there are any workarounds to the cost issue presented above. Please detail any additional findings in this ticket including what others in the Blacklight community are able to provide with a similar functionality.

**Comment by lovinscari** [comment]
Another option is twilio (per @rotated8) or SMS Gateways (text message via email - but this requires knowing the carrier of the user) and this would also require for email to be enabled.

**Comment by tclayton33** [comment]
Closing this one for now, but will probably want to revisit our options at a later date.
