### ISSUE TITLE
Enable search and display of barcodes

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/blacklight-catalog#1287]
This ticket is based on the enhancement request made by ILL/Atlas and other Library Search SEND team members to provide support for searching by barcodes. 

**New SOLR Field: Metadata Mapping:**

- [x] Create a new field that can support multiple values. From the OAI output, use` 997 $a ` which contains the barcode value(s)

**Search**
Please add the new SOLR field to:

- [x] Keyword search
- [x] Advanced Search > Identifiers

**Single Item View Display**
Please create a new display entry:

- [x] Label as Barcode
- [x] Display Barcode entries as the last element in the Additional Identifiers section:

![Barcode - display.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/ff945e57-f341-4c88-ada0-621d7bd9aafa)

**Comment by eporter23** [comment]
Looks great @alexBLR !

**Comment by tclayton33** [comment]
Deployed Dec 15, 2022
