### ISSUE TITLE
Ensure exact match for search results using basic title search

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#129]
As a library user, when performing a literal title search in basic search using the Title context, I expect to see results that exactly match the literal title I entered. For example, when entering Harry Potter and the Half-Blood Prince into the global search bar and selecting Title as the context of the search, I expect to get the following MMSID's (order could vary based on relevancy ranking) -

990005771480302486
990016747550302486
990016154450302486
990024937200302486
990030131990302486

_Examples of this not working as expected from Primo have been requested from the SEND Team._

**Comment by alexBLR** [comment]
This is the relevancy order that you currently get in arch:

990030131990302486 <- Non-musical Recording
990024937200302486 <- Visual Material
990024937200302486 <- Non-musical Recording
990035122590302486 <- Book (Electronic)
990016154450302486 <- Visual Material
990016747550302486 <- Book (Physical)
990005771480302486 <- Book (Physical)


![Screen Shot 2021-01-25 at 7.30.51 AM.png](https://images.zenhubusercontent.com/5c488275c10ae96cd915967b/5216bc86-f89e-4ffc-ac31-a2962019c425)

**Comment by alexBLR** [comment]
@lovinscari for all other examples of direct title search, it seems to be working as expected in Arch.
