### ISSUE TITLE
Temporary Items Missing from XML View for Ares Addon

### ISSUE THREAD

**Issue by lisahamlett** [emory-libraries/blacklight-catalog#1296]
The Reserves Team has pointed out that items in temporary locations aren't showing in the XML for the Ares Addon.

Here are their examples:
> 24HRES: https://search.libraries.emory.edu/catalog/990021350650302486.xml - missing 000011077368
> 3DRES: https://search.libraries.emory.edu/catalog/9936752865702486.xml - missing 010003041781
> 2HRES: https://search.libraries.emory.edu/catalog/990022524880302486.xml - missing 10002294394
> RESRV: https://search.libraries.emory.edu/catalog/990033468600302486.xml - missing 050000087214
> EXHIBIT: https://search.libraries.emory.edu/catalog/9936632414702486.xml - missing 010003047011
> The various new book categories (NEWBK,NEWACA,NEWNYT,NEWAC)
> e.g., https://search.libraries.emory.edu/catalog/9937466499202486.xml - missing 300000511142
> https://search.libraries.emory.edu/catalog/9936598458402486.xml - missing 010003027998

**Comment by bwatson78** [comment]
Preliminary findings: AVAs that aren't temporarily located still have subfield[code="8"] that we iterate over to pull holdings. Temporary holdings seem to now lack that field. Documentation [here](https://knowledge.exlibrisgroup.com/Alma/Product_Documentation/010Alma_Online_Help_(English)/090Integrations_with_External_Systems/030Resource_Management/100Publishing_to_Primo_and_Primo_Central) doesn't say anything about temporarily located items lacking this subfield.

@lisahamlett Please let me know if we can bring that subfield back or if I have to write a workaround.

**Comment by lisahamlett** [comment]
Example MMSID: 990021350650302486

https://na03.alma.exlibrisgroup.com/view/oai/01GALI_EMORY/request?verb=GetRecord&identifier=oai:alma.01GALI_EMORY:990021350650302486&metadataPrefix=marc21
In the OAI, 000011077368 is listed in both the 949 and 997 fields:
```
<datafield tag="949" ind1=" " ind2=" ">
  <subfield code="a">000011077368</subfield>
  <subfield code="b">EMU</subfield>
  <subfield code="c">wg</subfield>
  <subfield code="d">JV246 .B63 1987</subfield>
  <subfield code="t">b</subfield>
  <subfield code="z">ta/jm</subfield>
</datafield>
...
<datafield tag="997" ind1=" " ind2=" ">
  <subfield code="d">24HRES</subfield>
  <subfield code="b">BOOK</subfield>
  <subfield code="a">000011077368</subfield>
  <subfield code="c">UNIV</subfield>
</datafield>
```

However, it is not at all in the XML for that MMSID.
https://search.libraries.emory.edu/catalog/990021350650302486.xml

**Comment by lisahamlett** [comment]
All physical items have a 997 with the location, item type, barcode, and library.

**Comment by lisahamlett** [comment]
I previously commented about the 949, but I forgot that's a cataloger field and is unreliable and should not be used.

**Comment by lisahamlett** [comment]
I talked to Brad and he showed me there's a problem with the data from the bib API that is preventing us from pulling the holding information properly.  I have submitted case 06559567 to Ex Libris about the issue.

**Comment by bwatson78** [comment]
PR made: #1309

**Comment by bwatson78** [comment]
@lisahamlett If you feel comfortable marking this Accepted, can you? Otherwise, @lovinscari or maybe @eporter23, can you check for acceptance?

**Comment by tclayton33** [comment]
Closing this issue. Jenni Vitti's tracking document registers this issue as completed in Jan 2023, and Lisa also says is good to close. [see [enhancement #21 for tracking document](https://github.com/emory-libraries/librarysearch-enhance/issues/21)]
