### ISSUE TITLE
Temporary Items Not Showing in the XML for Ares

### ISSUE THREAD

**Issue by lisahamlett** [emory-libraries/blacklight-catalog#1297]
The Reserves Folks have discovered temporary items are not showing in the XML even though they're in the OAI.

For example:
24HRES: https://search.libraries.emory.edu/catalog/990021350650302486.xml - missing 000011077368
3DRES: https://search.libraries.emory.edu/catalog/9936752865702486.xml - missing 010003041781
2HRES: https://search.libraries.emory.edu/catalog/990022524880302486.xml - missing 10002294394
RESRV: https://search.libraries.emory.edu/catalog/990033468600302486.xml - missing 050000087214
EXHIBIT: https://search.libraries.emory.edu/catalog/9936632414702486.xml - missing 010003047011
The various new book categories (NEWBK,NEWACA,NEWNYT,NEWAC)
e.g., https://search.libraries.emory.edu/catalog/9937466499202486.xml - missing 300000511142
https://search.libraries.emory.edu/catalog/9936598458402486.xml - missing 010003027998

**Comment by bwatson78** [comment]
This is a duplicate of #1296. Please see preliminary findings in that ticket.

**Comment by lisahamlett** [comment]
This is a duplicate of 1296
