### ISSUE TITLE
SPIKE: Determine if Fuzzy Search results functionality can be refined or removed temporarily

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#130]
As the product owner, I previously asked for the fuzzy search relevancy that is standard with the current Blacklight Catalog to be implemented. However, the functionality of the basic fuzzy search is not always helpful and presents results that are not user friendly.

This seems to be happening primarily when entering a call number or MMSID into the keyword search as shown in the screen shot below.
![MMSIDFuzzySearch.png](https://images.zenhubusercontent.com/5c4a1fe1e9b5fb46bcedb9fc/17f5cc11-b5fa-4e41-a759-10d89c2cb8cf)

I would like for the application developers to determine if this functionality can be refined so that a fuzzy search only appears when the results of the search do not match the search term in any way. If entering an exact or similar search term, it is assumed the results returned are sufficient and do not require the "Did you mean to type..." 

If this cannot be refined without more specific acceptance criteria or will take more than 2 days to refine, then I would like to see if the fuzzy search can be temporarily disabled.

Acceptance Criteria (time bound to a 5)

- [x] Review the current functionality of fuzzy search

- [x] Determine the work involved with refining the fuzzy search based on the above information and document the steps needed in this ticket. If it appears the work for refinement is extensive (more than two days) then

- [x] Determine if the fuzzy search functionality can be temporarily disabled and update the ticket with this information.

**Comment by devanshu-m** [comment]
Fuzzy Search (Did you mean..)

Basic Search:
* Results for search query are returned in a solr response. This response contains an array of hashes with spellcheck suggestions. Each hash within it contains:
  * `numFound` - number of suggestions found
  * `origFreq` -  frequency of each original term in the index
  * `suggestion` - the value for this key contains an array of hashes with two keys. `word` which is the suggested word and `freq` is frequency of that word in the index.

![image](https://user-images.githubusercontent.com/17075287/116320476-4c26ce80-a786-11eb-9f55-19517e81b6ac.png)

In the above example, I searched for `pot` which returned five suggestions, hence, numFound is 5. Each suggested word has a frequency. The suggested word gets added to the list of suggestions only if it's frequency is greater than `origFreq`. Refer: https://github.com/projectblacklight/blacklight/blob/master/lib/blacklight/solr/response/spelling.rb#L57

**Comment by lovinscari** [comment]
@devanshu-m this is very helpful. Thanks.
