### ISSUE TITLE
SPIKE: Search and Indexing teach out

### ISSUE THREAD

**Issue by mark-dce** [emory-libraries/blacklight-catalog#131]
**ISSUE**
As a team, we would like a deeper understanding of how Solr and Blacklight configurations interact, so that we can more effectively code and test the new catalog application.

**ACCERPTANCE**
- [x] Identify a team member to facilitate the teach out (mark-dce)
- [ ] Facilitate a discussion and hands-on exercises covering relevant topics (including, but not limited to)
   - [ ] Solr schema configuration
   - [ ] Dynamic field mappings
   - [ ] Index tokenization
   - [ ] Query tokenization
   - [ ] Blacklight search field configuration
- [ ] Record the session to share with others within LTDS who have an interest in Solr indexing

**Comment by tmiles2** [comment]
Teach out slide deck: [https://docs.google.com/presentation/d/1iguya5KgvbN0gi7UeI65vObkb2OaHw2BRmCk54R3zfU/edit#slide=id.gb75ddc227a_0_130](url)

Audio: [https://emory.zoom.us/rec/play/-eu3vYVliv62bAzMO60l-HgJIruQFrC3K0UQT_hoY-EydPbejPC7tKLsUybgyiLHJK4Mz3he0fegT5e1.xq2B3zK_Crfxkn0D?continueMode=true](url)
