### ISSUE TITLE
Make availability on the item show page async

### ISSUE THREAD

**Issue by rotated8** [emory-libraries/blacklight-catalog#1315]
Right now, the "Where to find it" section on item show pages tries to load availability before the page is returned to the requestor. This leads to issues when the availability API is not available.

![Screenshot_20230118_075750.png](https://images.zenhubusercontent.com/544fb8857c6ccc6277a5b44e/28ac0fc8-3569-4dd2-b443-1f61e51bc69b)

The goal of this ticket is to change the "Where to find it" section to get the availability data asynchronously, so that the page can load without waiting.

**Comment by bwatson78** [comment]
PR made: #1316 . This is live in Test and Arch. @rotated8 and/or @eporter23, can you test and review for Prod deploy?

**Comment by abelemlih** [comment]
Released under v1.9.0.

**Comment by tclayton33** [comment]
Ready to deploy to production
