### ISSUE TITLE
Upgrade Blacklight to 7.33

### ISSUE THREAD

**Issue by abelemlih** [emory-libraries/blacklight-catalog#1325]

**Comment by abelemlih** [comment]
Ready for testing on Arch. These changes will only go through PR approval once the feature branch is tested and approved on Arch/Test.

**Comment by tclayton33** [comment]
@abelemlih I've discovered that a number of the links within the full records aren't working properly. Clicking on them is routing the user back to a top level "empty" search. So in Arch (currently) this is routing me to a result set of 249,481 records.

Links that aren't working:
additional author/creator - 9936814551202486 
subject - 9936814551202486
uniform title - 9936494594602486

Links that appear to be working:
author (both in the brief display and full record)
genre
language

**Comment by abelemlih** [comment]
Deployed to production under v1.12.0. A full reindex is in progress.

**Comment by abelemlih** [comment]
@tclayton33  v1.12.0 deployment is complete. This is ready to close.
