### ISSUE TITLE
Update SolrMarc version

### ISSUE THREAD

**Issue by devanshu-m** [emory-libraries/blacklight-catalog#133]
- [x] Update the SolrMarc version that is being used in the rake task

**Comment by tmiles2** [comment]
Devanshu will provide an update and close this ticket

**Comment by devanshu-m** [comment]
We are moving in a different direction now and using marc_indexer to map values from alma to SOLR. Brad is working on a rake task to convert XML MARC records we get from ALMA OAI to raw MARC records so that the internal indexer rake task can use it.
