### ISSUE TITLE
Review metadata model and associated read me file

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#134]
As the product owner, I want to ensure the software engineering team has a thorough understanding of the metadata model being developed for the Blacklight Catalog index. This is a work in progress and is subject to change as new information is obtained. The metadata model itself will be referenced in individual stories.

Link to the Read Me File - https://emory.box.com/s/df08z5ydg64n6g9x2w1p2c4dw3jdqjfh
Link to the Metadata Model - https://docs.google.com/spreadsheets/d/1jSqgNd6HnVJdJMrrShAofkmK8uGgHGdlKODmZOL5NfY/edit?usp=sharing

Review completed:

- [x] @alexBLR 
- [x] @bwatson78 
- [x] @rotated8 
- [x] @devanshu-m 
- [x] @mark-dce 
- [x] @mlooney

**Comment by devanshu-m** [comment]
Suggestions:

Please update following SOLR fieldnames if and when possible:
### SOLR Fieldname - Blacklight Label 
marc_display_tesi - MARC display
text_tesi - Text
language_facet_tesim - Language
format_tesi - Format
marc_resource_tesim - Resource Type
isbn_ssim - ISBN
issn_ssim - ISSN
lccn_ssim - LCCN
oclc_ssim - OCLC
other_standard_ids_ssim - Other Standard Identifier
publisher_number_ssim - Publisher Number
material_type_display_tesim - Physical Type Description
title_display_tesim - Title[Display] 
title_vern_display_tesi -Title[Vernacular]
title_addl_tesim - Title[Additional Title]
title_added_entry_tesim - Title Added Entry
title_ssort - Title sort
subtitle_display_tesim - Subtitle [Display]
subtitle_vern_display_tesi - Subtitle[Vernacular]
title_series_tesim - Series Title
title_abbr_tesi - Abbreviated Title
title_key_tesi - Key Title
title_host_item_tesim - Parts??
title_preceding_entry_ssim - Related titles
title_translation_tesim - Additional titles
title_varying_tesim - Sub/Alternate titles
title_former_tesi - Previous Title
title_enhanced_tesim - ??
title_graphic_tesim - ??
author_display_tesim - Author/Creator[Display]
author_addl_tesim - Additional Author/Creator
author_vern_display_tesim - Author/Creator[Vernacular]
subject_tesim - Subject
subject_addl_tesim - Subject[Additional]
subject_topic_facet_tesim - Subject[Facet]
subject_era_facet_tesim - Era
subject_geo_facet_tesim - Region
published_display_tesim - Publisher[Display]
published_vern_display_tesim - Publisher[Vernacular]
pub_date_tesi - Publication Date
lc_callnum_display_ssi - LC Call Number [Display]
lc_1letter_facet_tesi - Call Number[Facet]
lc_alpha_facet_tesi - LC Alphabetical Facet
lc_b4cutter_facet_tesi - LC Cutter Facet
url_fulltext_display_tesim - ??
url_suppl_display_tesim - ??
nonformat_table_contents_tesim - Contents
summary_tesim - Summary
local_note_tesim - Local Note
participant_performer_note_tesim - ??
creation_production_credits_tesim - ??

**Comment by mark-dce** [comment]
Is it possible to get a count or percentage of total representing how many of the total corpus of catalog records have data in each field represented in the metadata model?

e.g.
100% of ecords have 1: MMSID populated
97% of records have 14: Display Title populated
63% of records have 3: OCLC Number populated
48% of records have 6: ISBN Number populated
...
12% of records have 71: Contents populated
8% of records have: 25: Uniform title populated
1% of records have: 41: Participant/Performer Note populated
etc.

This information would help us prioritize the order in addressing analysis, decision making, and development to implement the various fields in search, faceting, display, and other contexts.
