### ISSUE TITLE
Library Search Help page - URL edits

### ISSUE THREAD

**Issue by tclayton33** [emory-libraries/blacklight-catalog#1358]
We’ve created a new [Library Search User Guide](https://guides.libraries.emory.edu/LibrarySearchUserGuide) and a few edits are needed to the [Library Search help page](https://search.libraries.emory.edu/help) to reflect those changes:

Under “Search Tips & FAQs”: 
1.	Update the target of **Library Search Frequently Asked Questions** to point to the FAQs page in the new guide: [https://guides.libraries.emory.edu/c.php?g=1317573&p=9689031](https://guides.libraries.emory.edu/c.php?g=1317573&p=9689031)
2.	Remove link (text and url): **Moving from discoverE to Library Search FAQ's** – this guide is being retired
3.	**Note:** no edits are needed to the url for Library Search User Guide (the new guide uses the same friendly url)

Under “Emory Libraries Service Contacts”:
1.	Remove link (text and url): **Ask eJournals** – original target/service no longer exists and the replacement is covered by the Report a Problem link lower on the page

**Comment by abelemlih** [comment]
@tclayton33 this ticket is ready for testing

**Comment by tclayton33** [comment]
@abelemlih these changes look good
