### ISSUE TITLE
Implement MARC Field Mapping with display labels on single item view

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#138]
As the product owner, I would like the MARC Fields mapped to the display labels on the single item view as indicated in the file (see ticket #140) so that when a field is displayed it is correlated to the correct MARC field. Emily Porter will continue to refine the metadata fields currently not mapped working with the software engineering team to add the fields that need to be mapped as tasks related to this story. 

This ticket relates to #140.

This story is less about design and more about data mapping itself so refinement of how text is displayed will be detailed in future stories or issues. 

As part of this work we should also update the Metadata Model Worksheet to indicate what is already mapped and the current SOLR filenames.

MARC/SOLR mapping info:

- [Metadata Model Worksheet](https://docs.google.com/spreadsheets/d/1jSqgNd6HnVJdJMrrShAofkmK8uGgHGdlKODmZOL5NfY/edit#gid=1979033236)
- [View Item Detail: Metadata Sources translation](https://docs.google.com/document/d/1_qgOXn8SUzdrJOO0KD8IBvAmHFLymQ8K2GDQP1I1M90/edit#)

**Comment by rotated8** [comment]
Question for @lovinscari - What differences would you expect to see when this is complete versus #140?

**Comment by tmiles2** [comment]
This work is noted in ticket #140; closing this one out.
