### ISSUE TITLE
Modify publishing procedures from Alma sandbox to Blackcat-Arch

### ISSUE THREAD

**Issue by tclayton33** [emory-libraries/blacklight-catalog#1380]
Our Ex Libris Linked Open Data focus group needs to be able to test how records created in Bibframe are displaying in a Blacklight test environment. I met with Collin, Sofia, and Laura and the desired solution is to use blackcat-arch for this purpose. 

Please set up the following:

- [ ] Clear the data currently in Arch
- [ ] Configure the Alma sandbox data to publish to Arch (I *think* the data currently in Arch already comes from the Alma sandbox)
- [ ] Publish the current Alma sandbox content to Arch (Collin will work with Lisa to make sure we have a set in place for this)
- [ ] Set up incremental updates that run once/day to pick up new/changed/deleted records in the Alma sandbox

**Comment by tclayton33** [comment]
Discussed with Ayoub 1/11/24 and we have a current operating timeline:
-Start work within a week
-A week to complete adjustments to settings/configs
-A day for Ayoub to complete his part

This timeline (a little less than 2.5 weeks to completion) would give Sofia and Laura a little over a week to test before our Feb 11 sandbox refresh. I've reached out to confirm this is acceptable.

**Comment by abelemlih** [comment]
@tclayton33 reindexing is complete on Arch, and this ticket is ready to close.
