### ISSUE TITLE
Create Solr Hot Spare Script

### ISSUE THREAD

**Issue by rotated8** [emory-libraries/blacklight-catalog#1381]
Currently, scripts exist to delete, backup, and restore a collection in Solr. This ticket will combine some of those features to allow us to automatically have a "Hot Spare" of the Search collection.

The script should:
- [ ] Delete any existing "librarysearch_collection_hotspare" collection
- [ ] Find the most recent backup of the "librarysearch_collection" collection
- [ ] Restore that backup to a new "librarysearch_collection_hotspare" collection

This script (and any existing ruby scripts for interacting with Solr) should live in a new folder "/lib/solr" in Search's repo.

**Comment by abelemlih** [comment]
PR: https://github.com/emory-libraries/blacklight-catalog/pull/1383

**Comment by abelemlih** [comment]
I added the script to the Test instance and ran it. A new hot spare collection was added successfully. I changed the Solr collection used in the Test instance to the hot spare so we can test it. This ticket is ready for testing.

**Comment by tclayton33** [comment]
@abelemlih Search functionality and index size all check out fine in Test. Does anyone besides me need to look at any other aspect of this in order to complete testing?

**Comment by abelemlih** [comment]
@tclayton33 your approval is the only one we need. We can proceed forward with creating a hot spare for production as soon as possible. @rotated8 when would be a good time to submit a CAB request for this change?
