### ISSUE TITLE
Spike: troubleshoot holdings not showing in Arch

### ISSUE THREAD

**Issue by tclayton33** [emory-libraries/blacklight-catalog#1386]
Bibframe records in Arch are not displaying inventory (showing print or electronic holdings), even though they have inventory according to the Alma sandbox. Here are some examples: 
9937772399902486
9937772300102486
9937772200102486

The inventory information is not missing from the OAI, which points to the issue being somewhere between Alma and Blacklight:
https://emory-psb.alma.exlibrisgroup.com/view/oai/01GALI_EMORY/request?verb=GetRecord&identifier=oai:alma.01GALI_EMORY:9937772399902486&metadataPrefix=marc21

https://emory-psb.alma.exlibrisgroup.com/view/oai/01GALI_EMORY/request?verb=GetRecord&identifier=oai:alma.01GALI_EMORY:9937772300102486&metadataPrefix=marc21

https://emory-psb.alma.exlibrisgroup.com/view/oai/01GALI_EMORY/request?verb=GetRecord&identifier=oai:alma.01GALI_EMORY:9937772200102486&metadataPrefix=marc21

**Comment by tclayton33** [comment]
Ayoub has investigated and reports (in Incident INC04196523 work note) that the breakdown is occurring at the point of the api call to Alma for real time availability. The xml that is returned is missing the values our code is expecting to indicate if the holdings are physical or electronic ("record/datafield[@tag="AVA"]" OR "record/datafield[@tag="AVE"]/subfield[@code="e"]"). Since neither is present, no holdings are shown. 

To verify this is the root issue, Ayoub tested a different record, ID #9937686688802486, which shows availability in Arch, and it does have data for datafield "record/datafield[@tag="AVA"]" in its XML, hence why availability is shown.

We can't fix this on the Blacklight end since we are just reading data from Alma. Next steps are either to open a ticket with ExLibris or check to see if something is different between the configuration of Alma and the Alma Sandbox. @rotated8 and @lisahamlett I'm not sure which is the best next step.

**Comment by lisahamlett** [comment]
I have verified there is no difference between the OAI configurations for Alma Production and Sandbox.

**Comment by lisahamlett** [comment]
Here's problem #1...  9937772399902486 is tied to different records in production and sandbox.

Production:
![Screenshot 2024-02-02 093610](https://github.com/emory-libraries/blacklight-catalog/assets/32074210/088ea5ba-3d4a-494a-b329-c1ecb0610f65)

Sandbox:
![Screenshot 2024-02-02 093804](https://github.com/emory-libraries/blacklight-catalog/assets/32074210/41ba4ce4-56da-4be9-8b18-8e3292b73270)


I recommend using a record that is the same in both systems for comparison.

**Comment by lisahamlett** [comment]
9937772300102486 is in Sandbox but not in production:

![Screenshot 2024-02-02 094225](https://github.com/emory-libraries/blacklight-catalog/assets/32074210/b268657d-3b33-459a-bea0-b0ddddb0eafa)

Once again, I can't compare what's different between the records because the items isn't even in production.

**Comment by lisahamlett** [comment]
And, of course, 9937772200102486 is also not the same record in Production and Sandbox:

![Screenshot 2024-02-02 094411](https://github.com/emory-libraries/blacklight-catalog/assets/32074210/d4e77581-d6ee-43e3-b28d-f936148653b1)

**Comment by lisahamlett** [comment]
@tclayton33 In order to tell Ex Libris that we're seeing one thing in production but not in sandbox, I need examples that are the same in both systems and not giving you what you want.

**Comment by lisahamlett** [comment]
Also, @tclayton33, keep in mind that the Sandbox refresh is February 11 at 3am, so we might want to wait to talk to ExL until after that since the data will be different then.

**Comment by tclayton33** [comment]
SRU querying was implemented in [#1415](https://app.zenhub.com/workspaces/blacklight-catalog-5f5f84a8a6d29939a0bc5d78/issues/gh/emory-libraries/blacklight-catalog/1415) and deployed to Arch under v1.14.0.
