### ISSUE TITLE
Some record links return the full database of results

### ISSUE THREAD

**Issue by tclayton33** [emory-libraries/blacklight-catalog#1387]
Testing of the Blacklight 7.33 upgrade has revealed that several types of the links in the full record display aren't working properly. When clicked, they are returning all records in the database instead of running a search on the link.

**The following types of links are returning the full database:**
additional author/creator - 990035122070302486 ; 9936814551202486
subject - 9936814551202486
uniform title - 9936494594602486

<img width="1422" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN3NzQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6a006a9a0bdfb1763230657a28c3eb676d78860e/search%20on%20additional%20author.PNG" alt="search on additional author.PNG" />

**These links appear to be working properly**
author (both in the brief display and full record)
genre
language

**Comment by abelemlih** [comment]
@tclayton33 I deployed a fix for this issue to Test, and it is now ready for testing.

**Comment by tclayton33** [comment]
@abelemlih clicking on a record's author/creator, subject, and additional author links now executes the same search we are see in prod, so this issue is resolved. I'm closing the ticket.
