### ISSUE TITLE
Articles+ gem should appear after 3rd result

### ISSUE THREAD

**Issue by tclayton33** [emory-libraries/blacklight-catalog#1388]
In the testing environment for Blacklight 7.33 the Articles+ gem appears after the 2nd result. It should appear after the 3rd result, as it does in production.

**Example from production:**
<img width="696" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOU1zQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b4da26436bf50f69bf868133b07bdb0dcbdbf0f6/articles%20gem%20location.PNG" alt="articles gem location.PNG" />

**Comment by abelemlih** [comment]
@tclayton33 this issue was fixed and is ready for testing on the Test instance

**Comment by tclayton33** [comment]
@abelemlih all fixed - this looks good
