### ISSUE TITLE
SPIKE: Scheduled synch with Alma - Performance Test

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#14]
As a product owner, I would like to know if there’s any performance impact related to when we run synchronization with Alma, so that I know whether there are any performance constraints that we need to include in the system design and scheduling

- [x] Determine current frequency Alma syncs with Primo and determine if synchronization times with Blacklight should happen at the same time or off times based on possible impact to Primo and length of time each synchronization process takes to complete.

- [x] Communicate proposed synchronization plan to Primo Product Manager and Blacklight Product Owner so both can communicate with stakeholders and monitor and problems with performance.

- [x] Update the OAI-PMH Harvest schedule for Blackcat-Test to run on the schedule identified in step 1.

- [x] The performance test should be run against Blackcat-Test

- [ ]  Run a one week test (work week, M-F) of the proposed synchronization schedule as proposed and capture performance data and stakeholder feedback.

- [ ] If performance problems are presented, modify the schedule and rerun the test for a period of two days to see if performance problems are resolved. Repeat process as needed until performance issues are no longer presented.

**Comment by lisahamlett** [comment]
I will set the 4x a day schedule in Alma for the OAI on Monday, April 12, so it doesn't run over the weekend in case there are issues.

This means Primo and the main Blacklight OAI will publish at 02:00, 08:00, 14:00, and 20:00.

**Comment by lisahamlett** [comment]
The main Blacklight OAI publishing job will now run four times a day at 04:00, 10:00, 16:00, and 22:00.
Primo publishes at 02:00, 08:00, 14:00, and 20:00.

I did not realize I was supposed to be using Blacklight Test, so I turned it on for the main Blacklight OAI.  As of now, everything is running as expected.  Primo is still loading in 15-30 minutes with no hiccups at all.  The main Blacklight OAI is running in 2-3 hours which is the standard it has been at for a while.

**Comment by lisahamlett** [comment]
The Blacklight publishing job from Alma is running successfully 4 times a day and averaging 3.5 hours to run.  The full log is here: [https://app.zenhub.com/files/295449627/97233102-8569-4e5a-b18e-399baaa8d037/download](https://app.zenhub.com/files/295449627/97233102-8569-4e5a-b18e-399baaa8d037/download)
