### ISSUE TITLE
Use Test instance for a full reindex of Solr

### ISSUE THREAD

**Issue by abelemlih** [emory-libraries/blacklight-catalog#1402]
A full reindex impacts Solr performance significantly in production. In this ticket, we will explore running a full reindex on the Test instance, which typically points to the same ALMA endpoint and collection, and use the Test collection's backup to recreate the Solr collection in production. This process will enable us to fully reindex the collection used in production with very minimal downtime and little impact on Solr performance in production.

Requirements:

- [ ] Run a full reindex on Test, ensuring the environment uses the same ALMA endpoint/collection as Production. The Test instance must also have the same version as Production.
- [ ] Export a backup of the fully reindexed collection in Test
- [ ] Use the backup to recreate the Solr collection used in Production
- [ ] Update documentation to reflect new practices

**Comment by abelemlih** [comment]
One additional requirement from the team meeting: use the hot spare collection on production to perform the backup from the newly reindexed collection on Test, then swap collection used by the application from existing collection to the hot spare.

**Comment by tclayton33** [comment]
Finished w release v1.16.3 on 11/20/24
