### ISSUE TITLE
Create Link in Single Item View for "More in this Series"

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#141]
As a library user viewing a single item record that is part of a series, I would like a link within the single item view titled "More in this series" that links to additional records that are part of that series. (User Acceptance Criteria and examples of MMSID's) to be provided prior to sprint planning.

- [Metadata spreadsheet](https://docs.google.com/spreadsheets/d/1jSqgNd6HnVJdJMrrShAofkmK8uGgHGdlKODmZOL5NfY/edit#gid=1979033236)

**Comment by rotated8** [comment]
We can use field id 22 from the metadata spreadsheet to find the series title, and if it is not blank, add a link to do a search for that title

**Comment by lovinscari** [comment]
Duplicate
