### ISSUE TITLE
In Arch environment, implement SRU to query availability/location

### ISSUE THREAD

**Issue by tclayton33** [emory-libraries/blacklight-catalog#1415]
As a solution for our BibFrame records not showing real time availability/location information in the Arch test environment, Ex Libris has asked that we replace using the Alma Bib Api with SRU (Search/Retrieve via URL). 

**Info from Ex Libris:**
The dev team is looking at this and has diagnosed the problem: When adding the availability of records to the Retrieve Bib API, the API adds a MARC field to the MARC records to show the availability. For BIBFRAME records, the MARC inventory field cannot be added. 
There is an alternative that works and functions for BIBFRAME and MARC records, and that is using the SRU. Once you configure the SRU to support inventory in the integration profile, you can retrieve the inventory for MARC and BIBFRAME records by searching by MMSID. Can you please try this? 
You can view the documentation for the SRU configuration here:
[https://developers.exlibrisgroup.com/alma/integrations/sru/
https://knowledge.exlibrisgroup.com/Alma/Product_Documentation/010Alma_Online_Help_(English)/090Integrations_with_External_Systems/030Resource_Management/190SRU_SRW_Search](https://developers.exlibrisgroup.com/alma/integrations/sru/
https://knowledge.exlibrisgroup.com/Alma/Product_Documentation/010Alma_Online_Help_(English)/090Integrations_with_External_Systems/030Resource_Management/190SRU_SRW_Search)

Additional documentation is located on issue #1404 (includes information provided during the 4/11 meeting with Ex Libris where they provided information on querying multiple MMS IDs)

**Comment by abelemlih** [comment]
Draft PR: https://github.com/emory-libraries/blacklight-catalog/pull/1419. I will submit it for approval on Monday.

**Comment by abelemlih** [comment]
Deployed to Arch under v1.14.0. @tclayton33 this ticket is ready for testing on Arch.

**Comment by tclayton33** [comment]
current records for testing:
9937864400102486
9937864399902486
9937864399702486
9937864399502486
9937864300102486
9937864299902486
9937864299702486
9937864299502486
9937864299302486
