### ISSUE TITLE
Create link to nearby items on the shelf in Single Item View Page

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#142]
As a library user, I would like to see nearby items on the shelf when viewing a single item view in the event there are other materials associated with the call number I am searching. (User Acceptance Criteria and mockup to be provided prior to sprint planning)

**Comment by rotated8** [comment]
Primo appears to use the Dewey  Decimal number for ordering items on a shelf. That info is stored in MARC 082, which we do not appear to have mapped currently.

**Comment by lovinscari** [comment]
Closing this for now as we will address this in Browse Search by Call Number.
