### ISSUE TITLE
Create a 404 Error Page in Blacklight

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#143]
As a library user, I would like to see an error "404 Error - Page Not Found" in the event I select a single item record that cannot be found or displayed for a particular reason. This story is simply to develop the static page in Blacklight and use cases for when the 404 Error page will be detailed in a separate story.

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/blacklight-catalog/pull/157

![Screen Shot 2021-01-25 at 12.00.35 PM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/1fb311e7-19af-4cd8-8582-6f9af9671af8)
