### ISSUE TITLE
Use AlmaAvailabilityService in the show action for single item view

### ISSUE THREAD

**Issue by devanshu-m** [emory-libraries/blacklight-catalog#145]
As I understand this, we need to show the availability for an item when a user goes to its show page. I think a good approach here would be to use the AlmaAvailabilityService that @bwatson78 has created in the show action and request the availability of an item when a user goes to view the item.

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/blacklight-catalog/pull/150

![Screen Shot 2021-01-22 at 5.00.21 PM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/9e9640fa-1fa0-4aed-87f3-358c778aaf1e)
![Screen Shot 2021-01-22 at 5.00.49 PM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/5b756c6f-38c8-4958-8c28-0676427a97e3)
![Screen Shot 2021-01-22 at 5.01.30 PM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/e9186112-7367-4424-877e-9f3624f81aa3)

**Comment by bwatson78** [comment]
Fixed the capitalized "A" in "UnAvailable".

![Screen Shot 2021-01-25 at 9.19.00 AM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/9a79f619-d201-4238-b823-4683bb238939)
