### ISSUE TITLE
RESEARCH: Requesting item and ALMA check out process

### ISSUE THREAD

**Issue by devanshu-m** [emory-libraries/blacklight-catalog#149]
In this ticket, I intend to research, understand, and create a workflow for requesting an item from alma via blacklight. I will be using the document shared by Alex Cooper: https://developers.exlibrisgroup.com/blog/integrating-with-alma-s-real-time-availability-and-get-it/ to understand the integration, and also the alma item check out presentation created by Lisa.

**Comment by lisahamlett** [comment]
Let me know if you need any help from me on this, Devanshu.

**Comment by devanshu-m** [comment]
We went through the tutorial as a group and created new tickets for implementing the get it tab with the request link as shown in the tutorial by ExLibris. We will also be referring to the alma-blacklight repo by Josh Weisman.
