### ISSUE TITLE
SPIKE: On-Demand Sync with Alma

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#15]
As the product owner of the Blacklight Discovery Layer Catalog, I would like to explore what options are available for On-Demand Sync with Alma in order to present options to the stakeholder group if different options are available.

User Acceptance Criteria:

- [ ] Developer team investigate what options are available to generate an on-demand sync with Alma

- [ ] Developer team present options to product owner with an explanation of how the on-demand sync would work including who would have access to the on-demand sync, the length of time needed to complete an on-demand sync, and any risks associated with an on-demand sync including an performance degradation.

**Comment by AGCooper** [comment]
- Alma is predicted to update the OAI-PMH 4 times a day at best

- Any real time sync would involve manually running the OAI publishing in Alma to refresh the data and the rake task to be kicked off after

**Comment by rotated8** [comment]
@AGCooper Do you have an estimate on how long the publishing in Alma could take, and what would affect that time?

**Comment by rotated8** [comment]
Added notes to https://wiki.emory.edu/display/BDL/Solr+Strategy
