### ISSUE TITLE
SPIKE: Review ART Documentation to determine any security requirements we might consider

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#154]
As the product owner, I would like recommendations from the development team on any security requirements identified from the previous ART Review  - @tmiles2 can you please provide a link to the ART Review Document? The security requirements could be based on the questions asked about security of the product. 

- [ ] Review the [ART Review wiki page ](https://wiki.emory.edu/display/cita/Blacklight+Discovery+Layer+Phase+1+ART+Reveiw)AND the Completed Network Questionnaire (linked at the both of the page)

- [ ] Within this issue, reply with comments of any new issues that should be considered OR

- [ ] Create a new issue with a recommendation of a new security requirement we should examine as a team

- [ ] The report should be reviewed by a member of the software engineering team AND Technical Lead (Brittle).

- [x] The report should be reviewed by all members of the Middleware team including Solomon, Mark P. and McClain.

- [ ] Outcomes of the review and suggested future work should be reviewed with the entire Scrum team to determine feasibility and priority.

**Comment by mlooney** [comment]
Our current design & future plans are in line with recommended practices, as outlined in the documents
