### ISSUE TITLE
SPIKE: Determine steps we should take to secure user credentials passed from Blacklight to/from other applications

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#155]
As the product owner, I want to ensure the user credentials passed to/from the Blacklight application are secured and cannot be captured or viewed for unintentional use. This includes intercepting user credentials when being passed from one application to the other. Additionally, we should prevent non-admin user from accessing the Blacklight application, associated AWS environments, or associated applications such as Alma with the intent of accessing user data. Other vulnerabilities we want to ensure the application is protected against include:

- [x] Injection
- [x] Broken authentication and session management
- [x] Cross-site scripting
- [x] Insecure direct object references
- [x] Security misconfiguration
- [x] Sensitive data exposure
- [x] Missing function-level access control
- [x] Cross-site request forgery
- [x] Using components with known vulnerabilities
- [x] Unvalidated redirects and forwards

- [x] As suggested during mid-sprint checkin, developing a diagram to depict the flow of user credential data flow between Blacklight, AWS Environments, Alma and third-party applications (Aeon, Ares, Illiad) might help us determine where we should focus on preventing vulnerabilities. Collin Brittle was in mid-sprint checkin and can provide more details if needed.

**Comment by alexBLR** [comment]
### SQL Injections
Use dynamic attribute-based finders when possible
Example: User.find_by(name: params[:name]) vs. User.find_by_name(name)
Never Pass a String as an Argument Unless It Is a Dynamic Finder
Example: User.where("name = '#{params[:name]'") # SQL Injection! Vs. User.where({ name: params[:name] })

### Cross-site scripting
Ruby on Rails has a built-in XSS protection mechanism which automatically HTML escapes all the data being transferred from Rails to HTML.
**HTML escaping**
Rails uses ERB::Util#html_escape function to escape HTML entities. 
**Transferring Data from Rails to JavaScript**
<script>current_user_id = <%=param[:id]%></script> vs. <script>current_user_id = <%=param[:id].to_i%></script>
To prevent these injections <script>current_user_id = alert(document.cookie)</script>
**JSON Escaping** - Rails uses ERB::Util#json_escape function to escape special JSON characters.

### IDOR – Insecure Direct Object Reference
Setting the @user parameter based on the “current_user” session variable

### Sensitive data exposure
Make sure that we set before_action filter for specific authorizations, search anywhere in the code where you have protect_from_forgery except

### Missing function-level access control
Setting the @user parameter based on the “current_user” session variable


### Cross-Site Request Forgery (CSRF)
An attack that allows a malicious user to spoof legitimate requests to your server.
protect_from_forgery with: :exception in application.rb
<%= csrf_meta_tags %> in application.html.erb

### Using components with known vulnerabilities
Make sure that all libraries are up to date and don’t have known vulnerabilities 

### Unvalidated redirects and forwards
URL is being explicitly declared in the code and cannot be manipulated by an attacker.
redirect_to params[:url] (bad) vs. redirect_to login_path (good)

### Broken authentication and session management
Where possible, implement multi-factor authentication to prevent automated, credential stuffing, brute force, and stolen credential re-use attacks.
* Do not ship or deploy with any default credentials, particularly for admin users.
* Implement weak-password checks, such as testing new or changed passwords against a list of the top 10000 worst passwords.
* Align password length, complexity and rotation policies with NIST 800-63 B’s guidelines in section 5.1.1 for Memorized Secrets or other modern, evidence based password policies.
* Ensure registration, credential recovery, and API pathways are hardened against account enumeration attacks by using the same messages for all outcomes.
* Limit or increasingly delay failed login attempts. Log all failures and alert administrators when credential stuffing, brute force, or other attacks are detected.
* Use a server-side, secure, built-in session manager that generates a new random session ID with high entropy after login. Session IDs should not be in the URL, be securely stored and invalidated after logout, idle, and absolute timeouts.

**Comment by alexBLR** [comment]
![Untitled drawing.png](https://images.zenhubusercontent.com/5c488275c10ae96cd915967b/2f401943-a18a-4753-9ed1-654f03eda1bc)
