### ISSUE TITLE
SPIKE: Determine steps we need to take around application performance

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#156]
As the product owner, I would like recommendations from the development team on steps we should take to ensure performance of the Blacklight application based on some general assumptions including:

- [ ] Response time is 1-2 seconds for a full page load including images and API calls 

- [ ] Standard download time is 32 secs for a 1 MB file (high speed internet connection assumed)

- [ ] Application should perform the same for one person using or 1000 people using concurrently

**Comment by rotated8** [comment]
Implemented via #253
