### ISSUE TITLE
MARC resource type electronic vs physical

### ISSUE THREAD

**Issue by devanshu-m** [emory-libraries/blacklight-catalog#163]
In the discussion we had today, we will be looking at 997 and 998 datafield tags to determine if an item is electronic vs physical in the second pass of mapping and compare those counts to the first pass; this will help us tell if looking at 997 and 998 is a better strategy than looking at 007, 006, 008, leader, etc.

Github link for conditional statements in solrmarc: https://github.com/solrmarc/solrmarc/wiki/Conditional-Specifications

**Comment by bwatson78** [comment]
Per @lisahamlett:
if 997 exists, resource type = physical
If 998 exists, resource type = electronic
If 997 & 998 exist, resource type = both
If 997 and 998 do not exist and form of item is o or s, record is electronic
If 997 and 998 do not exist and form of item is anything else, record is physical

If NO 997 or 998, AND
If 000/6 = e, f, g, k, o, or r AND 008/29 = o or s, record is electronic
If 000/6 = e, f, g, k, o, or r AND 008/29 != o or s, record is physical
If 000/6 != e, f, g, k, o, or r AND 008/23 = o or s, record is electronic
If 000/6 != e, f, g, k, o, or r AND 008/23 != o or s, record is physical

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/blacklight-catalog/pull/174

No screenshots necessary.

**Comment by lisahamlett** [comment]
After the most recent load:

Total in Blacklight: 4,897,346
Total in Alma: 4,868,323

Physical in Blacklight: 2,974,722
Physical in Alma: 2,645,318

Electronic in Blacklight: 1,928,222
Electronic in Alma: 2,979,037

835,591 are both
79,559 are neither

**Comment by lisahamlett** [comment]
We'll need to evaluate further but after spot checking, the items that fit this test are correct.

**Comment by lisahamlett** [comment]
Excluded items not piped to Blacklight because they were temporary e records in holding.  New counts:

Total in Blacklight: 4,897,346
Total in Alma: 4,868,323

Physical in Blacklight: 2,974,722
Physical in Alma: 2,645,318

Electronic in Blacklight: 1,928,222
Electronic in Alma: 2,979,037 1,652,450

835,591 are both
79,559 are neither (no attached items)
