### ISSUE TITLE
New field mappings from Metadata model worksheet

### ISSUE THREAD

**Issue by devanshu-m** [emory-libraries/blacklight-catalog#164]
There are fields from the metadata model worksheet that we aren't currently mapping in our index.properties file. We need to identify these fields and map them correctly with the new solrmarc version.

Worksheet: https://docs.google.com/spreadsheets/d/1jSqgNd6HnVJdJMrrShAofkmK8uGgHGdlKODmZOL5NfY/edit#gid=1979033236

**Comment by eporter23** [comment]
@lovinscari As we discussed in standup, as a review step I checked in SOLR and I am seeing many of the new/revised fields in SOLR. This should be good to close. We will still need to add/refine some fields in the worksheet but the recent tickets are great progress!
