### ISSUE TITLE
Create Blackcat collection in Solr Cloud

### ISSUE THREAD

**Issue by SolomonHD** [emory-libraries/blacklight-catalog#165]
Blackcat needs a Solr Cloud Collection created, with proper schema in solr-cor-arch, solr-cor-test and solr-cor. This should be the first step towards creating Blackcat in the target region.

- [x] solr-cor-arch
- [x] solr-cor-test
- [x] solr-cor

**Comment by lovinscari** [comment]
@SolomonHD - can you please provide an update on this issue. We want to make sure McClain has the right access to work with you on this so please also confirm this is done.

**Comment by libdgg** [comment]
Per the 1/29 meeting "ML will work on this and expect to close today"
