### ISSUE TITLE
Complete Terraform documentation and knowledge transfer to Mark P and McClain

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#167]
As a leader in LTDS and Product Owner for the Blacklight Product, I would like for Solomon Hilliard to complete documentation on work he has performed in Terraform on the Blacklight Project and review this documentation with Mark P. and McClain. 

- [ ] The documentation should be added to the Blacklight Wiki - https://wiki.emory.edu/x/ixa_Cg - under the technical design section

- [ ] Access to the documentation should be confirmed by McClain and Mark Prefer

- [ ] The documentation should be reviewed in a way that if McClain and Mark Prefer are reviewing the documentation, they can replicate the work performed on their own with no future intervention from Solomon. Therefore any questions or additional requirements should be identified and completed prior to accepting this as "done."

**Comment by libdgg** [comment]
Solomon has the following Terraform for Avalon docs already in the wiki

https://wiki.emory.edu/display/ULTS/Avalon+General+Infomation
https://wiki.emory.edu/display/ULTS/Avalon+Terraform+Apply+and+Deploys

**Comment by libdgg** [comment]
Per the 1/29 meeting "McClain is comfortable with this and will proceed on his own and reach out to SH for assistance as needed."

**Comment by libdgg** [comment]
@mprefer please review this for any questions or if you are ok with the documentation
