### ISSUE TITLE
Complete documentation and knowledge transfer for Mark P and McClain about backup SOLR/mysql via Ansible scripts

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#168]
In preparation of Solomon's departure from LTDS, I would like for him to complete documentation on his knowledge of and work performed with SOLR and MySql via Ansible Scripts.

- [ ] The documentation should be added to the Blacklight Wiki under Technical Design 

- [ ] Mark Prefer and McClain should confirm they can access the documentation independent of Solomon

- [ ] The review of documentation and knowledge transfer should be conducted with the goal of McClain and Mark Prefer performing similar work without future intervention from Solomon. Therefore any questions or edits to documentation should be completed prior to accepting this issue as complete. 

Reference: [DLP's backup and restoration documentation](https://wiki.emory.edu/display/DLPP/Backup+and+Restore+Strategy)

**Comment by libdgg** [comment]
Note from @SolomonHD 

As per current discussion with CB @rotated8 , current understanding of this ticket is documentation of which ansible roles are doing which backups, possibly some sort of live demo of DLPs backups running in AWX.

**Comment by SolomonHD** [comment]
The backup and restore strategy for DLP: [LINK](https://wiki.emory.edu/display/DLPP/Backup+and+Restore+Strategy)

This should be replicated for blackcat, at least for Solr. For mysql LTDS could go the route of enabling RDS snapshots.
