### ISSUE TITLE
SPIKE: Review the response from the ART Security Review and strategy with Mark P and McClain

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#169]
In preparation for Solomon's departure from LTDS, we would like for him to review any outcomes from the review of the ART Review Document identified in issue #154 to determine any steps that should be taken by Middleware from a security perspective. This strategy session should include Mark Prefer and McClain and any work identified should result in the creation of new issues specifically for the Middleware Team.

**Comment by tmiles2** [comment]
This work is documented in ticket #154
