### ISSUE TITLE
Inventory MARC fields to determine those fields most populated

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#170]
As the product owner, in an effort to improve the metadata mapping process, I would like to take the proposal by Mark Bussey to  inventory the fields in the metadata spreadsheet and determine what percentage of records in the 4M+ corpus have each field populated.  I think we should initially focus on the top 20-25 populated fields. This information will be shared with Emily Porter has she continues to refine the metadata model spreadsheet. By chunking the data, we can limit our focus to certain groups as opposed to trying to address the entire metadata model spreadsheet at one time. 

- [ ] The inventory report should be human readable.

**Comment by lovinscari** [comment]
@eporter23 - can you please review this task and add any other acceptance criteria you believe is necessary to helping you review the data to make an informed decision about how we manage the metadata model spreadsheet?

**Comment by lisahamlett** [comment]
We don't have access to the database on the Alma side, as Ex Libris keeps that all locked down.  I can give you counts if you tell me which fields you're interested in, but extracting the whole database to look at counts would be unmanageable.

I am wondering, however, if we can fix the schema so we're sure everything is getting uploaded into Solr, is there a way to get the full counts from Solr?  That might be easier than me trying to do this in an XML file on my computer...

Otherwise, @eporter23, send me a list of fields to check for you and I'll do it manually.

**Comment by eporter23** [comment]
@lisahamlett bit of a catch-22 as the goal of this, I think, is to assess the relative population of requested MARC fields that we haven't yet added to SOLR. So, as a first step I will go back to the full list of requested fields and pick out ones that are not yet mapped for SOLR, and then check back with you before we proceed.

**Comment by lisahamlett** [comment]
AHA! That makes sense!  Yeah, send me a list of the unmapped ones and I'll get you counts for them.  That will be easier than trying to do the whole db.

**Comment by eporter23** [comment]
@lisahamlett here is a list of the requested but unmapped fields. In most cases, these are at the field-level but in some cases subfields are noted. Let me know if there's anything specific we need to do about subfields or if it simpler to do this at the field-level.

**Comment by eporter23** [comment]
@lisahamlett before you start this in earnest, I'm checking with @lovinscari to see if there are any more SEND team requests that I should incorporate. I'll ping you when I get all of those.

**Comment by lisahamlett** [comment]
@eporter23 Don't worry about it. McClain is going to help me do a full histogram instead of me jury rigging it in Alma. We have everything we need. :)

**Comment by lisahamlett** [comment]
Job to publish list of fields for evaluation started 01/29/2021 15:15:40 EST.  Will probably take about a day to run.

**Comment by lisahamlett** [comment]
The job finished late Friday night but something happened and the output is corrupted.
I just restarted the job.

**Comment by lisahamlett** [comment]
Provided report to McClain to run through a script for the counts.

**Comment by eporter23** [comment]
Outcomes for this ticket:

The[ Metadata worksheet for SOLR](https://docs.google.com/spreadsheets/d/1jSqgNd6HnVJdJMrrShAofkmK8uGgHGdlKODmZOL5NfY/edit#gid=1979033236) is updated to indicate status of MARC data that's been requested to be indexed and what has already been configured for SOLR.

Collin wrote a utility that provides detailed inventories of MARC fields, subfields, and indicators, [available in a CSV file](https://emory-my.sharepoint.com/:x:/r/personal/rmetz_emory_edu/Documents/LTDS%20Division/LTDS%20Shared%20Documentation/Projects/Project%20Documentation/Blacklight%20Discovery%20Layer%20Phase%201/Scrum%20Team/Artifacts/Reference%20Materials/MARC%20data%20inventory/data.csv?d=w1a55912b3ba344a1ac68d176fd200d43&csf=1&web=1&e=K4hPPU). There is also a data set that can be further queried in SOLR.

I've also added a [summary analysis](https://docs.google.com/spreadsheets/d/1jSqgNd6HnVJdJMrrShAofkmK8uGgHGdlKODmZOL5NfY/edit#gid=1298850110) of the amount of SOLR fields mapped vs. pending requests for additional fields, and showing some increments of their frequency in the full catalog.
