### ISSUE TITLE
SPIKE: Determine usability of Blacklight_Alma gem.

### ISSUE THREAD

**Issue by bwatson78** [emory-libraries/blacklight-catalog#177]
Goal: Try [Blacklight_Alma](https://github.com/upenn-libraries/blacklight_alma) gem and see if its functionality simplifies any of our processes detailed in the associated Story.

Items of interest:
- [ ] Alma Authorization
- [ ] Item Availability
- [x] Requesting Item

**Comment by bwatson78** [comment]
Notes:

- Alma Authorization: I'd love to try this on a test environment to see if the SSO authorization the GEM claims is built in works.
- Item Availability: This is built for the index page--I remember @lovinscari stating that the Availability options were eventually going to live on the index page. As of now, this doesn't work locally. The AvailabilityAPI request it uses keeps going to an `undefined` domain, so I believe this could be an issue with a GEM that the parent GEM utilizes called `ezwadl`. I will spend a minimal amount of time seeing if I can fix the issue locally, but it may work (for some reason) once we get this on a test instance.
- Requesting Item:
![Screen Shot 2021-02-03 at 9.18.09 AM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/2db1d94a-064f-4eca-ae07-463058a81095)
As you can see, this is partially working. Once we get this on a test instance, we can see if the SSO authorization carries over to this iFrame.

**Comment by bwatson78** [comment]
Blocker: This is potentially blocked by the need for an additional test environment to see if the Authorization works.

**Comment by tmiles2** [comment]
Blocked by either a another test environment is completed or the ingest is done ( in about day)

**Comment by bwatson78** [comment]
Update: This was deployed to Arch 2/4/21 at 235p and doesn't seem to be registering a multiple login straight out of the box. The availability options are not working in the just the same way as my local instance.

@rotated8 Do you want me to tinker with this any longer? My next guess is to reach out to developers in the Code4Lib Slack for advice on the Gem or their recommended approach.

**Comment by bwatson78** [comment]
Conclusion: I've reached out to Code4Lib slack and have not found anybody with knowledge of a Shibboleth/Alma simultaneous authorization. I have, however, read deeply into [ExLibris documentation](https://knowledge.exlibrisgroup.com/Alma/Product_Documentation/010Alma_Online_Help_(English)/090Integrations_with_External_Systems/060Authentication/020SAML-Based_Single_Sign-On_Sign-Off) and have found that Alma integrations with Shibboleth can go either way (login to Alma, then a setting inside that ecosystem kicks off a login into Shibboleth using shared IDP settings, or vice versa). My educated guess, though, is that if we make the settings in Alma, we'd have to initiate the user's login using Alma signin, which isn't what we're looking for. 
What that possibly means (from the doc link above) is that there is a setting inside of our Shibboleth application that allows a parallel authorization into Alma, which then groups the Alma response within Shibboleth's auth response for us to initiate a separate Alma user in the application. I dug into the code of the gem I was trying to make work and the simplicity of its code implies that the heavy lifting happens in Shibboleth.
![Screen Shot 2021-02-05 at 10.02.25 AM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/ab45593b-424b-463a-b8ad-b47fcdde3c46)
I've taken a deep dive into [that code](https://github.com/tulibraries/blacklight_alma/blob/master/app/controllers/concerns/blacklight_alma/sso.rb) and cannot find any indication that the gem does anything other than receive the Alma response bundled in with the Shibboleth auth. 

I've asked to chat with @rotated8 for guidance on next steps.
