### ISSUE TITLE
SPIKE: Find examples of journals in Alma that include older versions in physical form and newer versions in digital form

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#181]
As the product owner, I would like to see examples of journals in Alma where the older versions are in physical form and newer versions are in digital form. 

- [ ] I would like to know how the journals are associated with each other. Based on previous conversations, I am assuming this has to do with the portfolio they are apart of but I would like to examine this in more detail based on the example that is found.

**Comment by lisahamlett** [comment]
National Geographic
http://discovere.emory.edu/discovere:default_scope:01EMORY_ALMA21187549470002486
MMS ID: 990011430870302486 & 9936501806702486

-----

National water quality inventory : report to Congress
http://discovere.emory.edu/discovere:default_scope:01EMORY_ALMA21262579350002486
MMS ID: 990029409410302486 

-----

Psychology Today
Online
http://discovere.emory.edu/discovere:default_scope:01EMORY_ALMA51272610410002486
MMS ID: 9936497486002486 

Microfilm 1967 - 1973 AND CURRENT PRINT
http://discovere.emory.edu/discovere:default_scope:01EMORY_ALMA21234193610002486
MMS ID: 990027482240302486 

Microfilm 1967-2014
http://discovere.emory.edu/discovere:default_scope:01EMORY_ALMA21216729320002486
MMS ID: 990019823250302486

**Comment by lisahamlett** [comment]
Ready for review by @lovinscari
