### ISSUE TITLE
SPIKE: Create inventory of platforms used to deliver electronic books

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#182]
As the product owner, I would like to understand the different platforms associated with delivering electronic books in Alma. I would like to see if this information is contained in Alma before asking for input by any of the SEND Team members.

**Comment by lisahamlett** [comment]
Individual eBooks are purchased through a vendor such as GOBI and handled in Alma.  The simplified process is this:
1. Order book through the vendor
2. Search for the title in Alma
3. Create order in Alma
4. Add and activate the portfolio

These items will show up with an electronic portfolio attached.
Examples: 9936778520102486

-----

Another way "online access" shows in Primo is based on the existence of a URL in the 856, regardless of the existence of portfolios or physical items.
Examples: 990003424270302486 & 990022248600302486 

-----

If this is related to availability, neither one of these display options allows us to show availability, as vendors and links change all the time and we'd have to hard code thousands of API calls, which is untenable and stupid.  :)

This is why Primo displays portfolios and online access like this:
![image.png](https://images.zenhubusercontent.com/5d379bd44943b962f4d2105c/239298f1-384d-4cd6-baf7-a9b506a69c71)

**Comment by lisahamlett** [comment]
Ready for review by @lovinscari
