### ISSUE TITLE
ServiceNow: Enable Shibboleth Login for Prod/Test

### ISSUE THREAD

**Issue by SolomonHD** [emory-libraries/blacklight-catalog#186]
ServiceNow ticket has been created

[INC03532984](https://emory.service-now.com/nav_to.do?uri=%2Fincident.do%3Fsys_id%3D61d883361b0a6850a8441f4ead4bcbd9%26sysparm_record_target%3Dtask%26sysparm_record_row%3D1%26sysparm_record_rows%3D137%26sysparm_record_list%3Dopened_by%3Djavascript:gs.getUserID()%5Esys_class_name!%3Dsc_request%5Esys_class_name!%3Dsc_req_item%5EORDERBYDESCsys_created_on)

**Comment by libdgg** [comment]
Per standup 2/5 The servicenow request ticket was completed. There are now errors being returned. Speculate that there may be an issue on the application site. @mlooney will take a look as a next step.

**Comment by SolomonHD** [comment]
#### Shibboleth is now working on Prod and Test, changes to environments:
- Re-enabled HTTPS/443 on prod and test, switched Target groups to HTTPS in terraform
 - On prod, ssl module was re-enabled
- /etc/httpd/conf.d/
  - ssl.conf was replaced with the ssl.conf from curate-test EC2
- In /etc/shibboleth/shibboleth.xml
  - handlerSSL="true"
  - cookieProps="https"
- On prod, even after enabling HTTPS in apache, the server would not actually listen on 443 until EC2 was restarted  in the AWS Console

![image.png](https://images.zenhubusercontent.com/5c191329a896da5d83d69955/d0d7bf8b-cc8e-4f21-a15b-eaaf6c8934c3)
![image.png](https://images.zenhubusercontent.com/5c191329a896da5d83d69955/5358b317-5ada-4518-b982-8f3238b76eb7)
