### ISSUE TITLE
STORY: Configure Subject Facet

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#196]
**Status:** does not yet exist; needs SOLR mapping confirmation

As an end user, I would like to search or browse resources by their topical subject matter, so that I can narrow my search to specific topics only

**Acceptance criteria**

- [x] Facet heading should be “Subject”
- [x] Facet should follow the general functionality as noted in [Facet - general wireframe](https://www.figma.com/file/ocSo3KytI6GgwjalSVAmE1/Blacklight-Wireframes?node-id=91%3A3920) [Facet - Modal window wireframes](https://www.figma.com/file/ocSo3KytI6GgwjalSVAmE1/Blacklight-Wireframes?node-id=91%3A3765)
- [x] Displays on search result pages only (not on homepage)

**Metadata/SOLR notes**

- [x] Recommend using: [subject_ssim # 96](https://docs.google.com/spreadsheets/d/1jSqgNd6HnVJdJMrrShAofkmK8uGgHGdlKODmZOL5NfY/edit#gid=1979033236), or create a new field if needed
- [x] Adjust existing mapping to remove 655 (Genre) - Genre will become a separate facet
- [x] Adjust existing mapping to show subfields noted on # 96
- [x] Should not be tokenized

**Comment by devanshu-m** [comment]
PR: https://github.com/emory-libraries/blacklight-catalog/pull/212

@lovinscari @eporter23 Is the work on new Genre field expected in this ticket?

**Comment by eporter23** [comment]
@devanshu-m @lovinscari this is working as requested and as mapped. I do want to note some odd results (data issues that I'll bring to the metadata subgroup) that users will see if they use the A-Z sort option. 

![Screen Shot 2021-02-19 at 2.22.54 PM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/e2c100ad-894a-4f44-9e85-657398c142e8)

![Screen Shot 2021-02-19 at 2.23.09 PM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/8572c7fa-fd9a-4bc7-94fc-6bfaf2e2aa95)

![Screen Shot 2021-02-19 at 2.23.47 PM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/28df6e8e-55ef-4f34-b3f6-95030771d653)
