### ISSUE TITLE
Configure Pre Facets on Home Page

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#206]
Once all of the individual facets are configured, the pre facets will need to be configured on the home page and should appear before a search begins.

**Acceptance Criteria:**

- [x] Pre Facets should follow the general functionality as noted in the [Facet - general wireframe](https://www.figma.com/file/ocSo3KytI6GgwjalSVAmE1/Blacklight-Wireframes?node-id=91%3A3920) and[ Facet - Modal window wireframes](https://www.figma.com/file/ocSo3KytI6GgwjalSVAmE1/Blacklight-Wireframes?node-id=91%3A3765)
- [x] Pre Facets are limited to the Access, Library, Resource Type, Language, and Publication Date facets thus the following facets should be suppressed include Author/Creator, Subject, Genre, Region, Era, LC Classification, and Collection

**Comment by devanshu-m** [comment]
![image.png](https://images.zenhubusercontent.com/5c12bc2dd3542818d52aa3a0/bf64639d-7357-481c-82fe-3059e2a01217)

**Comment by lovinscari** [comment]
Looks great!
