### ISSUE TITLE
STORY: Index Incremental Update (Infrastructure)

### ISSUE THREAD

**Issue by rotated8** [emory-libraries/blacklight-catalog#207]
As a catalog patron, I would like to have the most up-to-date catalog data available to me, with as little interruption to catalog service as possible.

- [x] Catalog data should be updated four times per day (matching current catalog rate).
- [x] Catalog functionality should not degrade during updates.

**Comment by rotated8** [comment]
Do we know how much cataloging can change at once (in an hour, in a day)?

Simplest thing possible: cron job to run an incremental update.
How would the cron job report success?
Log to syslog --> Cloudwatch, report to Honeybadger

**Comment by oraposa** [comment]
Creating rake task to be called by `cron`.

**Comment by oraposa** [comment]
Will add new tickets for creating log group and deployment wrinkles.

**Comment by oraposa** [comment]
Deployment of cron job successful. Cron as expected. Verifying output and results.

**Comment by oraposa** [comment]
Now that the initial full-indexing run is done, the periodic indexing job takes less than five minutes. The job runs four times daily.

I am presently editing the ansible script to remove some one-off items I added for initial Capistrano deploy. Once I test those changes I’ll put up PRs for my `blackcat-tf` (ansible) and `blacklight-catalog` (new rake task) branches.
