### ISSUE TITLE
TASK: Ensure deleted fields within a record are deleted when reindexing

### ISSUE THREAD

**Issue by rotated8** [emory-libraries/blacklight-catalog#218]
- [x] What will deleted fields look like coming from Alma?
- [ ] Test indexing fields in records, then reindexing without those fields. (Is that data removed?)
- [ ] Ensure the removed fields and data are removed when the document is reindexed

**Comment by bwatson78** [comment]
@rotated8 I'd argue that this is exactly the same as #219. We use the same rake task as indexing from an empty Solr instance--the only difference is that we clear the PropertyBag ingest time instance so that all records are processed. #219 being accepted makes this accepted as well.

**Comment by bwatson78** [comment]
`What will deleted fields look like coming from Alma?`

The data/subfields that we pull values from for each individual Solr field will disappear when they are deleted from an Alma XML record. This will cause the indexer to not populate the Solr field at all.

My intuition is that Traject's processing retains a Solr record's `id` and increments its `_version_` field, but then completely overwrites the remaining fields using the indexer logic.

Am now writing Rspec to test this.

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/blacklight-catalog/pull/250

No screenshots necessary.
