### ISSUE TITLE
Generate a new blacklight application

### ISSUE THREAD

**Issue by rotated8** [emory-libraries/blacklight-catalog#22]
- [x] Generate a new blacklight application in this repo with the same version as Lux
- [x] Update the README to include (at least a link to) development environment dependencies and setup instructions

**Comment by bwatson78** [comment]
New PR made: https://github.com/emory-libraries/blacklight-catalog/pull/24

![Screen Shot 2020-10-21 at 1.37.09 PM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/b48b1781-698d-4fe4-ade8-9efbe921fb06)
