### ISSUE TITLE
Review available Alma data to populate Library names in the Library facet

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/blacklight-catalog#223]
To confirm:

- [x] Are Library names standardized coming out of Alma? yes
- [x] What is available in the current OAI outputs? HOL852 is being added
- [x] What are all the available Library names? See link below
- [x] Identify mapping for SOLR field to use for Library facet: HOL852 $b

To implement:
- [x] Add HOL852 from [one existing set](https://na03.alma.exlibrisgroup.com/view/oai/01GALI_EMORY/request?verb=ListRecords&set=blacklightfederalregister&metadataPrefix=marc21) already created by Lisa to all sets

Additional info:
[Library codes and names from Alma](https://docs.google.com/spreadsheets/d/1oMdkTUqxiqpt0XlBqszYqqvR_bjVTU3i5qbX8EWGGOQ/edit#gid=0)

**Comment by eporter23** [comment]
Screenshot of HOL852 data that will be added:

![image.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/7940801f-f5d5-48ae-b99b-82d84d56650d)

**Comment by lisahamlett** [comment]
[https://app.zenhub.com/files/295449627/86ea207a-602c-42c5-87cd-307a9fa00bdf/download](https://app.zenhub.com/files/295449627/86ea207a-602c-42c5-87cd-307a9fa00bdf/download)
Here are the official codes and names of all libraries currently in active in Alma.

**Comment by lisahamlett** [comment]
OAIS blacklightbrad, blacklight4, and blacklightfederalreserve have been updated and republished.  Waiting for the all clear from Brad to update blacklight and blacklighttest.

**Comment by lisahamlett** [comment]
Blacklighttest is done.

**Comment by lisahamlett** [comment]
The blacklight OAI is done.

**Comment by eporter23** [comment]
I  spot checked a few of the OAI sets and they look good! Thanks @lisahamlett for the fast turnaround on this.
