### ISSUE TITLE
SPIKE: Investigate and present options for the Access Online iFrame from Alma

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#224]
As the product owner, I am trying to establish requirements for viewing online resources from Alma. The current workflow when viewing an electronic item from Alma indicates the iFrame (Alma Lightbox) includes the Actions dropdown list per the screenshot attached. I would like to understand what options are available in customizing the iFrame for Access Online as I ideally we should look at removing the drop down "Actions" list from the iFrame as not to interfere with Blacklight tools including Citation and Export tools. I would like feedback on the options available based on what the development team determines is technically feasible given a 3-5 point issue or story. 

![AccessOnlineIFrame.jpg](https://images.zenhubusercontent.com/5c4a1fe1e9b5fb46bcedb9fc/fda31e90-5ed1-44f9-9627-e9ed6492bcbd)

**Comment by lisahamlett** [comment]
The actions box appear to be generated from Primo and the LCS webserver Kleene.  I don't think this comes from Alma at all, but I will look into it once we have the lightbox available in test.

**Comment by lisahamlett** [comment]
I have confirmed the actions menu is an Alma-to-Primo thing and does not exist when building the lightbox separately, so this is a non-issue.
