### ISSUE TITLE
SPIKE: Reindex data in test [DUE FEB 24]

### ISSUE THREAD

**Issue by rotated8** [emory-libraries/blacklight-catalog#226]
@lovinscari needs an environment up-to-date and ready to demo for the SEND team on March 2nd. Any changes or updates to the environment should not happen after Feb 24th.

- [ ] The test environment should have the full production data loaded, with up-to-date mappings and facets

**Comment by devanshu-m** [comment]
Total count for previous ingest (Feb 18th-19th) 4,902,038 in test
Total count for new ingest (Feb 23rd-24th) 4,903,565 in test
