### ISSUE TITLE
Set up CircleCI

### ISSUE THREAD

**Issue by rotated8** [emory-libraries/blacklight-catalog#23]
Starting with the setup from Lux, set up CircleCI

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/blacklight-catalog/pull/30

No screenshot necessary.

**Comment by bwatson78** [comment]
Just realized I need to update the Readme to add further instructions on how to run tests locally.

**Comment by bwatson78** [comment]
README has been updated.
