### ISSUE TITLE
Determine shibboleth attributes currently in place for Primo

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#25]
As the product owner for Blacklight Discovery Layer, I would like to review the current attributes for a Shibboleth Login for Primo (discoverE). The information is unknown by Alex Cooper and Mark Prefer but suspect Laura Akerman might have some knowledge. If not, I would like to see if this information can be constructed somehow.

**Comment by tmiles2** [comment]
Gerry Hall provided the following response to my question about the attributes for Primo: "only uid (ie, Emory netID)". I did ask a follow-up question to gain more clarification but didn't get a response back as of today.

**Comment by tmiles2** [comment]
Found this file /exlibris/primo/p4_1/pds/conf_table/shib_01emory.conf in Production dE
[SHIB_ATTRIBUTES]
HTTP_SHIB_PERSON_UID = z312_source_id
HTTP_SHIB_PERSON_NAME = z312_name
[END]
[DEFAULTS]
[END]
[ATTRIBUTES_MAPPING]
[END]
