### ISSUE TITLE
TASK: Handling updated records

### ISSUE THREAD

**Issue by rotated8** [emory-libraries/blacklight-catalog#252]
When a cataloger changes a field in a record, the change should be reflected in Solr.

When a cataloger adds a field to a record, the new field should be reflected in Solr.

- [x] Test the indexer with an example
- [x] Change the indexer to ensure updated records are updated in Solr.

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/blacklight-catalog/pull/265

No screenshots necessary.

**Comment by lovinscari** [comment]
@bwatson78 - I am not sure if this is something you are needing me to test?

**Comment by bwatson78** [comment]
There isn't--my apologies. I'll close this.
