### ISSUE TITLE
SPIKE: How do we get a single record from OAI?

### ISSUE THREAD

**Issue by rotated8** [emory-libraries/blacklight-catalog#255]
How do we query OAI for a single record? What does the response look like?

**Comment by alexBLR** [comment]
According to Exlibris OAI integrations manual: https://developers.exlibrisgroup.com/alma/integrations/oai/

this is the syntax of how to get a record with metadata:
https://na01.alma.exlibrisgroup.com/view/oai/**TR_INTEGRATION_INST**/request?verb=**GetRecord**&identifier=oai:urm_publish:9974663900561&**metadataPrefix**=marc21

OAI Get Specific Record according to identifier and metadata prefix
https://eu00.alma.exlibrisgroup.com/view/oai/EXLDEV1_INST/request?verb=GetRecord&identifier=oai:urm_oai:99182611100121&metadataPrefix=marc21

We need to modify OaiQueryStringService or write a new one that addresses a query for one record.
Then we can write a new rake task for harvesting and indexing of one record
