### ISSUE TITLE
TASK: Full reindex

### ISSUE THREAD

**Issue by rotated8** [emory-libraries/blacklight-catalog#258]
A full reindex ignores the last time the indexer was run, and pulls all records from all time. We can reuse the existing rake task, but add an option to ignore the last run time, but still set it.

- [x] Add option to ignore last run time
- [x] Test rake task.

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/blacklight-catalog/pull/270

No screenshots necessary.
