### ISSUE TITLE
Configure CloudWatch dashboard setup to monitor AWS components

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#260]
Configure CloudWatch dashboard setup to monitor AWS components related to the ticket requirements when available (i.e. CPU, Disk, Memory, etc). While the team feels that most of the requirements will be met with CloudWatch, any requirement that is not met with will result in team exploration of alternate solutions for those partcular metric(s).

**Comment by mlooney** [comment]
By default, EC2 hosts are CloudWatch enabled, with 19 different metrics (at minimum):

The example below is an image of the CloudWatch console for a newly minted EC2 Host.

![image.png](https://images.zenhubusercontent.com/5e5d3aa83ca793986edab47d/b1b8e5a3-f283-446a-b800-1a45ada89184)

**Comment by AGCooper** [comment]
Looks good to me.
