### ISSUE TITLE
Configure CloudWatch Alarms

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#261]
CloudWatch alarms configured with initial metrics to evaluate for adjusting thresholds that trigger alarms. The team will review AWS, or other industry documentation for best practices for thresholds. The team will plan a review of the alarm thresholds to test their behavior. The thresholds are configurable so we can throttle them once they are in place to mitigate false alarms or otherwise change their behavior.

Acceptance Criteria:

- [x] Configure an alarm if Passenger stops running for Blacklight. The alert has to be configured for each environment. 

- [x] Configure an alarm if there is a spike in CPU utilization (prefer for middleware team to set this threshold). The alert has to be configured for each environment.

**Comment by lovinscari** [comment]
Scheduled to meet with @rotated8 on 3/12/21 to review acceptance criteria.

**Comment by libdgg** [comment]
@mlooney and @libdgg met. we setup a test alarm to work with slack alerts. we both have permissions blocking us from setting up slack in the AWS environment. 

@libdgg will be sending Paul Peterson some info and screen shots to see if we can get permissions to complete the work of setting up the alarms and slack integration.

**Comment by mlooney** [comment]
![image.png](https://images.zenhubusercontent.com/5e5d3aa83ca793986edab47d/101f1c50-9b31-43af-8155-ea57b9d245df)


Sample alarm configured for arch2 having cpu utilization > 25% for > 5m
