### ISSUE TITLE
Setup ThousandEyes to monitor Blacklight

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#262]
Setup ThousandEyes to monitor blacklight which will enable us to be aware of degradation of user access to the product.

NOTE: setup right before beta launch - or setup but ask the monitoring team to wait until beta to turn it on

In the past we submitted a ServiceNow ticket < INC03452322 > assigned to the "Network Management > Monitoring > OIT: Network Services - Monitoring and Tools" assignment group to talk about onboarding for monitoring for our digital library product. We talked to Nayef Smith and Stephen Bottinelli and the ticket was resolved by tony.dawson@emory.edu in LITS: Network/App Monitoring. I assume we can follow this same approach again.

Setup ThousandEyes Monitoring for (a URL and any special access info, and what response to expect):

- Catalog Homepage
- A sample search "pizza"
- A single result (i.e. a book, periodical)
~- Login / authentication~

Setup and test alerting (via ServiceNow/Paging)

LTDS Wiki Documentation: https://wiki.emory.edu/display/BDL/ThousandEyes+Monitoring

**Comment by libdgg** [comment]
@lovinscari @tmiles2 @AGCooper @jcrompton42 Are you all ready to pursue this at this time or other preferences for next steps?

**Comment by AGCooper** [comment]
@libdgg I could see the homepage load time could be an issue since that might well trigger alerts all the time. Also since thousand eyes emulates end users interacting with the application it seems like more of an app support / developer ticket than infrastructure.

**Comment by AGCooper** [comment]
Maybe a quick meeting between Collin, Lisa, and me to discuss what we want checked (probably the same or similar to DLP), and then check with Tony on thoughts about staging this and acceptable delays for like the home page loading?

**Comment by AGCooper** [comment]
Meeting scheduled for 11/16.

**Comment by rotated8** [comment]
Cutting the Authentication portion until we have features that depend on auth (that is, when API-based requesting is in)

Current timeout can be set for 15 seconds (usually it takes 7 seconds or less). We can revisit this as we continue working on perf, and we leave beta.

**Comment by libdgg** [comment]
NOTE: [Library Search CI is in ServiceNow](https://emory.service-now.com/nav_to.do?uri=%2Fcmdb_ci_appl.do%3Fsys_id%3Dcc1c6e3897cc0910f5749934a253afa8)

**Comment by libdgg** [comment]
Email sent to Lisa, Tony and Rose about next steps (which would unblock this ticket).

**Comment by libdgg** [comment]
@lisahamlett This ticket should be ready to unblock. Tony emailed back on 12/1 with the following. i assume you've got this going forward.

Email from 12/1/2021 - Re: Paging for Library Search/Blacklight" from Tony Dawson
"Got it. I am out tomorrow and part of Friday but will touch base with Lisa then or early next week if I have any questions"

**Comment by lisahamlett** [comment]
We just successfully tested and approved this.

**Comment by lovinscari** [comment]
Assuming this is monitoring production but I am moving to To Deploy to Prod just in case.
