### ISSUE TITLE
Setup Cloudwatch to send alerts to Slack

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#263]
Setup of slack and paging will enable us to use send alerts from Cloudwatch  as part of application and system monitoring enabling  two key communication channels for ongoing operations.

**Comment by lovinscari** [comment]
Scheduled to meet with @rotated8 on 3/12/21 to discuss removing paging from this issue and adding to a separate issue.

**Comment by tmiles2** [comment]
We will need Cari, Doug or Rosalyn to configure slack as they are admins.

**Comment by libdgg** [comment]
@mlooney and @libdgg met. we setup a test alarm to work with slack alerts. we both have permissions blocking us from setting up slack in the AWS environment. 

@libdgg will be sending Paul Peterson some info and screen shots to see if we can get permissions to complete the work of setting up the alarms and slack integration.

**Comment by libdgg** [comment]
@mlooney and @libdgg are working on this using Slack Webhooks as an alternative. McClain setup the alarm and Doug provided the webhook for #dlp-alerts to McClain on 3/34/2021

**Comment by mlooney** [comment]
![image.png](https://images.zenhubusercontent.com/5e5d3aa83ca793986edab47d/d1b62a7a-7bbc-4dfd-828d-3489efa33b6c)
