### ISSUE TITLE
Refine the single item view wireframe based on metadata requirements

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#269]
As the product owner, I would like the wireframe for the single item view (Item/Show/A/Details) Figma design to be updated with the fields defined in the [View Item Detail Template Metadata Only](url) document and with the acceptance criteria identified below.

Acceptance Criteria:

- [x] The Item Overview and Item Details section should reflect the fields identified in the View Item Detail Template 

- [x] The thumbnail block should be removed for now as implementing Thumbnails will need to wait until post beta to determine the best method for implementing thumbnails. 

- [x] The "More Options" block will include links to the respective "Materials Pages" from the Emory Libraries website. For example, if the item is a book, the "More Options" will include a link to the [Books Page](https://libraries.emory.edu/materials/books.html) with the wording "Book Details" or something similar as determined during wireframe planning session.

- [x] Document within the wireframe description that if a field is not populated that it does not show in the display. 

- [x] Discuss with Lisa Hamlett any options available with styling the iFrame for requesting and online access

- [x] The direct link on the wireframe should indicate this is a permalink that will be implemented as part of the single item display.

**Comment by norm0** [comment]
I've included screenshots of a first draft of the Item Display page "More Options" and the Item overview without a thumbnail.


![More Options.png](https://images.zenhubusercontent.com/5f8492d49b473a0cef37940f/690dec14-7eac-449e-ae62-22b23a32d13c)

![A.png](https://images.zenhubusercontent.com/5f8492d49b473a0cef37940f/08557e3e-a30f-4ffc-92bb-947dbe314ec8)

**Comment by norm0** [comment]
@lovinscari A updated design that is simple as well as manageable...

![Item - Component - More Options - B.png](https://images.zenhubusercontent.com/5f8492d49b473a0cef37940f/1e517cd5-7b9e-45d9-92b5-3f4f0dab48bc)

**Comment by norm0** [comment]
![A.png](https://images.zenhubusercontent.com/5f8492d49b473a0cef37940f/7f32fee8-1db8-4463-8eec-ca40236bccff)

**Comment by eporter23** [comment]
@norm0 @lovinscari these look good to me; Norm and I are continuing to work on identifying some variant mockup examples to add to the View Single Item display stories and will link those up over the next couple of days.
