### ISSUE TITLE
Refine date slider facet based on feedback from demo

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#274]
![PubDate_FacetFix.png](https://images.zenhubusercontent.com/5c4a1fe1e9b5fb46bcedb9fc/7c9c1e2f-05e5-47b3-bcac-481f6b1b8682)As discussed in the Sprint Review/Demo, the Date Slider Facet should be refined so the entire date range appears in the slider as opposed to only part of the last date range (see screen shot below).

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/blacklight-catalog/pull/284

![Screen Shot 2021-02-26 at 10.01.50 AM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/2aa75db3-9eda-4926-aff9-489c3ed7189e)

**Comment by lovinscari** [comment]
The change to the display of the date slider is accepted. However, when performing a test on Blacklight-Test using the date slider, the application produced an error. A new bug ticket will be submitted.
