### ISSUE TITLE
Refine number of results displayed with facets and modals

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#275]
As discussed in the Sprint Review/Demo on 2-24-21, the functionality of all facets should be refined so that if the number of results within a facet is less than 10 then all results should be shown beneath the facet heading as opposed to requiring the user to select "More" with the modal that will only show a few results. The current requirement is only to show up to 5 results beneath any facet heading. Note - Emily will look at two facets this would most apply to for Resource Type and Library so we will limit this logic to only those two facets and Emily will update ticket based on numbers to be shown for those facets. 

Maximum Count Estimate for Resource Type, Library facets: 
- The current list of Alma Library codes is **18** 
- An expanded set of Resource Type terms from Cari's original wireframes document is **14**
- Recommendation: set these two facets to display **25** in their initial view (instead of 5 as usual). This gives us some room for expansion, and given our ongoing organizational change, we know we could see more locations, etc coming into play before too long.

**Comment by eporter23** [comment]
This should apply to the Library and Resource Type facets specifically. I will count the maximum values expected for each.

**Comment by eporter23** [comment]
Discussed in sprint planning - we need to hard-code a max number for these two.

**Comment by bwatson78** [comment]
Ticket awaits a hard number to limit these facets. Emily is on vacation, so this ticket can wait until the week of 3/1-5.

**Comment by eporter23** [comment]
@bwatson78 @lovinscari I recommend we set these 2 facets to display the first 25 results. See notes in the description above.

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/blacklight-catalog/pull/287

![Screen Shot 2021-03-01 at 2.43.16 PM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/2f7beb4c-4578-4e2f-bb85-f047e74d011c)

**Comment by rotated8** [comment]
@eporter23 Bumping this up to 25 seems high compared to our normal default of 5. I think the original observation was that if we had ~7 items in a facet, opening the "more" modal to only see two more options is unsatisfying to users. This seems like we are well over that threshold. 

Using Lux as a stand in for "finished" styling, and assuming all the option only take one line of text, 25 facet options takes nearly a full screen on mobile
![facets2](https://user-images.githubusercontent.com/638392/109619732-1effcc00-7b07-11eb-9c61-df6a90f60dfd.png)
and about three quarters of a screen at 1080p
![facets](https://user-images.githubusercontent.com/638392/109619943-553d4b80-7b07-11eb-9338-8082a1a0b36a.png)

When the text doesn't fit on one line, the options can get very long
![facets3](https://user-images.githubusercontent.com/638392/109621046-94b86780-7b08-11eb-8fd8-e3886d039721.png)
