### ISSUE TITLE
Determine refinements needed to Library facet 

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#281]
As the product owner, I would like to know what refinements are needed to the Library facet to ensure all libraries with physical holdings are represented within the facet including Goizueta Business Library, Woodruff Health Sciences Library, Macmillan Law Library, Library Service Center, Robert W. Woodruff Library, Heilbrun Music and Media Library, Pitts Theology Library, Oxford Library, and Science Commons.

Additionally, I would like your recommendation with what changes are needed from either a metadata or development perspective to ensure the names of the libraries shown with the facet are meaningful to the end user. The current facet includes abbreviated names which have no meaning to the end user. 

Updated recommendations:

- For each Alma library code, map them to the display-friendly Library name confirmed by SEND team stakeholders as [noted in the first tab of this spreadsheet](https://docs.google.com/spreadsheets/d/1oMdkTUqxiqpt0XlBqszYqqvR_bjVTU3i5qbX8EWGGOQ/edit#gid=0)
- For holdings that are coded LSC, record a value for "Library Service Center"
- For holdings that are coded LSC, also store a value for the actual holding library. Translate the sublocation codes back to the holding library using the criteria [noted on the second tab of this worksheet ](https://docs.google.com/spreadsheets/d/1oMdkTUqxiqpt0XlBqszYqqvR_bjVTU3i5qbX8EWGGOQ/edit#gid=265534013&fvid=65214426)

SOLR/indexing notes

- [Existing field library_ssim # 72](https://docs.google.com/spreadsheets/d/1jSqgNd6HnVJdJMrrShAofkmK8uGgHGdlKODmZOL5NfY/edit#gid=1979033236) should be expanded to include $c in order to map LSC locations back to their parent holding library

Example of an LSC item that belongs to the Theology library:
![Screen Shot 2021-03-15 at 2.57.18 PM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/d76380b4-5e34-4327-8bdf-4dee2be92730)

**Comment by eporter23** [comment]
Discussed with the SEND team on 3/9. I will add notes to this ticket later about any requested name revisions.

**Comment by eporter23** [comment]
I am also waiting to hear back from Health Sciences about how they prefer to have their name displayed.

**Comment by lisahamlett** [comment]
Looks good to me.  Moving to accept for Cari.
