### ISSUE TITLE
BUG: Fix issue found when using the date slider function

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#288]
When using the date slider function in the facets, I found the following issue:

- Blackcat-test.library.emory.edu
- Keyword Search "Pizza" (no quotes)
- Received 88 results
- Selected > Publication/Creation Date facet
- See attached screen shot with results
- Used date slider to narrow date range to maximum 1951
- When I selected "apply" one of the times the application took me back to the home page with an error at the top stating the search was not understood.
-When attempting the same search a second time and using the date slider, I received two results but with an indicator at the top saying "Did you meant to type: proza" see attached.

As the product owner, I would expect the following behavior when using the date slider:

- [ ] Search is conducted using basic search and/or other facets
- [ ] When attempting to narrow the search by Publication/Creation Date, I should see all results for the given search within the publication/creation date facet.
- [ ] When using the date slider to narrow results for a given time range and selecting "apply" I expect to view results for the specified search including the given publication/creation date range

Seeing a message "did you mean to type: " and/or being returned to the home page with an error about not understanding the search is abnormal. 

![dateslider_error.png](https://images.zenhubusercontent.com/5c4a1fe1e9b5fb46bcedb9fc/2cbd7b2f-d336-4914-ae19-96f6945539ea)![pubdate_screenshot.png](https://images.zenhubusercontent.com/5c4a1fe1e9b5fb46bcedb9fc/3b5d9d2e-1773-4e11-aeaf-075949a0926f)

**Comment by rotated8** [comment]
Closing this in preference for #289
