### ISSUE TITLE
Error: "Sorry, I don't understand your search."  

### ISSUE THREAD

**Issue by tmiles2** [emory-libraries/blacklight-catalog#289]
The "Sorry, I don't understand your search." error seems to pop up on the **test environment** randomly. 

- If you logon to the page
- When doing a search or narrowing a search. 

![image.png](https://images.zenhubusercontent.com/5c07f3880498270a145dcf84/c110708f-6b53-4cf4-9dbb-5a86d2a47955)

![image.png](https://images.zenhubusercontent.com/5c07f3880498270a145dcf84/ef7717e3-3328-4391-a6b8-212688fbac67)

**Comment by devanshu-m** [comment]
Refreshed solr using this document: https://wiki.emory.edu/pages/viewpage.action?pageId=191727680

**Comment by tmiles2** [comment]
@devanshu-m @bwatson78 @rotated8 The issue is resolved for me. I completed the following actions: 

- Logged into the test environment 
- Completed a search by clicking the search button
- Completed a search by keyword and narrowed in the search with the date slider 
- Clicked on several books to see if the error would popup

All worked fine with no issues.
