### ISSUE TITLE
TASK: Review Ex Libris requesting APIs

### ISSUE THREAD

**Issue by rotated8** [emory-libraries/blacklight-catalog#291]
- [x] Identify and review Ex Libris APIs to work with the wireframe requirements for requesting an item.
- [x] Provide links to those APIs for later implementation
- [x] Document risks and knowledge gaps

Wireframes:
[Item Show Page Wireframes](https://www.figma.com/file/ocSo3KytI6GgwjalSVAmE1/Blacklight-Wireframes?node-id=791%3A1)
[Requesting Wireframes](https://www.figma.com/file/ocSo3KytI6GgwjalSVAmE1/Blacklight-Wireframes?node-id=579%3A7246)

**Comment by bwatson78** [comment]
Update: 
I have identified the API destination and structure, but am still working with @lisahamlett to communicate with Ex Libris the data that needs to be passed to the Alma API to create a successful Hold request. For example, the link below 
`curl -X POST "https://{api-code].hosted.exlibrisgroup.com/almaws/v1/users/bwatso9/requests?user_id_type=all_unique&mms_id=990021339300302486&apikey={api-key}" -H  "accept: application/json" -H  "Content-Type: application/json" -d "{\"request_type\":\"HOLD\", \"pickup_location_type\": \"LIBRARY\", \"pickup_location_library\": \"UNIV\", \"description\": \"Whole item\"}"`
fulfills all of the required datapoints to make the request without error, but I receive the response 
`{"errorsExist":true,"errorList":{"error":[{"errorCode":"401122","errorMessage":"There is no requestable items for selected record.","trackingId":"E01-0803150733-D9CZQ-AWAE349977505"}]},"result":null}%`
Truth is, there is a physical copy of the item available, but, per Lisa's knowledge, there needs to be more keys/values passed in the request object to push the request through correctly.

Effectively, this ticket is blocked until we hear word back from ExLibris identifying the missing datapoints.

**Comment by lovinscari** [comment]
@bwatson78 thanks for the thorough details on this. I would like to ask that @rotated8 includes this information in the decision document we are preparing for the overall plan of implementing that API's as I agree this work does sound significant and believe this also requires change at the organizational level.
