### ISSUE TITLE
TASK: Review Ex Libris availablility APIs

### ISSUE THREAD

**Issue by rotated8** [emory-libraries/blacklight-catalog#292]
- [x] Identify and review Ex Libris APIs to work with the wireframe requirements for real-time availability
- [x] Provide links to those APIs for later implementation
- [x] Document risks and knowledge gaps

Wireframes:
[Item Show Page Wireframes](https://www.figma.com/file/ocSo3KytI6GgwjalSVAmE1/Blacklight-Wireframes?node-id=791%3A1)
[Requesting Wireframes](https://www.figma.com/file/ocSo3KytI6GgwjalSVAmE1/Blacklight-Wireframes?node-id=579%3A7246)

**Comment by devanshu-m** [comment]
We have this implemented via APIs already. However, we are only showing availability as a badge right now. As per wireframes above, we are also required to show location and call number. This data is also available via the current implementation by Brad. However, we are not displaying it right now. Should we create new tickets to add the extra data?

Attaching these here so it is easier to discuss:

![image.png](https://images.zenhubusercontent.com/5c12bc2dd3542818d52aa3a0/972a56b4-41f2-4455-b6c5-8b060a2f513a)

![image.png](https://images.zenhubusercontent.com/5c12bc2dd3542818d52aa3a0/3bb28ac3-ce0e-4c8a-ade8-c4ac634d8359)

**Comment by devanshu-m** [comment]
Notes for decision document: We will be using the current API setup for real-time availability by Brad, but we will be modifying current implementation to add more data coming back in the XML response, to show location and call number details.
