### ISSUE TITLE
Refine Single Item Display Wireframe

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#293]
As a library user, I would like to be advised of the need to login in order to see certain information or perform certain functions within an item record. The current Alma iFrame includes a policy statement "Log in for more information" as shown on the screen shot below. However, this is not very prominent thus I do not understand the need to login. As such, I would like to see a button or block of text above the iFrame prompting me to login in order to see certain information or perform certain functions. An example of this is the "How to get this" button by Temple University Library as shown in the screen shot below. Temple University uses Alma thus this depicts behavior with the Alma iFrame. 

Acceptance Criteria:

- [ ] Determine the best option from a usability and UI design standpoint to prompt the user to login. The descriptive language should indicate action needed by the end user and if a button, should enable the user to login when selecting the button.

- [ ] Amend the current single item display iFrame to include a button or block of text prompting the user to login to see more information. 

![Temple_Howtoget.png](https://images.zenhubusercontent.com/5c4a1fe1e9b5fb46bcedb9fc/fe765d24-3c5d-45d5-a2c1-49d72253a277)![Login_AlmaiFrame.png](https://images.zenhubusercontent.com/5c4a1fe1e9b5fb46bcedb9fc/8ee6538e-f02e-4083-b5cf-1c1c4d1855a7)

**Comment by norm0** [comment]
I've create some quick mockups in html/css here: https://codepen.io/collection/ngNVep

**Comment by norm0** [comment]
Screen versions of the coded versions

![Screen Shot 2021-03-16 at 10.03.25.png](https://images.zenhubusercontent.com/5f8492d49b473a0cef37940f/f930b4f7-4a91-4f00-83d2-ddf9b4c30338)
![Screen Shot 2021-03-16 at 10.02.57.png](https://images.zenhubusercontent.com/5f8492d49b473a0cef37940f/6c14d36d-7cb2-403f-a3c1-429e87e96bfc)![Screen Shot 2021-03-16 at 10.04.14.png](https://images.zenhubusercontent.com/5f8492d49b473a0cef37940f/f70b81fa-4ccb-4a30-9628-614a1c7db4e0)
