### ISSUE TITLE
TASK: Review Ex Libris APIs for Resource Sharing Partners

### ISSUE THREAD

**Issue by rotated8** [emory-libraries/blacklight-catalog#294]
- [ ] Identify and review Ex Libris APIs to work with the wireframe requirements for requesting an item from a resource sharing partner
- [ ] Provide links to those APIs for later implementation
- [ ] Document risks and knowledge gaps

Wireframes:
[Item Show Page Wireframes](https://www.figma.com/file/ocSo3KytI6GgwjalSVAmE1/Blacklight-Wireframes?node-id=791%3A1)
[Requesting Wireframes](https://www.figma.com/file/ocSo3KytI6GgwjalSVAmE1/Blacklight-Wireframes?node-id=579%3A7246)

**Comment by bwatson78** [comment]
Group (Lisa, Alex, Collin, and I) conversation held on 3/8/2021 at noon. @lisahamlett will be adding detailed comments here about the procedure needed to tie Georgia Tech's Alma into ours. I will summarize afterwards, if that's needed.

**Comment by lisahamlett** [comment]
@bwatson78, @AGCooper, @rotated8, and I met about this.  Here's a brief summary of our options for resource sharing with Georgia Tech, our only resource sharing partner.

#1 - As of right now, Emory and GIT share limited user and item information between institutions via the Alma Fulfillment Network, which is an integration Ex Libris set up between GIT's Primo and our Alma as well as our Primo and GIT's Alma.  There are no API keys for the fulfillment network and the whole system is a black box for which we don't really have access.

I could work with GIT to set up an OAI for their materials, but there's no way to push user information through this system.

#2 - We could kill the fulfillment network and go back to resource sharing between the institutions, which I HIGHLY DO NOT RECOMMEND.  With this system, user records live with the borrowing institution and item records live with the item owning institution.  This makes communication between circulation departments manual, kills any shared My Account options, and would be a huge drop in service for the user.  Additionally, we would not be able to share user APIs with each other, as the agreement for what information can be shared restricts access to that information.  There would need to be a user database solution set up outside Alma and, even with that, I'm not sure how we'd integrate it back to Alma.

We also do not know how GIT integrates their fulfillment network with the rest of the USG, so in addition to a drop in service to Emory and GIT users, we might be affecting their relationship with their consortium.  As a result, if this is the option you all wish to pursue, you're going to need to create a project involving Emory, GIT, and the USG, as well as Ex Libris.

#3 - Emory requests for GIT items can be handled by Interlibrary Loan.  All we would need is the aforementioned OAI and an OpenURL setup to ILLiad.

**Comment by bwatson78** [comment]
I don't think I need to add anything else. Moving to "To Accept".
