### ISSUE TITLE
Review current bootstrap CSS and recommend changes needed for current theming and branding

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#295]
As the product owner, I would like to begin exploring what is needed to begin theming and branding the Blacklight application. The current bootstrap used for Emory Digital Collections is based off the pattern library for Emory Libraries website. Based on initial design of wireframes for header, footer, homepage, facets, and single item display, I would like to understand from a UI design perspective if any modifications are needed to the Bootstrap CSS. This will allow us to begin development of needed components of the header and footer in the coming sprints. 

Acceptance criteria:

- [x] Review the [Bootstrap Mapping for Emory Digital Collections](https://docs.google.com/spreadsheets/d/1-sbatCXlB7ysNHPrj3vT2mBy4nufx1ovlG7UwX2sdo8/edit?usp=sharing)

- [x] Determine if any new components are needed at this point for the Blacklight Catalog based on current designs for header, footer, facets, home page and single item view page.

- [x] Determine if any immediate changes are needed based on mark up requirements for the Single Item View page - specifically the header items.

- [ ] Document and review recommendations with product owner.

**Comment by norm0** [comment]
<iframe style="border: 1px solid rgba(0, 0, 0, 0.1);" width="800" height="450" src="https://www.figma.com/embed?embed_host=share&url=https%3A%2F%2Fwww.figma.com%2Fproto%2FocSo3KytI6GgwjalSVAmE1%2FBlacklight-Wireframes%3Fnode-id%3D791%253A1%26viewport%3D457%252C545%252C0.2110304981470108%26scaling%3Dmin-zoom" allowfullscreen></iframe>

**Comment by norm0** [comment]
I was able to move the footer over from Lux! You can see the attached screenshot of what it currently looks like...

![screencapture-localhost-3000-2021-03-24-10_07_13.png](https://images.zenhubusercontent.com/5f8492d49b473a0cef37940f/f78e7091-fcb6-4e8b-a394-a1db6149656f)

**Comment by norm0** [comment]
Documentation and recommendations are here; https://docs.google.com/document/d/1PwEzykI8FdLiqd4PHoyRSXScPeezFCW1KhfPLcOnnpo/edit?usp=sharing

**Comment by lovinscari** [comment]
@norm0 - I am confirming you reviewed this with the app dev team?
