### ISSUE TITLE
TASK: Describe the "browse" search festure in Discovere

### ISSUE THREAD

**Issue by rotated8** [emory-libraries/blacklight-catalog#302]
Using the [browse search](https://knowledge.exlibrisgroup.com/Primo/Product_Documentation/Primo/Technical_Guide/010The_PNX_Record/150The_Browse_Section/030Browse_Search) ExL KB article, and the [actual browse search](https://discovere.emory.edu/primo_library/libweb/action/search.do?fn=showBrowse&mode=BrowseSearch&vid=discovere&dscnt=0&dstmp=1615308903963) in Discovere, describe how Primo's browse search works, so that we can propose an implementation of it in Blacklight

The results of this ticket should be useful for defining acceptance criteria for a browse search implementation.

**Comment by alexBLR** [comment]
You have to select a browse field  to do any browse search

![Screen Shot 2021-03-17 at 9.17.48 AM.png](https://images.zenhubusercontent.com/5c488275c10ae96cd915967b/d962db36-88ae-4c80-aafe-c5f7ad8d5d81)

After selecting one of the browse fields

![Screen Shot 2021-03-17 at 9.19.01 AM.png](https://images.zenhubusercontent.com/5c488275c10ae96cd915967b/d6e9d874-409d-4f26-a214-2b03b63ad3d6)

And then clicking browse we have a display of 25 records in  a alphabetical order by the field (in our case call number)

![Screen Shot 2021-03-17 at 9.20.00 AM.png](https://images.zenhubusercontent.com/5c488275c10ae96cd915967b/5cd9d28e-5d6d-4b03-b6c5-9e0b150e4568)

When you type in a search bar and click enter, the result comes out filtered by the call number field, so you are searching within filtered records. DiscoverE calls it “browse X in field name” 

![Screen Shot 2021-03-17 at 9.26.51 AM.png](https://images.zenhubusercontent.com/5c488275c10ae96cd915967b/47634230-1fde-4e21-9b17-d875943648a6)

You can’t sort a results table by any of the headers

![Screen Shot 2021-03-17 at 9.29.18 AM.png](https://images.zenhubusercontent.com/5c488275c10ae96cd915967b/19be1916-ff63-41a1-b154-8890ff8fb768)


**The Headings Results**

Browse searches that use the author, title, and subject browse lists return a list of headings and the number of linked PNX records, which display in the brief results page format and include facets. Users can click the headings to display a list of the linked PNX records. 

The number that displays next to heading is the number of records that contain the heading.

![Screen Shot 2021-03-17 at 9.33.28 AM.png](https://images.zenhubusercontent.com/5c488275c10ae96cd915967b/60304a56-8157-4d72-8ea8-428ccd9ed99e)


A search for call numbers lists the PNX records in tabular format, with the call number displaying in the first column. Clicking the title opens the PNX record in full display.

**Comment by lovinscari** [comment]
I am accepting this but leaving it in To Accept until the entire story is completed.
