### ISSUE TITLE
TASK: Refactor Indexing

### ISSUE THREAD

**Issue by rotated8** [emory-libraries/blacklight-catalog#304]
- [x] Refactor indexer to extract complex mappings
- [x] Remove SolrMarc
- [x] Identify and remove any rubocop exceptions as possible.

UCSB has a nice Traject setup. Here's how they [map an ETD](https://github.com/ucsblibrary/alexandria/blob/0e86b0bccb924c2a93865cd7bbb95a82ebd5fe2a/lib/traject/etd_config.rb). When they need to map something complex, like [contributors](https://github.com/ucsblibrary/alexandria/blob/0e86b0bccb924c2a93865cd7bbb95a82ebd5fe2a/lib/traject/etd_config.rb#L43), they separate out the complexity into [a separate include](https://github.com/ucsblibrary/alexandria/blob/0e86b0bccb924c2a93865cd7bbb95a82ebd5fe2a/lib/traject/extract_contributors.rb). There are more examples in the [containing dir](https://github.com/ucsblibrary/alexandria/tree/0e86b0bccb924c2a93865cd7bbb95a82ebd5fe2a/lib/traject).

We should refactor our indexer to better match UCSB's, so that maintenance on the indexer is easier in the future.

Since we have used the traject mapper for a while now, we can be confident that the SolrMarc indexer is not needed and can be removed.

**Comment by rotated8** [comment]
@bwatson78 I know we talked about changing the Solr batch size, but now that I'm writing this, that feels like a change more than a refactor, so I think we should skip it for now. We can come back to it if that becomes a bottleneck.

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/blacklight-catalog/pull/316

No screenshot necessary.
