### ISSUE TITLE
Change Keyword search configuration to use text_tesi field only

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/blacklight-catalog#305]
Story: As a catalog provider, I want to expand the options searchable by keyword, so that I can ensure a large of matches are possible in order to fine-tune relevancy 

This ticket relates to ticket #273

**SOLR/indexing notes**

- [x] Adjust the Keyword search option so that it only includes **text_tesi** (Field ID # 9) - this field already exists and includes the full text of the entire MARC record and will provide a much larger set of results; when this is implemented we can better see opportunities to adjust relevancy
- [x] Remove other individual fields currently configured for Keyword search

**Comment by bwatson78** [comment]
@eporter23 I have also left `id` in, since control fields are not scraped for `text_tesi`.

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/blacklight-catalog/pull/330

No screenshot(s) necessary.

**Comment by eporter23** [comment]
Thanks for catching the id part, @bwatson78 !

**Comment by bwatson78** [comment]
You're welcome, @eporter23
