### ISSUE TITLE
Spike: Trim punctuation - preview various Traject options on small samples

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/blacklight-catalog#306]
Story: as a metadata specialist, I want to preview the impact of trimming punctuation on certain display fields, so that I can make adjustments to mappings related to display before we do a full reindex of millions of records

Notes: we should make this change in a development or subset of records, then do a comparison vs. the set on arch or test.

Mockup/References

- [Metadata Worksheet/SOLR fields](https://docs.google.com/spreadsheets/d/1jSqgNd6HnVJdJMrrShAofkmK8uGgHGdlKODmZOL5NfY/edit#gid=1979033236)
- [View Item - Metadata Details template](https://docs.google.com/document/d/1VFbatpccRFGczEz510oHQHQtLmjAXAk9hTR5az9fkDc/edit)

SOLR Fields to preview [some may be pending creation]
- Field # 110 (Subjects display field)
- title_main_display_tesim
- author_display_ssim
- material_type_display

Sample settings to preview: 

- Default: Trim punctuation off
- On: Trim punctuation On

**Comment by eporter23** [comment]
To do: pick an appropriate OAI subset to perform this on

**Comment by bwatson78** [comment]
@eporter23 Would you like the contrast in a spreadsheet? Or is that not necessary--just make you aware of the reindexed environment?

**Comment by eporter23** [comment]
@bwatson78 if it's in an environment I can get to, just let me know. But if it's on your local environment we'd need to coordinate on some specific samples. Main thing is we didn't want to reindex prod before testing this out in a smaller set.

**Comment by bwatson78** [comment]
Arch has 4.7K+ records and it reindexes pretty fast. I found a really easy way to query Solr and output CSV, so I can create the spreadsheets, no problemo.

**Comment by eporter23** [comment]
@bwatson78 in looking at some possible records to test against, I realize there won't be much to preview for material_type_display_tesim (300) until we implement the revised mapping for it (adds additional subfields to it). So, I could remove that one from the ticket for now unless you've already included it.

**Comment by bwatson78** [comment]
@eporter23 Link to Google Sheet: https://docs.google.com/spreadsheets/d/10YreTbntgJLsSqmcKseLgCg_hUCGN2HC4YoM01hieHs/edit?usp=sharing

**Comment by bwatson78** [comment]
And @eporter23, would you like me to push the mapping for `subject_display_ssim` onto github, or hold off until you've reviewed sheet?

**Comment by eporter23** [comment]
@bwatson78 feel free to push that new field mapping for subjects. Thanks! I will start reviewing the sheet, also.

**Comment by bwatson78** [comment]
@eporter23 `trim_punctuation` for that field off?

**Comment by eporter23** [comment]
@bwatson78 yeah let's leave trim_punctuation off for that new subjects field.

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/blacklight-catalog/pull/335

No screenshot(s) necessary.

**Comment by eporter23** [comment]
@bwatson78 @lovinscari FYI, I [wrote up some notes ](https://docs.google.com/document/d/1RQcD-JjvbwkGgh_FqMNf0mckTlHAiJFDWQTqY0hx558/edit#) about various outlier patterns I've seen in the test set that Brad generated, and will factor these into future mapping revisions if applicable.
