### ISSUE TITLE
Markup Review for View Single Item Display

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/blacklight-catalog#308]
Story: As a UI designer, I want to identify re-usable markup for recurring design patterns, so that we can streamline development and offer consistent user experience across the discovery application

Anticipated tasks

- [x] Look at headings and patterns needed and markup for them specifically to display groups of fields and headings
- [x] Provide a framework for developers for consistencies 
- [x] Recommend re-using patterns from Lux when possible

See also Review current bootstrap ticket #295

**Comment by eporter23** [comment]
@norm0 - we discussed this ticket in standup today and much of this work is being addressed in #309 . We assigned this to you in case you want to use this as a review task of what is produced in 309.

**Comment by norm0** [comment]
<h1 id="search-results">Search Results</h1>

<article>
<h3 id="title">Title</h3>
<h4 id="vernacular-title">Vernacular Title</h4>

```
<dl>
  <dt> Author/Creator</dt>
  <dd> author_display<dd>
  ...
</dl>
```

</article>




Item Display Show
<section class="summary">
  <h1 id="title">Title</h1>
  <h2 id="vernacular-title">Vernacular Title</h2>
  ```
  <dl>
    <dt>Author/Creator</dt>
    <dd></dd> author_display
    ..
  </dl>
  ```
</section>

<hr>
<section class="find_it">
<h2 id="where-to-find-it">Where to find it</h2>
<div class="iframe-container">
  <iframe src="" frameborder="0">ALMA Content</iframe>
</div>

```
<dl>  
  <dt> Full Text Access</dt>
  <dd> url_fulltext_ssm</dd>
</dl>
```

</section>
<hr>

<section class="more_details">
<h2 id="more-details">More details</h2>
<h3 id="additional-related-title-information">Additional/Related Title Information</h3>

```
<dl>
  <dt>...</dt>
  <dd>...</dd>
<div class="btn btn-more">Show [more|less] Title Information</div> 
</dl>
```

<h3 id="related-names">Related Names</h3>

```
<dl>
  <dt>...</dt>
  <dd>...</dd>
<div class="btn btn-more">Show [more|less] authors/creators</div> 
</dl>
```

<h3 id="subject-genre">Subject/Genre</h3>

```
<dl>
  <dt>...</dt>
  <dd>...</dd>
<div class="btn btn-more">Show [more|less] Title Information</div> 
</dl>
```

<h3 id="description-summary">Description/Summary</h3>

```
<dl>
  <dt>...</dt>
  <dd>...</dd>
  ...
</dl>
```

<h3 id="additional-identifiers">Additional Identifiers</h3>

```
<dl>
  <dt>...</dt>
  <dd>...</dd>
  ...
</dl>
```

</section>

**Comment by norm0** [comment]
ID selector for identification purposes only.
