### ISSUE TITLE
STORY: Implement Brief Summary section of View Record - Metadata Display

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/blacklight-catalog#310]
Story: as an end user, I want to see a brief, meaningful summary/description of the resource, so that I may identify if the resource is what I am looking for before I have to scan a lot of additional information 

Mockups/References:
- [Main Wireframe](https://www.figma.com/file/ocSo3KytI6GgwjalSVAmE1/Blacklight-Wireframes?node-id=791%3A1) (section 4)
- [Variant Wireframe: Vernacular Entries for Title and Author - Section 1](https://www.figma.com/file/ocSo3KytI6GgwjalSVAmE1/Blacklight-Wireframes?node-id=875%3A18453)
- [Metadata Worksheet/SOLR fields](https://docs.google.com/spreadsheets/d/1jSqgNd6HnVJdJMrrShAofkmK8uGgHGdlKODmZOL5NfY/edit#gid=1979033236)

- Markup patterns - Follow framework from Markup Review ticket #308, #309 

Fields to display (label : SOLR fieldname)

1. Brief Title: title_main_display_tesim
2. Brief Title (Vernacular): title_vern_display_tesim
3. Author/Creator: author_display_ssim
4. Author/Creator (Vernacular): author_vern_ssim
5. Publication/Creation Info: publication_main_display
6. Type: format_ssim
7. Edition: edition_tsim

Display behaviors
- Fields should display in the order shown above (also in View Item - Metadata Details template)
- If a field is not populated, it should not display
- Display should use approved markup patterns
- This section doesn’t receive an overall heading; the Brief Title field should be the primary heading for the page (e.g. h1 or as otherwise specified)
- If a vernacular title (non-Roman script) is supplied, this should display as a subheading beneath the primary Brief Title (e.g. h2 or as otherwise specified)
- The other fields in the section should display in a smaller heading (e.g. h3 or as otherwise specified) 
- None of the fields in this section are hyperlinked

SOLR/indexing notes
- See the Metadata Worksheet for more detail. The following fields are proposed but may need revisions.
- Title_main_display_tesim has mapping revisions needed and also, we need to disable alternate script on this field
- title_vern_display_tesi should include multiples, should use a revised mapping noted in the Metadata Worksheet, and should include alternate script only
- Author_display_ssim has mapping revisions and the order of subfields is significant (display the relator term/role last, e.g. “composer” or “director” or “author”; also need to disable alternate script on this field
- author_vern_ssim has mapping revisions and should include alternate script/vernacular only
- Publication_main_display has mapping revisions and proposed logic for how to only extract one instance of publication/creation info. If possible, we also want to ensure that $c does not repeat. There is also a language code appearing in the current output which should be removed.
- Type: format_ssim has revised labels for the existing mapping
- Edition: edition_tsim has a revised mapping

**Comment by eporter23** [comment]
From team discussion, I will clarify the vernacular field(s) and behavior. If we have more than one vernacular, we will definitely want to split these out separately.

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/blacklight-catalog/pull/338

Below is proof that the the vernacular title is a different size header and below the main title:
![Screen Shot 2021-03-18 at 4.55.38 PM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/8860f021-4085-4ee9-9f5b-48ecb4180201)
![Screen Shot 2021-03-18 at 5.02.43 PM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/7fe35969-58aa-471d-bd0c-fff0137243c5)
![Screen Shot 2021-03-18 at 5.02.04 PM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/6dcf6211-cd10-4df8-90f3-1826cbb17cb0)

**Comment by eporter23** [comment]
@bwatson78 just starting testing this but wanted to ask, were the revised labels mapped for Type (format_ssim)? See notes in [Metadata Worksheet](https://docs.google.com/spreadsheets/d/1jSqgNd6HnVJdJMrrShAofkmK8uGgHGdlKODmZOL5NfY/edit#gid=1979033236&range=11:11).

**Comment by eporter23** [comment]
@bwatson78 never mind - for some reason I see some instances of the new labels in test but not in arch. Probably due to the different data sets and different states of reindexing.

**Comment by lovinscari** [comment]
@bwatson78 and @eporter23 - For some reason, there is a label "Information" appearing in the brief summary section and I can't see where that is referenced in the wireframe or metadata requirements. In every instance I have looked at, the field is blank in the display so I am not sure if this is an error or perhaps I am overlooking it somewhere. If this does need to be reworked please move this back to In Progress. I am attaching a screen shot for reference.
![SS_310.png](https://images.zenhubusercontent.com/5c4a1fe1e9b5fb46bcedb9fc/40449b79-4237-46d0-80d1-81654992d1a5)

**Comment by bwatson78** [comment]
The label would read `Publication/Creation Information` with a change in styling, which is a change from the wireframe (`Info` to `Information`) I made after speaking with @eporter23 about the verbiage being too informal. She advised to go forward with the change, stating it may go back based on spacing.

**Comment by lovinscari** [comment]
@bwatson78 - Thanks for the update but I do wonder why the label is appearing with no content?

**Comment by bwatson78** [comment]
There is content. `Chicago, IL...` is the content for `Publication/Creation Information` , it's just that the value is lining up at the beginning of the row's column, not at the end of `...Information:`.

**Comment by lovinscari** [comment]
Accepting this ticket as is but will put in another ticket to fix the alignment on Publication/Creation Information

**Comment by eporter23** [comment]
@lovinscari we could also remove the word "Information" altogether.

**Comment by eporter23** [comment]
@bwatson78 this is looking good! In reviewing some examples with vernacular entries, including one of your screenshots above, it looks like the vernacular author is getting repeated 2x. Any insights? Here's an example: https://blackcat-test.library.emory.edu/catalog/9936667981302486 
![Screen Shot 2021-03-25 at 9.19.13 AM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/b285559b-05f0-469f-8709-7a78b0b3df23)

**Comment by bwatson78** [comment]
@eporter23 Looking now.

**Comment by bwatson78** [comment]
@eporter23 Because I cannot reach the Solr feeding Test right now, this is just a theory: I'm combining together `author_display_ssim` and `author_vern_ssim` blindly at the moment. If the values in `author_vern_ssim` match what's in `author_display_ssim`, they will show up again. I can make a simple change in a new PR sending only unique values to this field, if you'd like.

**Comment by eporter23** [comment]
Discussed with @bwatson78 that the author_display_ssim probably contains the vernacular version, also. Suggest we remove the alternate script variant from that mapping to resolve this issue.

**Comment by eporter23** [comment]
@lovinscari moving back to In Progress so we can make a small tweak to remove vernacular authors showing up twice. Otherwise this is good to go.

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/blacklight-catalog/pull/361

![Screen Shot 2021-03-26 at 12.53.33 PM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/2d9ae7ae-68af-4a24-96be-9847896bd84b)
![Screen Shot 2021-03-26 at 12.54.19 PM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/e9d08029-41b2-4e1f-b143-82d3827c4dd9)

**Comment by eporter23** [comment]
Vernacular authors not repeating now: ![Screen Shot 2021-03-26 at 3.50.36 PM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/393ab58a-e278-4980-8d90-e64568afd8a8)![Screen Shot 2021-03-26 at 3.49.19 PM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/e6ba3416-c3eb-48a9-82eb-7b3497ea95cd)

I think we are good to close this one @lovinscari
