### ISSUE TITLE
STORY: Implement Availability/Full-text Access Section of View Single Item

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/blacklight-catalog#312]
Story: as an end user, when I view a record in detail I want to quickly see availability information about a resource, so that I can determine if a resource is available either online or on-site  

**Mockups/References:**

- [Main Wireframe](https://www.figma.com/file/ocSo3KytI6GgwjalSVAmE1/Blacklight-Wireframes?node-id=791%3A0) (section 5)
- [Metadata Worksheet](https://docs.google.com/spreadsheets/d/1jSqgNd6HnVJdJMrrShAofkmK8uGgHGdlKODmZOL5NfY/edit#gid=1979033236)

- Markup patterns - Follow framework from Markup Review tickets #308, #309

**Section Heading**

- Heading text: Where to find it

**Metadata fields to display (label : SOLR fieldname)**

1. Full-text Access: url_fulltext_ssm Field ID # 69

**Display behaviors**

- Add the Alma iframe in this section
- Show the Full-text Access field near the Alma iframe as depicted in the wireframe
- The Full-text Access field should be hyperlinked (see SOLR notes below)
- If url_fulltext_ssm is not populated, this page element should not display
- Display should use approved markup patterns

**SOLR/Mapping Revisions**

- Url_fulltext_ssm has revised mappings including conditions for selecting which subfield contains the link text. The url for the hyperlink is consistently $u.
- For hyperlinking, use $u for the href and whichever other subfield is selected for the link text.

**Comment by eporter23** [comment]
@norm0 and @lovinscari : @devanshu-m and I just chatted about what to do with the iframe component of this ticket, since it's grayed out in the wireframe right now and Norm is continuing to do some design on that. One thing we thought would be a good first step is to make the iframe(s) load when a user loads the page, so that they don't have to click on the buttons Physical or Online in order to see it. This should be a step toward other refinements we may try to make with the iframe.

**Comment by eporter23** [comment]
To clarify the above comment, instead of seeing this: ![Screen Shot 2021-03-18 at 3.42.48 PM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/94af96db-b306-4bce-abc2-23091580f0b0)

Users would see this when they open a record

![Screen Shot 2021-03-18 at 3.42.56 PM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/98c2ed79-90d1-4b70-b420-a042f18472a4)

**Comment by devanshu-m** [comment]
Question: Can there be multiple 856s with indicator2 = 0?

**Comment by eporter23** [comment]
@devanshu-m Yes, that is possible.

**Comment by lovinscari** [comment]
@devanshu-m and @eporter23 - I am not seeing the link to the full text access as depicted in the wireframe. However, because we are still discussing how to handle the iFrame, I am inclined to accept this as is with the understanding there are possible refinements coming in Sprint 8. Please let me know your thoughts before I close this ticket. Thanks!

**Comment by eporter23** [comment]
@lovinscari I've seen the full text access link on some examples this morning, but since SOLR is erratic right now I can't link to any examples. The full text access link would only show up on records that have those in an 856 field, and it displays just beneath the iframe.

**Comment by eporter23** [comment]
@lovinscari @devanshu-m this looks great and I think it can be closed, although Devanshu noted one scenario that may need to be addressed if an 856 doesn't have any link text populated.
