### ISSUE TITLE
Implement Related Names section of Single Item View Detail 

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/blacklight-catalog#314]
**Story:** As an end user, I want to see additional authors/contributors involved with a resource along with the role they played in its creation, so that I can learn more about who has contributed to the resource

**Demoable examples**
https://blackcat-test.library.emory.edu/catalog/990036309240302486
https://blackcat-test.library.emory.edu/catalog/990030289410302486

**Mockups/References:**

- [Main Wireframe](https://www.figma.com/file/ocSo3KytI6GgwjalSVAmE1/Blacklight-Wireframes?node-id=791%3A0)
- [Variant wireframe: more than 5 authors](https://www.figma.com/file/ocSo3KytI6GgwjalSVAmE1/Blacklight-Wireframes?node-id=738%3A137)
- [Metadata Worksheet/SOLR fields](https://docs.google.com/spreadsheets/d/1jSqgNd6HnVJdJMrrShAofkmK8uGgHGdlKODmZOL5NfY/edit#gid=1979033236)
- [View Item - Metadata Details template](https://docs.google.com/document/d/1VFbatpccRFGczEz510oHQHQtLmjAXAk9hTR5az9fkDc/edit#heading=h.8pdrjnsvk3y2)
- Markup patterns - Follow framework from Markup Review tickets #308, #309

**Heading:** Related Names

**Fields to display (label: SOLR fieldname)**

1. Additional Authors/Creators: author_addtl_tesim (or new field, based on feasibility of hyperlinking)

**SOLR/Mapping Revisions**

- The first 5 values for author_addtl_tesim should be visible by default, with a toggle option to see more entries
- Ideal state: name entry could be hyperlinked separately from relator term. _If not feasible this can be presented as unlinked text for Phase 1._
- Examples of desired hyperlink behavior, where the full author phrase is searchable except for the relator term/role (e.g. editor), which is displayed last. Subfields included for clarity:
-- [a| Yates, David, d| 1963-](#) e| director.   
--[ a| Kloves, Steven,](#) e| screenwriter. 
--[ a| Rowling, J. K.,](#) e| producer. 
--[ a| Radcliffe, Daniel, d| 1989-](#) e| actor. 

**SOLR/Mapping Revisions**
- See [Metadata worksheet](https://docs.google.com/spreadsheets/d/1jSqgNd6HnVJdJMrrShAofkmK8uGgHGdlKODmZOL5NfY/edit#gid=1979033236) for more detail about mappings to revise or add
- If we use author_addtl_tesim: Revised Mapping; include alternate script
- The relator term/role subfield specified in the mapping should be displayed last (if this is controlled by the extraction process) - noted in mapping details
- If we are able to create a hyperlink on the string minus the relator term subfield at the end, do we need another non-tokenized field(s)?

**Comment by bwatson78** [comment]
@eporter23 Just some thoughts on how to approach this:
- The best way to achieve the separation you're speaking of is to incorporate a custom mapping that calls out the relator explicitly in the string (i.e "Markovina, Ana-Marija, 1970-, relator: instrumentalist"). Doing that, I can split on the `, relator: ` and facet link everything before the separator. All of that is very "inside baseball", but it's justifying bumping this to a 5 and the next sprint.
- As far as needing another field (one for the display, another to perform the facet search on), that depends on what the acceptable faceting search behavior would be. If we display and facet search on the current field (which is tokenized), the likely results would include the expected items plus other tangentially related items. If the expected behavior is to return only items with a perfect match to the searched string, then, yes, we would need another string (non-tokenized) field mapping all of the fields minus the relator. 

For the time being, I will move forward on hiding more than 5 authors in a field behind a collapsible, since that is a pretty solid requirement.

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/blacklight-catalog/pull/358

![Screen Shot 2021-03-25 at 2.47.27 PM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/0871da53-27cd-4d30-9e5b-7432cccee196)
![Screen Shot 2021-03-25 at 2.48.51 PM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/b640e219-adc6-461f-bd03-125f0af7796c)
![Screen Shot 2021-03-25 at 2.49.05 PM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/4a949c03-d635-4ef3-994f-39e3f8a5dc92)

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/blacklight-catalog/pull/363

After checking some newly reindexed records, I noticed that some Addl Authors' links weren't producing search results. Checking the Solr records, I saw that the fields `author_addl_display_tesim` and `author_addl_ssim` weren't matching like they should. Originally, we expected the traject extraction method to pull subfield values in the order we listed them, but it instead treats those tags as a pool that is checked on each subfield as the method processes them, which is "first-in-first-out". I have updated my custom method to mimic that traject method.

**Comment by bwatson78** [comment]
@eporter23 Arch has been reindexed with these changes.

**Comment by eporter23** [comment]
@bwatson78 this looks really good and I think I've tested it as much as I can. Thank you for tackling the bonus option of hyperlinking minus the relator term! This should be good to close. One lingering question I have is about the trailing commas after names in some situations but we can address that later if needed. In digging into one example, I notice that there are two relator terms entered.  ![Screen Shot 2021-04-02 at 4.56.20 PM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/12d14dc3-ecab-451b-a224-818aef75427f)

![Screen Shot 2021-04-02 at 4.54.52 PM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/eec771b7-ce74-454e-b1e5-0258a7b19efe)

**Comment by bwatson78** [comment]
@eporter23 So if you mean the trailing comma after, for example, `Spiro, Anais` above, that is insert by me after the fact. I am running `trim_punctuation` on both the search field and the display field and not using commas in the separation of the values in Solr mapping. As far as multiple relators--down the road enhancement? It wouldn't take much to pull all `e`'s and join them in a conversational verbiage.

**Comment by eporter23** [comment]
@bwatson78 I was wondering about the trailing comma after `Schiff, Andras, conductor, ` - are we not able to remove trailing punctuation after the relator term? I'll also make a note of the multiple $e scenario as a possible refinement.

**Comment by bwatson78** [comment]
@eporter23  Ah, now I understand. I can definitely trim punctuation on the relator terms. Do you want me to circle back in this ticket for that?

**Comment by eporter23** [comment]
@bwatson78 yes, exactly! There is occasionally some odd trailing punctuation after the relator term(s). In this example, the comma is there because there is more than one relator term. I will write up an enhancement ticket to deal with both of those factors (more than one relator term, and removing trailing punctuation after the last relator term). Other than that oddity this looks great to me.
