### ISSUE TITLE
 Repair abnormal behavior when non-logged in user logs in when viewing Alma iFrame

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#318]
As the product owner, I noticed the following abnormal behavior...

1. Viewing an item detail page while not logged in and selecting the Physical Copy button to view requesting availability
![Notloggedin_IFrame.png](https://images.zenhubusercontent.com/5c4a1fe1e9b5fb46bcedb9fc/3c399465-8271-4c29-a2f5-3c43f312caa3) 
2. Selecting login which takes me to the Emory University Login Page
3. Afer logging in, instead of returning me to the page displayed in Step 1, I was taken back to the home page indicating my login was successful but requiring I start my search over again.
![LoginReturntoHome.png](https://images.zenhubusercontent.com/5c4a1fe1e9b5fb46bcedb9fc/e77c08bf-c3da-45f7-8764-224d2883b1f2)

Acceptance Criteria:

- [ ] User who is viewing a record but is not logged in is prompted to login according to the message in the iFrame (accepting iFrame message as is for purposes of this issue).

- [ ] When user logs in, they are returned the page viewing prior to logging in

- [ ] Blacklight application displays message the user successfully logged in according to banner at top of page and name displayed in header.

**Comment by eporter23** [comment]
Possible related work in Lux: https://app.zenhub.com/workspaces/digital-library-project-5bf484ae4b5806bc2bf6875b/issues/emory-libraries/dlp-lux/669

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/blacklight-catalog/pull/331

![Screen Shot 2021-03-12 at 12.10.50 PM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/78688382-c68c-4b5a-8437-d609145d1be1)
![Screen Shot 2021-03-12 at 12.11.10 PM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/98153a22-b8bd-4575-a719-a39f2d211bad)
![Screen Shot 2021-03-12 at 12.11.25 PM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/6215439b-bca6-4315-97fd-2d6a305c2c1c)

**Comment by lovinscari** [comment]
@bwatson78 - I tested this today and am still getting the same results except now when logging in, I get a message (taking me back to the home page) stating I am already logged in. I am going to move this back to In Progress, and if need be can meet with you tomorrow (Tuesday) to review. Thanks!

**Comment by bwatson78** [comment]
@lovinscari No need to meet--I've seen this behavior while tweaking the settings and thought I had corrected the issue, but obviously not the case. More tweaking required!

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/blacklight-catalog/pull/334

Video Link: https://emory-my.sharepoint.com/:v:/g/personal/bwatso9_emory_edu/EXLQ7GHwvOJNt0oX2jsgiz0BMhdYX6110r_bwbE9MyfUJA?e=8WTQvh
