### ISSUE TITLE
BUG: Repair function of date slider from home page

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#319]
As the product owner, I would like the function of the date slider repaired when narrowing search results using the Date Slider Facet from the home page. Currently, the pre-facet of the Publication/Creation Date shows a range of 504 through 2023. 
![DateSlider_Prefacet.png](https://images.zenhubusercontent.com/5c4a1fe1e9b5fb46bcedb9fc/d2c465a6-6d2d-4c45-ac4e-9e03131cb74b)
When modifying the date range to begin at 1903, I expect to see results of records with a publication/creation date from 1903 through 2023. The Publication/Creation Date facet indicates the narrowing of results should have produced 3,946,009 records but no records are displayed.
![DateSliderFacetBug.png](https://images.zenhubusercontent.com/5c4a1fe1e9b5fb46bcedb9fc/988eb064-5edd-464b-8f52-98bc86db66d4)

Acceptance Criteria:

- [ ] Allow narrowing of results using the Publication / Creation Date facet as described above and display results according to the date range selected.

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/blacklight-catalog/pull/332

Links to videos of Slider working:
https://emory-my.sharepoint.com/:v:/g/personal/bwatso9_emory_edu/ESuVaKboF9pIvzWIzxT5ZoMBckngOR-ixAwT7wSaflO6BQ?e=LAaV6B
https://emory-my.sharepoint.com/:v:/g/personal/bwatso9_emory_edu/EZzy5Cww_jRNgFRcGQTW_C0BeAmhmKlBVNixLRO6nJl2Ww?e=3LPGcm

**Comment by eporter23** [comment]
@bwatson78 @lovinscari works for me in test
