### ISSUE TITLE
SPIKE: Investigate possible improvements to Alma iFrame behavior to improve usability of view digital version online

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#320]
As the product owner, I would like to investigate any possible improvements to the Alma iFrame to improve usability. Some of the current abnormal or non-user friendly behaviors include:

- [ ] When selecting an online version of an item the login page is displayed within the iFrame as opposed to a way to access the online resource. In this instance, I was logged into the application but it does not appear my credentials are shared with the online version of the item.
![SelectOnlineVersion.png](https://images.zenhubusercontent.com/5c4a1fe1e9b5fb46bcedb9fc/873d709a-ffdd-46b5-a893-f96e3074369a)

- [ ] When selecting the Login option within the iFrame, the requesting of the electronic item seems to have produced an error.
![OnlineVersionError.png](https://images.zenhubusercontent.com/5c4a1fe1e9b5fb46bcedb9fc/804ae399-9cce-451c-bdf2-91ed2af12a88)

I understand that limited improvements are available with the iFrame. However, I would like to explore if improvements can be made in the following areas, and if so, details of the work required in order to improve the functionality.

Ideal Behavior:

- [ ] When user is displaying a single item record, the results are displayed similar to that of the UPenn Libraries Catalog iFrame Example
including standardizing the Location and making the login to view request options more apparent
![UPennIFrame.png](https://images.zenhubusercontent.com/5c4a1fe1e9b5fb46bcedb9fc/561e9035-1321-470d-b56e-96af16abee7d)

- [ ] The Login credentials from the application (Blacklight) should be passed to Alma when the iFrame is visible indicating the user is logged in and able to view the digital online record.

- [ ] At a minimum, the iFrame should contain information from the Access Online Tab within Primo including a link to the full text similar to the screenshot below.
![Primo_ViewOnline.png](https://images.zenhubusercontent.com/5c4a1fe1e9b5fb46bcedb9fc/d2040f6f-da49-4042-b65d-0c045b72a36d)

Acceptance Criteria:

- [ ] Meeting including Core Systems representative, member of application development team, UI Designer, Metadata expert and product owner convened to discuss options and ideal behavior. 

- [ ] Prior to the meeting, those in the meeting should read the [GetIt Knowledge Article](https://knowledge.exlibrisgroup.com/Alma/Product_Documentation/010Alma_Online_Help_(English)/060Alma-Primo_Integration/060Configuring_Alma_Delivery_System/020The_Primo_Get_It_Tab) 

- [ ] Outcomes of the meeting should include the shared understanding of what is possible with the GetIt Tab, a shared understanding of any current configurations to the Alma lightbox, a proposed process to prototype an improved interface of the Alma iFrame (Get It Tab) that passes user credentials for a user logged into the application and offers availability and requesting that is intuitive, a link for Full Text Online that takes the user directly to the full text option for immediate viewing (assuming the user is logged in) and is styled in a way that blends with the single item display as though it is embedded into the page as opposed to a separate component.

**Comment by lisahamlett** [comment]
Here is the breakdown of your options for customization of the Alma lightbox: [https://app.zenhub.com/files/295449627/8c13a249-86f0-4236-9347-0c83aafb45b0/download](https://app.zenhub.com/files/295449627/8c13a249-86f0-4236-9347-0c83aafb45b0/download)

**Comment by lisahamlett** [comment]
@eporter23 and I looked at this and determined the CSS for the lightbox is here:
https://na03.alma.exlibrisgroup.com/view/branding_skin/css/mashup.css?skinName=skin_OTB&version=March2021&skinVersion=1591516437&customerId=2485&institutionId=2486

I created a new skin with the name Blacklight, which removes the indent on "Additional services": https://na03.alma.exlibrisgroup.com/view/branding_skin/css/mashup.css?skinName=Blacklight

Tried applying it to lightbox call for viewit page: https://na03.alma.exlibrisgroup.com/view/uresolver/01GALI_EMORY/openurl?rfr_id=info:sid/primo.exlibrisgroup.com&u.ignore_date_coverage=true&svc_dat=viewit&rft.mms_id=9936570178002486&skinName=Blacklight

Did not work.  Will investigate.

**Comment by lisahamlett** [comment]
Submitted ticket to Ex Libris: https://exlibrisgroup--c.visualforce.com/apex/VF_Case_WithoutJira?id=5004y00001XI5AyAAL

**Comment by tmiles2** [comment]
Cari will do a write up (summary of the meeting), Emily will followup with Norm on the wireframes edites and Lisa will continue to investigating the iFrame lightbox

**Comment by lisahamlett** [comment]
The Ex Libris ticket was assigned to a technician.  That's all I've got from Ex Libris so far.

**Comment by norm0** [comment]
I'm working on wireframes from this discussion

**Comment by norm0** [comment]
Here is a working prototype of the iframes in a modal rather than inline with limited space...

https://www.figma.com/proto/ocSo3KytI6GgwjalSVAmE1/Blacklight-Wireframes?node-id=1108%3A58&viewport=-2616%2C1042%2C0.408201664686203&scaling=min-zoom&page-id=815%3A6
