### ISSUE TITLE
Implement Additional Identifiers section of View Item Detail

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/blacklight-catalog#324]
**Story:** As an end user, I want to review additional identifiers for the resource I'm viewing, so that I can search for the resource in other environments or confirm it is the exact one that I want

**Demoable examples**
https://blackcat-test.library.emory.edu/catalog/9936570178002486

**Mockups/References:**

- [Main Wireframe](https://www.figma.com/file/ocSo3KytI6GgwjalSVAmE1/Blacklight-Wireframes?node-id=791%3A0)
- [Metadata Worksheet/SOLR fields](https://docs.google.com/spreadsheets/d/1jSqgNd6HnVJdJMrrShAofkmK8uGgHGdlKODmZOL5NfY/edit#gid=1979033236)

- Markup patterns - Follow framework from Markup Review ticket #308, #309

**Heading:** Additional Identifiers

**Fields to display (label : SOLR fieldname)**

1. Catalog ID (MMSID): id
2. ISBN: isbn_ssim
3. ISSN: issn_ssim
4. OCLC Number: oclc_ssim
5. Other identifiers: other_standard_ids_ssim
6. Publisher Number: publisher_number_ssim

**Display behaviors**

- Display in the order shown above

**SOLR/Mapping Revisions**

- See the metadata worksheet for more detail
- For some ID values, should we keep these as SSIM or tokenize them for search?
- Catalog ID (MMSID): id - Existing mapping
- ISBN: isbn_ssim - Existing field mapping
- ISSN: issn_ssim - revised mapping
- OCLC Number: oclc_ssim - revised mapping
- Other identifiers: other_standard_ids_ssim - revised mapping
- Publisher Number: publisher_number_ssim - revised mapping

**Comment by bwatson78** [comment]
@eporter23 Arch has been reindexed with these changes.

**Comment by eporter23** [comment]
@devanshu-m looks great in arch, I'll need to do more testing with the production data set in test after the reindex.

**Comment by eporter23** [comment]
@lovinscari @devanshu-m I think I've been able to test enough samples in arch and prod - this looks great and should be good to close.
