### ISSUE TITLE
Review fields in Title search for refinements to see if updates are needed

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/blacklight-catalog#325]
After we revise the metadata mappings for Single Item Display, we should review the fields configured for the Title search.

- [x] Review title-related fields in the Metadata Worksheet vs. most current indexer mappings
- [x] Review fields configured for the Title search dropdown for any changes needed (new fields to add, old fields to remove, etc.)
- [x] Review fields configured for the Advanced search form for any changes needed
- [x] Update Metadata Worksheet with any documentation updates needed
- [x] Write implementation tickets for any configuration changes needed

**Comment by lovinscari** [comment]
@eporter23 - Can you please update this ticket with acceptance criteria?

**Comment by bwatson78** [comment]
@eporter23 Here is the link to my analysis document: https://docs.google.com/document/d/1R-z4FR1J2VEpePcHwkp2z5Foc_xffC2vh6tyXlHUYZ8/edit?usp=sharing

**Comment by eporter23** [comment]
Looks good @bwatson78 and I wrote up revision ticket #529 to follow this.
