### ISSUE TITLE
Review Author/Creator search fields to see if updates are needed

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/blacklight-catalog#326]
After we revise the metadata mappings for Single Item Display, we should review the fields configured for the Author/Creator search.

- [x] Review author-related fields in the Metadata Worksheet vs. most current indexer mappings
- [x] Review fields configured for the Author search dropdown for any changes needed (new fields to add, old fields to remove, etc.)
- [x] Review fields configured for the Advanced search form for any changes needed
- [x] Update Metadata Worksheet with any documentation updates needed
- [x] Write implementation tickets for any configuration changes needed

**Comment by lovinscari** [comment]
@eporter23 - Can you please update this ticket with acceptance criteria?

**Comment by bwatson78** [comment]
@eporter23 Summary document to review: https://docs.google.com/document/d/1f0y0-KcSWwgxTKCJLmqu1jbiNjTmU5v_lsV3WB3GCrU/edit?usp=sharing

**Comment by eporter23** [comment]
@bwatson78 looks good, thanks! I added some comments to the doc. Do you want to write up the implementation ticket or should I?

**Comment by bwatson78** [comment]
@eporter23 I have created ticket #531 in response to the comments on the summary document above. I've also added the fields to review for deletion to #311.

**Comment by eporter23** [comment]
@bwatson78 thanks, I reviewed and commented on your notes. @lovinscari this should be good to close.
