### ISSUE TITLE
Review fields in Subject search for refinements to see if updates are needed

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/blacklight-catalog#327]
After we revise the metadata mappings for Single Item Display, we should review the fields configured for the Subjects search.

- [x] Review subject-related fields in the Metadata Worksheet vs. most current indexer mappings
- [x] Review fields configured for the Subject search dropdown for any changes needed (new fields to add, old fields to remove, etc.)
- [x] Review fields configured for the Advanced search form for any changes needed
- [x] Update Metadata Worksheet with any documentation updates needed
- [x] Write implementation tickets for any configuration changes needed

**Comment by lovinscari** [comment]
@eporter23 - Can you please update this ticket with acceptance criteria?

**Comment by bwatson78** [comment]
@eporter23 Summary document to review: https://docs.google.com/document/d/1a_CABvGfgZAb1_EcgqYXFicU1jWeHK80iJuyq-VS7Tk/edit?usp=sharing

**Comment by eporter23** [comment]
@bwatson78 looks good - I added a few comments. As with the others let me know if you want me to write up the implementation tickets or if you want to.

**Comment by bwatson78** [comment]
@eporter23 I have created a ticket off of the recommendations in the summary document (#532). I have also added the field deemed flagged for deletion to #311.
