### ISSUE TITLE
Determine metadata requirements for citation format options in Tools Menu

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#344]
- As a library user, I would like the ability to formulate a citation from a library record using various bibliography styles including APA, MLA, and Chicago. 

- I would like for the Cite option in the Tools Menu similar to the functionality currently in Emory Digital Collections that captures relevant data from the item record and format according to the bibliography styles. 

- The end result of this feature will allow me to copy the citation and paste into my research paper. Exporting into different citation tools will be a future enhancement.

Acceptance Criteria:

- [x] Develop a proposed for metadata requirements based on the current metadata model. 

- [ ] Present to the Metadata Subgroup Members for approval.

- [ ] Provide metadata requirements including SOLR field names to Norm (reference ticket [#345](https://app.zenhub.com/workspaces/blacklight-catalog-5f5f84a8a6d29939a0bc5d78/issues/emory-libraries/blacklight-catalog/345)) for incorporation into a future wireframe for this feature. 

Work notes:
Basic mappings and stories have been documented in tickets #413, #415, #417

**Comment by eporter23** [comment]
Per other meeting notes, I will be checking with Erin Mooney and Sarah Morris about major citation styles to support.
