### ISSUE TITLE
Refine wireframe for Tools Menu on Single Item View Display

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#345]
As the product owner, I would like refinements made to the Tools Menu that currently appears in the Single Item View Display in order to improve the overall functionality and make the feature more user friendly. 

The Tools Menu in its final form will include the following functions (listed in order as they should appear)

- Bookmark Item (with a check box the user will select to bookmark the item. Currently listed as "bookmark" but believe there should be a differentiation between bookmark the item and the Bookmarks in the header. )

- Cite (metadata requirements coming from Emily Porter reference ticket [#344](https://app.zenhub.com/workspaces/blacklight-catalog-5f5f84a8a6d29939a0bc5d78/issues/emory-libraries/blacklight-catalog/344))

- Print (currently does not exist but is a requirement defined by stakeholders)

- Direct Link (this will be a persistent identifier to the record that can be copied and shared This is based on similar functionality in emory Digital Collections - Reference DLP Zen Hub [#560] (https://app.zenhub.com/workspaces/digital-library-project-5bf484ae4b5806bc2bf6875b/issues/emory-libraries/dlp-lux/560)

- Help (this will eventually link to a static help page but will initially just include the label)

- Feedback (this will eventually link to a feedback form but will initially just include the label)

- Staff View (currently listed as Librarian View)

Acceptance Criteria:

- [x] Refine the existing wireframe for the Tools Menu based on requirements above

- [x] Annotate wireframe based on above requirements for future development

- [x] Provide CSS Markup of Tools Menu based on styling in Lux with dark blue header and gold text (see screen shot below)
![ToolsMenuStyle.png](https://images.zenhubusercontent.com/5c4a1fe1e9b5fb46bcedb9fc/ea59261a-bef5-4277-888d-5aa86c644724)

**Comment by norm0** [comment]
Wireframes and mockups
![Tools.png](https://images.zenhubusercontent.com/5f8492d49b473a0cef37940f/b774896b-1eaf-4c17-b868-0a97ee9c6122)

**Comment by norm0** [comment]
@lovinscari To confirm, these requirements remove the "Export to Endnotes" and "Export to Refworks" functions for future use.

**Comment by eporter23** [comment]
@lovinscari and @norm0 we should also confirm if the Export... options may be simpler to implement than the standard Cite option. I hope to confirm with @mark-dce soon.

**Comment by norm0** [comment]
This is the version for development

![Group 16.png](https://images.zenhubusercontent.com/5f8492d49b473a0cef37940f/58b5a4e4-52a4-422e-b492-1669bbc38ee8)
