### ISSUE TITLE
SPIKE: Determine what Cloudwatch Metrics are available to set benchmarks on SOLR Performance

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#348]
As the product owner, I would like for members of the Infrastructure Team, Collin Brittle, and Mark Bussey to determine what Cloudwatch Metrics are available to set benchmarks on SOLR performance. The outcome of this spike is to document what metrics are currently in place or should be implemented to set benchmarks on a steady state for SOLR performance so that alerts can be implemented when any degradation of performance occurs similar to the recent errors when SOLR has stopped communicating with the Test environment. 

Considerations:

- [ ] Cloudwatch metrics on SOLR to determine a baseline on connections to test environment
- [ ] Review DLP Alerts slack channel to the various alerts from Cloudwatch indicating SOLR has stopped communicating with Test. These same errors are occurring for both DLP and Blacklight test environments

Acceptance Criteria:

- [x] Meeting scheduled with @mlooney, @libah, @libdgg, @AGCooper, @rotated8, @mark-dce to review information above.

- [x] Metrics (existing or new) and benchmarks should be documented within ticket.

- [x] Create a new ticket for backlog to establish Cloudwatch alarms for any degradation of performance with SOLR that would indicate a lack of communication between SOLR and any of the associated environments in Blacklight or DLP.

- [x] Create a new ticket for backlog to rename DLP Alerts slack channel that includes the review of any scripts or other documentation that will need updating if the slack channel is renamed.

**Comment by rotated8** [comment]
Suggested metrics:
- Disk usage, alert when >=80%
- JVM heap usage, alert when >=95% for 5? minutes, polling every 1? minute
- system memory usage, no alert, watch for baseline first.
- cpu utilization, alert >=90% for 4? minutes, polling every 1? minute

Other suggestions:
- Spike for anomaly detection
- check solr connection pool in Blacklight app
- Spike for query resolution time

via @mark-dce: https://lucidworks.com/post/the-seven-deadly-sins-of-solr/

**Comment by mark-dce** [comment]
New stories:
* #403 Configure Additional CloudWatch Alerting#403 + associated tasks
* #404 SPIKE: Investigate LITS access to AWS Anomaly Detection
* #405 SPIKE: monitor web server response time
