### ISSUE TITLE
Fix alignment of Publication/Creation Information on Single Item View Display

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#349]
As noted in issue [#310](https://app.zenhub.com/workspaces/blacklight-catalog-5f5f84a8a6d29939a0bc5d78/issues/emory-libraries/blacklight-catalog/310), the alignment of the Publication/Creation Information display information is off since the word "Information" appears on a second line. 

Acceptance Criteria:

- [ ] App Developers, Metadata Expert, and UI Designer work together to determine a fix to bring all words of label on one line (such as abbreviating or removing words from the label) OR fix alignment so it is apparent the label is on two lines and the results are appearing on the second line.

- [ ] Implement change on the single item view in the Brief Details section.

**Comment by eporter23** [comment]
@norm0 @lovinscari I propose we remove the word "Information" from the label. This is [element 4b on the wireframe](https://www.figma.com/file/ocSo3KytI6GgwjalSVAmE1/Blacklight-Wireframes?node-id=791%3A1).

**Comment by eporter23** [comment]
Thanks @alexBLR ! Label is corrected now. ![Screen Shot 2021-04-02 at 1.00.02 PM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/62d75448-b1c8-4b57-9da6-e11c30c64de7)
