### ISSUE TITLE
Description/Summary - first 15 fields

### ISSUE THREAD

**Issue by mark-dce** [emory-libraries/blacklight-catalog#353]
NOTE: This ticket it part of Epic #323 - see that ticket for the broader context of the displayed fields

**Mockups/References:**

- [Main Wireframe ](https://www.figma.com/file/ocSo3KytI6GgwjalSVAmE1/Blacklight-Wireframes?node-id=791%3A0)
- Variant Wirefame:[ Resource with Many Notes](https://www.figma.com/file/ocSo3KytI6GgwjalSVAmE1/Blacklight-Wireframes?node-id=746%3A402)
- [Metadata Worksheet/SOLR fields](https://docs.google.com/spreadsheets/d/1jSqgNd6HnVJdJMrrShAofkmK8uGgHGdlKODmZOL5NfY/edit#gid=1979033236)
- [Metadata example with many notes](https://docs.google.com/document/d/189qK6_RQY_rSRvEgPpSTnRhzWwcUuS5moqy8BkAB248/edit) and main [View Item - Metadata Details template](https://docs.google.com/document/d/1VFbatpccRFGczEz510oHQHQtLmjAXAk9hTR5az9fkDc/edit)
- Markup patterns - Follow framework from Markup Review ticket #308, #309

**Heading:** Description/Summary

**Fields to display (label : SOLR fieldname)**

- [x] 1. Finding Aid: [TBD # 101]
- [x] 2. Table of Contents: [TBD new field # 71]
- [x] 3. Summary: [TBD new field # 77]
- [x] 4. Publication Note: TBD Field # 106
- [x] 5. Publication Dates: TBD Field # 118
- [x] 6. Language: language_ssim 
- [x] 7. Language Note: [TBD # 105]
- [x] 8. Accessibility Note: [TBD # 74]
- [x] 9. Physical/Type Description: material_type_display_tesim
- [x] 10. Technical Note: [TBD - field # 116]
- [x] 11. Restrictions on Access: [TBD Field ID # 99]
- [x] 12. Use and reproduction: [TBD Field ID # 100]
- [x] 13. General Note: note_general_tsim
- [x] 14. Local Note: [TBD Field # 79]
- [x] 15. Participant/Performer Note: [TBD Field ID # 41]

**Display behaviors**
- Display in the order shown above
- If a field is not populated, it should not display
- If no fields in the section are populated, the accompanying section heading should also not display
- Finding Aid: [TBD # 101]: Field should be hyperlinked if $u populated; link text $a; url = $u 
- Language: language_ssim: Hyperlinked for exact phrase search

**SOLR/Mapping Revisions**
- See [Metadata worksheet](https://docs.google.com/spreadsheets/d/1jSqgNd6HnVJdJMrrShAofkmK8uGgHGdlKODmZOL5NfY/edit#gid=1979033236) for more detail about mappings to revise or add
- Finding Aid: [TBD # 101] New field mapping 
- Table of Contents: [TBD new field # 71] - new field mapping
- Summary: new field # 77
- Publication Note: TBD Field # 106 - new field
- Publication Dates: TBD Field # 118 - new field
- Language: language_ssim - existing mapping; remove exact duplicates if feasible
- Language Note: [TBD # 105]  - new field
- Accessibility Note: [TBD # 74]  - new field
- Physical/Type Description: material_type_display_tesim - revised mapping
- Technical Note: [TBD - field # 116]  - new field
- Restrictions on Access: [TBD Field ID # 99]  - new field
- Use and reproduction: [TBD Field ID # 100]  - new field
- General Note: note_general_tsim  - new field
- Local Note: [TBD Field # 79]  - new field
- Participant/Performer Note: [TBD Field ID # 41]  - new field

**Comment by norm0** [comment]
I asked a question on the Blacklight forum for any read more examples... this the response I received...

> https://dlmenetwork.org/library/catalog/81055%2Fvdc_100000000419.0x0000a0_dlme (see the description field). which wraps the whole field and truncates to 6 visible lines of text

> https://github.com/sul-dlss/dlme/blob/master/config/initializers/blacklight.rb#L11
> https://github.com/sul-dlss/dlme/blob/master/app/processors/collapse.rb#L4
> https://github.com/sul-dlss/dlme/blob/master/app/assets/javascripts/line-collapse.js
> https://github.com/sul-dlss/dlme/blob/master/app/controllers/catalog_controller.rb#L88
> are… the key pieces of our implementation, at least

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/blacklight-catalog/pull/364

**Comment by bwatson78** [comment]
![Screen Shot 2021-03-29 at 6.00.24 PM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/94fb9010-2388-4b5b-984d-eb1e2ea0294b)
![Screen Shot 2021-03-29 at 6.07.15 PM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/33d5183e-3ce2-4844-b774-4c7fef77f06e)
![Screen Shot 2021-03-29 at 6.07.31 PM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/d42dfe37-d8d8-4b7e-84e7-9d260574b80c)
![Screen Shot 2021-03-29 at 6.11.10 PM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/202fc7c6-73e4-421e-bc63-feffb81a3a49)
![Screen Shot 2021-03-29 at 6.13.27 PM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/d8d74cb9-ac10-4401-9419-552980b11361)
![Screen Shot 2021-03-29 at 6.15.34 PM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/42a1311a-c5ed-457f-b777-c256bb1cefc4)

**Comment by eporter23** [comment]
Looks great, @bwatson78 and @lovinscari.
