### ISSUE TITLE
Description/Summary - remaining fields

### ISSUE THREAD

**Issue by mark-dce** [emory-libraries/blacklight-catalog#354]
**Mockups/References:**

- [Main Wireframe ](https://www.figma.com/file/ocSo3KytI6GgwjalSVAmE1/Blacklight-Wireframes?node-id=791%3A0)
- Variant Wirefame:[ Resource with Many Notes](https://www.figma.com/file/ocSo3KytI6GgwjalSVAmE1/Blacklight-Wireframes?node-id=746%3A402)
- [Metadata Worksheet/SOLR fields](https://docs.google.com/spreadsheets/d/1jSqgNd6HnVJdJMrrShAofkmK8uGgHGdlKODmZOL5NfY/edit#gid=1979033236)
- [Metadata example with many notes](https://docs.google.com/document/d/189qK6_RQY_rSRvEgPpSTnRhzWwcUuS5moqy8BkAB248/edit) and main [View Item - Metadata Details template](https://docs.google.com/document/d/1VFbatpccRFGczEz510oHQHQtLmjAXAk9hTR5az9fkDc/edit)
- Markup patterns - Follow framework from Markup Review ticket #308, #309

**Heading:** Description/Summary

**Fields to display (label : SOLR fieldname)**

-- Add the following fields at the end of the section --

- [x] 16. Creation/Production Credits Note: [TBD: Field ID # 42]
- [x] 17. Date/Time and Place of an Event: [TBD: Field ID # 120]
- [x] 18. Organization and Arrangement: [TBD # 98]
- [x] 19. Additional Physical Form: [TBD # 102]
- [x] 20. Biographical/Historical Note: [TBD # 108]
- [x] 21. Reproduction Note: [TBD # 103]
- [x] 22. Location of Originals: [TBD # 104]
- [x] 23. Ownership and custodial history: [TBD # 88]
- [x] 24. Copy and version identification: [TBD # 89]
- [x] 25. Binding note: [TBD # 90]
- [x] 26. Citation/Reference note: [TBD # 91]
- [x] 27. Related Collections: [TBD # 107]
- [x] 28. Related Resources Link: url_suppl_ssm.
- [ ] 

**Display behaviors**
- Display in the order shown above (after the first 15 fields)
- If a field is not populated, it should not display
- If no fields in the section are populated, the accompanying section heading should also not display
- Finding Aid: [TBD # 101]: Field should be hyperlinked if $u populated; link text $a; url = $u 
- Language: language_ssim: Hyperlinked for exact phrase search
- Related Resources Link: url_suppl_ssm: hyperlink using $u for url and extracted subfield (y/3/z) for link text (see worksheet for more details)

**SOLR/Mapping Revisions**
- See [Metadata worksheet](https://docs.google.com/spreadsheets/d/1jSqgNd6HnVJdJMrrShAofkmK8uGgHGdlKODmZOL5NfY/edit#gid=1979033236) for more detail about mappings to revise or add
- Creation/Production Credits Note: [TBD: Field ID # 42]  - new field
- Date/Time and Place of an Event: [TBD: Field ID # 120]  - new field
- Organization and Arrangement: [TBD # 98]  - new field
- Additional Physical Form: [TBD # 102]  - new field
- Biographical/Historical Note: [TBD # 108]  - new field
- Reproduction Note: [TBD # 103]  - new field
- Location of Originals: [TBD # 104]  - new field
- Ownership and custodial history: [TBD # 88]  - new field
- Copy and version identification: [TBD # 89]  - new field
- Binding note: [TBD # 90]  - new field
- Citation/Reference note: [TBD # 91]  - new field
- Related Collections: [TBD # 107]
- Related Resources Link: url_suppl_ssm - revised field mapping

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/blacklight-catalog/pull/368

@eporter23 About a half a dozen of the latter fields were hard to find records to display label/value examples, so I'm just posting a couple of examples that cover as many of the fields I can find in `blacklighttest'.

![Screen Shot 2021-03-31 at 11.30.04 AM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/5f5ac3bb-4b33-4de7-8b5e-87b0fe084914)
![Screen Shot 2021-03-31 at 11.32.06 AM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/e9a25877-d984-4fd7-bfed-8c8cc43f8bb1)

**Comment by eporter23** [comment]
@bwatson78 If this hasn't been deployed yet, related to #353 I just noticed this typo: _Physical Type/Desription:_ - can we change to Physical/Type Description

**Comment by eporter23** [comment]
Looks great @bwatson78 and @lovinscari - closing.
