### ISSUE TITLE
Truncate long fields - Description/Summary initial fields

### ISSUE THREAD

**Issue by mark-dce** [emory-libraries/blacklight-catalog#355]
**Story:** As a searcher, I don't want to see super long fields, so that the page has a visual rhythm that helps me quickly scan all the metadata.

**Details:**  We have a number of fields that potentially contain very long text entries that would span many lines, these can throw off the visual rhythm for folks trying to quickly scan metadata values.  To help give the page better visual rhythm, we'd like to truncate these 

**Display behaviors**
- When initially displaying the page, show first 160 characters of the field plus a “read more” link
- When the user clicks "read more", the remaining text in the field should be displayed followed by a "read less" link
- When the user clicks "read less" link, revert to showing the first 160 characters plus the "read more" link

**Mockups/References:**

- [Main Wireframe ](https://www.figma.com/file/ocSo3KytI6GgwjalSVAmE1/Blacklight-Wireframes?node-id=791%3A0)
- Variant Wirefame:[ Resource with Many Notes](https://www.figma.com/file/ocSo3KytI6GgwjalSVAmE1/Blacklight-Wireframes?node-id=746%3A402)
- [Metadata Worksheet/SOLR fields](https://docs.google.com/spreadsheets/d/1jSqgNd6HnVJdJMrrShAofkmK8uGgHGdlKODmZOL5NfY/edit#gid=1979033236)
- [Metadata example with many notes](https://docs.google.com/document/d/189qK6_RQY_rSRvEgPpSTnRhzWwcUuS5moqy8BkAB248/edit) and main [View Item - Metadata Details template](https://docs.google.com/document/d/1VFbatpccRFGczEz510oHQHQtLmjAXAk9hTR5az9fkDc/edit)
- Markup patterns - Follow framework from Markup Review ticket #308, #309

**Acceptance:**
We have a read-more toggle similar to the mock-ups applied to the following 15 fields
- [x] Finding Aid (this should be a link already and should not be truncated)
- [x] Table of Contents
- [x] Summary
- [x] Publication Note
- [x] Publication Dates
- [x] Language (all values should always be displayed, do not toggle)
- [x] Language Note
- [x] Accessibility Note
- [x] Physical/Type Description
- [x] Technical Note
- [x] Restrictions on Access
- [x] Use and reproduction
- [x] General Note
- [x] Local Note
- [x] Participant/Performer Note

**MOCKUP** see [figma](https://www.figma.com/file/ocSo3KytI6GgwjalSVAmE1/Blacklight-Wireframes?node-id=829%3A16887) for more detail
<img width="621" alt="image" src="https://user-images.githubusercontent.com/3064318/112517461-58be9e00-8d66-11eb-8abc-52d7179e7a3f.png">

**Comment by norm0** [comment]
I asked a question on the Blacklight forum for any "read more" examples... this the response I received...

> https://dlmenetwork.org/library/catalog/81055%2Fvdc_100000000419.0x0000a0_dlme (see the description field). which wraps the whole field and truncates to 6 visible lines of text

> https://github.com/sul-dlss/dlme/blob/master/config/initializers/blacklight.rb#L11
> https://github.com/sul-dlss/dlme/blob/master/app/processors/collapse.rb#L4
> https://github.com/sul-dlss/dlme/blob/master/app/assets/javascripts/line-collapse.js
> https://github.com/sul-dlss/dlme/blob/master/app/controllers/catalog_controller.rb#L88
> are… the key pieces of our implementation, at least

I'd also like to call your attention to the original idea or design I intended: https://hclib.bibliocommons.com/v2/record/S109C5212440

**Comment by norm0** [comment]
<p class="codepen" data-height="265" data-theme-id="light" data-default-tab="js,result" data-user="norm0" data-slug-hash="gOgrPQQ" style="height: 265px; box-sizing: border-box; display: flex; align-items: center; justify-content: center; border: 2px solid; margin: 1em 0; padding: 1em;" data-pen-title="Read More option A">
  <span>See the Pen <a href="https://codepen.io/norm0/pen/gOgrPQQ">
  Read More option A</a> by Norm Orstad (<a href="https://codepen.io/norm0">@norm0</a>)
  on <a href="https://codepen.io">CodePen</a>.</span>
</p>
<script async src="https://cpwebassets.codepen.io/assets/embed/ei.js"></script>

**Comment by norm0** [comment]
<p class="codepen" data-height="265" data-theme-id="light" data-default-tab="html,result" data-user="maxds" data-slug-hash="jgeoA" style="height: 265px; box-sizing: border-box; display: flex; align-items: center; justify-content: center; border: 2px solid; margin: 1em 0; padding: 1em;" data-pen-title="jQuery Read More/Less Toggle">
  <span>See the Pen <a href="https://codepen.io/maxds/pen/jgeoA">
  jQuery Read More/Less Toggle</a> by Max (<a href="https://codepen.io/maxds">@maxds</a>)
  on <a href="https://codepen.io">CodePen</a>.</span>
</p>
<script async src="https://cpwebassets.codepen.io/assets/embed/ei.js"></script>

**Comment by norm0** [comment]
@bwatson78 I'm looking for help on how do I exclude the fields(Finding Aid URL and Language).

**Comment by norm0** [comment]
Animation of read more/ read less![2021-03-29 17.32.04.gif](https://images.zenhubusercontent.com/5f8492d49b473a0cef37940f/e0b2c849-dcd0-4983-90fa-5745a1387ef2)

**Comment by eporter23** [comment]
Looks great @norm0, looking forward to the second set getting deployed!
