### ISSUE TITLE
Truncate long fields - Description/Summary remaining fields

### ISSUE THREAD

**Issue by mark-dce** [emory-libraries/blacklight-catalog#356]
Add a truncation toggle to the remaining fields in the Description/Summary section of the single item show page.  See #355 *Truncate long fields - Description/Summary initial fields* for more details

**Acceptance:**
Add the field truncation toggle to the following fields
- [x] Creation/Production Credits Note
- [x] Date/Time and Place of an Event
- [x] Organization and Arrangement
- [x] Additional Physical Form
- [x] Biographical/Historical Note
- [x] Reproduction Note
- [x] Location of Originals
- [x] Ownership and custodial history
- [x] Copy and version identification
- [x] Binding note
- [x] Citation/Reference note
- [x] Related Collections
- [x] Related Resources Link (this field should already be a link and *should not* be truncated)

**Comment by lovinscari** [comment]
@eporter23 - this looks good to me but I would like you to take a second look. If you are good with it please close this issue.

**Comment by eporter23** [comment]
I tested this in arch and to some degree in test and it looks good to me. Test and arch are having some issues at present but I feel like we are good to close this. Thank you @alexBLR
