### ISSUE TITLE
Adjust trailing punctuation on facet fields

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/blacklight-catalog#357]
For the following facets, we should implement the trim punctuation feature from Traject to remove miscellaneous trailing characters that can occur due to how we are only mapping selected subfields in these facets:

- [x] Author/Creator
- [x] Collection

Examples of unwanted trailing punctuation:

![Screen Shot 2021-03-25 at 2.17.07 PM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/8f9ea099-f74e-4e4b-8d5e-a5ffe6e4f74a)

![Screen Shot 2021-03-25 at 2.19.35 PM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/54508814-62fa-4110-905f-4bac1cb5d15a)

**Comment by eporter23** [comment]
@lovinscari adding this to Backlog in case we have any extra time to address it

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/blacklight-catalog/pull/366

No screenshots necessary.

**Comment by eporter23** [comment]
Looks good so far in arch, pending more robust testing on production data once we reindex again.

**Comment by eporter23** [comment]
Looks much improved! Thanks @bwatson78 . Closing this, @lovinscari
