### ISSUE TITLE
Build new TEST environment using automation/scripting

### ISSUE THREAD

**Issue by mark-dce** [emory-libraries/blacklight-catalog#359]
**Story:**
We would like a TEST environment that has been built using automated processes rather than cloned and manually modified from another environment.

**Acceptance:**
Using the scripting developed in #254 **Automate Infrastructure Configuration**,
- [x] Build a new environment (TEST-2) to take the place of the existing test environment (TEST-1)
- [x] Populate, clone, restore, or link to existing data sources as needed
- [x] Confirm the environment works as expected
   - [x] I can search when on VPN
   - [x] I can login and request a hold on VPN (identify if this needs to happen after the next step)
- [x] Swap external DNS to point (TEST-2) instead of (TEST-1)
- [x] Decommission the old environment (TEST-1)

**Comment by mlooney** [comment]
https://internal-blackcat-test2-alb-1615745440.us-east-1.elb.amazonaws.com Is up and running.


DNS will have to wait for Ann to file the tickets

**Comment by libah** [comment]
Updated DNS and added f5 rules.

**Comment by mlooney** [comment]
verified dns is updated, but shibboleth is having difficulty, despite identical configuration to prod2. investigating.

**Comment by lisahamlett** [comment]
Ticket submitted asking for help from Shibboleth team.

**Comment by lisahamlett** [comment]
I have set up a meeting with McClain and Gerry at 12pm tomorrow (4/2).

**Comment by libah** [comment]
Test is now pointing to the new environment.
