### ISSUE TITLE
Build a new PROD environment using automation/scripting

### ISSUE THREAD

**Issue by mark-dce** [emory-libraries/blacklight-catalog#360]
**Story:**
We would like a PROD environment that has been built using automated processes rather than cloned and manually modified from another environment.

**Acceptance:**
Using the scripting developed in #254 **Automate Infrastructure Configuration**,
- [x] Build a new environment (PROD-2) to take the place of the existing test environment (PROD-1)
- [x] Populate, clone, restore, or link to existing data sources as needed
- [x] Confirm the environment works as expected
   - [x] I can search when on VPN
   - [x] I can login and request a hold on VPN (identify if this needs to happen after the next step)
- [x] Swap external DNS to point (PROD-2) instead of (PROD-1)
- [x] Decommission the old environment (PROD-1)

**Comment by mlooney** [comment]
https://internal-blackcat-prod2-alb-606824226.us-east-1.elb.amazonaws.com 


When Ann returns, we can file the tickets to swap around dns.

**Comment by libah** [comment]
Updated dns and added f5 rules

**Comment by mlooney** [comment]
verified dns & Shib are working

**Comment by eporter23** [comment]
@mlooney and @libah I just checked this out with @oraposa. Everything looks good, but note for future testing - the certificate trust alarms are a little distracting when you first open the url up. I understand this will get resolved when we switch things out, just an FYI to others who might test this.

**Comment by eporter23** [comment]
Putting this back into team review in case we need to discuss the prod swap out.

**Comment by libah** [comment]
Prod is now pointing to the new environment.
