### ISSUE TITLE
Convert Genre Values Into Facet Search Hyperlinks

### ISSUE THREAD

**Issue by bwatson78** [emory-libraries/blacklight-catalog#369]

**Comment by bwatson78** [comment]
PR made:m https://github.com/emory-libraries/blacklight-catalog/pull/373

![Screen Shot 2021-03-31 at 2.34.46 PM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/6a019a8b-b595-44e1-a07c-b43713011a15)

**Comment by eporter23** [comment]
Looks good, thanks!
