### ISSUE TITLE
Create DCE test accounts in Alma 

### ISSUE THREAD

**Issue by tmiles2** [emory-libraries/blacklight-catalog#37]
Accounts needed
- [x] NetID: Rlynn3 – Rachel Lynn 
- [x] NetID: Mbusse2 – Mark Bussey 
- [x] NetID: MLOONE2 – McClain Looney 
- [x] NetID: NORSTAD – Norman Orstad

**Comment by libah** [comment]
Everyone should be able to login now with the specified permissions. 
Mark (faculty access)
Norm (staff access)
Rachel (student)
McClain (librarian)

**Comment by tmiles2** [comment]
@libah how can DCE confirm their specific permissions are correct when they log in? what should they look for?

**Comment by libah** [comment]
I will create screenshots for each user type.

**Comment by libah** [comment]
After signing in you will see in the top right-hand corner, 'My Account', which lists the books you have checked out. 
<img width="1247" alt="my-account" src="https://user-images.githubusercontent.com/222633/98701708-95ee3a80-2347-11eb-98f2-89b4d7afc53e.png">

Your recent search queries:
<img width="1145" alt="most-recent-search-queries" src="https://user-images.githubusercontent.com/222633/98701840-b6b69000-2347-11eb-9f7d-ee96dd9ccab1.png">

Items you have saved to your 'eshelf':
<img width="1120" alt="eshelf" src="https://user-images.githubusercontent.com/222633/98701914-cb932380-2347-11eb-8bc2-68e74932ec68.png">

Tabs seen when looking at books:
<img width="1110" alt="tabs-for-books" src="https://user-images.githubusercontent.com/222633/98702053-f2e9f080-2347-11eb-99fb-9506319430db.png">

Tabs for online material:
<img width="1052" alt="JAMA (Online) - Emory University Libraries 2020-11-10 11-15-11" src="https://user-images.githubusercontent.com/222633/98702097-009f7600-2348-11eb-9428-73f1a33a75f9.png">

Online material in this case the journal JAMA:
<img width="1094" alt="2JAMA (Online) - Emory University Libraries 2020-11-10 11-15-37" src="https://user-images.githubusercontent.com/222633/98702131-0ac17480-2348-11eb-9405-5336174f41d2.png">

**Comment by libah** [comment]
Sent screenshots to Rachel specific to what a student user would see.
