### ISSUE TITLE
Add support for all dates in a ranges in the date range slider

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/blacklight-catalog#371]
Current behavior: date ranges not fully supported (extraction seems to store only include a single date, usually the start date).
See prior notes in #203.

Examples: 
Date range with a start and end date
https://blackcat-test.library.emory.edu/catalog/990022253520302486 (008: 19302010; "pub_date_isi":1930)

Date range with an open-ended date (e.g. a journal that is still being published)
https://blackcat-test.library.emory.edu/catalog/990027542670302486 (008: 19529999; “pub_date_isi":1952)

In the Lux application, we currently index all the years in a range.

**Comment by mark-dce** [comment]
Here's some sample code for indexing year ranges 
https://github.com/curationexperts/rangey/commit/ed63fbdf144b86b24238d319687677499f461699

And some example tests 
https://github.com/UCLALibrary/californica/blob/main/spec/indexers/year_parser_spec.rb

**Comment by devanshu-m** [comment]
As per discussion with Emily on Friday, we are only handling specific cases in this ticket. One in which there is a date range given and if the end year is 9999. We will look at exact dates in 006[11-14] and other corner cases in a later ticket.
