### ISSUE TITLE
Re-locate MARC inventory data set from Blacklight production to DLP-arch environment

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/blacklight-catalog#372]
We need to do before we synchronize or clone data to the new production environment

**Comment by rotated8** [comment]
We'll use the `blacklight_collection` on arch for this. The catalog uses `blackcat_collection`, and this way we don't clobber a DLP collection.

**Comment by rotated8** [comment]
Edit to the above: new collection to use `marc_collection`

**Comment by rotated8** [comment]
Script repo: https://github.com/rotated8/alma-reporter

**Comment by eporter23** [comment]
I see 4,917,332 in the arch marc_collection now and have run a few queries. Looks good. Thanks!
