### ISSUE TITLE
Adjust column width for View Single Item Display Metadata fields for better readability

### ISSUE THREAD

**Issue by norm0** [emory-libraries/blacklight-catalog#377]
Currently the metadata fields labels are wrapping to two lines and potential user confusion at larger view sizes(desktop). 

Change the column width on the metadata fields blocks from col-3/col-9 to col-4/col-8 to display the labels without line breaks.

**Comment by eporter23** [comment]
@norm0 Looks great, labels no longer wrapping:

![Screen Shot 2021-04-02 at 12.58.54 PM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/683c894c-111a-4d04-b334-a9985bef4eea)
