### ISSUE TITLE
Investigate/resolve outlier dates in Publication/Creation display field

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/blacklight-catalog#383]
After significant work on mappings and display fields, some outlier patterns are showing up related to the display date in the Publication/Creation display field. Can we investigate these to see if they are extraction issues or catalog data issues?

1. In some cases, the publication date field contains two subfield c instances, or for other reasons, there are two dates showing up in the display. If there are 2 $c instances, can we include only the first one?

Examples:
https://blackcat-test.library.emory.edu/catalog/9937007411902486
https://blackcat-arch.library.emory.edu/catalog/9937007415102486

2. In this instance, the publication date doesn't seem to be extracted correctly for display:
https://blackcat-arch.library.emory.edu/catalog/9937172247202486
The "publication" date in the facet is 2019, but the display date is different: 1945. Is the order of preferred date selection different for the display field than for the facet? 

3. In this instance, the date includes YYYYMMDD, but isn't formatted in an obvious way that a user would understand:
https://blackcat-arch.library.emory.edu/catalog/9937006094502486
![Screen Shot 2021-04-02 at 2.28.22 PM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/caea2383-a6bb-499d-bd67-69b69ac1b530)

**Comment by devanshu-m** [comment]
Initial investigation notes:
* We are currently not using `008` field for publication/creation display field in question here. Therefore, the facet date might be different to what shows in the main display field.
* For the second scenario in this ticket `008[7-14]` has the year 2019 which is used for facet, however, `245g` is where we get the year for the display field.

Current mappings:
* For facet field (pub_date_isim): `008`
* For publication/creation display field (publication_main_display_ssim): `264abc:260abc:245fg:502abcdg`

**Comment by eporter23** [comment]
@devanshu-m looks good so far. A couple of the examples haven't reindexed yet but I will keep checking.

**Comment by lovinscari** [comment]
@eporter23  - Please close this when you have tested after the reindex.

**Comment by eporter23** [comment]
Thanks @devanshu-m ! I am good with closing this and will check again after we reindex the prod data set on test.
