### ISSUE TITLE
Review/reindex works whose Library codes aren't converted in the Library facet 

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/blacklight-catalog#384]
After the reindex on 4/2, there are still several resources whose Alma Library codes have not been converted to the Library display name label:

OXFD
https://blackcat-test.library.emory.edu/catalog/990017296400302486
"timestamp":"2021-03-24T17:50:58.479Z",

THEO
https://blackcat-test.library.emory.edu/catalog/9936861002502486
"timestamp":"2021-03-24T15:08:05.866Z",

**Comment by eporter23** [comment]
I'm removing the reindexing tag because this doesn't require a full data set reindex, it's just a quick fix on two records.

**Comment by devanshu-m** [comment]
Both records have been reindexed in test. @eporter23 

I am unsure why these did not get reindexed during our full ingest. It could be because of the stoppages.

**Comment by eporter23** [comment]
@devanshu-m thanks! the Library facet looks good now in test.
