### ISSUE TITLE
Refinements to relator term display in additional authors/creators

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/blacklight-catalog#385]
In some cases, when a value in Additional Authors/Creators (author_addtl_tesim) ends with a relator term ($e or $j) such as ", editor" or ", composer" there is a trailing comma or other punctuation at the end. In investigating some of these examples, I noticed that some of these entries can contain more than one relator term. Currently we are only bringing in one, but it would be useful to have all/any that are populated.

See screenshots and comments in ticket #314.

For display refinement:

- [ ] Remove trailing punctuation after relator terms in display
- [ ] Build support for bringing in multiple relator terms ($e or $j), if applicable

See the following record and https://blackcat-arch.library.emory.edu/catalog/9936829437402486 screenshots for an example:

![Screen Shot 2021-04-02 at 4.56.20 PM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/840f551a-72ef-4320-9a27-31bd9f776096)

![Screen Shot 2021-04-02 at 4.54.52 PM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/15039af4-cc49-492f-8241-280d0538dd31)

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/blacklight-catalog/pull/389

![Screen Shot 2021-04-05 at 3.07.08 PM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/6dd25c14-7d41-4b19-8c5c-832c120557fa)
