### ISSUE TITLE
Refine Show More Authors and Show Titles feature on single item view display

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#388]
As the product owner, I would like for the "Show More Authors" feature on the Single Item View Display to function like the "Show More" and "Show Less" feature for consistency among features and consistency with hyperlinks within the Single Item View Display.
![ShowMoreAuthors_Refinement.png](https://images.zenhubusercontent.com/5c4a1fe1e9b5fb46bcedb9fc/e98abe95-9732-4ae9-86dc-3a9b65ae89f7)

Specific User Acceptance Criteria included below. 

User Acceptance Criteria:

- [ ] Consult with Norm on UI Design ideas

- [ ] When the "Show More Authors" feature appears based on number of authors listed, the text should appear in the same blue as all other hyperlinks indicating the link is active

- [ ] When the "Show More Authors" link is selected, the link should either switch to "Show Less Authors" and appear as an active hyperlink at the bottom of the list of authors OR disappear completely. I prefer the former if not too difficult to implement.

**Comment by eporter23** [comment]
@lovinscari would it be helpful to wireframe this first or consider what the final styling might look like? It would probably be good to consider the design of both the show more authors and show more titles toggles at the same time.

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/blacklight-catalog/pull/426

https://images.zenhubusercontent.com/295449627/ec4d2808-13de-4b50-bcc3-ca52c45f35ca/show_more.mov

**Comment by eporter23** [comment]
@bwatson78 @norm0 looks good to me!

**Comment by lovinscari** [comment]
@bwatson78 - This looks great!
