### ISSUE TITLE
How do we get DCE VPN Proxy access to the work-to-date (OAI)

### ISSUE THREAD

**Issue by tmiles2** [emory-libraries/blacklight-catalog#39]
Confirm access:
- [x] Mark 
- [x] Rachel

Provide access:
- [x]  McClain - Net ID: MLOONE2
- [x]  Norm - Net ID: NORSTAD

**Comment by rotated8** [comment]
All four are in AWS@Emory as admins

**Comment by lovinscari** [comment]
Emailed @norm0 and @mlooney instructions with how to access VPN. I will follow up with them on Slack since I have not received a response to email.
