### ISSUE TITLE
CloudWatch Alerts: Solr Disk Utilization > 80%

### ISSUE THREAD

**Issue by mark-dce** [emory-libraries/blacklight-catalog#396]
**ISSUE**
As part of an earlier spike, we have identified available disk space as a key metric to monitor and alert on.  For further details see #348 SPIKE: Determine what Cloudwatch Metrics are available to set benchmarks on SOLR Performance.

**ACCEPTANCE**
- [x] We have CloudWatch metrics configured for all active Solr & Solr Cloud instances
- [x] We are tracking disk utilization
- [x] We trigger an alert to the *TBD* slack channel when free disk space drops below 20%

**Comment by oraposa** [comment]
[test] solr-cor-test-1 disk usage percent - rootfs
