### ISSUE TITLE
CloudWatch Alerts: Webserver disk use > 50%

### ISSUE THREAD

**Issue by mark-dce** [emory-libraries/blacklight-catalog#397]
**ISSUE**
As part of an earlier spike, we have identified available disk space as a key metric to monitor and alert on.  For further details see #348 SPIKE: Determine what Cloudwatch Metrics are available to set benchmarks on SOLR Performance.

**ACCEPTANCE**
- [x] We have CloudWatch metrics configured for all active application server instances
    - [x] arch
    - [x] prod
    - [x] test
- [x] We are tracking disk utilization
- [x] We trigger an alert to the *TBD* slack channel when free disk space drops below 50%

**Comment by oraposa** [comment]
[prod] blackcat-web Disk Usage
 [test] blackcat-web Disk Usage

Not seeing an arch instance available in aws console for the metric `used_percent`

**Comment by oraposa** [comment]
Also tested alarms - alert sent to DLP Alerts
