### ISSUE TITLE
CloudWatch Alerts: JVM Heap > 95%

### ISSUE THREAD

**Issue by mark-dce** [emory-libraries/blacklight-catalog#398]
**ISSUE**
As part of an earlier spike, we have identified available disk space as a key metric to monitor and alert on.  For further details see #348 SPIKE: Determine what Cloudwatch Metrics are available to set benchmarks on SOLR Performance.

**ACCEPTANCE**
- [x] We have CloudWatch metrics configured for all active Solr & Solr Cloud instances
- [x] We are tracking JVM Heap Usage
- [x] We trigger an alert to the *TBD* slack channel when JVM Heap usage exceeds 95% continuously over a span of 5 minutes (based on a 1 minute polling interval)

**Comment by mlooney** [comment]
We currently log heap statistics, but in a way that CloudWatch doesn't like. wrestling with the query parser currently.

**Comment by mlooney** [comment]
current max is 7gb, set threshold to 6gb

**Comment by mlooney** [comment]
![image.png](https://images.zenhubusercontent.com/5e5d3aa83ca793986edab47d/bfc24174-b3df-40e1-9a54-ef9a3d34fcc0)
