### ISSUE TITLE
CloudWatch Alerts: Solr main memory >= 100%

### ISSUE THREAD

**Issue by mark-dce** [emory-libraries/blacklight-catalog#399]
**ISSUE**
As part of an earlier spike, we have identified available disk space as a key metric to monitor and alert on.  For further details see #348 SPIKE: Determine what Cloudwatch Metrics are available to set benchmarks on SOLR Performance.

**ACCEPTANCE**
- [ ] We have CloudWatch metrics configured for all active Solr & Solr Cloud instances
- [x] We are tracking memory utilization
- [x] We trigger an alert to the *TBD* slack channel when free memory drops below 0%

**Comment by oraposa** [comment]
[arch] solr-cor-arch-1 memory used percent
[arch] solr-cor-arch-2 memory used percent
[arch] solr-cor-arch-3 memory used percent

**Comment by oraposa** [comment]
[test] solr-cor-test-1 memory used percent
[test] solr-cor-test-2 memory used percent
[test] solr-cor-test-3 memory used percent

[prod] solr-cor-1 memory used percentage
[prod] solr-cor-2 memory used percentage
[prod] solr-cor-3 memory used percetage
