### ISSUE TITLE
CloudWatch Alerts: Solr CPU utilization > 90%

### ISSUE THREAD

**Issue by mark-dce** [emory-libraries/blacklight-catalog#401]
**ISSUE**
As part of an earlier spike, we have identified available disk space as a key metric to monitor and alert on.  For further details see #348 SPIKE: Determine what Cloudwatch Metrics are available to set benchmarks on SOLR Performance.

**ACCEPTANCE**
- [x] We have CloudWatch metrics configured for all active Solr & Solr Cloud instances
- [x] We are tracking CPU utilization
- [x] We trigger an alert to the *TBD* slack channel when CPU utilization exceeds 90% consistently for 5 minutes (based on a 1 minute polling interval)

**Comment by oraposa** [comment]
### Alerts 
solr-cor-test-1 cpu
solr-cor-1.library cpu

**Comment by libah** [comment]
solr-cor-test-2 cpu

**Comment by libah** [comment]
solr-cor-test-3 cpu

**Comment by oraposa** [comment]
[arch] solr-cor-arch1 CPUUtilization
[arch] solr-cor-arch-2 CPU Utilization [delete if promoted]
[arch] solr-cor-arch-2 CPU Utilization

**Comment by libah** [comment]
[test] Solr-Cor-test-1-cpu CPU Utilization
[test] Solr-Cor-test-2-cpu CPU Utilization
[test] Solr-Cor-test-3-cpu CPU Utilization
