### ISSUE TITLE
CloudWatch Alerts: Webserver CPU utilization > 90%

### ISSUE THREAD

**Issue by mark-dce** [emory-libraries/blacklight-catalog#402]
**ISSUE**
As part of an earlier spike, we have identified available disk space as a key metric to monitor and alert on.  For further details see #348 SPIKE: Determine what Cloudwatch Metrics are available to set benchmarks on SOLR Performance.

**ACCEPTANCE**
- [x] We have CloudWatch metrics configured for all active web server instances
    - [x] Arch
    - [x] Test
    - [x] Staging
- [x] We are tracking CPU utilization
- [x] We trigger an alert to the *TBD* slack channel when CPU utilization exceeds 90% consistently for 5 minutes (based on a 1 minute polling interval)

**Comment by libah** [comment]
I added the following cloudwatch alarms. 

[test] blackcat-test-web CPU Utilization
[arch] blackcat-arch-web CPU Utilization
[prod] blackcat-prod-web CPU Utilization
