### ISSUE TITLE
SPIKE: Investigate LITS access to AWS Anomaly Detection

### ISSUE THREAD

**Issue by mark-dce** [emory-libraries/blacklight-catalog#404]
**STORY**
AWS provides an [Anomaly Detection](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch_Anomaly_Detection.html) service as part of CloudWatch; however, we are not certain whether Campus IT has made this service available to LITS.  We would like to attempt to configure this service on one of our existing metrics to determine the feasibility of using the service at all, and the level of effort to configure it if we do have access.

**ACCEPTANCE**
Invest a time-boxed effort to 
- [x] Configure anomaly detection on system memory usage for the test web server environment (blackcat-test)
- [x] Document whether we can or cannot configure the service
    - [ ] If yes, identify any additional requirements or questions necessary to configure the service for additional metrics and servers

**Comment by libah** [comment]
It looks as though you can pretty much set up anomaly detection for any built-in amazon metric and any custom metric. I was able to set up anomaly detection for memory usage for blackcat-test-web. Level of effort is no more than setting up other alarms.
