### ISSUE TITLE
SPIKE: monitor web server response time

### ISSUE THREAD

**Issue by mark-dce** [emory-libraries/blacklight-catalog#405]
**STORY**
We would like to know when average response time of the system starts to degrade, but we also know that individual user queries can trigger long searches.  Therefore, we'd like a method to measure and alert on system performance that ignores outlier data.  Possible options are to measure and alert on average response times (better for weeding out single outliers and describing typical system behavior) or when response times exceed an upper threshold for an extended period.  This spike is to research options and test potential configurations in order to present a final recommedation.

**ACCEPANCE**
- [x] Research mechanisms to monitor average response times for the catalog web server
   - [x]  Configure an alert if average response times exceed 1000ms if possible
- [x] Research mechanisms to monitory running response times for the catalog web server
   - [x]  Configure an alert if the per-query response time exceeds 500ms for over 2 minutes sustained (using a 5 second polling interval - i.e. for 24 straight samples)
- [x] Write up a ticket to implement the preferred solution for the web server in all environments

**Comment by mark-dce** [comment]
Note - I quickly looked a using an external service like Pingdom for this, but we won't be able to use external monitoring tools for any system that sits behind the Emory VPN.

AWS CloudWatch now offers a "Synthetic Monitor" capability that works similarly to Pingdom and other eternal monitoring services.  It would be great to be able to handle this in the same way we manage all our other monitoring and alerting, so we should explore configuring CloudWatch to do this before exploring other options.

For additional details see  
https://aws.amazon.com/blogs/aws/new-use-cloudwatch-synthetics-to-monitor-sites-api-endpoints-web-workflows-and-more/

**Comment by mlooney** [comment]
ALB keeps a history of target response times, should be able to alert off of it.

**Comment by mlooney** [comment]
![image.png](https://images.zenhubusercontent.com/5e5d3aa83ca793986edab47d/7a78d062-6346-4bd5-9ec1-6b0326e4ea83)

**Comment by mlooney** [comment]
test, prod & arch all have alerts on response time
