### ISSUE TITLE
Reconfigure DLP Alerts Slack Channel

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#409]
A requirement in issue [#348](https://app.zenhub.com/workspaces/blacklight-catalog-5f5f84a8a6d29939a0bc5d78/issues/emory-libraries/blacklight-catalog/348) was to create a new ticket for backlog to rename DLP Alerts slack channel that includes the review of any scripts or other documentation that will need updating if the slack channel is renamed. 

Acceptance Criteria:

- [x] Review alerts currently sent to DLP Alerts Slack Channel

- [x] Trace alerts to their source to determine how scripts are configured and the need for revisions to the scripts if the channel is renamed.

- [x] Rename the Slack Channel to something that encompasses the new purpose of the channel that will collect all Cloudwatch Alerts for AWS environments used for DLP and Blacklight.

- [x] Update scripts with new Slack channel name

- [x] Add everyone from the Blacklight Scrum Team to the Slack channel for alerts

**Comment by jcrompton42** [comment]
to rename a channel I need to be an admin. @libdgg or @lovinscari  would you like to give me admin permissions for slack workspace or should I get with you to do the rename?

**Comment by libdgg** [comment]
the dlp-alerts slack channel was renamed aws-alerts. here are the members of the channel
