### ISSUE TITLE
TASK: Working meeting to complete decision document for Browse Search

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#410]
As the product owner, I need to review the recommended decision regarding Browse Search with Executive Sponsor and Sponsor no later than April 15, 2021 in order to present to Libraries OMT and possibly Libraries Cabinet the first week in May. As such, I am proposing a working meeting with product owner, technical lead, and project co-sponsor to complete this document.

Acceptance Criteria:

- [x] Meeting scheduled with those identified above.

- [ ] Draft document created

**Comment by rotated8** [comment]
Ongoing work: https://emory-my.sharepoint.com/:w:/r/personal/rmetz_emory_edu/_layouts/15/Doc.aspx?sourcedoc=%7BB9804234-6895-4CB8-95FC-28CE2FC535CD%7D&file=Decision-%20APIs%20and%20Browse%20Search.docx&action=default&mobileredirect=true
