### ISSUE TITLE
SPIKE: Conduct brainstorming session regarding SOLR Cloud Problems

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#412]
As a follow up to the meeting on April 7, 2021, a brainstorming session was suggested to review the configuration of SOLR Cloud currently configured for Blacklight Catalog and DLP.

Acceptance Criteria  with targeted completion of April 21, 2021:
- [x] Schedule a meeting with technical lead, members of infrastructure team, technical consultant and director of technology operations to review issues presented with performance and stability of SOLR Cloud and previous performance issues, including the scenario presented on April 6, 2021.

- [ ] Determine adjustments needed to SOLR Cloud including number of cores etc

- [ ] Propose a plan for changes and present to Blacklight and DLP product owners for review. Plan should include a rollout process for change including any downtime of current environments or applications, expected cost of the change (new cost compared to previous cost) and desired timeframe to implement the change. 

- [ ] Once product owners have reviewed, the project sponsors will review proposal and seek approval from Executive Sponsor 

- [ ] Once approved, technical lead and product owner will create new issues for backlog to complete the work. 

POSSIBLE REFERENCE INFORMATION:
https://tech.olx.com/improving-solr-performance-f4202d28b72d

**Comment by lovinscari** [comment]
Emily, Alex and Clare are optional to the meeting invite.

**Comment by libdgg** [comment]
Meeting scheduled for Monday 4/19 and invite sent to the those on this ticket.

**Comment by libdgg** [comment]
The team met Monday 4/19. [Meeting notes are in OneDrive.](https://emory-my.sharepoint.com/:w:/r/personal/rmetz_emory_edu/Documents/LTDS%20Shared%20Documentation/Projects/Project%20Documentation/Blacklight%20Discovery%20Layer%20Phase%201/Scrum%20Team/Meetings%20and%20Agendas/Ad%20Hoc%20Meetings/2021-04-19-SPIKE-Meeting-SOLR-Cloud-Issue-412.docx?d=w98db3355cc8d465e9a7c4866078a47de&csf=1&web=1&e=MiQfHl)

ACTIONS

1. Create 3 tickets for the upcoming sprint for EC2 size, EBS/EFS, and adding a load balancer
2. DG will check with RM today about budget constraints that would inform our decisions
3. DG will create a ticket for cost model

**Comment by mark-dce** [comment]
I've written up an Epic to cover Solr enhancements:
* #459 Improve Solr performance across environments

It currently contains three stories for
* Adding a load balancer in front of the nodes in each Solr Cloud
* Making CPU and RAM consistent across Solr Cloud nodes in all environments
* Making Solr Cloud storage consistently sized in all environments.
