### ISSUE TITLE
Spike: investigate how the built-in Cite and Export to Endnote's tool’s metadata fields are configured

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#413]
As a library user, I would like for information to be captured from a single item record display I plan to use for my research and formatted into various citation formats so I can copy the citation information and paste it into my research paper.  

NOTE: Our current Black-cat instances include a Cite option. It currently seems to detect titles and in some cases, authors, but it is unclear where these fields have been defined. Similar behavior occurs when exporting an EndNote files. 
![BlackcatCite.png](https://images.zenhubusercontent.com/5c4a1fe1e9b5fb46bcedb9fc/c5095884-11bf-40a3-8a8f-00a94bac3376)

Reference Information:

- https://github.com/sandbergja/blacklight-citeproc : is this utilized by Blacklight?

- [Prior work and gems used in Lux](https://app.zenhub.com/workspaces/digital-library-project-5bf484ae4b5806bc2bf6875b/issues/emory-libraries/dlp-lux/490)

- [Citation Mapping Worksheet](https://docs.google.com/spreadsheets/d/1j8A8Sw3P3A8FtXSRJ4BWRpL0-ZCiZ5nQli_BjU4j7AE/edit#gid=0)

Spike outcome:

- [ ] Gain understanding on how to customize the Blacklight Cite or export tools to use our MARC data or locally defined SOLR fields as needed to support common citation fields.

**Comment by devanshu-m** [comment]
Most code references we are looking for around citations can be found here: https://github.com/projectblacklight/blacklight-marc/blob/master/app/models/concerns/blacklight/solr/document/marc_export.rb

This file has method definitions for our three available citations and also lists which marc datafields it looks at when constructing a citation. Below, going in detail for each available citation and references to code:

* `apa_citation`: 
  * For the apa citation we take the record and first get the author list here: https://github.com/projectblacklight/blacklight-marc/blob/8228966ab0d880a4d06c22b86c1766a7ab6d6fea/app/models/concerns/blacklight/solr/document/marc_export.rb#L376
  * In the `get_author_list` method we look for `primary` and `secondary` authors. The code here suggests that `primary` authors are collection from datafield `100` subfield `$a` (refer: https://github.com/projectblacklight/blacklight-marc/blob/8228966ab0d880a4d06c22b86c1766a7ab6d6fea/app/models/concerns/blacklight/solr/document/marc_export.rb#L515), whereas, secondary authors are collection from datafield `700` again subfield `$a` (refer: https://github.com/projectblacklight/blacklight-marc/blob/8228966ab0d880a4d06c22b86c1766a7ab6d6fea/app/models/concerns/blacklight/solr/document/marc_export.rb#L521)
  * Once, `authors` are collected in an array, it is passed into a block that adds and formats the citation as required in the APA style with its citation meta tags, only for authors.
  * After this, publication date is extracted from datafield `260` subfield `$c` (refer: https://github.com/projectblacklight/blacklight-marc/blob/8228966ab0d880a4d06c22b86c1766a7ab6d6fea/app/models/concerns/blacklight/solr/document/marc_export.rb#L421)
  * After pub date, we have title info, for which the original method is using datafield `245` and concatenating subfields `$a` and `$b` (refer: https://github.com/projectblacklight/blacklight-marc/blob/8228966ab0d880a4d06c22b86c1766a7ab6d6fea/app/models/concerns/blacklight/solr/document/marc_export.rb#L475)
  * Then we have edition for the record, which is setup using datafield `250` subfield `$a` and other edition decisions are made here: https://github.com/projectblacklight/blacklight-marc/blob/8228966ab0d880a4d06c22b86c1766a7ab6d6fea/app/models/concerns/blacklight/solr/document/marc_export.rb#L502
  * Finally, we have setting up of publication_info for which datafield `260` subfields `$a` and `$b` are used which are separated with `:` punctuation.
   * All of the above strings are concatenated to form the apa citation.

* `mla_citation`: 
  * Here, we first get the primary and secondary author lists similar to apa citation using the same `get_authors_list` method.
  * Then we get the title info similar to apa, using the same `setup_title_info` method referenced above.
  * After this edition is setup again in a similar way as apa, using the same `setup_edition` method referenced above.
  * Finally, publication info and publication dates are concatenated to the string using methods referenced in the apa citation section above.
  * Refer: https://github.com/projectblacklight/blacklight-marc/blob/8228966ab0d880a4d06c22b86c1766a7ab6d6fea/app/models/concerns/blacklight/solr/document/marc_export.rb#L321

* `chicago_citation`:
  *

**Comment by eporter23** [comment]
@devanshu-m further clarified for me that the method described above is reading from the MARC xml data in our OAI feed, so if a given record contains the tag(s) as configured, they should appear in the Cite tool or exports. We are going to do some further testing on different specific examples to see where more tag definitions may be needed.

**Comment by eporter23** [comment]
@devanshu-m fyi: [my notes after reviewing some more examples](https://docs.google.com/spreadsheets/d/1j8A8Sw3P3A8FtXSRJ4BWRpL0-ZCiZ5nQli_BjU4j7AE/edit#gid=1786779385) of different types of records
