### ISSUE TITLE
Generate a basic copy and pasteable citation in MLA 8th Edition format

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/blacklight-catalog#415]
**Story:**
As an end user, I want to easily capture critical citation information about a resource, so that I can use that to help document my references in an MLA-formatted research artifact 

**Notes:**
After consulting with the Libraries instruction team, MLA 8th edition was identified as a priority style for the new catalog to support. As a first step, this ticket outlines potential metadata fields needed to support a basic citation for a book.

**Mockups/References**

- Standard Blacklight Cite option in Tools menu - modal window
- Primo’s auto-generated MLA 8 Citation
- [MLA Core reference](https://owl.purdue.edu/owl/research_and_citation/mla_style/mla_formatting_and_style_guide/mla_formatting_and_style_guide.html)
- [ Mapping worksheet for citations](https://docs.google.com/spreadsheets/d/1j8A8Sw3P3A8FtXSRJ4BWRpL0-ZCiZ5nQli_BjU4j7AE/edit#gid=0)
- [Metadata and Indexing Worksheet](https://docs.google.com/spreadsheets/d/1jSqgNd6HnVJdJMrrShAofkmK8uGgHGdlKODmZOL5NfY/edit#gid=1979033236)
- Prior work in Lux 

**Sample Citation Output** 
ID: 990027503070302486
Yeats, W. B. _The Autobiography of William Butler Yeats : Consisting of Reveries over Childhood and Youth, The Trembling of the Veil, and Dramatis Personae_. The Macmillan Company, 1938.

**Metadata and Indexing**

- See the [Citations mapping worksheet](https://docs.google.com/spreadsheets/d/1j8A8Sw3P3A8FtXSRJ4BWRpL0-ZCiZ5nQli_BjU4j7AE/edit#gid=0) first tab and MLA tab for more details. Assumption: we are specifying MARC mappings instead of SOLR mappings based on the related [Spike ticket 413's outcomes.](https://app.zenhub.com/workspaces/blacklight-catalog-5f5f84a8a6d29939a0bc5d78/issues/emory-libraries/blacklight-catalog/413)

**Comment by lovinscari** [comment]
@alexBLR and @eporter23 - It does not look like the publication information is included in the MLA Citation. I see the fields defined on the metadata worksheet so I am not sure if I am missing something? 

When looking at https://blackcat-test.library.emory.edu/catalog/990024996580302486 and creating an MLA Citation using citationmachine.net, The following citation appears -

Whited, Lana A. The Ivory Tower and Harry Potter: Perspectives on a Literary Phenomenon. University of Missouri Press, 2004. 

It looks like we are only picking up the primary author and title. I know there is a question about the author when multiple authors but I am not seeing any reason the publisher information should not be picked up. Let me know if I am missing something.

**Comment by eporter23** [comment]
@alexBLR thanks for the work on this, @lovinscari and I are going to close it out. There are some revision items noted in #500 for later.

**Comment by eporter23** [comment]
@alexBLR thanks for the work on this, @lovinscari and I are going to close it out. There are some revision items noted in #500 for later.
