### ISSUE TITLE
STORY: Implement More Options feature on Single Item View Display

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#416]
As a library user, I would like to access additional information about the resource type I am viewing in the event the single item view display does not contain all information I am seeking, most of which can be found on the [Materials Page](https://libraries.emory.edu/materials/index.html) on the Emory Libraries Home Page. 

Acceptance Criteria:

- [ ] Implement a box below the Tools Menu titled More Options per the [wireframe](https://www.figma.com/file/ocSo3KytI6GgwjalSVAmE1/Blacklight-Wireframes?node-id=1217%3A14525)

- [ ] The contents within the box will be dynamically generated based on the resource type of the record with each linking to the corresponding materials page indicated below with the words prefaced by each link "Find more information about XXX" with XXX replaced by the resource type as indicated on the [mapping document](https://docs.google.com/document/d/1ag7FiwGIbkAJagI145cH6vexNucgx1RT98QaHpBoluc/edit?usp=sharing)

**Comment by norm0** [comment]
More Options Examples:
![✅ Item - Component - More Options - C.png](https://images.zenhubusercontent.com/5f8492d49b473a0cef37940f/ce532ed4-5006-4d1d-8100-468be5a993f3)

Placement in the single item view:
![Item Show.png](https://images.zenhubusercontent.com/5f8492d49b473a0cef37940f/a74ba447-965e-491d-baea-757749a20cdd)

**Comment by bwatson78** [comment]
@lovinscari and @norm0 I heard there was some more discussion about verbiage for this section. I'm to that point now--should I follow directly from the requirements list or from one of the two variants in the wireframes?

**Comment by eporter23** [comment]
@bwatson78 mapping looks great. @lovinscari I wonder if we may want to adjust the link text? For example, "Find more information about Books" seems a little awkward to me. Perhaps something like "More ways to find Books"? I'll touch base with you and @norm0 about it later though.

**Comment by lovinscari** [comment]
@eporter23 - I agree that we might want to discuss the wording but for now I think it's fine. I am going to accept as is and we can discuss more during our meetings next week.
