### ISSUE TITLE
Determine metadata requirements for iFrame related table 

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#418]
As the product owner, I would like to know the metadata needed to dynamically generate information in the [planned table](https://www.figma.com/file/ocSo3KytI6GgwjalSVAmE1/Blacklight-Wireframes?node-id=1175%3A14433) that will be presented to all users as part of the "How to get it" or requesting process.

Acceptance Criteria:

- [ ] Determine metadata fields associated with the "Where to Find It" physical holdings layouts in order to generate information pertaining to Library and Call Numbers of physical items. If existing SOLR Fields, add information to the associated wireframe. If a new SOLR Field, document requirements that will be included in future application development ticket for this feature.

- [ ] Determine metadata fields with the "Where to Find It" for the Online layout that would generate this table and link users to the iFrame modal to access the electronic resources and/or the Full Text Access. f existing SOLR Fields, add information to the associated wireframe. If a new SOLR Field, document requirements that will be included in future application development ticket for this feature.

**Comment by eporter23** [comment]
@lovinscari I have [proposed a mapping in this document](https://docs.google.com/spreadsheets/d/1JOcExlIp1yO4i5oBJwFz6CrkTN_QTV-2lPjMCdMuySs/edit#gid=187904302), which is also added to two tickets in New Issues to build out the respective tables.

**Comment by bwatson78** [comment]
@eporter23 This works for me.

**Comment by lovinscari** [comment]
@eporter23 - this works for me as well. Thanks for all of your work on this.
