### ISSUE TITLE
Configure fields and facets for Advanced Search

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/blacklight-catalog#419]
**Story**
As an end user, I want to perform complex searches across multiple fields at once, so that I can more precisely locate material using detailed information I already have 

**Mockups/References**

- [Wireframe for Advanced Search](https://www.figma.com/file/ocSo3KytI6GgwjalSVAmE1/Blacklight-Wireframes?node-id=638%3A57)
- [Requirements document for Advanced Search](https://docs.google.com/document/d/1C0W4Za9x5nVvfRaLp2-H0H7VjDHtdq-sYNisQ1ue8rg/edit#)
- [Metadata and Indexing Worksheet - Advanced Search filtered view](https://docs.google.com/spreadsheets/d/1jSqgNd6HnVJdJMrrShAofkmK8uGgHGdlKODmZOL5NfY/edit#gid=1979033236&fvid=69102880)
- Prior work in Lux 

**SOLR and Indexing**

- See the Metadata and Indexing Worksheet and Requirements document above for matching SOLR fields to the advanced search form
- Some existing fields may need revisions, noted in the Metadata Worksheet
- To confirm: do we need to convert/recreate some existing fields as _tesim for searching?
- To confirm: for Local Call Number (new field identified), should we break this into different types of call numbers (if needed later for browsing)?

**Comment by lovinscari** [comment]
@devanshu-m and @eporter23 - I am trying to test Local Call Number in Advanced Search on Blackcat-Arch but the examples I have "1522 BBL" from Pitts Library is not showing up. Can one of you provide details of what data has been indexed on Arch? I'll adjust my testing based on this information. Thanks.

**Comment by lovinscari** [comment]
@devanshu-m and @eporter23 I am still unable to find the local call numbre of 1522 BBL. I'm wondering if blackcat-test can been reindexed?

**Comment by devanshu-m** [comment]
@lovinscari I think blackcat-arch was reindexed after the local call number change, however, I don't think blackcat-test has been reindexed. Are you testing this on arch or test?

**Comment by eporter23** [comment]
I have done quite a few random searches of call numbers within the arch environment and they're all working so far. I think this is good to close but we could also keep it open if we want to wait for the full production set to reindex.

**Comment by eporter23** [comment]
@devanshu-m this looks great overall. I am writing up a few followup/revision tickets for search field functionality (Publisher and Author/Creator) and also for some of the filters (Language, Collection). I also noted that some of the sort options aren't quite working but I think they may not be configured in general yet. Everything else seems to be in good shape.
