### ISSUE TITLE
Manually add the Shibboleth SP to Arch

### ISSUE THREAD

**Issue by rotated8** [emory-libraries/blacklight-catalog#42]
- [x] Add the Shibboleth SP to Arch

This is done when the application can receive a response from the IDP.

**Comment by rotated8** [comment]
@mprefer @SolomonHD The check off for this ticket is bad. Can you come up with 3-5 check offs for this work?

**Comment by mprefer** [comment]
Added the shibboleth yum repo info to server:

[shibboleth]
name=Shibboleth (CentOS_7)
# Please report any problems to https://issues.shibboleth.net
type=rpm-md
mirrorlist=https://shibboleth.net/cgi-bin/mirrorlist.cgi/CentOS_7
gpgcheck=1
gpgkey=https://shibboleth.net/downloads/service-provider/RPMS/repomd.xml.key
       https://shibboleth.net/downloads/service-provider/RPMS/cantor.repomd.xml.key
enabled=1

Installed shibboleth SP:
   yum install shibboleth

Started shibboleth:
   service shibd start

Just awaiting the XML from the Messaging team.

**Comment by mprefer** [comment]
Tested browsing to 'http://blackcat-arch.library.emory.edu'. Apache with the mod_shib_24.so module loaded redirected to http://login.emory.edu, presented the log in page, and accepted and authorized my credentials.

So, it seems that Shibboleth is working on blackcat-arch and is ready for prime time.
