### ISSUE TITLE
Determine metadata requirements for Search Results display

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#420]
As the product owner, I would like to know the metadata fields needed to provide to UI developer to include in the wireframe for the search results display. Based on stakeholder feedback, they would like to see

Title
Author
Publisher 
Publication Date
Resource Type

Availability Information including holding library and/or view online* This should be discussed in terms of how the table on the single item view display could possible be reused on the search results page. 

Work notes:

- See [requirements summary document](https://docs.google.com/document/d/10NM4F11wWXGMvIjDBocrVxZfQz4h6om3l2CWrNWkNYY/edit#)
- Availability segment will be further detailed in a wireframe and will use real-time availability information as well as SOLR fields if needed

**Comment by eporter23** [comment]
I sent out a review document to the Metadata Subgroup on 4/14 with a deadline to get feedback by 4/19.

**Comment by eporter23** [comment]
@lovinscari @norm0 please see the work notes in the description above.
