### ISSUE TITLE
Implement Tools Menu for Single Item View Display

### ISSUE THREAD

**Issue by norm0** [emory-libraries/blacklight-catalog#428]
Implement [wireframe](https://www.figma.com/file/ocSo3KytI6GgwjalSVAmE1/Blacklight-Wireframes?node-id=1217%3A19421) and ticket [#345](https://app.zenhub.com/workspaces/blacklight-catalog-5f5f84a8a6d29939a0bc5d78/issues/emory-libraries/blacklight-catalog/345)

The Tools Menu in its final form will include the following functions (listed in order as they should appear)

- Bookmark Item (with a check box the user will select to bookmark the item. Currently listed as "bookmark" but believe there should be a differentiation between bookmark the item and the Bookmarks in the header. )

- Cite (metadata requirements coming from Emily Porter reference ticket [#344](https://app.zenhub.com/workspaces/blacklight-catalog-5f5f84a8a6d29939a0bc5d78/issues/emory-libraries/blacklight-catalog/344))

- Print (currently does not exist but is a requirement defined by stakeholders)

- Direct Link (this will be a persistent identifier to the record that can be copied and shared This is based on similar functionality in emory Digital Collections - Reference DLP Zen Hub [#560] (https://app.zenhub.com/workspaces/digital-library-project-5bf484ae4b5806bc2bf6875b/issues/emory-libraries/dlp-lux/560)

- Help (this will eventually link to a static help page but will initially just include the label)

- Feedback (this will eventually link to a feedback form but will initially just include the label)

- Staff View (currently listed as Librarian View)
![Group 16.png](https://images.zenhubusercontent.com/5f8492d49b473a0cef37940f/58b5a4e4-52a4-422e-b492-1669bbc38ee8)

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/blacklight-catalog/pull/446
![Screen Shot 2021-04-16 at 11.25.17 AM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/faf137c9-d7eb-4dd3-a9f6-160328217115)
