### ISSUE TITLE
Implement functionality for Direct Link in Tools Menu

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#431]
Use findings from Issue [#430](https://app.zenhub.com/workspaces/blacklight-catalog-5f5f84a8a6d29939a0bc5d78/issues/emory-libraries/blacklight-catalog/430) to implement functionality for Direct Link in Tools Menu.

Acceptance Criteria:

- [ ] Implement Solution for Direct Link in Tools Menu

- [ ] Document any information in this ticket any information that should be shared with end user on a help page regarding Direct Link Functionality including details about why a Direct Link could stop working in the future.

- [ ] Document within this ticket any pertinent information about possible maintenance needed for direct links. For example, if a catalog record changes in Alma and a new URL is created, the steps for updating the Direct Link content should be documented and included in future operational procedures.

**Comment by devanshu-m** [comment]
@lovinscari I tested this on safari, firefox, and chrome, and it seems to work as expected. When I click on Direct Link in the tools menu it takes me to the record. I tested both arch and test. Can you please send me a screenshot of what you are seeing?

**Comment by lovinscari** [comment]
Accepting this but there were requirements in my original request (Ticket #430) that were not carried over into this ticket. I will put in a refinement for my original specifications.

**Comment by norm0** [comment]
Prototype: https://www.figma.com/proto/ocSo3KytI6GgwjalSVAmE1/Blacklight-Wireframes?page-id=815%3A6&node-id=1108%3A58&viewport=-3272%2C1279%2C0.4351534843444824&scaling=min-zoom
