### ISSUE TITLE
SPIKE: Investigate CSS Styling for Printing Style Sheets

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#432]
As a library user, I would like the ability to print a single item record so I can refer to it later as part of my research and/or use the printout to find the material when visiting the libraries. When selecting the print feature in the Tools Menu on a Single Item Record, I expect a new window to appear (modal window) with a print menu. The print menu should default to an 8.5 x 11 (letter) paper and recognize printers installed on my device. The printout should be on a single page where possible (dependent on the amount of content in the record) removing traditional headers and footers traditionally found when printing a web page. I should have the ability to change the printer and the orientation of the page and the size of the paper if so desired. 

Acceptance Criteria:

- [x] It is unclear how a default print job is styled in Blacklight thus research should be conducted to determine how other institutions who use the Print Feature in their Blacklight Catalog.

- [ ] Application developer and UI Designer are asked to work together to determine what updates are needed in the CSS

**Comment by norm0** [comment]
Any patron can print pages directly from their browser. We can target print styles in our CSS to accommodate this need. 

We should separate our print styles into a singular "print" stylesheet. `<link rel="stylesheet" media="print" href="print.css" />` The downside to this workflow is this stylesheet could be neglected after new features are added to the single item review page.  We'll have to remind our selves to check this file when frequent features are created.


There are three things we can do to create CSS for print. 

1) Hiding content through the 'display:none' property
2) Inserting content like the direct-link or url in the print stylesheet

```
.wrapper::after {
  content: "This page printed from: https://blackcat-test.library.emory.edu/catalog/990016148150302486";
}
```

3) Advanced print styling includes page margins, page breaks and orphans and widows

**How do I test for print styles?**
DevTools in both chrome and firefox allow use to view the page as a printer would. 

CHROME
Open DevTools, click on the three dots icon and then select “More Tools” and “Rendering”. You can then select print under Emulate CSS Media.

FIREFOX
Open the Developer Toolbar then type media emulate print at the prompt.

**Comment by bwatson78** [comment]
@norm0 This sounds fine.

**Comment by lovinscari** [comment]
@norm0 This sounds reasonable to me. Will you be updating the CSS with this information or do I need to submit another ticket for this work?
