### ISSUE TITLE
Implement Print Feature based on Findings from Research

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#433]
Based on findings from Issues [#432](https://app.zenhub.com/workspaces/blacklight-catalog-5f5f84a8a6d29939a0bc5d78/issues/emory-libraries/blacklight-catalog/432), implement the Print Feature as part of the Tools Menu.

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/blacklight-catalog/pull/454

[https://app.zenhub.com/files/295449627/10a751f5-c947-4d05-a1a9-e1ac33c4e662/download](https://app.zenhub.com/files/295449627/10a751f5-c947-4d05-a1a9-e1ac33c4e662/download)

**Comment by lovinscari** [comment]
@bwatson78 - I tested this on blackcat-arch and everything looks good.
