### ISSUE TITLE
Enable prefix-based A-Z navigation on selected facets

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/blacklight-catalog#440]
We found the following option in the catalog controller which can enable further sub navigation on facets with very large quantities of values. In our instance, we had already flagged a usability issue with trying to navigate alphabetically through Authors and Subjects being extremely time consuming.

https://github.com/emory-libraries/blacklight-catalog/blob/118a00e545fb21993c82b14d4d95873a5b9ff5dd/app/controllers/catalog_controller.rb#L105

We want to configure this option for the following facets:

- [ ] Language
- [ ] Author/Creator
- [ ] Subject
- [ ] Collection
- [ ] Region
- [ ] Era
- [ ] Genre

Inaccessible docs note:

```
Class: Blacklight::Configuration::FacetField — Documentation ...https://www.rubydoc.info › github › projectblacklight
Icons to use for pivot facet expand + collapse. #index_range ⇒ Enumerable. A list of facet prefixes (default: A-Z) to allow users to 'jump' to particular values.

```
Here's a possible sample implementation:
https://github.com/projectblacklight/blacklight_summit_princeton_demo/blob/afb13d6cb672024c2be359dcda91c9edfdd9b180/app/controllers/catalog_controller.rb#L76

@norm0 was able to test this parameter out in his local environment and once enabled, it produces an A-Z navigation menu as shown below. This may also be of interest related to Browse functionality we are researching.

![A-Z Prefix Sorting on Large Facets.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/fd8b48ba-92f8-43cf-900f-db0e241737a1)

**Comment by eporter23** [comment]
@norm0 I went ahead and created this but if you have more details to add please do when you have a minute.

**Comment by lovinscari** [comment]
I am not seeing this change on blackcat-arch or blackcat-test

**Comment by eporter23** [comment]
These are looking great, @devanshu-m ! One minor suggestion is that perhaps we remove "0" from the Era facet, since it doesn't really pull anything up.![Screen Shot 2021-04-19 at 11.08.24 AM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/22807dda-94a2-47c8-bc6c-3161c1866df1)

**Comment by lovinscari** [comment]
This looks great!
