### ISSUE TITLE
STORY: Display physical holdings summary from Single Item View page

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/blacklight-catalog#441]
**Story:** As an end user, I want to quickly assess if physical copies of materials are available on campus, so that I can review options for accessing them on-site or through other requesting options

**Notes:**
**"Done" for this ticket will be populating the table only; additional tickets will be written to address how users connect to the iframe.**

The wireframe shows multiple examples of concise data tables for real catalog records that mix physical and/or electronic access and it includes links to their relevant iframes if applicable.

For complex holdings such as journals or microfilms or books with many copies across various libraries, in Phase 1 we are opting to only show a summary statement and then send users to the iframe to see those details instead of outputting all this information on the View Single Item page itself.

**Mockups and References**

- [Wireframe: Where to Find It overview](https://www.figma.com/file/ocSo3KytI6GgwjalSVAmE1/Blacklight-Wireframes?node-id=1108%3A58)
- [Wireframe with multiple table examples ](https://www.figma.com/file/ocSo3KytI6GgwjalSVAmE1/Blacklight-Wireframes?node-id=1175%3A14433)
- [Wireframe prototype of user flow to reach iframe details](https://www.figma.com/proto/ocSo3KytI6GgwjalSVAmE1/Blacklight-Wireframes?node-id=1108%3A58&viewport=-2742%2C1019%2C0.42044636607170105&scaling=min-zoom&page-id=815%3A6)
- Wireframe/prototype of login message overlaid on iframe: see ticket #293
- [Data mapping worksheet](https://docs.google.com/spreadsheets/d/1JOcExlIp1yO4i5oBJwFz6CrkTN_QTV-2lPjMCdMuySs/edit#gid=187904302)

**Display Behaviors **
- [iframe overlay](https://codepen.io/norm0/pen/OJWaKZv)

**Metadata and Indexing**
See the [proposed data mapping](https://docs.google.com/spreadsheets/d/1JOcExlIp1yO4i5oBJwFz6CrkTN_QTV-2lPjMCdMuySs/edit#gid=187904302) for how to populate the tables. The mapping assumes we can use the Retrieve Bib API data and and in some cases, SOLR data. We have identified multiple table types/states that could potentially get generated for physical items:

- Physical: Single Holding
- Physical: Single Holding at LSC
- Physical: Multiple Holdings 

See also the related ticket for connecting users to online access details.

**Comment by eporter23** [comment]
@lovinscari @norm0 draft tickets created here and in #442 for the iframe. There are a couple of things I am hoping you can help me fill in.

**Comment by eporter23** [comment]
From sprint planning we will focus this story on generating the table only; will write a new story about launching the iframe in the Locate/Request button etc.

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/blacklight-catalog/pull/480

Demo video: https://emory-my.sharepoint.com/:v:/g/personal/bwatso9_emory_edu/ERlAfWgAS4dKql2Z8zq30QIBxz4CnuFkVgfX9FET7QUqlA?e=ebNuBq
