### ISSUE TITLE
STORY: Show summary of online access details from Single Item View page

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/blacklight-catalog#442]
**Story:** As an end user, I want to preview available online access options, so that I can understand what options are available to me 

**Notes:** 
**"Done" for this story will be outputting the tables as specified below; additional tickets will be written about how to launch the iframe when applicable.**

The wireframes show multiple examples of concise data tables for real catalog records that mix physical and/or electronic access and it includes links to their relevant iframes if applicable. For Phase 1, we are leveraging the online resource iframe primarily but also need to incorporate additional instances of 856 full text links that are sometimes added to records.

**Mockups and References**

- [Wireframe: Where to Find It overview](https://www.figma.com/file/ocSo3KytI6GgwjalSVAmE1/Blacklight-Wireframes?node-id=1108%3A58)
- [Wireframe with multiple table examples](https://www.figma.com/file/ocSo3KytI6GgwjalSVAmE1/Blacklight-Wireframes?node-id=1335%3A695)
- [Wireframe prototype of user flow to reach iframe details](https://www.figma.com/proto/ocSo3KytI6GgwjalSVAmE1/Blacklight-Wireframes?page-id=1335%3A21&node-id=1335%3A350&viewport=-956%2C548%2C0.14187297224998474&scaling=min-zoom)
- Wireframe/prototype of login message overlaid on iframe: see ticket #293
- [Data mapping worksheet](https://docs.google.com/spreadsheets/d/1JOcExlIp1yO4i5oBJwFz6CrkTN_QTV-2lPjMCdMuySs/edit#gid=187904302)

**Display Behaviors [pending design requirements]**

- Very long tables
- [iframe overlay (see the login prompt wireframe above)](https://codepen.io/norm0/pen/OJWaKZv)

**Metadata and Indexing**
See the [proposed data mapping](https://docs.google.com/spreadsheets/d/1JOcExlIp1yO4i5oBJwFz6CrkTN_QTV-2lPjMCdMuySs/edit#gid=187904302) for how to populate the tables. The mapping assumes we can use the Retrieve Bib API data and and in some cases, SOLR data. We have identified multiple table types/states that could potentially get generated for online/e-resource items:

- Online: Standard
- Online: 856 tag(s) only
- Online: Standard + 856 tag(s)

See also the related ticket #441 for connecting users to physical access details.

**Comment by lovinscari** [comment]
closing this epic since there was only the one issue associated with it (currently) and the issue was previously accepted.
