### ISSUE TITLE
Refine Modal for Citation (Copy/Paste)

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#444]
As the product owner, I would like to ensure library users are aware the citations generated by Blacklight are automatically generated and might not be 100% accurate since the information is based on the catalog record. I like the way North Carolina State University presents this information on their modal (see attached). This information is specific to the modal for the Cite feature on the Tools menu.
![CitationModalDisclaimer.png](https://images.zenhubusercontent.com/5c4a1fe1e9b5fb46bcedb9fc/ca0f36f0-e8a5-4879-9b95-b11ed67006e8)
Acceptance Criteria:

- [ ] App Dev work with @norm0 on styling for the modal window for User Interface Recommendations to draw attention to the disclaimer. 

- [ ] Based on UI recommendation, refine Citation Modal window to include disclaimer, "These citations are automatically generated and may not always be correct. Remember to check your citations for accuracy before including them in your work."

**Comment by devanshu-m** [comment]
From Norm:

https://www.figma.com/proto/ocSo3KytI6GgwjalSVAmE1/Blacklight-Wireframes?page-id=81[…]58&viewport=-3272%2C1279%2C0.4351534843444824&scaling=min-zoom

**Comment by norm0** [comment]
Figma UI first draft: https://www.figma.com/file/ocSo3KytI6GgwjalSVAmE1/Blacklight-Wireframes?node-id=1335%3A3521

**Comment by eporter23** [comment]
@bwatson78 @norm0 looks great to me.
