### ISSUE TITLE
Revise other_standard_ids_ssim and publisher_number_ssim to be _tesim for easier advanced search usage

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/blacklight-catalog#447]
After some initial testing on the Advanced Search form fields, certain identifiers are not easily searchable in the advanced search form unless you know the exact prefix and formatting and wrap the entire phrase in quotes.

Example: if you search a known DOI such as `doi: 10.1007/978-1-349-18209-1` or `10.1007/978-1-349-18209-1` this returns no results unless you format it exactly as `"doi: 10.1007/978-1-349-18209-1"` in the advanced search.

Other examples that contain phrases:

Other Identifiers (other_standard_identifiers_ssim):
Universal Product Code: 738715291863

Publisher Number (publisher_number_ssim):
BSTC-0138 Bright Shiny Things

**Comment by eporter23** [comment]
@devanshu-m I've been testing this against known examples in blemily on arch such as 9936762389202486 which has a doi. In SOLR, I see "other_standard_ids_tesim":["doi: 10.1007/978-1-349-18209-1"] but advanced searches on : `10.1007/978-1-349-18209-1` or `doi: 10.1007/978-1-349-18209-1` don't find any results. Same thing is happening with  Publisher number, e.g. "publisher_number_tesim":["CRC 2301 Centaur"] from 990011061190302486. 

Do we need to do some work on the search form itself to reflect the change in field names?

I am also seeing another impact of this change where I suspect we need to update the Single Item Display page to show the new _tesim fields instead of the prior _ssim versions. See the difference in the Additional Identifiers section between arch and test for this record: https://blackcat-arch.library.emory.edu/catalog/990036327060302486 

https://blackcat-test.library.emory.edu/catalog/990036327060302486

**Comment by devanshu-m** [comment]
@eporter23 yes, the search form modifications were pending. PR made: https://github.com/emory-libraries/blacklight-catalog/pull/465

**Comment by eporter23** [comment]
@devanshu-m works much better now! I tested on some sample UPC codes, dois, and publisher numbers. @lovinscari I think this is good to close. We also have a followup ticket related to make sure the renamed fields show up on the metadata display page.
