### ISSUE TITLE
BUG: Error with iFrame on Blackcat-Test when viewing record with online availability

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#449]
I am getting an error when viewing a [record with online availability](https://blackcat-test.library.emory.edu/catalog/9936715589202486). The iFrame is presenting an error as shown in the attached screenshot.![OnlineResourceError.png](https://images.zenhubusercontent.com/5c4a1fe1e9b5fb46bcedb9fc/db6d1fca-118e-4564-9757-02296b880371). 

The error is only presented when logged in before viewing the record. When I logged out, I was able to select the electronic resource provider (ProQuest), after which I was directed to accept the terms of use and login.

**Comment by bwatson78** [comment]
Unable to reproduce the behavior on Firefox (standard and private browsing). Moving onto Safari.

**Comment by AGCooper** [comment]
I tried Chrome and Firefox and also couldn't reproduce the error. I do get the "Firefox could not open this ..." after I first login but after refresh or other action it works fine. 

![image.png](https://images.zenhubusercontent.com/5c75948e37910a45fad7cb77/139591cb-0d7e-42e0-8ca7-d961c9f18646)

I have seen the error message in this ticket before, I believe after: my Alma session times out > Alma kicks me back to the shib login page > I click login > "You must have used the back button"; but I don't know how helpful that is. Maybe a caching issue?

**Comment by AGCooper** [comment]
I tried Six Sigma too while logged in and did not see this error.

**Comment by bwatson78** [comment]
Reproduced the error on Chrome and Safari. Consulting @rotated8 for direction, since it seems to come from the University's Shibboleth.

**Comment by bwatson78** [comment]
@lovinscari After a Software Engineer meeting about the issue, the issue seems to stem from a recent Chromium build. It is possible that ExLibris has changed some settings that is causing this, but it isn't clear. 

Possible next steps:
- Have a meeting with Gerry to see if he can identify any possible causes on our side.
- Refocus efforts on the API integration.

**Comment by tmiles2** [comment]
Cari will setup a meeting with Mark, Emily, Collin, Alex, Doug and Rachel to discuss the scope of work.

**Comment by tmiles2** [comment]
The is will close out, the team will move forward with the work in ticket #497
