### ISSUE TITLE
SPIKE: Cost Model for SOLR

### ISSUE THREAD

**Issue by libdgg** [emory-libraries/blacklight-catalog#450]
**STORY**
We are currently utilizing AWS for the Blacklight infrastructure and will need to detail the costs related to running the various components of the environment for each instance and total costs expected. We will need to address cost savings rationale and how the environment is configured to deliver cost savings. The threshold that we have been given to benchmark against is $2000 per month. 

**ACCEPTANCE**
A cost model that describes the expected costs for the Blacklight environments listed below with rationale for how each are configured to balance uptime, customer service expectations and financial stewardship.

**UDPATE**
Converting this ticket to a spike to setup the plan. I recommend separating out  the work into a few tickets and possibly as an EPIC to parse out the work and tracking changes over the next few months. See the notes at the end of this ticket thread.

- [x] OVERALL (i.e. cost savings rationale, estimated savings, estimated monthly/annual costs, risks if not implemented) - will include the ARCH, TEST and PROD instances in the plan and actions.

**Comment by libdgg** [comment]
Scheduled meeting with Mark and Doug to work on this ticket on Wed 5/5/ at 1:30pm.

**Comment by libdgg** [comment]
@mark-dce and @libdgg met to review the AWS cost reporting and plan next steps for the next few months. Notes are below for review, edits or questions. Doug will setup an Epic with associated tickets for this work unless there are concerns or other preferences from the team.

Blacklight Cost Management in AWS
aws.emory.edu > AWS Console > then select role 
Account: aws-account-70 (556359784184) 
Region: US East 2 (Ohio) 

NOTES: 

1. The process will be to explore changes needed, make changes and then monitor through the next month. Focus on the biggest bars for the first month or two. 
2. SOLR is shared between Blacklight and DLP 
3. At times it may be difficult to separate costs out for Blacklight specifically if it is using a shared item/service with DLP. One objective of this work is to ensure all costs and items/service being used are expected, accurate and any spikes or changes are accounted for. 

AWS REPORTS: 

1. Service: provides info about the distinct types of servers/instances running (small vs. Large) 
2. Usage Type: Storage costs vs server costs 

NEXT STEPS: 

1. Reports have been set up to start exploration work. 
2. Confirm what is coming from where to explore and clean up non-current stuff. We have items and costs from outside of expected regions and we need to know what those are and if they can be removed. NOTE: Use the “Usage Type” filter to exclude our known regions to explore what those are. 
3. Look at slices by region, service and usage and identify go after the biggest identified “bars” to understand what they are and if they are expected and needed. If not, they will be either adjusted or removed for cost savings. 
4. Make initial changes and track through May and June for any cost savings or impact.  
5. Review reports again by the end of June for any other areas needing exploration or adjustment and monitor through July for cost savings impact. 
6. Once we know a stable server size by July, we can pursue reserved instances for final cost savings and confirm after running for a month or two. 
7. Plan for cost model to be in place and manageable by the end of August 2021. 
8. Future enhancement: Explore tags to be able to filter reports for more accurate cost evaluations. 

RISKS:
 
Since Blacklight shares AWS regions with DLP it may make some evaluations more difficult or time consuming. This is expected to be a medium probability but low risk. The work is expected to uncover any unknown costs, despite this risk, that are not being used for DLP or Blacklight. Risk mitigation action is to pursue the plan above since it will result in known cost saving actions or confirm the need for costs. The degree of impact for this risk is expected to be confirmed within the first month if we run into barriers to cost management exploration work within AWS. If that does occur the risk mitigation and cost model plan will be reviewed for adjustments.

**Comment by lovinscari** [comment]
Thanks @libdgg and @mark-dce. I will put in new tickets based on your recommendation for next steps.
