### ISSUE TITLE
Make solr node cpu sizes consistent

### ISSUE THREAD

**Issue by mark-dce** [emory-libraries/blacklight-catalog#456]
**ISSUE**
We currently have different EC2 instances configured for the Solr Cloud nodes in the Test environment compared to Arch and Prod environments.  We've decided it makes more sense for now to have all environments identically sized.

**ACCEPTANCE**
Each environment's Solr Cloud is configured with 3 nodes with each node running on a T3.Large instance
- [x] ARCH (probably done already but triple check)
- [x] TEST
- [x] PROD (probably done already but triple check)

**Comment by mlooney** [comment]
All test instances are t3.large now
