### ISSUE TITLE
Make solr storage capacity consistent

### ISSUE THREAD

**Issue by mark-dce** [emory-libraries/blacklight-catalog#457]
**STORY**
We'd like to be able to load the full production dataset in any environment, but we don't have enough storage capacity on some instances.

**ACCEPTANCE**
Allocate 1TB of EBS storage on each node of the Solr Cloud in each environment - i.e. 1TB x 3 nodes/environment x 3 environments
- [x] ARCH
- [x] TEST
- [x] PROD

**Comment by oraposa** [comment]
#### Helpful Links
##### Create EBS Snapshots (backups)
  https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebs-creating-snapshot.html
##### EBS Volume Management
  https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/requesting-ebs-volume-modifications.html

**Comment by oraposa** [comment]
##### bumped to 1 TB
solr-cor-test-1.library.emory.edu
solr-cor-test-2.library.emory.edu
solr-cor-test-3.library.emory.edu

will extend filesystems on each once volume optimization process has completed.

**Comment by oraposa** [comment]
##### filesystem extended 
solr-cor-test-1.library.emory.edu (10.65.89.14)

**Comment by mlooney** [comment]
verified arch & test are 3x 1TB (prod already was)
