### ISSUE TITLE
Add load balancer in front of solr cloud nodes

### ISSUE THREAD

**Issue by mark-dce** [emory-libraries/blacklight-catalog#458]
**STORY**
We are currently using round-robin DNS to resolve hosts within the Solr Cloud in each environment.  Blacklight does not refresh it's name lookup, so is effectively a single node or only 1/3 of the total Solr Cloud capacity.  We'd like to change this behavior to make use of all nodes.

**ACCEPTANCE**
Blacklight points at a load balancer in each environment with dynamically distributes load across the three nodes in each Solr Cloud cluster
- [x] ARCH
- [x] TEST
- [x] PROD

**Comment by mlooney** [comment]
Arch has been configured .  I'll run through the process w/ @libah & @oraposa monday.

**Comment by mlooney** [comment]
in order not to disrupt DLP, the prod local balancer lives at blackcat-prod-alb.internal.emory.edu
