### ISSUE TITLE
Documentation for importing records from Alma

### ISSUE THREAD

**Issue by rotated8** [emory-libraries/blacklight-catalog#46]
This documentation should cover
- [x] connecting to alma (using the vpn proxy)
- [x] the required environment vars and what they should be
- [x] what a successful import looks like
and can go into the wiki

This is done when DCE can follow the instructions and get a successful import

**Comment by wulman16** [comment]
Documentation is live: https://wiki.emory.edu/display/BDL/Using+SolrMarc+to+harvest+data+from+Alma+into+Solr+Index

**Comment by tmiles2** [comment]
Brad and Zo will review the documentation first. Norm and McClain will review once their done.

**Comment by bwatson78** [comment]
@tmiles2 I have tried the steps in the documentation and it works for me.

**Comment by alexBLR** [comment]
I have reviewed the documentation and it works for me as well
