### ISSUE TITLE
Task: Implement table for physical items on single item view

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#461]
User story and general acceptance criteria provided (story level) provided in Epic/Story [#441](https://app.zenhub.com/workspaces/blacklight-catalog-5f5f84a8a6d29939a0bc5d78/issues/emory-libraries/blacklight-catalog/441).

Because there are discussions around possible changes to how the iFrame displays, this task will be limited to implementing the table on the Single Item View Page for physical items. 

The table for the physical item display should be implemented according to the [Wireframe: Where to Find It overview](https://www.figma.com/file/ocSo3KytI6GgwjalSVAmE1/Blacklight-Wireframes?node-id=1108%3A58).

The metadata used to populate the table comes from the Real Time Availability API. Emily Porter has worked with the metadata team and constructed a [table ](https://docs.google.com/spreadsheets/d/1JOcExlIp1yO4i5oBJwFz6CrkTN_QTV-2lPjMCdMuySs/edit?usp=sharing) that includes the data mappings and various examples of how the data should be populated.

Acceptance Criteria:

- [x] The table will appear below the Where to Find It section on the Single Item View Display

- [x] If a single holding record (one item at one library), the details of the holding library and call number will be populated in the table

- [x] If multiple holdings (multiple copies and/or multiple libraries), the table will indicate this with text "Multiple locations and/or copies" in the At the library section of the table. The call number section will show a - 

- [x] In all cases (single holding or multiple holdings) the Status section will include availability information indicated by the words Available or Not Available. The word Available should appear in green and the words Not Available should appear in red.

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/blacklight-catalog/pull/480

Demo video: https://emory-my.sharepoint.com/:v:/g/personal/bwatso9_emory_edu/ERlAfWgAS4dKql2Z8zq30QIBxz4CnuFkVgfX9FET7QUqlA?e=ebNuBq

**Comment by eporter23** [comment]
@bwatson78 @lovinscari this is looking great. I want to mention for later an odd example I found where we have non-circulating items at the LSC with no readily apparent holding library (something to tackle later): https://blackcat-test.library.emory.edu/catalog/990008508220302486
