### ISSUE TITLE
Task: Implement table for electronic items on the single item view page

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#462]
User story and general acceptance criteria provided (story level) provided in Epic/Story [#442](https://app.zenhub.com/workspaces/blacklight-catalog-5f5f84a8a6d29939a0bc5d78/issues/emory-libraries/blacklight-catalog/442).

Because there are discussions around possible changes to how the iFrame displays, this task will be limited to implementing the table on the Single Item View Page for electronic items. 

The table for the electronic item display should be implemented according to the [Wireframe: Where to Find It overview](https://www.figma.com/file/ocSo3KytI6GgwjalSVAmE1/Blacklight-Wireframes?node-id=1108%3A58).

The metadata used to populate the table comes from the Real Time Availability API (Retrieve Bib) and the 856 tag(s) for full electronic items available for viewing from the catalog as opposed to the vendor. Emily Porter has worked with the metadata team and constructed a [table ](https://docs.google.com/spreadsheets/d/1JOcExlIp1yO4i5oBJwFz6CrkTN_QTV-2lPjMCdMuySs/edit?usp=sharing) that includes the data mappings and various examples of how the data should be populated.

Acceptance Criteria:

- [x] The table will appear below the Where to Find It section on the Single Item View Display. If a physical item also exists for the record, the electronic information will appear below the physical holding table.

- [x] If the electronic record is provided by the vendor (not from the 856 field) then the table for Online should include the words "View more access options" and what will eventually be the link to the iFrame for the electronic holding information (link to the vendor / resource provider).

- [x] If the record includes a link from the 856 field only then the table should be populated with the words "Access Online" and a URL to the full electronic record

- [x] If both a vendor provided electronic resource and a link from the 856 field are available then the Access Online (856 field URL) should appear on the first line and a link to the vendor provided resource on the second line.

_Until the matter with the iFrame is resolved, the link to the electronic (vendor provided) resource should not be included._

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/blacklight-catalog/pull/482

![Screen Shot 2021-04-27 at 1.40.54 PM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/8300ca8b-df28-4f3e-84e4-fca339093bc8)

**Comment by eporter23** [comment]
This looks great - I have tested against my various case samples. @lovinscari we should also remember to remove the existing 856 link which is still appearing below the iframe. ![Screen Shot 2021-05-03 at 2.11.00 PM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/bc7c07d4-14e1-46f4-a0d9-256d339e5544)

**Comment by lovinscari** [comment]
@bwatson78 - This looks great. Thank you! @eporter23 - Agreed we will need to remove the link below. I will wait to submit this until we have decisions around the iFrame. Thanks!
