### ISSUE TITLE
SPIKE: Propose an approach to addressing objectionable or offensive vocabulary terms

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#464]
As the product owner, I would like for the application developers to propose a solution to addressing objectionable or offensive language that appears in the catalog. Because certain titles or content from the catalog could be objectionable or offensive to certain audiences, I would like to see if there is an approach to dealing with this within Blacklight. 

For example, one approach could be to include a general boilerplate statement on the home page of the catalog similar to that on [Yale University Digital Collections Home Page](https://collections.library.yale.edu/) (bottom of page). 

Another approach (perhaps more sophisticated) is for a library of objectionable or possibly offensive terms could be developed by Product Owner and stakeholders that if appearing in the catalog, a statement could appear on the single item view page addressing the language.

This Spike could include meeting with Sofia from Cataloging to understand the cataloging strategy moving forward before recommending a solution. The product owner will contribute where needed but should not be a bottleneck for this work moving forward.

After researching possible alternatives, a proposal for how to address this should be documented in this ticket along with an estimate of time to deliver so we can determine if this is post or pre beta work.

**Comment by eporter23** [comment]
@lovinscari FYI, I'm on the Anti-systemic racism in metadata working group and I'm aware of Emory Libraries statements being written related to the catalog. I'm happy to work on this ticket.

**Comment by lovinscari** [comment]
I am going to close this ticket as I believe we have a plan to address this. I would like to start with @eporter23 and @norm0 to propose where this information should be contained on the Blacklight site and introduce a wireframe.
