### ISSUE TITLE
Revise publisher name field for advanced search and citations

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/blacklight-catalog#467]
This ticket follows the work done in #419 for configuring Advanced Search fields as well as the various Cite tools tickets.

The Publisher field in advanced search does not return matches against known items. The [requested mapping is noted here](https://docs.google.com/document/d/1C0W4Za9x5nVvfRaLp2-H0H7VjDHtdq-sYNisQ1ue8rg/edit#), but there was an open question about if the field suffix needed to be changed. 

If it is `_ssm`, does this indicate the field isn't searchable at all? It would also be more flexible if we converted this to support keyword searching so __tesim_ may be better. 

`University Press of Kansas` search fails - based on values in
https://blackcat-arch.library.emory.edu/catalog/9936600924002486

This example also fails.
https://blackcat-arch.library.emory.edu/catalog/9936516164102486
`University of Pittsburgh Press`
9936516164102486
In SOLR: `published_ssm":["University of Pittsburgh Press"],`

**SOLR/Indexing:**
We should also revise this field as follows so that there are fallback selections based on different types of publication entries:

- If 264 exists: 264**b**
- If no 264 but 260 exists: 260**b**
- If none of the above and a 502: 502 **c** (for theses/dissertations info)

**Citations/Cite tool**
If we make changes to the published_ssm field we should also be aware of impacts to the Cite functions.

**Comment by eporter23** [comment]
If we make changes to the _published_ssm_ field we should also be aware of impacts to the Cite functions.

**Comment by bwatson78** [comment]
@eporter23 Am I understanding this correctly: with the mapping, are we only grabbing one matching value, or are we grabbing all that match in that particular order?

**Comment by eporter23** [comment]
We're grabbing only one, but using that order of preference.

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/blacklight-catalog/pull/474

No screenshots necessary.

**Comment by eporter23** [comment]
This is working well, thanks @bwatson78 ! @lovinscari you should now have better experience with these two fields on the blemily set. I think this is good to close unless you want to wait for a full reindex.
