### ISSUE TITLE
Adjust single item view page to use new _tesim fields for Additional Identifiers

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/blacklight-catalog#469]
After we did the work to refine several identifier fields for Advanced Search, the single item view display is no longer showing these fields, and should be updated to reflect the changes in fieldnames:

- [x] other_standard_ids_tesim
- [x] publisher_number_tesim

Example of missing identifier fields (pre and post reindex):

Arch version: 
https://blackcat-arch.library.emory.edu/catalog/990036327060302486
![Screen Shot 2021-04-22 at 12.24.14 PM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/821071af-9c33-4aa8-9272-c0151a08e97e)

Test version shows :
https://blackcat-test.library.emory.edu/catalog/990036327060302486

![Screen Shot 2021-04-22 at 12.30.09 PM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/469cd1cc-46a5-4ebe-a7b5-740887f7cc71)

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/blacklight-catalog/pull/481

![Screen Shot 2021-04-26 at 4.56.31 PM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/406bc2ee-4719-436e-98c5-9591d21a094b)

**Comment by eporter23** [comment]
@bwatson78 @lovinscari looks great to me, should be good too close.
