### ISSUE TITLE
Advanced search - enable users to select/search within full range of values in Language and Collection filters

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/blacklight-catalog#473]
This ticket follows work to configure the Advanced Search form. In testing, we can see that both the Language and Collection filters in the form see to be only showing the first 6 values in the set. Both of these fields in the standard facet can have hundreds or thousands of values. Also, users can't search for additional values within these two filters.

Example of current behavior: the Language facet seems to show the first 6 most populated values (same as our facet):

![Screen Shot 2021-04-23 at 11.47.37 AM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/ca1cd4b1-cf56-45ff-8e3a-de88ec06266f)

A search for Chinese fails:
![Screen Shot 2021-04-23 at 11.47.27 AM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/60591edb-2a31-418f-86dc-891f655e672a)

Desired behavior:

- Drop down shows the first 6 values (by count)
- Users can search for additional values and select them
- Users can begin typing and see terms that match (before completing a full, exact entry) 

SOLR/indexing:

- If the type ahead functionality requires keyword searching, do we need to use _tesim fields?

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/blacklight-catalog/pull/485

Demo Video: https://emory-my.sharepoint.com/:v:/g/personal/bwatso9_emory_edu/EW5nhXjPm3VIvLyHNZVD2agBhL2DNc65DoNl7KTm237gIg?e=yJscdE

**Comment by eporter23** [comment]
@bwatson78 This is working well in arch. I'm having very sluggish response in test, but that may be unrelated, so I'll test this again later.

**Comment by eporter23** [comment]
@bwatson78 @lovinscari I'm still seeing really slow response on this page in test when trying to test it. It takes me 30 seconds + to load the page, and then it's sluggish if I try to search within one of the limiters noted in the ticket. @bwatson78 not sure if this is related to the recent work to try to fix these facet limiters?

**Comment by bwatson78** [comment]
@eporter23 Has Solr been restarted since you tested last?

**Comment by lovinscari** [comment]
@bwatson78 and @eporter23 - I am not sure where this was left? I tried testing this morning and it took over 15 seconds to open the Advanced Search page and then about a minute for the Advanced Search page to fully load with the drop downs for the facets. I am inclined to accept this issue and open a new bug ticket for Advanced Search performance. I will confirm this with both of you during standup today.

**Comment by lovinscari** [comment]
I am going to close this issue and put in a new ticket to investigate what should be done to improve performance.
