### ISSUE TITLE
Refine selection logic for Publication/creation information

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/blacklight-catalog#479]
In some records we may have multiple instances of a 264 field. When this occurs, there is one pattern where we see a date only (such as a copyright date), and the other 264 has more subfields populated. We should refine our extraction logic so that if 2 such entries are populated we should use the more fleshed out one for the `publication_main_display_ssm` field.

Examples:
https://blackcat-arch.library.emory.edu/catalog/990017129950302486
The best of James Brown. Volume 2, The '70's
Author/Creator: Brown, James, 1933-2006
Publication/Creation: ©2007 
In the MARC, this also has 
264   4 c| ©2007
264   1 a| Santa Monica, Calif. : b| Universal Records, c| [2007]
The longer 264 seems to be used by the Cite tool, but the display version is only showing ©2007

Additional examples: 
https://blackcat-arch.library.emory.edu/catalog/990016719930302486
https://blackcat-arch.library.emory.edu/catalog/990001121290302486
https://blackcat-arch.library.emory.edu/catalog/990009794770302486
https://blackcat-arch.library.emory.edu/catalog/990016827000302486

**Comment by eporter23** [comment]
@devanshu-m does this require a reindex to test (since 4/30)?

**Comment by devanshu-m** [comment]
@eporter23 yes this was deployed today and will require a reindex. Should I reindex with bl-emily on arch?

**Comment by eporter23** [comment]
Looks great @devanshu-m. @lovinscari this should be good to close.

**Comment by lovinscari** [comment]
@devanshu-m and @eporter23 - I think this is good to close. Thank you both for your work on this!
