### ISSUE TITLE
SPIKE: Infrastructure Post-Mortem

### ISSUE THREAD

**Issue by libdgg** [emory-libraries/blacklight-catalog#486]
As project sponsors (representing both products and operations), we would like for the infrastructure team to conduct a retrospective of the work involved and ensure documentation is in place in the wiki (and linked to appropriate external sites) to support ongoing operational support and training for the product post-launch.

Acceptance Criteria:

- [ ] Documentation Start Page (wiki): https://wiki.emory.edu/display/BDL
- [ ] System Architecture documentation and work instructions for setup and maintenance
- [ ] Alert/Alarm Architecture and configurations and work instructions for setup and maintenance
- [ ] Documented knowledge deficits that remain, risks if not mitigated, and mitigation recommendations

**Comment by lovinscari** [comment]
Moving this under leadership responsibilities and out of backlog for the product.
