### ISSUE TITLE
Spike: Determine how and where deduplication will take place.

### ISSUE THREAD

**Issue by tmiles2** [emory-libraries/blacklight-catalog#49]
Topics/decision for discussion:
- Determine where deduplication would be handled (Alma, SolrMarc, or SOL) 
- Determine the normalization rules (if we can) for deduplication (i.e., what is the general consensus around how deduplication should be handled for all records).

**Comment by laura-ake** [comment]
Michael Gibney from U. Penn libraries shared some information on Code4Lib Slack:  " wrt deduping in Blacklight/Solr I thought I'd link to this: [https://github.com/upenn-libraries/solr-source-deduplication/] 
TL;DR: deduplication in blacklight/Solr can be done as a pre-processing step, or at query-time via Solr "collapse", or (the mean topic of the link above) cached "join" queries. There are benefits/drawbacks of each appraoch, but I favor the "join"-based approach, and am happy to discuss with anyone who's interested in implementing.
The approach outlined in the linked writeup is still more or less valid/in use ... but there are some subtle changes/updates I'd recommend if you're actually planning to embark on implementation ... "
