### ISSUE TITLE
Enable users to search by call number in the default/Keyword search

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/blacklight-catalog#491]
**Story:** As an end user, I want to quickly search for material by its call number, so that I don't have to navigate to the Advanced Search field to do so

**Note**: we configured a new field for call number while building our Advanced Search form, but users can't reliably search for call numbers in the Keyword search option

**SOLR/Indexing**
- Enable `local_call_number_tesim` to be searchable in the Keyword option
- The existing `text_tesi` field doesn't always have this information because it is not always in the MARC bib record.

**Comment by lovinscari** [comment]
@devanshu-m - This looks great. Thank you!
