### ISSUE TITLE
Refine Fuzzy Search based on number of results returned

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#492]
As explained in ticket [#130](https://app.zenhub.com/workspaces/blacklight-catalog-5f5f84a8a6d29939a0bc5d78/issues/emory-libraries/blacklight-catalog/130) - "We have the option of setting number of results that are required in order to show suggestions. Meaning when we search, if the number of results returned is lesser than that number only then show suggestions. Currently this has been set to 5. Therefore, all result sets that have less than five results will show suggestions."

As the product owner, I would like for the Fuzzy Search to be changed so that suggestions are offered only if the result set is zero. I believe the strange behavior when entering the MMSID is due to the fact only one result is returned, thus the Fuzzy Search is making suggestions about alternative searches.

Acceptance Criteria:

- [ ] If a basic search or advanced search is conducted and there are no results from the search then the Fuzzy Search should suggest alternatives for searching using the current configuration of Fuzzy Search in Blacklight.

**Comment by eporter23** [comment]
This looks good to me. I've been doing some ID number searches of various types and see the 

> did you mean...

 message much less now.

**Comment by lovinscari** [comment]
@devanshu-m - This looks great. Thank you!
