### ISSUE TITLE
SPIKE: How do we do sign in with Ex Libris?

### ISSUE THREAD

**Issue by rotated8** [emory-libraries/blacklight-catalog#497]
What we know:
- Attempting to sign into ExL through the iframe does not work due to CORS restrictions.
- Emory Shibboleth is not sufficient to sign into ExL through the iframe either.
- A user must be signed into ExL in order to request an item
- We cannot proxy the request to Alma to get around the CORS restrictions.

What we want to know:
- Can we use the same "Are you Emory-affiliated?" login screen that Discovere does? Do we get user information back to our application?
- Can we use APIs to get a req_id for a user who has logged in from our current shibboleth login flow?

**Comment by laura-ake** [comment]
@rotated8 Did you see these Josh Weisman developers blog posts?

https://developers.exlibrisgroup.com/blog/leveraging-the-public-cloud-creating-a-cors-proxy/ 
which references
https://developers.exlibrisgroup.com/blog/using-a-simple-proxy-to-add-cors-support-to-ex-libris-apis/ 

not sure whether this would be helpful, but maybe https://developers.exlibrisgroup.com/blog/working-with-jwt-authentication-tokens/ 

Laura

,
