### ISSUE TITLE
Set up API access for the team

### ISSUE THREAD

**Issue by rotated8** [emory-libraries/blacklight-catalog#498]
To support the login spike #497, it would be useful for the developers to be able to make API calls to the ExL sandbox. 

- [x] Create API keys for the bib and user APIs, for sandbox and production.
- [ ] Setup access to the API console in ExL.

**Comment by rotated8** [comment]
@mark-dce - API keys are specific to the API you want to use and to the environment you want to use them in (sandbox or prod). We have four keys now (users prod, users sandbox, bib prod, and bib sandbox). The base url matters little, the actual target of the request is managed by the API key. @AGCooper can work on API console access for DCE next week.

**Comment by rotated8** [comment]
We'd like to add @mark-dce @mlooney @norm0 @oraposa @alexBLR @devanshu-m and @bwatson78 to the API Console.

**Comment by lisahamlett** [comment]
@AGCooper is going to show me how to set everyone up and then I'll be able to walk through how to use it with folks.
