### ISSUE TITLE
APA Citation Revisions

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/blacklight-catalog#499]
This ticket follows work in #417 to configure basic APA 7th edition citations in our Cite tool.

Simplified reference for a basic APA 7 citation:

> Authorlastname, F. M. (Copyright Year). _Title of the book_ (Nth ed.). Publisher. DOI

After testing the outputs of APA 7, a few formatting issues were identified:

1. Author name formatting for 1XX entries with additional subfields
2. Authors vs. editors
3. Punctuation for DOIs

**1: Complex author name formatting**
Some 1xx entries will contain additional name qualifiers such as spelling out initials, showing birth/death dates, titles etc. We should pare the name component down so that it only shows the last name, first initial and middle initial.

https://blackcat-arch.library.emory.edu/catalog/990027503070302486

Current output

> Yeats, W. B. (. B. (1938). _The autobiography of William Butler Yeats: Consisting of reveries over childhood and youth, the trembling of the veil, and dramatis personae._ The Macmillan Company.

Desired output

> Yeats, W. B. (1938). _The autobiography of William Butler Yeats: Consisting of reveries over childhood and youth, the trembling of the veil, and dramatis personae_. The Macmillan Company.

**2 & 3: Example with Editor Name and DOI**
https://blackcat-arch.library.emory.edu/catalog/9936777323402486
In this example the name shown is actually an editor and not the author. There is also punctuation around the DOI which isn't needed.

**Current output:**

Gleason, A. (2007). _A companion to Russian history._ Blackwell. (doi: 10.1002/9781444308419)

**Desired output**

Simple option: omit the editor and show no author; start with the title element as shown below. Remove parenthesis around the dog:

> _A companion to Russian history._ (2007). Blackwell. doi: 10.1002/9781444308419

Complex option/enhancement: if we can detect that there is a 7XX entry whose role is an editor, then output as follows. Note the addition of (Ed). below: 

> Gleason, A. (Ed.). (2007). _A companion to Russian history_. Blackwell. doi: 10.1002/9781444308419

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/blacklight-catalog/pull/505

![Screen Shot 2021-05-05 at 8.13.10 AM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/5b4d1f1c-f8d0-4afe-b836-cbb710e67d77)

**Comment by lovinscari** [comment]
@eporter23 - this looks good to me but I would like for you to review and close if acceptable. Thanks!

**Comment by eporter23** [comment]
Thanks @bwatson78 this looks good on the examples I've tested in arch.
