### ISSUE TITLE
Revise Indexer Failure Handling

### ISSUE THREAD

**Issue by rotated8** [emory-libraries/blacklight-catalog#502]
Currently, the indexer logs errors from Solr when committing docs fails, but keeps running, and fails immediately when fetching the records from Alma fails.

In the first case, rather than interacting with Solr via HTTP requests, we can use the [rsolr gem](https://www.rubydoc.info/gems/rsolr) (which is required by Blacklight), and take advantage of [built-in retrying](https://www.rubydoc.info/gems/rsolr#label-Retry+503s). Additionally, we should ensure that errors committing to Solr stop the indexer. Ideally, the resumption token would not be updated, so we could attempt to restart indexing without losing our place.

[Faraday](https://lostisland.github.io/faraday/) provides "[retry with backoff](https://lostisland.github.io/faraday/middleware/retry)" that we can leverage to cover the latter case. Faraday is a dependency of rsolr, and using it here would remove RestClient from our dependencies.

Finally, logging in the reindexer should be reviewed and standardized. Logging appears to have grown organically over time, and with the new revision going on in this ticket, it is time to review the current logging and standardize on an approach. Currently, there are two loggers, and they can be very chatty. Can one of the loggers be removed? Do we need to log all the information currently outputted?

**Comment by bwatson78** [comment]
@rotated8 
Currently, the update records interaction is handled by Traject, rolling together the index mapping and the posting to Solr after processing the fields. I'm going to move forward with researching Traject further, seeing if they provide the same "retry x times after waiting x seconds" settings. 

If this isn't how you want me to proceed, please "at" me here and I'll switch gears.

**Comment by bwatson78** [comment]
I have, however, got RSolr working in the Service file for deleting ids.

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/blacklight-catalog/pull/521

No screenshots necessary.

**Comment by lovinscari** [comment]
@bwatson78 and @rotated8 - I am not sure there is anything for me to test with this so I am going to close since I am assuming @rotated8 approved this during the review.

**Comment by rotated8** [comment]
@lovinscari Sounds good. This is something we should keep in the back of our minds as we reindex in the future, and can revisit if we have more issues.
