### ISSUE TITLE
SPIKE: Determine work needed to effectively address how series are handled in citations for MLA 

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#507]
As @alexBLR reported during the demo on 5/5/21, there are refinements needed to address how series are handled with the current formatting for MLA and APA citations. 

According to owl.purdue.edu - 
When citing only one volume of a multivolume work, include the volume number after the work's title, or after the work's editor or translator.

Quintilian. Institutio Oratoria. Translated by H. E. Butler, vol. 2, Loeb-Harvard UP, 1980.

_Comments: since we can't predict which volume a user may be referencing, this must be a manual process._

When citing more than one volume of a multivolume work, cite the total number of volumes in the work. Also, be sure in your in-text citation to provide both the volume number and page number(s) (see "Citing Multivolume Works" on our in-text citations resource.)

Quintilian. Institutio Oratoria. Translated by H. E. Butler, Loeb-Harvard UP, 1980. 4 vols.

_Comments: the total number of volumes could appear in several MARC fields, but none of them are specifically designed for this purpose and the entries may contain other information. We think this would be a significant engineering effort to address and don't recommend it at this time._

If the volume you are using has its own title, cite the book without referring to the other volumes as if it were an independent publication.

Churchill, Winston S. The Age of Revolution. Dodd, 1957.

_Comments: this is essentially what we output in many cases already._

Acceptance Criteria:

- [x] App Developer work with Emily Porter to determine if any modifications are needed to Solr Fields to introduce information needed as part of a series.

- [x] Based on findings of work that is needed, generate new ticket(s) to complete the work to refine the MLA citation feature to include accurate series information. See ticket #534.

**Comment by devanshu-m** [comment]
Notes (from alma marc research):

- `245n` field does appear to store the volume of a given title
- From blacklightemily set, I see that `245n` is not the only field that stores volume information. The following datafields store volume:
  - `830 $v`
  - `490 $v`
  - `362 $a`
  - `588 $a`
  - `500 $a`
  - `050 $b`
 This is based on the blacklightemily set and may not represent all possible datafields that have volume information. Also, not all of the above fields might be useful in determining volume.

**Comment by devanshu-m** [comment]
More notes around `245 $n $p` and `300 $a`:

- We are adding information gathered from fields `245 $n` and `245 $p` if available. These fields may have volume information or could also have part information. Eg from @eporter23 : `Harry Potter part 1`
- We are not currently considering `300 $a` field at all. This datafield may sometimes contain number of volumes present for a title. Eg: `Harry Potter, 4 volumes.` 
Emily is going to talk to cataloging to confirm this.

**Comment by eporter23** [comment]
I discussed with @lovinscari a number of challenges posed by trying address the use cases above. After a review with @devanshu-m and consulting with Erin Mooney, we recommend doing the following work which will be written as additional tickets:

- Remove the volume-specific component of the citation output, but ensuring that part numbers and part names are included in the title component (e.g. Book One, Part One, Volume 1) because volume information can appear in multiple fields and is often not consistently formatted
- Remove the edition component of the citation output, because the majority of these are not formatted as numeric indications, but are textual in nature. Users can see the edition information on the item detail and format as needed.

**Comment by lovinscari** [comment]
@eporter23 - I am going to close this ticket and believe you said you would create the new tickets referenced above?
