### ISSUE TITLE
Remove Chicago citation style from Cite feature 

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#509]
Because Emory University Libraries does not actively promote the use of Chicago Style citations, we will remove the Chicago style from the cite feature for now and reintroduce post-beta after additional details are gathered regarding the version of Chicago style that should be referenced.

Acceptance Criteria:

- [ ] Remove Chicago Style from the Cite feature on the Tools Menu.

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/blacklight-catalog/pull/517

![Screen Shot 2021-05-06 at 9.19.48 AM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/049adfc3-33c5-430e-b273-b987492f0c1a)

**Comment by lovinscari** [comment]
@bwatson78 - This looks good to me. Thanks!
