### ISSUE TITLE
Provide a list of users, grouping them by the functionality they have access to with discoverE

### ISSUE THREAD

**Issue by tmiles2** [emory-libraries/blacklight-catalog#51]

**Comment by tmiles2** [comment]
Review tables to determine access via user group, library, material type, item policy, request type etc.

**Comment by AGCooper** [comment]
Ann is working on a list for the custom request options. Added Lisa in case we also need to map Alma based request options. Will reach out to Rachel to see if there is a need for Alma based requesting information.

**Comment by libah** [comment]
Attached is a workbook with several sheets that explain how users permissions are defined by service. [https://app.zenhub.com/files/295449627/0fa2e108-2eac-4234-a26e-17391882aded/download](https://app.zenhub.com/files/295449627/0fa2e108-2eac-4234-a26e-17391882aded/download)

**Comment by AGCooper** [comment]
The attached workbook is for user access to requesting options configured via primo vs. the request options that are currently managed in and through Alma and accessible through the Alma lightbox in Primo.
