### ISSUE TITLE
SPIKE: Determine if new view in Primo is possible to show only information from Central Discovery Index (CDI)

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#512]
As the product owner, I would like for users to have access to other electronic resources (Article Plus) that are not in the Alma Catalog but that come from Primo's Central Discovery Index (CDI). This would require a new view in Primo that would show only information from CDI so that a link could be provided from the home page of Blacklight allowing users to access this view and complete their search specific to Articles Plus outside of Blacklight until this functionality is incorporated into Blacklight during Phase 2. This new view could also be linked to the search tool on the Libraries Home Page (post-beta) providing users the ability to conduct a search of this feature from the Libraries Home Page. 

Acceptance Criteria:

- [x] Confirm new view in Primo can be generated to search and access only information from Central Discovery Index.

- [x] Assuming a new view is possible, determine what styling is possible and needed, and what styling can be obtained from the Blacklight CSS. Work with Norm on styling requirements. 

- [x] Document the work needed in this ticket for the team to determine how this work should be addressed moving forward.

**Comment by libah** [comment]
It is possible to create a view with a limited search scope of CDI.

**Comment by libah** [comment]
It is possible to limit the search scope in a view to just CDI. 
Sandbox:
http://discoveretest.emory.edu/primo_library/libweb/action/search.do?vid=cdi

Some things that will need to be done. 
1. Create view - 
2. Limit scope to cdi only 
3. Remove tabs 
4. thumbnail images
5. Should we remove 'Advanced search', 'Browse search'? (they are only searching CDI)


Styling - met with Norm, Clare, Alex

**Comment by norm0** [comment]
Follow up thoughts with work to be done: https://docs.google.com/document/d/19GW39zaWWUesRW4f7Xm7iH7jD-BHwT7lMMWaN2EGjqk/edit?usp=sharing

**Comment by norm0** [comment]
@libah @CB987 and I found a way a path forward to edit the header and footers html files. 

https://docs.google.com/document/d/19GW39zaWWUesRW4f7Xm7iH7jD-BHwT7lMMWaN2EGjqk/edit?usp=sharing
