### ISSUE TITLE
SPIKE: Determine how style sheets can be refined

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#514]
**Story**
In the theming and branding branch we are currently using the existing DLP/Lux stylesheets. These files may have used OOCSS to manage the styles but are starting to becoming larger with a lot of duplicates. We can reduce styles bug fix searches but reducing duplicates.

**Acceptance**
Merge, revise and reduced redundant styles on the following components:
- [x] Header
- [x] Footer
- [x] Item show page
- [x] Advanced Search
- [x] Bookmarks
- [x] History
- [x] Staticpages

**Comment by devanshu-m** [comment]
PR merged. I do have one concern around static pages and making them text editor friendly within the application, so that they are no longer hard-coded, which will make changing text on those pages easier if we can do them from the UI itself.

**Comment by lovinscari** [comment]
@norm0 - I am going to close this assuming you reviewed and completed this work with the developer. We can review during our Wireframes Meeting on 5/19/21.
