### ISSUE TITLE
SPIKE: Determine work needed to stabilize backups for Blacklight 

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#515]
There is a current backup and restore process that has been created for the repository. It is unclear if that process is stable and can be re-used/modified to incorporate what is needed for backups and restore of the catalog. There are some variations in that not all data from Solr would have to be backed up and restored from the backup as a new data import could be generated from Alma. 

The infrastructure team is asked to:

- [x] Review the work previously completed by Solomon for backups of the  production environment for DLP.
- [x] Determine what work is needed to refine this process to include backups for Blacklight environments. Alex Cooper and Collin Brittle should determined what backups should take place for the current stage of the project. 
- [x] Ensure any work needed includes automation of the backups and communication with Slack as an alert if the backup process fails. 

- [x] Document any work needed in this ticket to determine when this work should be completed.

**Comment by rotated8** [comment]
Solomon provided [three](https://wiki.emory.edu/display/DLPP/Backup+and+Restore+Strategy) [wiki](https://wiki.emory.edu/display/DLPP/Detailed+S3+Backup+Strategy) [pages](https://wiki.emory.edu/display/DLPP/Restoration+Process+-+Testing+Checklist) with backup and restore documentation.

The ansible implementation for backup and restore should live in the [cor-cm](https://github.com/emory-libraries/cor-cm) repository.

**Comment by oraposa** [comment]
@rotated8 please update my credentials for the above-linked content. Thanks.

**Comment by rotated8** [comment]
@oraposa and I met today. I think when we've got tickets to work on, this work should be towards the top of our queue.
