### ISSUE TITLE
Cleanup AWS to remove any environments or services no longer needed to help manage costs

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#516]
As a result of spike ticket #450 to review costs (current and projected) for the Blacklight product, it was identified that one task was needed to confirm what is coming from where to explore and clean up non-current stuff. We have items and costs from outside of expected regions and we need to know what those are and if they can be removed. NOTE: Use the “Usage Type” filter to exclude our known regions to explore what those are.

- [x] The infrastructure team should work with Collin Brittle and Alex Cooper to review what environments or services are currently in AWS for Emory Libraries that are no longer needed (as described above).
ACTION: Remove services that are generating costs in US East (OH)
- [x] This information should be communicated to Doug Goans so he can also review with Rosalyn Metz and confirm those environments or services can be removed.
ACTION: Rosalyn is ok with monitoring for costs (i.e. $2500 per month) while we investigate the "Other" cost categories. The idea is that we can reduce down from $2500 to a lower figure.
- [x] Once approved, remove any environments or services no longer needed.
ACTION: Close this ticket, create a new ticket regarding removal of costs in US East (OH). Start monitoring monthly for any changes to costs and create new ticket to confirm the "Other" costs are valid or if they can be removed.

[See summary report](https://emory-my.sharepoint.com/:b:/r/personal/rmetz_emory_edu/Documents/LTDS%20Shared%20Documentation/Projects/Project%20Documentation/Blacklight%20Discovery%20Layer%20Phase%201/Scrum%20Team/Artifacts/Blacklight-Cost-Model-2021-05-17-Summary.pdf?csf=1&web=1&e=tnn0UZ)

**Comment by libdgg** [comment]
Meeting scheduled Tues 5/11 with the assignees.

**Comment by libdgg** [comment]
Did some analysis work on the action items in the comment above and plan to review with Rosalyn today (Monday May 17th). Will update this ticket with status and next steps.

**Comment by libah** [comment]
I searched the blackcat-tf repo and keys for any Ohio region dependencies and didn't find any. Including keys.

**Comment by libdgg** [comment]
Finishing up a final step of "Other" costs category to prepare my summary.

**Comment by libdgg** [comment]
@mark-dce @rotated8 @AGCooper 
Please review my summary and the actions there (and in the ticket description above) and let me know if you are ok to close this ticket for this sprint and we can create tickets for action steps. Or, if you would like to meet to go over anything in more detail first. Thanks -DG

**Comment by mark-dce** [comment]
Summary report looks great!

**Comment by libdgg** [comment]
Thanks @mark-dce 
I'm closing this ticket and adding tickets for

1. the US East OH work
2. another round of investigative work for the Other costs
3. clean up AWS report to start a monthly process of reviewing AWS costs
