### ISSUE TITLE
Update footer wireframes for harmful language and about link

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#518]
It has been decided the best place to link the Harmful Language statement is within the footer. As such, please update the wireframes to reflect the following changes:

- [x] Replace the wording and link "Copyright and Content" with the wording "Harmful Language in the Catalog" with a link to https://libraries.emory.edu/about/policies/statement-harmful-language.html

- [x] Additionally, similar to the changes in the header wireframe, please change the word "About" to "About Library Search"

If time permits, please create tickets for the application developers (front-end) to implement the changes shown on the wireframe.

Wireframes/mockups:

- [x] Generate visual mockups (seen screenshot below)
- [x] Update [Figma files](https://www.figma.com/file/Z7y52FyJlYYjOx7QMAmnyz/Blacklight-Wireframes-v2?node-id=91%3A4720)
- [x] Create implementation tickets for changes: #803

![Footer Revised.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/e26710a9-47e2-4337-8262-df7ac66f2a1e)

**Comment by eporter23** [comment]
Statement will be hosted on the Emory Libraries Policies page. Discovere will link to it.

**Comment by lovinscari** [comment]
After a conversation with @norm0, I will work with Sofia on options for providing a link to the harmful language statement.
