### ISSUE TITLE
Review header styling and branding with a developer(s)

### ISSUE THREAD

**Issue by norm0** [emory-libraries/blacklight-catalog#519]
**Story**
Currently, the header styles are almost an exact copy from DLP or Lux project but could use some revisions.

**Acceptance**
Review the current markup and decided any improvements or enhancements 

- [x] Document revisions and enhancements

**Comment by eporter23** [comment]
FYI, prior work in Lux and I will check around for anything else I can find: https://app.zenhub.com/workspaces/digital-library-project-5bf484ae4b5806bc2bf6875b/issues/emory-libraries/dlp-lux/341

**Comment by norm0** [comment]
Scheduled for 5/11 at 4pm EST

**Comment by norm0** [comment]
https://docs.google.com/document/d/1PrK2Rctd0js4tKNXjSzSdV1Ytt5TSsndFldeOklY2oM/edit#
