### ISSUE TITLE
Test current Restore process for SOLR Cloud  

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#520]
Related to the research for ticket #515, this ticket is to test the backups currently in place for DLP and test a restore in a new environment.

**Comment by eporter23** [comment]
In sprint planning, we discussed that this work will focus on testing a backup and restore of SOLR Cloud data to a new environment. This will not be a restore on any actively used environments for DLP.

**Comment by mlooney** [comment]
we successfully backed up & restored all collections on the production cluster.

**Comment by eporter23** [comment]
Note: we also found the original DLP SOLR backups which are stored in the cor-devops-binaries bucket. See additional notes about S3 buckets and backups on the DLP wiki.
