### ISSUE TITLE
SPIKE: Research technical feasibility and usability of the Alma Services Page for Requesting Physical Items

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#524]
Because we are unsure of the path forward for the iFrame problem, I would like for members for Lisa, Alex, Ann (or Clare), Emily, Norm, and Devanshu to work together to research what it would take to implement the Alma Services Page [(example)](https://na03.alma.exlibrisgroup.com/discovery/openurl?institution=01GALI_EMORY&vid=01GALI_EMORY:AlmaGeneralView&rft.mms_id=990022757740302486) as a possible replacement for the iFrame to replicate requesting

**Acceptance Criteria:**

- This is high priority and other work within Blacklight for any of the assignees should be deferred until this work is completed. Because it is essential to have a good understanding of the feasibility of the Services Page from a Requesting a Physical Item standpoint, I am suggesting an estimate of 13 (also based on the number of people involved). It is assumed an initial meeting will be necessary to devise a game plan to complete the requirements below.

- Follow up from the initial research performed in February, and complete a  test intended to serve a as a prototype to demonstrate the technical feasibility and overall functionality of the Alma Services Page based on the following criteria:

Criteria to assess:

- [x]  The Service Page should show the locations  for the physical holding or holdings (if multiple) of a single item record if physical holdings exist. The preferred functionality would be having the Services Page show as a modal when the user selected Request It from the Single Item View Page.

_Update: because the page is hosted on ExLibris servers, we can't load this in a modal (similar to iframe functionality) due to cross-origin security issues. We could load the services page in a new tab instead. We have also been able to modify the page styling by adding custom CSS to [the sandbox view](https://emory-psb.alma.exlibrisgroup.com/discovery/openurl?institution=01GALI_EMORY&vid=01GALI_EMORY:AlmaGeneralView&rft.mms_id=990022757740302486)._

- [x] The Service Page should show availability of the holdings for each location if there are multiple

_Update: it currently shows holdings per Bib ID with sub-navigation including ability to filter to a specific Library._

- [ ] The ability to request the physical item(s) should be based on authentication with Alma (Alma User Groups permissions)*

_Update: prior to Shibboleth integration and work in ticket 527, the login option shown is configured for affiliate logins. We need to determine how to configure Shibboleth for this page._

- [x] If the user (based on authentication) is able to request a physical item, they should see a Request Option with the GetIt Section of the Services Page

![GetIt_Request_ServicesPage.png](https://images.zenhubusercontent.com/5c4a1fe1e9b5fb46bcedb9fc/5270a417-4b62-42ab-ba07-60cc1a79d9ae) 

_Update: we have tested with an affiliate/test login and that user can see the basic request option (the others shown above would have to be added)._

- [x]  I am unsure how the requesting feature is supposed to function within the Services Page but within the iFrame, once the user selected the request option, they were presented with a modal to complete certain criteria for the request (length of check out, delivery option, etc.). I would expect similar functionality from the Services Page

- [ ] A transaction was successfully completed within the iFrame if the requested item appeared in MyAccount. 

- [x] The findings should be documented in this ticket with specific work to be completed if it is determined the Services Page 

Unknowns:

- [ ] *How we can utilize either Blacklight or the Services Page for account login for both Shibboleth (Emory Users) and Affiliates (local Alma accounts) using the same process currently in place for [Primo Login](https://emory-primoprod.hosted.exlibrisgroup.com/pds?func=load-login&calling_system=primo&institute=01EMORY&lang=eng&isMobile=false&url=http://discovere.emory.edu:80/primo_library/libweb/action/login.do?targetURL=http%3a%2f%2fdiscovere.emory.edu%2fprimo_library%2flibweb%2faction%2fsearch.do%3fvid%3ddiscovere%26amp%3bdscnt%3d0%26amp%3bdstmp%3d1620849553055%26amp%3binitializeIndex%3dtrue). This group can determine if this question can be answered as part of this ticket, and there will be a separate ticket created to look at the login service in general.

_Update: more work for authentication is happening in #527._ See also notes and reference links in our [working session document](https://docs.google.com/document/d/1qrSjcuXEtub8AGkBCWMvhcG9B4a95Bk3Ov2Kz51muVE/edit#) and [screen captures with notes.
](https://docs.google.com/document/d/1IQF3dACpnbS1Jh-_CgqXYQPsH9L-rxOT3pM1Eslwfgw/edit#)
_Additional work recommended:_

- Investigate options to modify page content using Javascript
- Manage Alma package file customizations in a GitHub repository and set up a workflow for easier maintenance
- Identify navigation pathways and modifications needed to connect users back to Blacklight once they have reached the Services page
- Investigate how and where to add locally customized request methods such as Aeon

**Comment by lisahamlett** [comment]
Added Norm and McClain since they've both been looking at this.

**Comment by eporter23** [comment]
Meeting scheduled for morning of 5/17.

**Comment by eporter23** [comment]
Work in progress: team has been able to make layout customizations using the the General view/service page's package file CSS and will also investigate JS capabilities. The authentication portion of this spike is happening in #527.

**Comment by lisahamlett** [comment]
I have created a blacklight services page that has both Shib and non-Shib authentication working in Alma Sandbox:
https://emory-psb.alma.exlibrisgroup.com/discovery/openurl?institution=01GALI_EMORY&vid=01GALI_EMORY:blacklight&rft.mms_id=990022757740302486

**Comment by lisahamlett** [comment]
The page is basically ready to go for visual customization.
