### ISSUE TITLE
SPIKE: Determine possible paths for User Login and Authentication for Alma Requesting

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#527]
As discussed during mid-Sprint review, the team needs to look at how we might replicate the current [login/authentication process for Primo and Alma](https://emory-primoprod.hosted.exlibrisgroup.com/pds?func=load-login&calling_system=primo&institute=01EMORY&lang=eng&isMobile=false&url=http://discovere.emory.edu:80/primo_library/libweb/action/login.do?targetURL=http%3a%2f%2fdiscovere.emory.edu%2fprimo_library%2flibweb%2faction%2fsearch.do%3fvid%3ddiscovere%26amp%3bdscnt%3d0%26amp%3bdstmp%3d1620849553055%26amp%3binitializeIndex%3dtrue) 

Having a general understanding of this process will most likely apply to any route we take for requesting including iFrame resolution, Services Page, or API's. It does not appear the Ex Libris Identity Service addresses this issue specifically as Emory users are managed through Shibboleth and would not be stored in the Ex Libris Identity Service. 

If not already explored, there appears to be some helpful information in the [Alma Authentication Knowledge Article](https://knowledge.exlibrisgroup.com/Alma/Product_Materials/050Alma_FAQs/User_Management/Authentication). If needed, perhaps a meeting with Josh Weisman could be established as he might be able to provide some insight. If Josh seems reluctant, perhaps he could be hired for a teach out with the Blacklight Scrum Team?

There could also be other institutions who use Alma and have Blacklight as their discovery layer who might be able to shed some insight. Known institutions are UPenn, and Temple. 

Although this is a Spike ticket, those involved with this ticket should take any time needed to explore all options as this requirement is needed for requesting, which is a critical component of the catalog. 

Acceptance Criteria:

- [ ] Identify, test, and prototype any viable solutions that will replicate the current functionality between Primo and Alma (see above) that identifies and authenticates Emory Users using Shibboleth and Affiliates using Alma or Ex Libris Identity Service

- [ ] Document all findings within this ticket including any work needed to implement this for the Blacklight Catalog.

**Comment by eporter23** [comment]
Work in progress: team has been able to make layout customizations using the the General view/service page's package file CSS and will also investigate JS capabilities. We're now looking into authentication options as part of ticket #527.

**Comment by eporter23** [comment]
Lisa has filed a ticket with ExLibris as of 5/17.

**Comment by mlooney** [comment]
### Current status

After much fiddling, it has been determined that the PDS authentication system at Ex-Libris is not connected to the service pages in any sensible way.


### The long version:


Authenticating either via shibboleth, or affiliate login from the ex-libris authentication interface ([here](https://emory-primoprod.hosted.exlibrisgroup.com/pds?func=load-login)), is successful, but navigating over to the service page displays "not-logged-in" state, until the sign-in process occurs on that page.

Further, If a user has previously authenticated as one user in Primo, logging in as a second user on the service page, causes the *first* user to be authenticated as the current user (not the user so very recently authenticated).

This indicates that there is at least one significant authentication bug, and possibly a misconfiguration of SSO settings for the service pages.

Tickets have been filled with Ex-Libris seeking clarification of SSO settings for service pages.

**Comment by mlooney** [comment]
Saving this here for posterity:

```
<p>
Pretend this is the item detail page for 9936710411802486
<div>
  <p>Rails current user: <%=current_user.inspect%>
</div>
</p>

<%-require 'cgi'%>
<%-item='9936710411802486'%>
<% prod_spu="https://na03.alma.exlibrisgroup.com/discovery/openurl?institution=01GALI_EMORY&vid=01GALI_EMORY:AlmaGeneralView&rft.mms_id=#{item}"%>

<%pdslogin="https://emory-primosb-alma.hosted.exlibrisgroup.com/primo_library/libweb/pdsLogin?targetUrl=#{CGI.escape(prod_spu)}"%>

<%mega_login="https://emory-primoprod.hosted.exlibrisgroup.com/pds?func=load-login&calling_system=primo&institute=01EMORY&lang=eng&url=#{pdslogin}"%>

<% auth_selector="https://emory-primoprod.hosted.exlibrisgroup.com/pds?func=load-login&calling_system=primo&institute=01GALI_EMORY&PDS_HANDLE=&url=http://discovere.emory.edu:80/primo_library/libweb/action/login.do?targetURL=http%3A%2F%2Fdiscovere%2Eemory%2Eedu%2Fprimo%5Flibrary%2Flibweb%2Faction%2Fsearch%2Edo%3Fvid%3Ddiscovere&dscnt=0&dstmp=1621367370430&initializeIndex=true" %>


<%abc="https://emory-primoprod.hosted.exlibrisgroup.com/pds?func=load-login&calling_system=primo&institute=01EMORY&lang=eng&isMobile=false&url=#{prod_spu}"%>

<%-the_thing="https://emory-primoprod.hosted.exlibrisgroup.com/pds?func=load-login&calling_system=primo&institute=01GALI_EMORY&PDS_HANDLE=&url=http://discovere.emory.edu:80/primo_library/libweb/action/login.do?targetURL=http%3A%2F%2Fdiscovere%2Eemory%2Eedu%2Fprimo%5Flibrary%2Flibweb%2Faction%2Fsearch%2Edo%3Fvid%3Ddiscovere&dscnt=0&dstmp=1621367370430&initializeIndex=true"%>

<%-prod_pds="https://emory-primoprod.hosted.exlibrisgroup.com/pds?func=load-login&url=https://emory-primoprod.hosted.exlibrisgroup.com/pds"%>

<%-hacked = "https://emory-primoprod.hosted.exlibrisgroup.com/pds?func=load-login&calling_system=primo&institute=01GALI_EMORY&PDS_HANDLE=&url=https://emory-primosb-alma.hosted.exlibrisgroup.com/primo_library/libweb/pdsLogin&targetURL=#{CGI.escape(prod_spu)}"%>
<%-sso='https://login.emory.edu/idp/profile/SAML2/Redirect/SSO'%>
<p><a href="<%=the_thing%>">lisas_thing</a>
<p><a href="<%=auth_selector%>">auth_selector</a>
<p><a href="<%=abc%>">abc</a>
<p><a href="<%=mega_login%>">mega</a>
<p><a href="<%=sso%>">sso</a>
<p><a href="<%=pdslogin%>">pdslogin</a>
<p><a href="<%=hacked%>">hacked</a>
<p><a href="<%=prod_pds%>">prod_pds</a>

```

**Comment by lisahamlett** [comment]
Screenshots for Ex Libris: 
[Shibboleth for the Alma Services Page.pdf](https://github.com/emory-libraries/blacklight-catalog/files/6504610/Shibboleth.for.the.Alma.Services.Page.pdf)

**Comment by eporter23** [comment]
Possibly tangential, but @AGCooper noted this alternate Alma view type that our prior developer Bernardo Gomez had configured a few years back. From this page, I do seem to be able to authenticate via Shibb successfully, and it routes me to the Primo login page and back to this Alma page. If others can investigate it may be helpful. https://emory-primosb-alma.hosted.exlibrisgroup.com/primo-explore/fulldisplay?docid=01EMORY_ALMA21220720890002486&context=L&vid=bernardo&lang=en_US&search_scope=default_scope&adaptor=Local%20Search%20Engine&tab=emory_catalog&query=any,contains,Critical%20perspectives%20on%20Harry%20Potter&offset=0

**Comment by lovinscari** [comment]
Josh W. responded by email referencing article https://developers.exlibrisgroup.com/alma/integrations/discovery/fulfillment_services/#authentication

**Comment by lovinscari** [comment]
This ticket is being closed as two different paths are being explored. One path will be by ExLibris Technical Services Team who will look at Shibboleth authentication issues with the Services Page, and the other by the Blacklight Scrum Team who will look at authentication when using the API's.
