### ISSUE TITLE
Revise fields in Basic Search - Title

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/blacklight-catalog#529]
This ticket follows a review in #325. If a field is not noted below, it needs no changes at this time.

**Revise existing mapping**

- [x] title_key_tesi (should allow multiples > title_key_tesi**m**)

**Add to Title search**

- [x] title_later_tesim (new field, copy of title_later_ssim used for display and hyperlinking)
- [x] title_series_tesim
- [x] title_key_tesim (see mapping note above)

**Remove from Title search**

- [x] title_graphic_tesim
- [x] title_ssort
- [x] title_series_ssim
- [x] title_details_display_tesim
- [x] title_display_tesim
- [x] subtitle_vern_display_tesim
- [x] subtitle_t

Note: some fields in this ticket may also be recommended to delete in #311.

**Comment by bwatson78** [comment]
@eporter23 `title_details_display_tesim` isn't inside Title Search. Is it safe to say that you'd like me to delete the fields referenced in #311 within the scope of this ticket?

- [ ] title_details_display_tesim
- [ ] subtitle_vern_display_tesim
- [ ] subtitle_t
- [ ] title_display_tesim
- [ ] title_graphic_tesim

**Comment by eporter23** [comment]
@bwatson78 I'd like to keep them intact for the moment and do a final check before we delete anything.

**Comment by bwatson78** [comment]
@eporter23 Some of those are not associated with Title Search at all, so I will take no action on them.

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/blacklight-catalog/pull/530

No screenshots necessary.

**Comment by lovinscari** [comment]
@eporter23 - Please close this issue if you are satisfied with the results. Thanks.

**Comment by eporter23** [comment]
@lovinscari looks good so far in Basic Search but I can't fully test on Advanced Search in test.

**Comment by lovinscari** [comment]
Keeping this ticket open until @eporter23 returns from vacation and can complete her testing in Advanced Search.

**Comment by eporter23** [comment]
Looks good @lovinscari and @bwatson78
