### ISSUE TITLE
Revise fields in Basic Search - Author/Creator

### ISSUE THREAD

**Issue by bwatson78** [emory-libraries/blacklight-catalog#531]
This ticket follows a review in #326. If a field is not noted below, it needs no changes at this time.

Revise existing mapping

- [x] author_display_ssim: switch extraction method to `extract_ordered_fields` so that values are ordered by subfield codes.
- [x] author_vern_ssim: switch extraction method to `extract_ordered_fields` so that values are ordered by subfield codes.

Add to Author/Creator search

- [x] note_participant_tesim
- [x] note_production_tesim
- [x] author_vern_tesim (Copy of the author_vern_ssim in text form.)

Remove from Author/Creator search

- [x] author_display_ssim

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/blacklight-catalog/pull/535

No screenshots necessary.

**Comment by lovinscari** [comment]
@eporter23 - Please close this issue if you are satisfied with the results. Thanks!

**Comment by eporter23** [comment]
@lovinscari same comment as for Title, tested a bit for Basic Search but can't test Advanced yet.

**Comment by lovinscari** [comment]
Keeping this open until @eporter23 returns from vacation and can test in Advanced Search.

**Comment by eporter23** [comment]
Looks good @bwatson78 @lovinscari
