### ISSUE TITLE
Revise fields in Basic Search - Subject

### ISSUE THREAD

**Issue by bwatson78** [emory-libraries/blacklight-catalog#532]
This ticket follows a review in #327. If a field is not noted below, it needs no changes at this time.

Revise existing mapping

- [x] subject_tsim: First, convert this to `subject_tesim` in all code the field is used. Then, update the mapping to pull all subfields of the datafields already mapped: `600a-z:610a-z:611a-z:630a-z:650a-z:651a-z:653a-z:654a-z:655a-z`

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/blacklight-catalog/pull/550

No screenshot necessary.

**Comment by eporter23** [comment]
@lovinscari same comments as for the other search revisions - these look good in Basic Search; pending testing in Advanced Search on test.

**Comment by lovinscari** [comment]
Keeping this open until @eporter23 returns from vacation so she can continue test in Advanced Search.

**Comment by eporter23** [comment]
@bwatson78 @lovinscari looks good
