### ISSUE TITLE
Revise volume and edition information for MLA 8 citations

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/blacklight-catalog#534]
**Story:** As a researcher, I want to see minimal but correctly formatted citation suggestions in the catalog, so that I can enhance them with additional information that I select in MLA 8 format

**Notes:**
This ticket follows the spike in #507 and #508 to investigate feasibility of enhancing multi-part information in automatically generated citations. Our general findings were that MARC data is often too unstructured to achieve the desired results programmatically, so at this time we are opting to remove some of these citation components.

**Revisions needed:**
- [ ] Remove the volume component ("Number" in MLA) from citation output
- [ ] Revise mapping for` title_display_partname_tesim `(245 $p) field or create a new field (`title_partinfo_citation_tesim`)
- Ensure that both subfields 245 $n (part number), 245 $p (part name) are included in the original source order from the MARC record. Sometimes $n precedes $p, and sometimes $p precedes $n, but it has a significance when read by users (see the example 1 below).
- If we revise the existing field, flag the unused `title_display_partnumber_ tesim` (245 n) field for deletion in #311
- [ ] As a related revision, ensure that `title_main_display_tesim` displays its mapped subfields in the original MARC subfield order
- [ ] Remove the edition/version component from the citation output (see example 2)
- [ ] Check punctuation: MLA 8 citations should always end with a period. Commas may separate some elements depending on which elements have been populated.

Simple citation format with volume and edition indicators removed

> Authorlastname, Authorfirstname. _Title Components._ Publisher, YYYY.

More complex citation format
> Authorlastname, Authorfirstname. _Title Components._ Title of Container, Publisher, YYYY, doi.

**Example 1: Sample record with part information**
https://blackcat-test.library.emory.edu/catalog/9936771726402486

245 0  0 
a| 60 minutes. p| President Ahmadinejad. n| Part one / c| produced by Robert G. Anderson.

Current output

![Screen Shot 2021-05-19 at 10.56.52 AM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/1198a06f-bd1e-4f7f-ba85-b545bfc25bdb)

Desired output

![Screen Shot 2021-05-19 at 10.56.57 AM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/f1e9f0d1-0e92-4a33-9785-e341ae7f325f)

**Example 2: Sample record with edition information**
https://blackcat-test.library.emory.edu/catalog/990036288900302486

Current output
![Screen Shot 2021-05-19 at 10.57.58 AM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/5cb39065-4956-4c55-9602-5381de5365e5)

Desired output (some revisions are pending work in #500)

![Screen Shot 2021-05-19 at 10.58.05 AM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/4005d503-eddd-48ec-b1ae-487d9a9025cb)

**Comment by lovinscari** [comment]
@alexBLR - When testing https://blackcat-test.library.emory.edu/catalog/9936771726402486 - I am no longer seeing the author name at the beginning of the citation. ![MLACitationNoAuthorShowing.png](https://images.zenhubusercontent.com/5c4a1fe1e9b5fb46bcedb9fc/a83d6d84-7937-43de-8be5-7c60275f091a). 

The other record https://blackcat-test.library.emory.edu/catalog/990036288900302486 seems to be fine so I am not sure what happened with the other one. I am testing both on Blackcat-test so I am not sure if perhaps reindexing has not finished. I am going to move this back into In Sprint so you can take a look but if this was due to reindexing feel free to move back To Accept and tag me so I can take another look.

**Comment by eporter23** [comment]
@alexBLR @lovinscari these changes look good, thanks!
