### ISSUE TITLE
Revise volume and edition information for APA 7 citations

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/blacklight-catalog#536]
Story: As a researcher, I want to see minimal but correctly formatted citation suggestions in the catalog, so that I can enhance them with additional information that I select in APA 7 format

This ticket follows the spike in #507 and #508 to investigate feasibility of enhancing multi-part information in automatically generated citations. Our general findings were that MARC data is often too unstructured to achieve the desired results programmatically, so at this time we are opting to remove some of these citation components. See also equivalent work in ticket #534 for MLA.

Revisions needed:

- [x] Remove volume component from citation output (see example 1)
- [x] Revise mapping for` title_display_partname_tesim `(245 $p) field or create a new field (`title_partinfo_citation_tesim`)
- Ensure that both subfields 245 $n (part number), 245 $p (part name) are included in the original source order from the MARC record. Sometimes $n precedes $p, and sometimes $p precedes $n, but it has a significance when read by users (see the example 1 below).
- If we revise the existing field, flag the unused `title_display_partnumber_ tesim` (245 n) field for deletion in #311
- [x] As a related revision, ensure that `title_main_display_tesim` displays its mapped subfields in the original MARC subfield order
- [x] Remove the edition/version component from the citation output (see example 2)
- [x] Punctuation: ensure that the removal of elements does not break punctuation or formatting other requirements. See the formatting examples for APA 7 citations below.

Simple citation format

> Authorlast, F. M. (YYYY). _Title: The subtitle components._ Publisher Name.

More complex citation format

> Authorlast, F. M. (YYYY). _Title: The subtitle components_. Publisher Name. doi

**Example 1: Sample record with part information**
https://blackcat-test.library.emory.edu/catalog/9936771726402486

245 0  0 
a| 60 minutes. p| President Ahmadinejad. n| Part one / c| produced by Robert G. Anderson.

Current output

![Screen Shot 2021-05-19 at 12.55.29 PM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/ef0abab8-a0bc-4f2c-9d5c-eb21c5d0bd2a)

Desired output

![Screen Shot 2021-05-19 at 12.55.54 PM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/87b66ed4-3945-49f3-b1c9-bfc9a10efd8f)

**Example 2: Sample record with edition information**

https://blackcat-test.library.emory.edu/catalog/990036288900302486

Current output

![Screen Shot 2021-05-19 at 12.57.10 PM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/b35b0794-141a-43f8-8a26-adbfd0112567)

Desired output

![Screen Shot 2021-05-19 at 12.57.40 PM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/645fa5f5-beb4-4bc6-81db-37927a49475f)

**Comment by bwatson78** [comment]
@eporter23 Placed `title_display_partname_tesim` and `title_display_partnumber_tesim` in #311 to have them considered for deletion.

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/blacklight-catalog/pull/556

![Screen Shot 2021-05-20 at 4.06.14 PM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/2ae08b6f-1805-4209-8363-cf5d6971ee52)
![Screen Shot 2021-05-20 at 4.07.13 PM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/fe69a9c2-bc76-4c99-a465-9355971929a7)

**Comment by lovinscari** [comment]
I need to review this with @eporter23 when she returns from vacation as there seems to be some confusion (could just be me).

**Comment by eporter23** [comment]
@bwatson78 @lovinscari looks good to me!
