### ISSUE TITLE
AWS Cost Management: Remove US East OH RDS components

### ISSUE THREAD

**Issue by libdgg** [emory-libraries/blacklight-catalog#540]
Per ticket #516 we have confirmed there are no known depdendencies on US East OH. With Blacklight running in another region we can decommission AWS services/components to save costs.

Review the following information to confirm there is no impact to decommission and then execute decommission.

**Using the April 2021 bill here is what is running in US East (OH) = $191.41**  

**EC2 / EBS (Elastic Block Store) $18** 

- **Amazon Elastic Compute Cloud running Linux/UNIX$0.55** 
- NOTE: https://us-east-2.console.aws.amazon.com/ec2/v2/home?region=us-east-2#Instances: 
- STATE: Currently stopped 
- $0.0832 per On Demand Linux t3.large Instance Hour282.516 Hrs$23.51 
- t3.large Linux instance usage covered by Compute Savings Plans280.516 Hrs-$23.34 
- $0.1664 per On Demand Linux t3.xlarge Instance Hour282.201 Hrs$46.96 
- t3.xlarge Linux instance usage covered by Compute Savings Plans279.910 Hrs-$46.58 
- **EBS $18.32** 
- NOTE: https://us-east-2.console.aws.amazon.com/ec2/v2/home?region=us-east-2#Volumes:sort=desc:createTime 
- STATE: in-use 
- $0.05 per GB-Month of snapshot data stored - US East (Ohio)6.433 GB-Mo$0.32 
- $0.10 per GB-month of General Purpose SSD (gp2) provisioned storage - US East (Ohio)180.000 GB-Mo$18.00 

**ELB $16.47** 
- Elastic Load Balancing – Application $16.47 
- NOTE: https://us-east-2.console.aws.amazon.com/ec2/v2/home?region=us-east-2#LoadBalancers:sort=loadBalancerName 
- STATE: active 
- $0.008 per used Application load balancer capacity unit-hour (or partial hour)33.919 LCU-Hrs $0.27 
- $0.0225 per Application LoadBalancer-hour (or partial hour)720.000 Hrs$16.20 

**RDS $84.94** 
- Amazon Relational Database Service for MySQL Community Edition $73.44 
- NOTE: https://us-east-2.console.aws.amazon.com/rds/home?region=us-east-2#databases: 
- STATE: stopped 
- USD 0.034 per db.t3.small Single-AZ instance hour (or partial hour) running MySQL720.000 Hrs$24.48 
- USD 0.068 per db.t3.medium Single-AZ instance hour (or partial hour) running MySQL720.000 Hrs$48.96 
- Amazon Relational Database Service Provisioned Storage $11.50 
- $0.115 per RDS GB-month of provisioned GP2 storage100.000001 GB-Mo $11.50 

**VPC $72** 
- No Instance Type  
- NOTE: https://us-east-2.console.aws.amazon.com/vpc/home?region=us-east-2#vpcs: 
- STATE: Available 
- $0.05 per VPN Connection-Hour1,440.000 Hrs $72.00

**Comment by libdgg** [comment]
Starting work on this today.

**Comment by libdgg** [comment]
@rotated8 @mark-dce @oraposa @mlooney @libah @AGCooper 

Below are the items I plan to delete for items in US East (Ohio) us-east-2

Please let me know (i.e. approve) this plan unless you see anything I should not remove or if you want to touch base to walk through this plan with me first. If there are things I should hold off on please identify them. Please let me know if you have any questions, concerns or suggestions. Thanks -Doug

TERMINATE 2 EC2 INSTANCES (currently stopped)
old-blacklight-solr-arch.library.emory.edu
old-blackcat-arch.library.emory.edu

DELETE 2 VOLUMES
blacklight-arch.library.emory.edu
blacklight-arch.library.emory.edu

DELETE 3 KEY PAIRS
blackcat_key
my_test
thekey

DELETE 8 SECURITY GROUPS
Blacklight_EFS_SG
Blacklight_Arch_Solr_SG
Solr_UI
Blacklight_SG
Blacklight_MySQL_SG

DELETE 1 ELB
Blackcat-ELB

DELETE 3 SNAPSHOTS 
3 snapshots dated January 25, 2021


DELETE 2 RDS Databases
blackcat-arch db.t3.small
blacklight db.t3.medium

DELETE 3 RDS Database Snapshots
blacklightshutdown May 11, 2021, 8:45:25 PM UTC
blackcatarchshutdown May 11, 2021, 8:45:00 PM UTC 
rds-launched-in-disallowed-subnet-2020-10-27-105316 October 27, 2020, 2:59:59 PM UTC

DELETE 8 RDS Database - Automatic snapshots
rds:blacklight-2021-06-01-07-41
rds:blacklight-2021-05-31-07-41
rds:blacklight-2021-05-30-07-40
rds:blacklight-2021-05-29-07-41
rds:blacklight-2021-05-28-07-41
rds:blacklight-2021-05-27-07-41
rds:blacklight-2021-05-26-07-41
rds:blacklight-2021-05-25-07-40

DELETE 1 RDS Database Subnet Group
blacklight_subnet_group

**Comment by rotated8** [comment]
@libdgg I'd like to confirm that deleting the blackcat_key and the security groups will only affect us-east-2. @mlooney- can you weigh in? Other than that, I'm 👍

**Comment by libdgg** [comment]
This ticket is complete. The remaining work will be in a second ticket to remove the VPC (which should also make it possible to delete the security, option and parameter groups or at least reveal when/how to remove them since AWS won't let me delete them without addressing how they are associated).

I am leaving the snapshots as well until I delete the VPC if possible just in case.

I'll create a new ticket for the next step.
