### ISSUE TITLE
AWS Cost Management: Implement Cost Savings Measures

### ISSUE THREAD

**Issue by libdgg** [emory-libraries/blacklight-catalog#543]
Per ticket #516, this work will focus on implementing AWS cost savings measures such as reserved instances. inputs for this work are the preliminary findings that our costs run about $2500 per month and have stable blocks of services. Other tickets that need to complete prior to this will determine if there are services in the "Other category that can be removed and that monthly monitoring of costs is in place and that costs continue to show stability with no spikes or large fluctuations.

**Comment by lovinscari** [comment]
Moving this under leadership responsibilities and out of backlog for the product.
