### ISSUE TITLE
Modify search results statement if no results are found

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#546]
As the product owner, I would like for the end user to be presented with a statement indicating no results found as shown on the following wireframe:

[No Results Wireframe](https://www.figma.com/file/ocSo3KytI6GgwjalSVAmE1/Blacklight-Wireframes?node-id=84%3A19)

Acceptance Criteria:

- [ ] If a search implemented by a user produces no results, the user should be presented with the statement "No results found..." as shown in the wireframe.

**Comment by eporter23** [comment]
We think the current behavior is good enough and closely matches the wireframe.

![Screen Shot 2021-05-20 at 11.33.30 AM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/86460e6d-f27b-474c-a7ca-98a973620d41)
