### ISSUE TITLE
Refine sorting options on Search Results pages (Sort by Year)

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#547]
As the product owner, I would like the sorting options on the search results page to reflect that shown in the following wireframe:

[Relevance and Sorting Wireframe](https://www.figma.com/file/ocSo3KytI6GgwjalSVAmE1/Blacklight-Wireframes?node-id=92%3A2581)

The associated metadata fields for the sort options are contained in the [Google Doc](https://docs.google.com/document/d/10NM4F11wWXGMvIjDBocrVxZfQz4h6om3l2CWrNWkNYY/edit) - focussing on the "Sort Options" section only for this ticket.

Acceptance Criteria:

- [ ] Sort Options to appear in a drop-down list allowing the end user to select one of the sort by options of Year (Oldest), Year (Newest)

- [ ] Based on the selection, the results should be sorted by year (or the beginning of the value, if it contains more than a year) according to the selection based on associated Solr field selection. 

SOLR and Indexing

- Use the same logic to extract dates as we do in `pub_date_ssim` (date facet field)
- The extracted date should be normalized to a sortable numeric value
- If a single value start date field is needed, create a new sort-specific field as needed based on `pub_date_ssim`
- If an end date field is needed, create a new sort-specific field as needed based on `pub_date_ssim`

**Comment by eporter23** [comment]
@devanshu-m @lovinscari looks great with basic testing, but I will also do a little more to test more complex options like a date range.

**Comment by lovinscari** [comment]
@eporter23 - As discussed during demo yesterday - I am going to close this issue as the basic requirements are met. As we are completing additional testing we can create new tickets for any refinements.
