### ISSUE TITLE
Create new view in Primo to show Central Discovery Index records only

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#548]
Based on feedback from the investigation around this request, please implement the following steps in order to show a view from Primo reflecting only the records from the Central Discovery Index. This work is needed to provide users with access to Articles+ (from CDI) until Phase 2 of the project is completed. 

Acceptance Criteria:

- [x] Create a new view in Primo showing only records from Central Discovery Index based on that shown in the [Sandbox](http://discoveretest.emory.edu/primo_library/libweb/action/search.do?vid=cdi)

- [x] Change the name of view (page) to Articles +

- [x] Change the logo the Emory Libraries logo

- [x] Remove thumbnails from the records shown since thumbnails will not be available in Blacklight

- [x] Remove the Browse Search option but keep Advanced Search

- [x] Update styling according to notes provided by Norm in the [Google Doc](https://docs.google.com/document/d/19GW39zaWWUesRW4f7Xm7iH7jD-BHwT7lMMWaN2EGjqk/edit#). Please work with Norm if there are questions about the styling needed.

- [x] If possible, provide a link in the header to return to Blacklight Catalog (work with Norm on styling for this).

**Comment by norm0** [comment]
[Homepage/Search ](Page(http://discoveretest.emory.edu/primo_library/libweb/action/search.do?vid=cdi))
![screencapture-discoveretest-emory-edu-primo-library-libweb-action-search-do-2021-06-04-16_09_10.png](https://images.zenhubusercontent.com/5f8492d49b473a0cef37940f/beb2e906-5782-439a-a9ae-cb2fefedbd69)

[Search Results](http://discoveretest.emory.edu/primo_library/libweb/action/display.do?tabs=detailsTab&ct=display&fn=search&doc=TN_cdi_webofscience_primary_000180445700009CitationCount&indx=1&recIds=TN_cdi_webofscience_primary_000180445700009CitationCount&recIdxs=0&elementId=0&renderMode=poppedOut&displayMode=full&frbrVersion=&frbg=&&dscnt=0&scp.scps=scope%3A%28CDI%29%2Cprimo_central_multiple_fe&mode=Basic&vid=cdi&srt=rank&tab=default_tab&vl(freeText0)=pizza&dum=true&dstmp=1622840958873)
![screencapture-discoveretest-emory-edu-primo-library-libweb-action-search-do-2021-06-04-16_09_21.png](https://images.zenhubusercontent.com/5f8492d49b473a0cef37940f/b1c49749-faa9-425b-8288-894df28e918d)

[Single Item View](http://discoveretest.emory.edu/primo_library/libweb/action/display.do?tabs=detailsTab&ct=display&fn=search&doc=TN_cdi_webofscience_primary_000180445700009CitationCount&indx=1&recIds=TN_cdi_webofscience_primary_000180445700009CitationCount&recIdxs=0&elementId=0&renderMode=poppedOut&displayMode=full&frbrVersion=&frbg=&&dscnt=0&scp.scps=scope%3A%28CDI%29%2Cprimo_central_multiple_fe&mode=Basic&vid=cdi&srt=rank&tab=default_tab&vl(freeText0)=pizza&dum=true&dstmp=1622840958873)
![screencapture-discoveretest-emory-edu-primo-library-libweb-action-display-do-2021-06-04-16_09_33.png](https://images.zenhubusercontent.com/5f8492d49b473a0cef37940f/6ab0734f-8e41-4067-aea7-572adbeb8772)

**Comment by eporter23** [comment]
@norm0 @libah @CB987 really nice! I was clicking around on this and noticed the "Return to Library Catalog" link actually sent me to the Libraries homepage. @lovinscari I assume this should take us back to blacklight?

![Screen Shot 2021-06-07 at 2.34.47 PM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/016d04b8-af42-41a3-b2d7-001338caf747)

**Comment by norm0** [comment]
@eporter23 it should be I didn't want to assume what should go there.  @lovinscari  Good catch!

**Comment by lovinscari** [comment]
This looks really good! Thanks to all of you for your work on this!
