### ISSUE TITLE
Suppress the Collections Facet on Advanced Search Page to improve performance

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#549]
Based on testing performed in ticket [#510 ](https://app.zenhub.com/workspaces/blacklight-catalog-5f5f84a8a6d29939a0bc5d78/issues/emory-libraries/blacklight-catalog/510), the performance of advanced search improved significantly when the Collections Facet was removed. In an effort to improve immediate performance, I would like for the Collections Facet to be suppressed as additional work (post-beta) may determine that improvements made to caching could allow for the Collections Facet to be shown in the future.

Acceptance Criteria:

- [ ] Suppress the Collections Facet on the Advanced Search page so it no longer appears as an option for advanced search.

**Comment by eporter23** [comment]
@lovinscari Looks good on arch, but still needs to be deployed to test.

**Comment by lovinscari** [comment]
Tested on blackcat-test and performance is significantly improved by removing the Collections Facet. I will make note of this when I provide a demonstration about Advanced Search.
