### ISSUE TITLE
Add Blackcat-Arch to Alma IPs

### ISSUE THREAD

**Issue by rotated8** [emory-libraries/blacklight-catalog#55]
In order to import records from Alma into Solr, we need to add it's IP address.

- [x] Get blackcat-arch ip address from @mprefer or @SolomonHD 
- [x] Add that address to Alma, so we can import records from it.

**Comment by mprefer** [comment]
blackcat arch: 10.65.121.227
blackcat arch solr: 10.65.121.251

**Comment by devanshu-m** [comment]
Correct IP addresses were added to the alma allowed list. Thanks @lisahamlett @SolomonHD 

Moving in to accept again.
