### ISSUE TITLE
Refine sorting options on Search results and Advanced Search Page

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#551]
As the product owner, I would like the sorting options on the Search results and Advanced Search pages to reflect that shown in the following wireframe:

[Relevance and Sorting Wireframe](https://www.figma.com/file/ocSo3KytI6GgwjalSVAmE1/Blacklight-Wireframes?node-id=92%3A2581)

The associated metadata fields for the sort options are contained in the [Google Doc](https://docs.google.com/document/d/10NM4F11wWXGMvIjDBocrVxZfQz4h6om3l2CWrNWkNYY/edit) - focussing on the "Sort Options" section only for this ticket.

See also individual tickets for sorting by Title, Year, and Author.

Acceptance Criteria:

- [x] Sort Options to appear in a drop-down list allowing the end user to select one of the sort by options shown in the wireframe and documents above.

- [x] Based on the selection, the results should be sorted according to the selection based on associated Solr field selection.

**Comment by bwatson78** [comment]
It seems that all of the Sorting Options inherit from the main options set in previous tickets. I will make one change to title-ize the Relevance label.

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/blacklight-catalog/pull/573
![Screen Shot 2021-05-26 at 10.42.31 AM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/0c0eb1fe-6649-4540-9b41-5a97813e0ef6)

**Comment by lovinscari** [comment]
Looks good!
