### ISSUE TITLE
Refine sorting options for Title

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/blacklight-catalog#554]
As the product owner, I would like the  sorting options on the Advanced Search page to reflect that shown in the following wireframe:

[Relevance and Sorting Wireframe](https://www.figma.com/file/ocSo3KytI6GgwjalSVAmE1/Blacklight-Wireframes?node-id=92%3A2581)

The associated metadata fields for the sort options are contained in the [Google Doc](https://docs.google.com/document/d/10NM4F11wWXGMvIjDBocrVxZfQz4h6om3l2CWrNWkNYY/edit) - focussing on the "Sort Options" section only for this ticket.

See also the sort behavior used in Lux.

Acceptance criteria: 
Expand options for sorting by Title so that users can sort 
- alphabetically, e.g. starting with titles beginning with A first

- alphabetically, e.g. starting with titles beginning with Z first

SOLR and indexing notes:
- Base the sort on the values used in the  `title_main_display_tesim field` (at a minimum, including 245ab)
- Review mappings and usage of the existing `title_ssort` field and determine if we can use this
- If a new field is needed, ensure that initial articles are removed (including A, An, The): there appears to be a method for this in Traject already

**Comment by eporter23** [comment]
@alexBLR @lovinscari looks great!

**Comment by lovinscari** [comment]
Great job!
