### ISSUE TITLE
Refine sorting options for Author/Creator (placeholder ticket)

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/blacklight-catalog#555]
As the product owner, I would like the  sorting options on the Advanced Search page to reflect that shown in the following wireframe:

[Relevance and Sorting Wireframe](https://www.figma.com/file/ocSo3KytI6GgwjalSVAmE1/Blacklight-Wireframes?node-id=92%3A2581)

The associated metadata fields for the sort options are contained in the [Google Doc](https://docs.google.com/document/d/10NM4F11wWXGMvIjDBocrVxZfQz4h6om3l2CWrNWkNYY/edit) - focussing on the "Sort Options" section only for this ticket.

See also the sort behavior used in Lux.

Acceptance Criteria:

- [x] Sort Options appear in a drop-down list allowing the end user to select from author sort options:  Author (A-Z), Author (Z-A).
- [ ] The sorting should be based on the primary author's name (typically entered as last name, first, or as a corporate/organization name) 
- [ ] Based on the selection, the results should be sorted alphabetically from A or Z, working from the beginning of the name entry as indexed

Example for testing:

SOLR and Indexing

- The sort value should be the primary author, which is currently stored in multiple fields (`author_display_ssim` or `author_tesim`)
- Leading articles should be omitted (e.g. A, An, The)
- Determine how to handle vernacular authors
- Recommend we look at creating a sort-friendly version or investigate how these fields are configured: `author_si`

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/blacklight-catalog/pull/566

![Screen Shot 2021-05-25 at 1.38.30 PM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/8771cf8a-cc45-4f9c-8810-54b87ab999ff)

**Comment by eporter23** [comment]
@bwatson78 @lovinscari looks great to me!

**Comment by lovinscari** [comment]
Great job!
