### ISSUE TITLE
Fix indexing errors related to pub_date_isim field (BUG).

### ISSUE THREAD

**Issue by bwatson78** [emory-libraries/blacklight-catalog#558]
While processing the `blacklighttemp` OAI set, errors were found related to records 9936520934202486, 990015672450302486, and 990025965030302486. The errors seem to be related to attempting to index that field with string values.
Errors are listed here: [https://app.zenhub.com/files/295449627/75c49a9f-5133-43a2-a1af-d0fbe5039abf/download](https://app.zenhub.com/files/295449627/75c49a9f-5133-43a2-a1af-d0fbe5039abf/download)

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/blacklight-catalog/pull/560

No screenshots necessary.

**Comment by lovinscari** [comment]
Tested records referenced and all looks good to me.
