### ISSUE TITLE
Update Blacklight Print stylesheets

### ISSUE THREAD

**Issue by norm0** [emory-libraries/blacklight-catalog#561]
With the current update to the styles to the Blacklight the print styles on the Single Item Display are broken or addition. Chat with @norm0 if there are any questions

- [x] Remove or hide footer on print stylesheets
- [x] Confirm other pieces are also removed

**Comment by bwatson78** [comment]
@norm0 You ok with me taking this?

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/blacklight-catalog/pull/578

[https://app.zenhub.com/files/295449627/73dc7e57-c6ad-453c-87c1-095fbe7b3e6a/download](https://app.zenhub.com/files/295449627/73dc7e57-c6ad-453c-87c1-095fbe7b3e6a/download)

**Comment by lovinscari** [comment]
Looks great!
