### ISSUE TITLE
Update Notifications styles

### ISSUE THREAD

**Issue by norm0** [emory-libraries/blacklight-catalog#568]
Update notifications styles to match [Pattern Library](https://template.library.emory.edu/styleguide/patternlibrary/patternlab/1.0.8/?p=viewall-molecules-messaging) Notifications.

![Screen Shot 2021-05-25 at 14.33.14.png](https://images.zenhubusercontent.com/5f8492d49b473a0cef37940f/5bc6f5d5-c8ac-4c98-8cea-5064f5a8287f)

![Screen Shot 2021-05-25 at 14.34.30.png](https://images.zenhubusercontent.com/5f8492d49b473a0cef37940f/0d74a886-2d72-4e9f-9e85-d9a280554305)

![Screen Shot 2021-05-25 at 14.34.52.png](https://images.zenhubusercontent.com/5f8492d49b473a0cef37940f/0bdcb463-19e3-43ff-9e4a-1f583ac09266)

![Screen Shot 2021-05-25 at 14.35.30.png](https://images.zenhubusercontent.com/5f8492d49b473a0cef37940f/f2df7c37-dbf2-439b-a919-d36c3234fad5)

![Screen Shot 2021-05-25 at 14.33.46.png](https://images.zenhubusercontent.com/5f8492d49b473a0cef37940f/f9a482cc-c720-42cc-ab6b-b9e5e94c5264)

**Comment by bwatson78** [comment]
@norm0 These are the alerts styled to the notification spec (1-to-1 as far as type:

`alert-info`
![Screen Shot 2021-05-27 at 12.57.10 PM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/c6d3e710-b8a1-4740-92dc-0165f30bd1df)
'alert-success`
![Screen Shot 2021-05-27 at 12.58.19 PM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/b8e7e200-a997-4af7-9a4f-105f064663ab)
`alert-warning`
![Screen Shot 2021-05-27 at 12.58.52 PM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/0b8b6f64-67f3-4b5f-b8e8-d57aa62a4e31)
`alert-danger`
![Screen Shot 2021-05-27 at 12.59.19 PM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/f8bc1bac-33fb-4675-bf18-402efe93e38b)
default
![Screen Shot 2021-05-27 at 12.59.44 PM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/dc446f08-7256-4692-bd95-11e0ff054a33)

**Comment by bwatson78** [comment]
@norm0 I'm guessing you meant a different styling for `success`. Is that right?

**Comment by bwatson78** [comment]
@norm0 Probably this one:
![Screen Shot 2021-05-27 at 12.59.44 PM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/b6b91f5d-26b0-4846-b3b7-4d526e9b755b)

**Comment by norm0** [comment]
@bwatson78 I'm happy with the green unless useability testing says otherwise (https://template.library.emory.edu/styleguide/patternlibrary/patternlab/1.0.8/?p=viewall-molecules-messaging)

**Comment by bwatson78** [comment]
@norm0 Thanks

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/blacklight-catalog/pull/584

`info`
![Screen Shot 2021-06-01 at 2.52.46 PM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/5de09821-68cc-48e5-957e-bcc42bebc147)
`success`
![Screen Shot 2021-06-01 at 2.53.26 PM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/ba1eb75e-5da8-4bc4-931f-aad4fc695a65)
`warning`
![Screen Shot 2021-06-01 at 2.53.47 PM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/fe2667b2-c6dc-4ba2-b9e6-e3a47ed70d66)
`danger`
![Screen Shot 2021-06-01 at 2.54.04 PM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/0143c22a-d24d-427e-b13b-5362330cdde2)
default
![Screen Shot 2021-06-01 at 2.54.29 PM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/4c2fd664-6f2f-49ce-8089-ccf40c31828a)

**Comment by lovinscari** [comment]
Great work!
