### ISSUE TITLE
Update Bookmark Page Citation tool UI/UX design

### ISSUE THREAD

**Issue by norm0** [emory-libraries/blacklight-catalog#569]
Citation tools within blacklight bookmarks needs a way to stand out. Its currently just floating without context or information about what it is.

![Screen Shot 2021-05-25 at 14.37.52.png](https://images.zenhubusercontent.com/5f8492d49b473a0cef37940f/ecdd7c39-2f82-47b7-a940-81565b63c173)

Acceptance:
- [x] Mockup or screenshot of possible solutions for discussion
- [x] Meet and discuss solutions and way forward

**Comment by norm0** [comment]
Moved to #694

**Comment by norm0** [comment]
Ideal citation layout:
![screencapture-localhost-3000-bookmarks-2021-06-30-12_09_57](https://user-images.githubusercontent.com/8102/124003242-5179e280-d99c-11eb-9837-d3d89b8d19b0.png)

**Comment by norm0** [comment]
Markup and styles in this branch

**Comment by norm0** [comment]
Branch: https://github.com/emory-libraries/blacklight-catalog/tree/style_bookmarks_citation_694

Notes:
- cite in this branch is missing the functionality 
- if the RIS export function is used, this design might need adjustments.

**Comment by lovinscari** [comment]
Blocked until bug #760 is resolved.

**Comment by lovinscari** [comment]
I am going to accept this as it met Norm's requirements but I am going to ask for a refinement as this is an action button (similar to search and login) therefore should follow the same pattern with the blue background and white text.
