### ISSUE TITLE
Citations should be sorted by type not per book

### ISSUE THREAD

**Issue by norm0** [emory-libraries/blacklight-catalog#570]
When a user collects or bookmarks their selections, they should be able to view the citation framework by type(MLA, APA) rather than by individual book. See example below of incorrect formatting for three books...

NO:
![Screen Shot 2021-05-25 at 14.43.32.png](https://images.zenhubusercontent.com/5f8492d49b473a0cef37940f/9f80da50-9e96-439b-8a49-5762f6ee595a)

YES: 
![Screen Shot 2021-05-25 at 14.47.20.png](https://images.zenhubusercontent.com/5f8492d49b473a0cef37940f/a4ae68ef-a1b2-4eec-9d31-f8b0857f9c10)

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/blacklight-catalog/pull/580

![Screen Shot 2021-05-26 at 4.27.52 PM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/d8aba410-61de-43d5-97a7-bdc84d56f014)
![Screen Shot 2021-05-26 at 4.28.09 PM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/65530798-2d86-4b9d-9707-f58108b3135e)

**Comment by eporter23** [comment]
@bwatson78 @norm0 @lovinscari looks very good - nice enhancement.

**Comment by lovinscari** [comment]
Great job!
