### ISSUE TITLE
Refine responsive views on header

### ISSUE THREAD

**Issue by norm0** [emory-libraries/blacklight-catalog#574]
Some UI elements are not displaying on smaller screen sizes(tablets, phones). 

1. Top navbar navigation doesn't show up in the hamburger menu when opened (see figure 1b)
2. Search bar isn't displaying full width when it should be
3. Advanced search should have even padding above and below on smaller screens

Figure 1a ![Header-Responsive notes 05:26:2021.jpg](https://images.zenhubusercontent.com/5f8492d49b473a0cef37940f/dcad028d-9dd5-4f85-b8e0-e44c4bf830e6)

Figure 1b. ![Screen Shot 2021-05-26 at 09.55.37.png](https://images.zenhubusercontent.com/5f8492d49b473a0cef37940f/b5406449-c3c2-4a53-b2af-c2c1882e71e2)

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/blacklight-catalog/pull/630
![Screen Shot 2021-06-07 at 11.33.35 AM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/832f57eb-4530-4057-a5a0-67cea4945eaf)
