### ISSUE TITLE
Revise search navigation breakpoint

### ISSUE THREAD

**Issue by norm0** [emory-libraries/blacklight-catalog#576]
Sorting/Per Page navigation is overlapping and congested at md screen sizes (see figure 1a). The breaking point should be larger size so that the two dropdowns don't overlap.

Figure 1a:
![Screen Shot 2021-05-26 at 10.19.39.png](https://images.zenhubusercontent.com/5f8492d49b473a0cef37940f/c6838627-6a0d-4944-a800-e69fb071bc3c)

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/blacklight-catalog/pull/587
![Screen Shot 2021-06-02 at 12.29.30 PM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/f530f298-daaa-42a7-a08b-d1b2c8781728)
![Screen Shot 2021-06-02 at 12.29.57 PM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/91daa30f-df22-4fc2-b0ab-1181270a934a)
![Screen Shot 2021-06-02 at 12.30.12 PM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/a080fa7d-cb06-4885-a3b5-8b8ec701523f)
![Screen Shot 2021-06-02 at 12.30.24 PM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/ec3e8b85-acde-446d-b338-a440b6943580)

**Comment by lovinscari** [comment]
@norm0 - let's review this during the wireframes meeting on 6/9/21
