### ISSUE TITLE
SPIKE: Determine scope of items available for checkout (e.g., laptops) to determine if equipment resources are clearly categorized

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#58]
As a product owner, I would like to look specifically at equipment resources imported into the Solr Index from the OAI-PMH publishing report from Alma in order to determine if equipment resources are clearly categorized so that it can be determined which equipment resources should appear in the catalog versus those that are used solely for check-out purposes. 

- [ ] Product Owner with subject matter experts reviews the human readable report from Issue #56 that looks specifically at content types from the index to determine which items are for check-out only and should not appear in the catalog.

- [ ] Development team determines how records can be suppressed in Blacklight

**Comment by lisahamlett** [comment]
MMSID / 001 fields for some suppressed items in the blacklight subset (the first two are equipment):
990034703300302486
9936767178802486
9937017175002486

**Comment by bwatson78** [comment]
It isn't obvious what fields will provide us with the most definitive classifier for non-searchable equipment. Of the three provided, the field that one would believe would give the best indication is misleading:

format: "Book", "Unknown", and "Musical Score".

The last object has a key of "subject_t" populated with "Electronic books", but that is the only object of the three with that key present. 

There are more "unapparent" similarities that dive into the "marc_display" attributes of each Solr record. After a conversation with @AGCooper, @devanshu-m, and @lisahamlett, the current state of what we receive from Alma may need to be modified to better be able to determine what items should be cataloged.

**Comment by bwatson78** [comment]
After standup, the best approach to getting a clear denotation of what each item categorizes as is to have a meeting between our Software Engineering staff and catalogers. @lisahamlett has volunteered to schedule a meeting with a cataloger and will include @devanshu-m, @AGCooper, and myself as required, and @mark-dce, @RachelDCE, and @rotated8 as optionals.
