### ISSUE TITLE
AWS Cost Management: Cloudwatch cost identification

### ISSUE THREAD

**Issue by libdgg** [emory-libraries/blacklight-catalog#585]
Per ticket #541, this is a ticket for a deeper look into the Cloudwatch costs. They are one of the largest costs in the reports for AWS Blacklight costs. However, Cloudwatch is used by both DLP and Blacklight. The costs are generally stable but hight. This ticket will identify details of the Cloudwatch costs to confirm that it is setup as expected and if anything needs to be adjusted for Blacklight and/or any follow-up with DLP costs outside of the Blacklight project.

**Comment by lovinscari** [comment]
Moving this under leadership responsibilities and out of backlog for the product.
