### ISSUE TITLE
Revise metadata fields shown on search results

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/blacklight-catalog#589]
_As an end user, I want to preview critical information about resources that turn up in a search, so that I can differentiate between items by date, edition, or publication information_

Acceptance criteria

- [x] [See wireframe](https://www.figma.com/file/ocSo3KytI6GgwjalSVAmE1/Blacklight-Wireframes?node-id=92%3A2763)
- [x] Show the same fields and field labels used at the top of the single item view page (see ticket #310 )
- [x] Use the same display logic as indicated in ticket #310 
- [x] Use fonts and sizes appropriate to the search results layout (relative heading sizes, etc.)

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/blacklight-catalog/pull/632

![Screen Shot 2021-06-07 at 1.53.02 PM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/bfb51f1a-50a5-444b-9214-2ada7364d15d)

**Comment by eporter23** [comment]
I'm not seeing Edition showing up, was this field added? Examples:
https://blackcat-arch.library.emory.edu/catalog/990009983790302486

You can see the edition statement on the view item detail, but not in the listing.

**Comment by bwatson78** [comment]
@eporter23 My apologies, that's my blunder, I will circle back to this tomorrow.

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/blacklight-catalog/pull/646
![Screen Shot 2021-06-10 at 10.02.22 AM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/b869e655-15a5-4842-be5c-33772fc0c871)

**Comment by eporter23** [comment]
Looks good, thanks @bwatson78!
