### ISSUE TITLE
Alma API Configurations for OpenURL Requests

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#59]
As the product owner, I want to ensure Alma API's are properly configured in order to meet the functionality identified below.

- [ ] A form in Blacklight can send an OpenURL request to the Alma resolver, to determine what version(s) of an online article or other content may be available to me so I can discover availability of articles based on citations

**Comment by tmiles2** [comment]
Theme: Request
Note: There maybe more than one epic this applies to: AEON or Aeres

**Comment by lovinscari** [comment]
I suspect this will be resolved through other issues but am keeping this in Post Beta Refinements to be used as a functional test.

**Comment by lovinscari** [comment]
This will be handled as part of the API integration and the integration with ILL, Aeon, and Course Reserves
