### ISSUE TITLE
Teach out on how relevancy is configured in Blacklight

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#590]
@mark-dce has been asked to complete a teach-out for the product owner and application developers with general information about how relevancy is configured in Blacklight and how relevancy might be customized in the future. The teach-out will also address how fuzzy search is associated with relevancy. 

Acceptance Criteria:

- [ ] Schedule a meeting for the teach-out conducive to @mark-dce availability with the assumption the teach-out can be recorded for any unable to attend 
- [ ] Design the relevancy teach out
- [ ] Complete a teach-out that explains the basic relevancy configuration in Blacklight and how it might be customized in the future. The teach-out should also include information about fuzzy search and how it is associated with relevancy.

Topics to include (not exhaustive)
* Understanding of current relevancy configuration (teach out)
* Spike - Determine what customization is possible based on user stories
* Fuzzy Search Refinement (move into relevancy)
* Revisit fuzzy search to determine if any “tweaks” are possible based on user stories (app dev)

**Comment by mark-dce** [comment]
Deck from today's presentation https://docs.google.com/presentation/d/103NRpVzK0ZpO58pFNmL8DGp6thG_-HVkGnw5o8tm-xw/edit#slide=id.gdf39b0f82c_0_278
