### ISSUE TITLE
Spike: Determine any customizations for relevancy and fuzzy search after teach-out

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#591]
After the teach-out on relevancy, the application developers are asked to determine what customization is needed to address the following user stories around relevancy and fuzzy search:

**Relevancy:**

- If my search word or phrase exactly matches the title of a resource, I want to have that higher in the ranking of search results.  Same is true if I am searching on a title commonly known but appearing differently on the title page (i.e. "uniform title") so titles or phrases that are common don't cause me to have to wade through irrelevant results, e.g. reviews or books about the book I'm seeking.

- When I search for a foreign language title (such as a book or movie), I want the common English titles to appear in the first-level search results because user's can't always read the foreign language titles (especially those with non-Roman characters), and shouldn't have to open the full record to figure out if that is the one they need.

- In basic searches on government topics such as felon disinfranchisement or immigration, monographs should appear higher up in a results list than government documents (such as congressional reports) because In discoverE, searches on government topics often prioritize government topics, and those are not what Emory researchers most want. People who are looking for government documents will go to lower pages of results, anyway.

**Fuzzy Search**
- Get "Did you mean" search suggestions so if I've made a typo indicated by no results, I get a helpful suggestion of alternative search terms.

-Search results include variations of a search term. For example, if performing a search using a "truncated word" so I can get all variants, e.g. catech* finds catechism and also catechismus in the search results.

**Acceptance Criteria**

- [ ] After the teach-out determine what customizations are needed to address the above user stories including level of effort (estimate) for the customization. 

- [ ] If the level of effort (customizations) is less than 13 total points then new tickets should be created by the app developer to complete the work needed. Any work in excess of 13 points should be discussed with product owner to determine when (and if) the work should be completed.

**Comment by bwatson78** [comment]
Relevancy teachout deck:  https://docs.google.com/presentation/d/103NRpVzK0ZpO58pFNmL8DGp6thG_-HVkGnw5o8tm-xw/edit#slide=id.p
Recordings of that teachout: https://emory-my.sharepoint.com/personal/rmetz_emory_edu/_layouts/15/onedrive.aspx?FolderCTID=0x012000969121B6B74B634592C8045C36018112&id=%2Fpersonal%2Frmetz%5Femory%5Fedu%2FDocuments%2FLTDS%20Shared%20Documentation%2FProjects%2FProject%20Documentation%2FBlacklight%20Discovery%20Layer%20Phase%201%2FScrum%20Team%2FMeetings%20and%20Agendas%2FZoom%20Recordings%2F2021%2D06%2D10%20Blacklight%20Blacklight%20Relevancy%20Teach%20Out

**Comment by rotated8** [comment]
Hey @lovinscari- @bwatson78, @devanshu-m and I talked about this today and have some recommendations for each of the points.

- First, we are assuming this is in the context of a keywords search. The keywords search as defined in the metadata spreadsheet does not include titles, only mmsid, text, and local call number. [Original ticket](https://github.com/emory-libraries/blacklight-catalog/issues/95), [update ticket](https://github.com/emory-libraries/blacklight-catalog/issues/121), and [spreadsheet](https://docs.google.com/spreadsheets/d/1jSqgNd6HnVJdJMrrShAofkmK8uGgHGdlKODmZOL5NfY/edit?usp=sharing). Solr gives more relevancy to searches that match more of a searched field, so the text field here is working against us. A user will never search for all of the data in that field, so a better described item with more information will always be less relevant than an item with less description (i.e.- closer to a full search term match), when they both contain the same search query in their descriptions. To allow a search to fully match on a title, the semantics of keyword search would need to change to include searching against title fields specifically. We have over twenty title fields, and would need to identify which are relevant for exact matching. Changing the keyword search to use the identified field or fields should take little effort. More generally, keyword search results may be improved by removing the aggregated text field and replacing it with all the individual fields that make it up. Again, depending on the ease of identification of the appropriate fields to substitute, this could be a low-effort amount of work. Plus, once that was done, we could tune results to favor certain fields over others, which we cannot do now.
- We believe this currently happens. See [this search](https://blackcat-arch.library.emory.edu/?utf8=%E2%9C%93&f%5Blanguage_ssim%5D%5B%5D=Chinese&search_field=keyword&q=Hai+shang+hua) as an example with English transliteration as the primary title, and the Chinese original as the additional title. Changes to this behavior require changes to the MARC data to specify a language for the metadata, changes to our indexing to incorporate that language data, changes to our Solr index to accept and understand multiple languages, and changes our application to prioritize English text metadata. More commonly, alternate language titles are missing. For instance, the first Harry Potter book has [over sixty title translations](https://harrypotter.fandom.com/wiki/List_of_titles_of_Harry_Potter_books_in_other_languages). Even within English, the book has two versions of its title, which the Library of Congress calls out in its [catalog record](https://lccn.loc.gov/2020286067). Our version has no alternate titles in [Blackcat](https://blackcat-test.library.emory.edu/catalog/990011077980302486) or [DiscoverE](https://discovere.emory.edu:443/discovere:default_scope:01EMORY_ALMA21183098690002486). I do not think we could robustly handle any existing language metadata in three months.
- How do we identify government topics, and government documents? I assume the latter can be done with existing MARC metadata. If that is the case, we can expose that as another resource type, to allow people to filter those results out if they do not want them, or to search them exclusively if they do, which is better than making the latter skip pages of results. This approach allows us to avoid having to create and maintain a list of government topics, and a special search setting for searches matching items in that list. Depending on the complexity of identifying government docs via MARC, this could require a low to medium effort to accomplish.
- With the provided context, the feature described is "Suggestions". Fuzzy search refers to a search term followed by a tilde and a number, like "Hairy~3", where the number specifies the "distance" from the given term acceptable terms are. Suggestions [exist](https://blackcat-test.library.emory.edu/?utf8=%E2%9C%93&search_field=keyword&q=hary+potter), and show up if zero results were found. It is not clear what changes are suggested.
- Wildcard searching (terms with an asterisk) appears to be completely broken. Searching Solr directly against the `text_tesi` field (mimicking keyword search), "catech\*" produces [over 9000 results](https://solr-cor-test.library.emory.edu/solr/blackcat_collection/select?q=text_tesi%3Acatech*) compared to [four in blackcat](https://blackcat-test.library.emory.edu/?utf8=%E2%9C%93&search_field=keyword&q=catech*). "catechismus": Solr - [455](https://solr-cor-test.library.emory.edu/solr/blackcat_collection/select?q=text_tesi%3Acatechismus), Blackcat- [455](https://blackcat-test.library.emory.edu/?utf8=%E2%9C%93&search_field=keyword&q=catechismus). "catechism": Solr - [5386](https://solr-cor-test.library.emory.edu/solr/blackcat_collection/select?q=text_tesi%3Acatechism) Blackcat - [5386](https://blackcat-test.library.emory.edu/?utf8=%E2%9C%93&search_field=keyword&q=catechism). What exactly is going on here is unclear, and deserves its own bug ticket to fix. The work would include identifying the exact search query Blackcat produces and the work to make it produce the correct one. Exactly what is involved is not clear, so this would require moderate effort to fix.

**Comment by lovinscari** [comment]
Thanks @rotated8 for the detailed description and for all of the work with the app dev team on this ticket. I will review this information with @eporter23 to see if she has any recommendations from a metadata field in order to improve relevancy in any of the areas you have provided info on. I really appreciate all of the details and work on this.
