### ISSUE TITLE
Create request screen wireframe

### ISSUE THREAD

**Issue by mark-dce** [emory-libraries/blacklight-catalog#596]
**ACCEPTANCE**
- [x] Holding level items are shown with library, location, call number
- [x] Holding level availability is shown (copies, available, holds)
- [x] I can click on holding information to show item level info
- [x] Item level info includes barcode, loan policy
- [x] If I'm not logged in, loan policy displays as "Please login to view"
- [x] I can click on request targets at the holding level
     - [x] General circulation
     - [x] Special Collections
     - [x] Place on Reserves
     - [x] Document Request (article/chapter)

![image](https://user-images.githubusercontent.com/3064318/120659439-fc55ba00-c44b-11eb-8de2-ade504e79da1.png)

**Comment by norm0** [comment]
Working prototype of all the interactions possible: https://www.figma.com/proto/ocSo3KytI6GgwjalSVAmE1/Blacklight-Wireframes?page-id=1604%3A15106&node-id=1604%3A15107&viewport=-2%2C1330%2C0.37542155385017395&scaling=min-zoom

**Comment by norm0** [comment]
### Studies for action options
![Actions - Options.png](https://images.zenhubusercontent.com/5f8492d49b473a0cef37940f/31204d87-f101-4636-9bdb-933576707c90)

**Comment by norm0** [comment]
### Options for Holding level information

1. ![Table - Expand.png](https://images.zenhubusercontent.com/5f8492d49b473a0cef37940f/25bffc32-759e-44fc-b82d-2a688df48049)
2. ![Table - Modal.png](https://images.zenhubusercontent.com/5f8492d49b473a0cef37940f/de26ee94-e2d1-4e8a-ae93-bec2f294bd44)
3. ![Table - New Tab.png](https://images.zenhubusercontent.com/5f8492d49b473a0cef37940f/da541c26-97bd-4837-b2a2-0863c1311ce5)

**Comment by lovinscari** [comment]
@mark-dce - Can you please review this and close if acceptable to what you have in mind for a prototype? Thanks!

**Comment by eporter23** [comment]
@norm0 @mark-dce looks good, interesting choices presented!

**Comment by mark-dce** [comment]
FYI - I've started a tab in the "iFrame Details" spreadsheet titled "Physical Requests - API permutations" to capture MMSIDs that represent the various bib / holding / item permutations that the display and request functions need to support.

https://docs.google.com/spreadsheets/d/1JOcExlIp1yO4i5oBJwFz6CrkTN_QTV-2lPjMCdMuySs/edit?pli=1#gid=1074478919

**Comment by norm0** [comment]
Updated wireframe link: https://www.figma.com/file/ocSo3KytI6GgwjalSVAmE1/?node-id=1604%3A15106
