### ISSUE TITLE
Display Holding Level Information

### ISSUE THREAD

**Issue by mark-dce** [emory-libraries/blacklight-catalog#598]
**ACCEPTANCE**
When a physical copy of a book exists
- [x] I can see holding level information on the single item view
   - [x] Library
   - [x] Location
   - [x] Call Number
   - [x] Availability

NOTE: do the simplest possible UI for now, we'll style the UI based on the work in ticket #596 Design the request pages

**Comment by lovinscari** [comment]
Unable to test this due to the problems discussed in the blacklight-dce channel on 6/7/21.

**Comment by mark-dce** [comment]
DiscoverE
<img width="549" alt="image" src="https://user-images.githubusercontent.com/3064318/121381687-8cdc4080-c90b-11eb-9e1a-aca408f9ba21.png">

Blacklight Catalog
<img width="842" alt="image" src="https://user-images.githubusercontent.com/3064318/121381976-cf058200-c90b-11eb-9b31-e77a51d9d35a.png">
