### ISSUE TITLE
Show/Hide Item-level information

### ISSUE THREAD

**Issue by mark-dce** [emory-libraries/blacklight-catalog#599]
**ACCEPTANCE**
- [x] I can click on holding-level availability to show & hide item level information

NOTE: we'll implement detailed styling later based on #596

<img width="554" alt="image" src="https://user-images.githubusercontent.com/3064318/120661668-198b8800-c44e-11eb-9b02-bc28b38a8d0d.png">

**Comment by rotated8** [comment]
Scoped to show information for multiple copies (when applicable)

@lovinscari will add details (example MMSIDs, what info to show)

Example MMSID: 9936550118202486

**Comment by lovinscari** [comment]
@alexBLR - Included below are some examples with item level holdings that will need to be configured in the future but for now I think the intent is just to show the item level detail of the holdings.

Example 1 - 990010702060302486:  multi-part monographs with a separate holding created for each part. In discoverE (Primo), only one item is able to be requested as opposed to each volume. ![discovere_multvolumes.png](https://images.zenhubusercontent.com/5c4a1fe1e9b5fb46bcedb9fc/9b2850eb-a49c-42aa-a0c7-141de9dcd852)

Example 2 - 9936508485302486 is a government document with multiple parts ![discoverE_GovtDocsMultipart.png](https://images.zenhubusercontent.com/5c4a1fe1e9b5fb46bcedb9fc/d66e8a73-1d35-4d34-b1c4-b406d2350750)

Example 3 - BoundWith - Laura had provided numerous examples in ticket [#98](https://app.zenhub.com/workspaces/blacklight-catalog-5f5f84a8a6d29939a0bc5d78/issues/emory-libraries/blacklight-catalog/98)

Let me know if you need any additional details.

**Comment by alexBLR** [comment]
Example of the item level view for holdings:

![Screen Shot 2021-06-09 at 9.35.18 AM.png](https://images.zenhubusercontent.com/5c488275c10ae96cd915967b/ece8b434-ea66-4878-9c39-767b432a27b3)

**Comment by alexBLR** [comment]
![Screen Shot 2021-06-09 at 11.05.16 AM.png](https://images.zenhubusercontent.com/5c488275c10ae96cd915967b/bcaf4de3-441d-4f56-b5d4-c43f2630292c)

**Comment by eporter23** [comment]
@alexBLR looks good! I noticed that we seem to cap at 10 results on really long holdings like journals with many volumes but I think that will be addressed in separate tickets. (For complex holdings we should also look at getting some kind of number/volume/copy/part identifier in addition to barcode in the detail table.) @mark-dce since you wrote this up, I'll leave this open for you to close.
