### ISSUE TITLE
Alma API's

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#60]
As the product owner, I would like Alma API's to be configured to provide functionality specific to Real Time Availability, and OpenURL Link Resolver. Acceptance criteria for the functionality of API's will be identified in each issue. The requirements and/or acceptance criteria for each API will be detailed in the individual issues.

**Comment by tmiles2** [comment]
Theme: Request/Manage Acccount

**Comment by tmiles2** [comment]
Work completed, new work identified may be done within Request Physical Item epic
