### ISSUE TITLE
SPIKE: Course Reserve Request walkthrough

### ISSUE THREAD

**Issue by mark-dce** [emory-libraries/blacklight-catalog#600]
**ACCEPTANCE**
- [x] Create a flow diagram similar to request and special collections flows for 
   - [x] Placing an item on course reserves
   - [x] Accessing an item on course reserves

Miro board for reference: https://miro.com/app/board/o9J_lfYQF4o=/?moveToWidget=3074457359388346432&cot=14

**Comment by RachelDCE** [comment]
A meeting has been scheduled for Monday, June 7.

**Comment by mark-dce** [comment]
Miro board: https://miro.com/app/board/o9J_lfYQF4o=/?moveToWidget=3074457359832464890&cot=14

![image.png](https://images.zenhubusercontent.com/5ca3b270500af570674ef5bc/02c98925-116f-4909-880d-ee8015b75794)
