### ISSUE TITLE
Port Solr backup scripts and docs to Github

### ISSUE THREAD

**Issue by oraposa** [emory-libraries/blacklight-catalog#603]
Choose a repository where the new scripts and docs will reside, create a branch and PR for merging.

**Comment by oraposa** [comment]
placed initial scripts and docs in [blackcat-tf](https://github.com/emory-libraries/blackcat-tf).

**Comment by libah** [comment]
Steve, Collin, and I met to go through the process. The documentation is clear and precise. I would like to do a walkthrough where I do an actual restore, at some point with Steve.
