### ISSUE TITLE
Show/Hide holdings when there are many holdings

### ISSUE THREAD

**Issue by mark-dce** [emory-libraries/blacklight-catalog#604]
**ACCEPTANCE**
When there are many holdings (e.g. > 5),
- [ ] The show page shows a general message "Click to see holdings"
- [ ] The limit is configurable (start with 5)
- [ ] When I click on "Click to see holdings", I get a (modal) window that shows all the related holdings for the bibID

NOTE: See #596 for detailed design

**Comment by eporter23** [comment]
@maxkadel @mark-dce here is the example I mentioned in standup today as an example of complex monograph holdings (multiple libraries and multiple locations). https://blackcat-test.library.emory.edu/catalog/990010439240302486 But if you're looking for serials examples let me know.

**Comment by mark-dce** [comment]
After further consideration, there's an upper limit on holdings (total number of libraries times total number of holding locations) and this worst case would happen rarely or never.  It seems like the screenshot below is a typical upper limit, so we're just going to show everything the same way Primo does for now.

<img width="970" alt="image" src="https://user-images.githubusercontent.com/3064318/122246582-48f9b600-ce8c-11eb-80ac-cca003949b42.png">
