### ISSUE TITLE
SPIKE: Document Delivery Walkthrough (local ILLiad requests)

### ISSUE THREAD

**Issue by mark-dce** [emory-libraries/blacklight-catalog#608]
**ACCEPTANCE**
- [x] Create a flow diagram similar to request and special collections flows for 
   - [x] Steps to request an article or chapter via ILL
   - [x] Document any OpenURL / API parameters that we identify in the process
- [ ] Document initial requirements around ILL requests for items not in the Emory Catalog

Miro board for reference: https://miro.com/app/board/o9J_lfYQF4o=/?moveToWidget=3074457359388346432&cot=14

**Comment by RachelDCE** [comment]
A meeting has been scheduled for Tuesday, June 8.

**Comment by mark-dce** [comment]
Miro board: https://miro.com/app/board/o9J_lfYQF4o=/?moveToWidget=3074457359832464890&cot=14

![image.png](https://images.zenhubusercontent.com/5ca3b270500af570674ef5bc/02c98925-116f-4909-880d-ee8015b75794)
