### ISSUE TITLE
Urls that don't include "http" not linking correctly

### ISSUE THREAD

**Issue by maxkadel** [emory-libraries/blacklight-catalog#609]
See e.g. https://blackcat-test.library.emory.edu/catalog/990016148150302486 
The "Access online" link address is https://blackcat-test.library.emory.edu/catalog/pid.emory.edu/ark:/25593/b66vt/IA (a sub-page of our application), but it should be simply https://pid.emory.edu/ark:/25593/b66vt/IA

The 856 field, in this case, does not include the protocol in the url. 
```
<datafield tag="856" ind1="4" ind2="1">
  <subfield code="u">pid.emory.edu/ark:/25593/b66vt/IA</subfield>
  <subfield code="y">Internet Archive version</subfield>
</datafield>
```

When this happens, I believe the application should provide "https" as the default protocol. We could do this at time of Solr indexing, so that we don't have to re-calculate it very often.

**Comment by rotated8** [comment]
@eporter23 I see 590 offenders in Solr.

**Comment by eporter23** [comment]
Update as of 6/4: we will contact cataloging about cleanup needed (approximately 600 records impacted) as opposed to implementing a workaround in code.
