### ISSUE TITLE
Alma API - Real Time Availability

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#61]
As the product owner, I want Alma API's to be configured for Real Time Availability so that search results can show the availability of each item including if an item is 

- [ ] "Available" for physical items that are available for requesting and/or checkout

- [ ] "Online" for online resources that can be accessed online

- [ ] "Check Availability" for items that require additional follow-up such as special collections that require consultation with members of the special collections team

**Comment by rotated8** [comment]
Closing as complete
