### ISSUE TITLE
Update search on Emory Libraries Home Page

### ISSUE THREAD

**Issue by tmiles2** [emory-libraries/blacklight-catalog#615]
The Search Box on Emory Libraries Home Page will need to be updated for the production launch on 1/6/22. 

- [ ] The Library Catalog link should be updated to search search.libraries.emory.edu instead of discovere.emory.edu with the same functionality to pass the search parameters as a keyword search (default) to search.libraries.emory.edu

- [ ] A link should be added for Articles Plus to search https://emory.primo.exlibrisgroup.com/discovery/search?vid=01GALI_EMORY:articles by passing the search parameters to Articles Plus

The work can be completed for testing at any point but should not be moved to production until production launch on 1/6/22.

**Comment by tmiles2** [comment]
Is this ticket still needed @tmiles2? I have seen the new search tool announced on the Emory Libraries site but I think that's still pending correct?

**Comment by eporter23** [comment]
@tmiles2 @lovinscari I think this ticket refers to adjusting the search box on the libraries homepage, which will require development.

**Comment by lovinscari** [comment]
@tmiles2 - This work is still needed but we do not want to make this change until production launch.

**Comment by CB987** [comment]
on the cascade side, i was able to add the articles+ option to the search bar (in staging, for testing purposes) and have documented the process.
![Screen Shot 2021-11-29 at 3.29.55 PM.png](https://images.zenhubusercontent.com/5d379c9d5221e52414fca85c/57b045b2-b323-4664-a1a6-34fc1f4c4759)
![Screen Shot 2021-11-29 at 3.30.41 PM.png](https://images.zenhubusercontent.com/5d379c9d5221e52414fca85c/8069b52a-0080-45bb-957e-bbdf8da1428f)
the search url should be https://emory.primo.exlibrisgroup.com/discovery/search?query=any,contains,:query&tab=CentralIndex&search_scope=CentralIndex&vid=01GALI_EMORY:articles&offset=0

**Comment by CB987** [comment]
was able to update the library catalog on staging to be library search, and documented steps. search url is https://search.libraries.emory.edu/?utf8=%E2%9C%93&search_field=keyword&q=:query
![Screen Shot 2021-11-29 at 3.45.34 PM.png](https://images.zenhubusercontent.com/5d379c9d5221e52414fca85c/a997810c-0dbd-4f04-8b72-ff233dc1f6c6)
![Screen Shot 2021-11-29 at 3.46.05 PM.png](https://images.zenhubusercontent.com/5d379c9d5221e52414fca85c/6be21a86-a827-4c43-9b4a-4df86c136d48)

**Comment by CB987** [comment]
I've seen a demonstration of where/how to do this in the new site, but have not yet had the opportunity to walk through the process myself (it involves creating my own instance of the codebase which is a multi-step process).

**Comment by CB987** [comment]
have been able to add articles+ on my own cloud instance of the site ![Screen Shot 2021-12-03 at 4.19.01 PM.png](https://images.zenhubusercontent.com/5d379c9d5221e52414fca85c/7bd49c8f-7b25-49cb-81b2-b0322564f0bc)
