### ISSUE TITLE
Refine Former/Later Title hyperlinked search behavior from View Item Detail page

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/blacklight-catalog#618]
_As an end user, I want to be able to easily search for former and later titles of a resource that I am currently viewing, so that I can see additional metadata or holdings about the material as it changes over time_

In our current implementation (see ticket #313 for prior work), the hyperlinks on title_former_ssim and title_later_ssim run a search against themselves, which sends a user in a circular pattern. Ideally, we want the hyperlink on these fields to start a search against a broader 245/title field, so that if Emory owns the former or later title, a user can get to that record quickly.

- [Example of circular search behavior](https://blackcat-test.library.emory.edu/catalog/990029595390302486)
- [More background and stakeholder comments](https://docs.google.com/document/d/1Ic8RCS1QGG3MRkOiwHBNzLS0vebiXLNHKswtK5xy-gY/edit?ts=60ba67c2)

![Screen Shot 2021-06-04 at 2.07.05 PM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/e4412833-e467-4a4a-b74d-9f58d352497c)

**Preferred Option:**

1. Send the terms in the entry to our existing Basic Search > Title search in the search bar (multiple title-related fields configured for search). 

Example: https://blackcat-test.library.emory.edu/?utf8=✓&search_field=title&q=Electronic+musician+0884-4720

If possible, combine this with the appropriate format/Resource Type to make it more targeted. Example below:
 https://blackcat-test.library.emory.edu/?f%5Bformat_ssim%5D%5B%5D=Journal%2C+Newspaper+or+Serial&q=Electronic+musician+0884-4720&search_field=title

**Alternate options:**

2. Keep the display output as is, including the identifiers, and send the terms in the entry as a keyword search to the Full Title field that we use for display.

3. Remove the hyperlinks on these fields until we can come up with a solid solution. (Easy to implement but puts the search burden solely on users.)

**Comment by eporter23** [comment]
@lovinscari FYI I wrote this up if we need it.

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/blacklight-catalog/pull/659

https://images.zenhubusercontent.com/295449627/d998a8c3-91b4-4deb-b5b5-d846d6ffabcf/screen_recording_2021_06_14_at_12_18_21_pm.mov

**Comment by eporter23** [comment]
@bwatson78 looks great, thanks!
