### ISSUE TITLE
SPIKE: Determine how to simplify access and authorization of current Alma User Groups

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#62]
As a product owner, I would like to work with the development team and subject matter experts to prepare a proposal for simplifying access and authorization of Alma and third party features that display in Blacklight to certain Alma User Groups. The current state of access provided is various Alma User Groups is detailed in the Google Spreadsheet - https://drive.google.com/file/d/1pLU3pvrlYfsfow51_VxE_aVFlGqnLHyR/view?usp=sharing

The current state of Alma User Groups is overly complex and will be difficult to map access and authorization needed from the Blacklight Application. An ideal scenario would be

- [ ] Teaching Faculty Level Access = Can view all resources, Can access all online resources, Can request all resources including document delivery, Can place items on Course Reserves, Can request items via Interlibrary Loan to request materials not available from Emory University.

- [ ] General Faculty, Staff and Student Level Access = Can view all resources, Can access all online resources, Can request all resources including document delivery, Can request items via Interlibrary Loan to request materials not available from Emory University.

- [ ] Affiliate Access (Including Alumni and Visitors) - Can view all resources, Can Borrow but not request

Additional notes:
the outcomes for this ticket should include a matrix or assessment of what unique functions these groups can perform in the discovery layer specifically - how are they truly different?

**Comment by eporter23** [comment]
@lovinscari As noted by @lisahamlett notes, certain types of affiliates cannot be consolidated.

**Comment by AGCooper** [comment]
Special collections requesting is missing in the description. ALL users (logged in or not) can place a booking request for select collections and archival materials.

**Comment by libah** [comment]
Have removed locations no longer in use, in process of removing duplicate permissions. Finished BUS, CHEM (Science Commons). Working on Health, Law, Theology LCS, MUSME. (sheet marked "modified").

**Comment by tmiles2** [comment]
@lovinscari Sorry if you covered this during standup. With regards to this ticket, what are we trying to accomplish by the end of this sprint?

**Comment by lovinscari** [comment]
@tmiles2 - I am going to  move this back to New Issues for now since this will require information specific to how access and authorization is handled at the meta level (what is handled by Alma, and what is handled by Shibboleth), which we currently do not have.

**Comment by tmiles2** [comment]
Theme: Request 
epic level - Request Physical Item (Hold / Recall)
Note: This will come up again in other epics

**Comment by rotated8** [comment]
@lovinscari @AGCooper With the request-it api ticket in progress, I'd like to meet about this again.

**Comment by lovinscari** [comment]
It does not sound like this is a current requirement. I will create a new ticket if we determine refinements are needed.
