### ISSUE TITLE
Refine wireframes and styling requirements for CDI View

### ISSUE THREAD

**Issue by tmiles2** [emory-libraries/blacklight-catalog#621]
In an effort to complete the work on the CDI view, please revise wireframes and styling information needed for the CDI view. The reference is our [punchlist of styling and display items](https://docs.google.com/document/d/1dSTOiboKkpYzVod2SaYmP910rDge3T2dSW3y_2BThNo/edit#)

- [x] Review the current state of the CDI view.
- [x] Confirm wireframe and styling requirements
- [x] Add CSS to the CDI view in sandbox
- [x] Apply other view configurations as identified

Working notes:

- [Primo VE articles view in Alma sandbox](https://emory-psb.primo.exlibrisgroup.com/discovery/search?vid=01GALI_EMORY:articles) (for previewing)
- [Unstyled CDI view in sandbox for comparison](https://emory-psb.primo.exlibrisgroup.com/discovery/search?vid=01GALI_EMORY:CDI)

**Comment by eporter23** [comment]
Norm's styling added here:
https://emory-primosb-alma.hosted.exlibrisgroup.com/primo-explore/search?query=any,contains,yacht&tab=default_tab&search_scope=cdi&vid=newuicdi&offset=0

See also Primo design UI:
http://primo-studio.exlibrisgroup.com/?dirName=1g3vEr&url=https:%2F%2Femory-primosb-alma.hosted.exlibrisgroup.com&vid=newuicdi&ve=false¢ral=false

**Comment by eporter23** [comment]
Note: I think this is the current CDI view for Primo VE but I will confirm. https://emory.primo.exlibrisgroup.com/discovery/search?vid=01GALI_EMORY:CDI

**Comment by libdgg** [comment]
Emily doing a walk through and making punch list of things to follow up on.

**Comment by libdgg** [comment]
Emily will talk to Ann about whether there is a My Account link/view in the CDI.

**Comment by libdgg** [comment]
Punchlist work still in progress. The work will be done in sandbox so we will know more once we get sandbox setup with the view.

**Comment by libdgg** [comment]
Emily can start work on styling now that we have a view in sandbox.

**Comment by eporter23** [comment]
"articles" view in sandbox with CSS in progress: https://emory-psb.primo.exlibrisgroup.com/discovery/search?query=any,contains,pizza&tab=CentralIndex&search_scope=CentralIndex&vid=01GALI_EMORY:articles&offset=0

**Comment by libdgg** [comment]
Emily will review with Cari on Wed.

**Comment by libdgg** [comment]
Emily will plan next steps - this is almost ready to accept.
