### ISSUE TITLE
Requesting as Handled via Alma

### ISSUE THREAD

**Issue by AGCooper** [emory-libraries/blacklight-catalog#63]
To produce a report of Alma based requesting options and services currently delivered to Primo in the lightbox.

**Comment by lisahamlett** [comment]
[https://app.zenhub.com/files/295449627/6a826f68-76d0-4d51-ac7c-3609e81bd33e/download](https://app.zenhub.com/files/295449627/6a826f68-76d0-4d51-ac7c-3609e81bd33e/download)
