### ISSUE TITLE
Library location display - remove extra colon

### ISSUE THREAD

**Issue by maxkadel** [emory-libraries/blacklight-catalog#633]
If there is no location after the library, do not show the colon after the library name

https://blackcat-test.library.emory.edu/catalog/990028709320302486

![bug - remove colon.png](https://images.zenhubusercontent.com/5d51624a5b89150001ae0b03/0928c61d-ee50-433a-be46-a3e74eaef0b6)

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/blacklight-catalog/pull/662

**Comment by eporter23** [comment]
General note - in our original wireframes and in an earlier implementation we were showing the Library Service Center and also the original holding library that owns the material. I'll review with @lovinscari if we want to add that back.
