### ISSUE TITLE
SPIKE: Determine feasibility of providing Links to electronic holdings not represented in 865 fields

### ISSUE THREAD

**Issue by maxkadel** [emory-libraries/blacklight-catalog#634]
Online resources that do not have an 856 field in the MARC record are not displaying a link to find them in blackcat.

**ACCEPTANCE**
Timebox a research spike into 
- [x] Quantifying how many titles in the catalog are impacted by this issue
- [x] Identifying how many different situations cause this - is it just portfolio items, or are there other electronic resources that are identified some other way than via 856 fields?
- [x] Prototyping methods to obtain viable links - e.g. the AVE field discussion below.

## Example: 
JAMA (https://blackcat-test.library.emory.edu/catalog/9936493491502486) 
![image.png](https://images.zenhubusercontent.com/5d51624a5b89150001ae0b03/64878132-2669-4529-932e-fdb09ee3f710)

Compare this with Primo [JAMA on discovere](http://discovere.emory.edu/primo_library/libweb/action/display.do?tabs=detailsTab&ct=display&fn=search&doc=01EMORY_ALMA51271722070002486&indx=1&recIds=01EMORY_ALMA51271722070002486&recIdxs=0&elementId=0&renderMode=poppedOut&displayMode=full&frbrVersion=&frbg=&&dscnt=0&scp.scps=scope%3A%28repo%29%2Cscope%3A%2801EMORY_ALMA%29%2CEmory_PrimoThirdNode&tb=t&vid=discovere&mode=Basic&srt=rank&tab=emory_catalog&vl(341573392UI1)=all_items&dum=true&vl(freeText0)=9936493491502486&dstmp=1623092596513)
![image.png](https://images.zenhubusercontent.com/5d51624a5b89150001ae0b03/c8bb16cb-32f6-48d0-a70e-8ab1015a8cc6)

## Technical thoughts
* Through the Alma API, this journal does not have an 856 field, but it does have two AVE fields. 
* The Blackcat code is not currently displaying info from the AVE fields in part because they are showing up as `publishing_base_url undefined?u.ignore_date_coverage=true&amp;rft.mms_id=9936493491502486`
* The documentation in the API for the AVE field says "Note: $$u will be created based on a Customer Parameter in the Customer Parameters mapping table (module: general): publishing_base_url.", so this appears to be an Alma configuration issue
* The relationship between this suggested url in the Alma api, the Central Discovery Index (CDI), portfolios, open url, and find it, is entirely mysterious to me. 
  * The first link on discoverE is https://na03.alma.exlibrisgroup.com/view/action/uresolver.do?operation=resolveService&package_service_id=38534854600002486&institutionId=2486&customerId=2485 
  * The second link on discoverE is https://na03.alma.exlibrisgroup.com/view/action/uresolver.do?operation=resolveService&package_service_id=38534854590002486&institutionId=2486&customerId=2485 
  * Both of these send me to https://proxy.library.emory.edu/login?url=https://jamanetwork.com/journals/jama
  * I can't get any further because I don't believe my usergroup allows me access to any online journals

**Comment by AGCooper** [comment]
CDI should be out of the scope of this phase I believe.
It looks like the 2 links that show in discoverE are provided via portfolios.
Open URLs or General Electronic Services from Alma I'm not sure how you get via API (others know I'm sure).
FindIt@Emory is a mystery to me too though others may understand it better (I think it's an integration on the vendors' end if we're talking about the same thing).

**Comment by maxkadel** [comment]
Yes, I think each AVE field represents

**Comment by maxkadel** [comment]
More information on configuration of the `publishing_base_url` parameter - it looks like it's intended to point to a Primo url, so I'm not sure that, even if it's configured appropriately, it's ultimately where we want this information to live.

https://knowledge.exlibrisgroup.com/Alma/Product_Documentation/010Alma_Online_Help_(English)/050Administration/050Configuring_General_Alma_Functions/080Configuring_Other_Settings

![image.png](https://images.zenhubusercontent.com/5d51624a5b89150001ae0b03/9341a47c-e7b7-4a57-85b3-706b2a9295f5)

**Comment by bwatson78** [comment]
Preliminary Findings: This JAMA example does have links on the service page. @AGCooper When you mention that those links are pointing to portfolios, do you know if you have a overarching list of portfolios that would be available to users? Basically one place that we could reference and, therefore, map portfolio to the record when a user loads that certain page?

It just seems to me that there should be a page in Alma that should list all Package Services.

**Comment by bwatson78** [comment]
Running List of IDs Showing Behavior:

Possible Portfolio
9936493491502486
9937240716502486

Redirects to X When Trying To Access Service Page
9936898863402486 (EBSCO)
9937109344702486 (EBSCO)
9937109354102486 (EBSCO)
9937013757102486 (JSTOR)

Neither PID or Suspected Service Page Redirect Work
9936898863402486

No Online Availability in Blacklight or Services Page
9936898863402486 (AVE lists provider as EBSCO)

**Comment by bwatson78** [comment]
Final Conclusions: I pulled the latest version of catalog into my local, cleared my Solr, and ingested `blacklighttest`. Next, I faceted `Online` access and viewed 500 records of 1780 available to me. I allowed the availability API to query each of my viewed records and clicked on Services Page only when there was no other Online resource link provided, or when the resource link wasn't passed a description (https://pid...). I documented the ids and their behaviors above. Of the 500 online resources, 2 stayed on the Services Page, which provided links to the exterior sites that hosts the content. 121 others redirected me directly to the content provider immediately, skipping a view of the Service page.

@Lisa queried Alma using the following parameters: record's datafields with "AVE" tags that contain the substring `publishing_base_url` in the subfield coded with "u", which also do not contain "856"-tagged datafields with a second indicator field equaling "0" or "1". This would provide us with the records that would show no link for external online content but may likely redirect the user when they click on the service page link. Her query produced 963,395 records, nearly twenty percent of the overall catalog.

If we decide to not utilize the Services Page in the future, it would still be beneficial to us to utilize it as a "hop-to" the online content providers if cataloging cannot easily populate the links to this content into the "856" datafields.

**Comment by eporter23** [comment]
@bwatson78 and I are continuing to investigate this, because we need to determine whether or not we can retrieve resource links from portfolio information via API alone. The Services Page may not be available to us long-term depending on our product licensing.

**Comment by bwatson78** [comment]
@eporter23 Following the path of [https://developers.exlibrisgroup.com/alma/apis/electronic/](https://developers.exlibrisgroup.com/alma/apis/electronic/), the `collection_id` is `AVEc` and is not found in the bib record.

**Comment by bwatson78** [comment]
IDs that are not producing content when openurl clicked:
9937177765002486
9937286692702486
9937275387702486

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/blacklight-catalog/pull/705

![Screen Shot 2021-06-22 at 9.13.48 AM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/328e248e-ef87-4bfe-b134-0471b94206e1)

**Comment by lovinscari** [comment]
@eporter23 - I am sure the concerns presented by Kat, Sofia and Jessie to me have also been presented to you with regards to the electronic resources that are part of a portfolio. I'd like your thoughts on how we should proceed based on the information provided by Brad and Alex. Thanks!

**Comment by lovinscari** [comment]
@eporter23 - Please close this once you have completed your testing. Thanks!

**Comment by eporter23** [comment]
@bwatson78 all the examples I've checked look good. Thanks! I also have a [couple of interesting examples I used for testing](https://docs.google.com/document/d/1ehbHJZNRx7B6qawmtG0MhWKPs2ZAMwgg7JxPfmW9VEY/edit?usp=sharing) here just for reference.
