### ISSUE TITLE
Revise mapping for related resources 856 mapping (url_suppl_ssim) 

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/blacklight-catalog#643]
We currently have a large number of 856 fields that don't specify a second indicator (in part due to the fact that these indicators weren't all available when the tag was first introduced).

In order to not exclude these 856 links, which may be helpful to users, cataloging proposed that we include these unspecified types of 856s to the related links field.

SOLR/indexing

- `url_suppl_ssim` : see revised mapping at [metadata worksheet](https://docs.google.com/spreadsheets/d/1jSqgNd6HnVJdJMrrShAofkmK8uGgHGdlKODmZOL5NfY/edit#gid=1979033236)
- Summary: include 856s with no second indicator in addition to those with second indicator = 2

**Comment by lovinscari** [comment]
@eporter23 - can you please review and close if it meets your requirements? Thanks!

**Comment by eporter23** [comment]
@alexBLR looks great. I tested on arch, but we will need to reindex on test at some point too. @lovinscari should I go ahead and close it, or wait for a reindex? Here are a few records I spot checked which all show the revised mapping working as expected:

https://blackcat-arch.library.emory.edu/catalog/990004872810302486
https://blackcat-arch.library.emory.edu/catalog/990007076840302486
https://blackcat-arch.library.emory.edu/catalog/990005608660302486
https://blackcat-arch.library.emory.edu/catalog/990005580850302486
https://blackcat-arch.library.emory.edu/catalog/990002957810302486
