### ISSUE TITLE
SPIKE: Review accuracy of report from Alma on Alma User Groups

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#65]
After meeting with Alex Cooper to review the Alma User Report - https://docs.google.com/spreadsheets/d/12MOZtcZ4VmKo-I7XACV2P_A00YAkCi0FkV96jrHbDLA/edit?usp=sharing might include legacy data, and perhaps further review/cleanup of the data might be needed in order to truly decipher the correlation to services, Alma user groups, and various rules associated with user groups and services. 

- [ ] Core Systems to determine if the report generated (referenced above) includes any legacy data that perhaps should be excluded

- [ ] Operations Lead, Technical Lead, and Product Owner review the revised report (if applicable) to determine if report should be reviewed with SEND Team for additional verification/validation of the report in an effort to simplify the Alma User Groups access and authorization of various resources.

**Comment by AGCooper** [comment]
We can definitely do some cleanup on this without too much work. After about 30 minutes of work I was able to reduce the number of rows from 448 to 381 just getting rid of some low hanging fruit. Trying to collapse some of the rows could be trickier.

**Comment by AGCooper** [comment]
@lovinscari and @rotated8 Ann modified the requesting table for BUS, CHEM, and HLTH to illustrate what we could do. Please review and see what you think before I ask her to do more work and create a work ticket vs. a spike. See the "modified" tab.

**Comment by eporter23** [comment]
From standup: see the Modified Table tab.
