### ISSUE TITLE
SPIKE: Quantify API Usage

### ISSUE THREAD

**Issue by mark-dce** [emory-libraries/blacklight-catalog#652]
**ISSUE**
The team has raised concerns that ExLibris enforces limits on API usage (i.e. daily usage is metered and calls may be rejected once we hit our limits and/or are there any throttling limits that take place before we hit our overall limit)

**ACCEPTANCE**
- [ ] In a 3 day timebox, gather as much information as possible on the following questions (and any new questions that surface during the research period) - *treat this as a timed test, answer the questions that you can, move on from those that will take too much time to answer*
* **LIMITS**
   * What are the metering limits
       * What is the behavior when limits are reached (hard stop vs. service reduction)
   * Which API calls are metered 
       * Unauthenticated calls
       * Per user calls
   * Has or would ExLibris increase the limits under any circumstances
      * Short-term so to allow the catalog to remain operaitonal while Emory re-engineers specific processes to reduce calls
      * Permanently (as part of an additional for-fee offering?)
      * Can Emory buy more seats to increase the limits - could this help, what would it cost
   * Are current Primo activities contributing to API usage
   * Is Kleene using any API calls
* **USAGE**
   * Is there a way to monitor the current quota usage
      * Can we set threshold alerts like we do for other system stats (e.g. like disk usage - warn us when were at 75%)
   * How many calls are currently made when we do an initial search
      * Could any particular searches trigger significantly more API calls than the typical search
   * How many calls are made when we view a single item page
       * Could any items result in significantly higher numbers of calls than the average item (because of multiple holding or items or other reasons)?
    * How many calls are made for login 
        * Are there other non-search features that make API calls
   * How many affiliate logins are there currently
       * During a typical day
       * During high usage periods (like finals week)
   * How many searches are there currently
      * During a typical day
      * During high usage periods (like finals week)
   * Has Temple experienced any issues with API call limits?
   * Are there any features we could turn off during high utilization periods to reduce API hits (e.g. some institutions appear to suppress unsolicited requests for availability - see [IUCat](https://iucat.iu.edu/?utf8=%E2%9C%93&search_field=all_field&q=leaves+of+grass)
   * How much holding-level information can we get through the OAI endpoint rather than through API requests
   * Can we do availability-level API calls via ajax only when a user wants to see avaiability at the item level
- [ ] Summarize the information gathered and formulate an initial prediction about whether or under what circumstances Emory might exceed API limits

**Comment by AGCooper** [comment]
You can find our API analytics here after you login to the ExLibris Developer Network https://developers.exlibrisgroup.com/manage/reports/

**Comment by AGCooper** [comment]
- What are the metering limits
Not sure. We've never reached the limit.
- Which API calls are metered 
Any that require an api key
- Has or would ExLibris increase the limits under any circumstances
No
- Are current Primo activities contributing to API usage
Yes re: custom integrations
- Is Kleene using any API calls
Yes. Most come from kleene. Also hopper and turing to a lesser extent. (these are all Core systems servers)
- Is there a way to monitor the current quota usage
See link above. As for monitoring it might could be done by monitoring the header responses from api calls in api scripts
- Are there any features we could turn off during high utilization periods to reduce API hits (e.g. some institutions appear to suppress unsolicited requests for availability - see IUCat
I can't think of any (in particular on the metered side)

**Comment by tmiles2** [comment]
@lovinscari @rotated8  Mark will have the API document ready by the end of the day tomorrow.

**Comment by tmiles2** [comment]
Here's the information Mark put together. [https://app.zenhub.com/files/295449627/25c21af4-9054-4954-92d8-d804620b3a60/download](https://app.zenhub.com/files/295449627/25c21af4-9054-4954-92d8-d804620b3a60/download)

Link to the original document:[https://docs.google.com/document/d/11LumCk89y_jN1Z69PpbHuTeSWNmkcXiXzZX3bjFQLwY/edit?usp=sharing](url)
