### ISSUE TITLE
Display Serials Holdings Level with enumeration and chronology

### ISSUE THREAD

**Issue by maxkadel** [emory-libraries/blacklight-catalog#660]
### Story

As a user looking for a specific physical volume of a long-running periodical, I want to see the enumeration and chronology (volume numbers and date coverage) for each holding in order to select the appropriate holding to drill down into to find a specific volume. 

### Implementation note
* Currently, this holding information is available in ~either the Marc21 HOL852 field, subfield $$v~ subfield $$v in the AVA holdings information through the Alma API. 
* I do not believe we are currently persisting it to Solr (other information from the HOL852 field is being persisted to Solr, but not in a way where you could ask for all the information for just one holding together)

### Examples:

Title: Percussive Notes
mms_id: 990009408820302486
Current discoverE
![image.png](https://images.zenhubusercontent.com/5d51624a5b89150001ae0b03/2830db6f-81ea-4897-87d8-77f7df7d4a22)

Current BlackCat
![image.png](https://images.zenhubusercontent.com/5d51624a5b89150001ae0b03/6f530f3b-2623-44c9-824a-2b7296cdee8b)

----
Title: Nature
mms_id: [990027470250302486, 990008508220302486]
Current discoverE
![image.png](https://images.zenhubusercontent.com/5d51624a5b89150001ae0b03/5cf45784-84e3-4710-ad9f-03e490adc41d)

Current BlackCat (first)
![image.png](https://images.zenhubusercontent.com/5d51624a5b89150001ae0b03/457ef963-ec97-4e03-8425-26cfe18618aa)

Current BlackCat (second)
![image.png](https://images.zenhubusercontent.com/5d51624a5b89150001ae0b03/3c6b5061-c0b0-4efc-90cd-515b598be20c)

**Comment by eporter23** [comment]
@maxkadel I think our HOL852 in OAI contains, essentially, whatever is populated in the holding record (tag 852) but we can confirm with @lisahamlett. I don't think there is a $v in MARC holdings 852 (https://www.loc.gov/marc/holdings/hd852.html), but that may be populated in other holdings record tags (863 etc). All that said, not sure if we need additional granularity for enumeration per holding in SOLR or not just yet, but if so, that may require additional data in the OAI.

**Comment by maxkadel** [comment]
You're right about the 852 field, and I haven't played with the OAI enough to know quite how our data looks for serials. All the test objects in the fixtures right now don't appear to be serials.

**Comment by maxkadel** [comment]
![image](https://user-images.githubusercontent.com/45948126/123875251-55a7f080-d907-11eb-9ab3-a42a23dd0c5e.png)
