### ISSUE TITLE
Configure custom requesting options on Services Page

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/blacklight-catalog#663]
This ticket tracks work already in progress to configure our Emory requesting options in the Services page.

- [x] Basic hold request
- [x] ILL request
- [x] Document delivery request
- [x] Aeon request
- [x] Reserves request

Some of the above work requires support from Ex Libris.

EDIT: Here is an example of the logic issue for which I have a ticket in to Ex Libris.
[https://app.zenhub.com/files/295449627/fdd2953c-4210-4326-8208-e5c637296c45/download](https://app.zenhub.com/files/295449627/fdd2953c-4210-4326-8208-e5c637296c45/download)

**Comment by lisahamlett** [comment]
Basic holds requests, ILL requests, and Aeon requests are working.  Document delivery and reserves requests will require a tweak to the services page by Ex Libris as well as (probably) a tweak to the script that passes the OpenURL to Ares and ILLiad.

**Comment by lisahamlett** [comment]
Next steps:
- Submitting a ticket to Ex Libris for bug where restricting services to certain user groups is not working
- Need assistance to modify scripts for document delivery and reserves requesting so they no longer require a user ID, as the general electronic services do not allow passing of user information from Alma

**Comment by lisahamlett** [comment]
I was able to integrate document delivery and course reserves by linking them through the Alma URL Resolver, but I have not yet restricted them to the user groups and collections that should be allowed to use them.

**Comment by lisahamlett** [comment]
I just poked Ex Libris about fixing the GES logic so I can limit which users can see which options for which items.

**Comment by lisahamlett** [comment]
The logic for reserves requests is added.  Obviously, it won't take effect until Ex Libris fixes the bug.

**Comment by lisahamlett** [comment]
Aeon requesting is complete.
Example: https://emory-psb.alma.exlibrisgroup.com/discovery/openurl?institution=01GALI_EMORY&vid=01GALI_EMORY:blacklight&rft.mms_id=990016709110302486

![image.png](https://images.zenhubusercontent.com/5d379bd44943b962f4d2105c/5ee24962-dc2a-4508-93bb-5299a487b586)

Ares and ILLiad requesting is integrated and will only show for appropriate user groups when Ex Libris fixes the bug.
Example: https://emory-psb.alma.exlibrisgroup.com/discovery/openurl?institution=01GALI_EMORY&vid=01GALI_EMORY:blacklight&rft.mms_id=990022757740302486

![image.png](https://images.zenhubusercontent.com/5d379bd44943b962f4d2105c/ab9155a8-0ba1-414b-8289-ed1f5a34cbbc)

**Comment by lisahamlett** [comment]
I just received this update from Ex Libris:

```
Dear Lisa Hamlett, 

A new comment was received for case #00968853: 

Case Title: Alma GES API Not Showing All GES Options 

Last comment: 
Hello Lisa,

Thank you for contacting Ex Libris Support.

I will transfer ownership of this case to our Alma Tier 2 Support Team for further analysis. An Alma Tier 2 Analyst will be assigned ownership of this case, perform additional research to verify the cause of this problem, and consult with product development to determine how the issue will be addressed. Tier 2 will continue to provide status updates via the case.

Respectfully,

Robert Sebek
Technical Support Analyst 

Status:Tier 1 Analysis 

Priority:Normal
```

**Comment by lovinscari** [comment]
@lisahamlett and @eporter23 - I was able to test and confirm Aeon requesting is working. I will get with Elizabeth Roke when I return as I don't love that the user is required to register if identified as an Emory User but believe this is an Aeon / Rose Library issue as opposed to Blacklight. I don't believe the issue with Ares and Illiad is resolved or it could be I don't have permissions? I am asking @eporter23 to discuss with @lisahamlett and if not completed, believe we should move this into blocked. Thanks!

**Comment by lisahamlett** [comment]
Everyone has to register for Aeon.  They have to do it in Primo now.  That page comes up for everyone all the time in both systems.
As for Ares, you have to have a faculty account AND an open class in order to get in.

**Comment by eporter23** [comment]
@lovinscari @lisahamlett I would like to go ahead and close this one, and create a new ticket for any followups with ExLibris or others.
