### ISSUE TITLE
Clear guest users with their bookmarks and searches

### ISSUE THREAD

**Issue by devanshu-m** [emory-libraries/blacklight-catalog#664]
In this ticket we are going to work on deleting guest users along with the bookmarks and searches that they created. Please refer previous spike tickets: #592, #593

**Comment by lovinscari** [comment]
@devanshu-m - How often does the kron job run?

**Comment by devanshu-m** [comment]
@lovinscari this should be working as expected now. Please note cron job is run at 0th and 30th minute of the hour. There is a possibility that your bookmarks as a guest may get deleted after one hour because there is internal database checking as well to make sure the guest user and their bookmarks are older than 30 minutes.
For example: If you bookmark something at the 45th minute as a guest user, those bookmarks will not get deleted when cron is run at the 0th minute of the hour, but will be deleted at the 30th minute. It will be best to check if this is working after one hour.
