### ISSUE TITLE
Provision new Google Analytics account in larger LTDS account 

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/blacklight-catalog#666]
This ticket follows work done in ticket #594 and also closely relates to work in #667.

Standard configurations
- [x] Generate new sub-account code for development 
- [x] Generate new sub-account code for and production
- [x] Configure the account to roll up into an existing analytics account for LTDS, if applicable
- [x] Configure [site search tracking](https://support.google.com/analytics/answer/1012264?hl=en#zippy=%2Cin-this-article) for user-entered query terms

Desired enhancements: 
- [x] [Configure search categories](https://support.google.com/analytics/answer/1012264?hl=en#zippy=%2Cin-this-article) (search_field) to differentiate between use of
Keyword search
Title search
Author search
Subject search
Advanced search

If the above is not feasible in Google Analytics configurations, this may become part of ticket #667.

**Comment by libdgg** [comment]
`
<script async src="https://www.googletagmanager.com/gtag/js?id=G-DZ32K8GZMM"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-DZ32K8GZMM');
</script>`

**Comment by libdgg** [comment]
GA set up in test environment first. Global Site Tag is attached to this and the related ticket to implement into the product as a next step so we can proceed with testing.

**Comment by eporter23** [comment]
I set up site search tracking in the new test account. This allows us to see user search terms as well as which type of search they are using (basic vs. advanced) ![Screen Shot 2021-11-08 at 10.13.08 AM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/05c386b4-d9db-4e78-88d3-49cc422f330d)

**Comment by libdgg** [comment]
@eporter23 Do you think this is ready for developers to implement for the test instance at this time ( ticket #667 )?

**Comment by eporter23** [comment]
@libdgg yes, and I moved that ticket up in the backlog.

**Comment by eporter23** [comment]
We have now created a second account for production. I will update the additional ticket to add this account info to production.
