### ISSUE TITLE
Integrate Google Analytics code and custom events into Blacklight application

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/blacklight-catalog#667]
This ticket follows work done in ticket #594 and also closely relates to work in #666. See also[ DCE's setup docs](https://curationexperts.github.io/recipes/patterns/google_analytics.html).

See also our implementation in Lux.

- [x] Add standard Google Analytics JS and account code (testing account and production account) - test account info in #666

Add additional JS as needed for custom event tracking
- [x] Capture on-click events when users click on a facet heading, to track the use of facets
- [x] Capture an on-load event to track page views for a records associated with a given holding repository (`library_ssim`)
- [x] Capture an on-load event to track page views for a given Resource Type (`format_ssim`)

**Comment by libdgg** [comment]
[Global Site Tag](https://emory-my.sharepoint.com/:w:/r/personal/rmetz_emory_edu/Documents/LTDS%20Shared%20Documentation/Projects/Project%20Documentation/Blacklight%20Discovery%20Layer%20Phase%201/Scrum%20Team/Work%20Planning/GoogleAnalytics%20Global%20Site%20Tag%20for%20Test.rtf?d=w7faa099a6dfb4ccd819c7dc3aa70132c&csf=1&web=1&e=JlrB4T)

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/blacklight-catalog/pull/1045

**Comment by eporter23** [comment]
@bwatson78 tracking is up and running! Pending some minor category naming adjustments this will be good to go.

**Comment by eporter23** [comment]
@tmiles2 @bwatson78 just a reminder that we still have to add this to the production environment once that account code is created. To keep track of that I can create a new ticket.
