### ISSUE TITLE
Delivery Options for Oxford users

### ISSUE THREAD

**Issue by mark-dce** [emory-libraries/blacklight-catalog#673]
**STORY**
As an Oxford campus patron, I would like delivery locations appropriate to my location when I request a circulation hold, so that I don't have to travel to the main campus.

**ACCEPTANCE**
When I log in as an Oxford campus user
- [x] Oxford appears at the top of the delivery list

NOTE: See #674 for music media specific overrides

**Comment by alexBLR** [comment]
This work has been done by @maxkadel here: https://github.com/emory-libraries/blacklight-catalog/blob/main/app/models/hold_request.rb#L70-L86
