### ISSUE TITLE
Delivery Options for music media and other restricted music holdings

### ISSUE THREAD

**Issue by mark-dce** [emory-libraries/blacklight-catalog#674]
**STORY**
As a music media librarian, I would like to restrict locations that patrons can pick up specific types of media, so that we don't have to send media to other library locations.

**ACCEPTANCE**
When a patron can request materials from media-specific holding locations
- [x] Oxford Users, the delivery pickup location is restricted to to the Oxford College Library
- [x] All other users, the delivery pickup location is restricted to the music library 

NOTE: This rule takes precedence over Oxford Delivery options described in #673

SAMPLE ITEMS
990011519900302486 Concertos for recorder and flute (CD)
990000897490302486 Soepa

<img width="961" alt="image" src="https://user-images.githubusercontent.com/3064318/122326740-5ba6d600-cef2-11eb-8f16-dd98c3c193c3.png">

**NON-OXFORD USERS**
<img width="968" alt="image" src="https://user-images.githubusercontent.com/3064318/122326961-bc361300-cef2-11eb-8737-bc8f4e28e3e4.png">

**Comment by alexBLR** [comment]
The work has been done by @maxkadel here:
https://github.com/emory-libraries/blacklight-catalog/blob/main/app/models/hold_request.rb#L70-L78
