### ISSUE TITLE
One-step circulation request via API - single item titles

### ISSUE THREAD

**Issue by mark-dce** [emory-libraries/blacklight-catalog#677]
**ACCEPTANCE**
When only one item exists for a title and I click on "Request item/Request"
- [ ] Take me directly to the delivery location screen
- [ ] Once I enter delivery info and click submit, send a request for the item

SAMPLE ITEMS
9937271562602486 Art is everything : a novel - Only one copy at Woodruff
990012931580302486 The practice of the presence of God - Only one copy at Pitts

**Comment by eporter23** [comment]
After reviewing, we think this is the same work as #678.

**Comment by mark-dce** [comment]
The book 9937271562602486 shows as being available and I can request it through primo, but not through blacklight

![image](https://user-images.githubusercontent.com/3064318/124008569-2abeaa80-d9a2-11eb-8f60-e95183aa29f9.png)


![image](https://user-images.githubusercontent.com/3064318/124008399-fe0a9300-d9a1-11eb-9175-3fb25a9c174e.png)

**Comment by mark-dce** [comment]
FWIW - Alma seemed to be having issues today, so this may have been an API response time issue.  Folks should make sure they can reproduce the issue - if you can't I'd be comfortable closing this ticket for now.  I had this error above happen to me twice while testing, but I was also able to successfully request two other titles including the MLA handbook, so the problem I saw may have been due to some transient system issue.

**Comment by bwatson78** [comment]
Record 9937271562602486 hasn't been added to sandbox, which we're operating from. It was created for Alma on 02/18/21, which was three days after the last push of records into sandbox.

**Comment by lisahamlett** [comment]
Alma Sandbox was last synced with production on 2/13/21.  Any records created or updated in production after that date WILL NOT be reflected in Sandbox.

The next sync with production will be the Sunday after the Alma release on production environments in August.  (August 8, 2021)

Reference:
https://knowledge.exlibrisgroup.com/Alma/Release_Notes/Release_and_Maintenance_Schedule

If we REALLY need a refresh another time and can justify it (such as we broke something), I can put in a request to Ex Libris for that, but we can't do it every two weeks.

**Comment by lovinscari** [comment]
I am going to hold off closing this ticket until I meet with App Dev team on Monday to review the current configuration of getting real time availability from production Alma and making requests through Sandbox.
