### ISSUE TITLE
Circulation request via API - require login before providing requesting options

### ISSUE THREAD

**Issue by mark-dce** [emory-libraries/blacklight-catalog#680]
**ACCEPTANCE**
When a user is not logged in and they click on the "Request Item" split-button,
- [x] Provide login options for Affiliate (Ex-Libris) and Emory (Shibboleth) users
     - [x] Create a login choice page. When a user clicks the login button, they should go to a page where they can choose to login with shibboleth or the affiliate login. If database login is enabled for developers, it should show up too.
- [x] Return the user to the single item page once they are logged in (i.e. redraw the page with appropriate request options and circulation policy info)
     - [x] More generally, setup affiliate login to take the user back to the page they were on before they stopped to log in.

**Comment by lovinscari** [comment]
I tried testing this today but found a bug with the affiliate login that prevents me from completing my test. As soon as the bug is resolved I will continue my testing.

**Comment by lovinscari** [comment]
Disregard above comment as it was determined the change to affiliate logins is not a bug but rather a change to the process.
