### ISSUE TITLE
Implement detailed design for holding and item display

### ISSUE THREAD

**Issue by mark-dce** [emory-libraries/blacklight-catalog#681]
**ACCEPTANCE**
- [x] Request options are moved to a single title-level split button (see #680, #679, #677, #678) - see wireframe
- [x] Holdings show Library, Location, and Call number per wireframe
- [x] Holdings show holding-level description and availability per wireframe
- [x] Holdings show expand/collapse options next to the availability listing ▶️🔽
- [x] When a holding is expanded
    - [x] Item-level details show
         - [x] Barcode	
         - [x] Type
         - [x] (circulation) Policy (when the user is logged in)
         - [x] Description
         - [x] Status
   - [x] The height is limited to a max of 5 items
   - [x] When there are more than items than can be displayed, provide a scroll bar

**Comment by norm0** [comment]
![33e1372f-2806-4954-bd76-c8b31f310762.png](https://images.zenhubusercontent.com/5f8492d49b473a0cef37940f/562a3d30-4df8-4564-986e-8615405d92f5)

**Comment by norm0** [comment]
Scrolling tables for longer than 5 holding items:
![screencapture-localhost-3000-catalog-990007890860302486-2021-06-28-13_34_58.png](https://images.zenhubusercontent.com/5f8492d49b473a0cef37940f/1a815263-f994-405e-ae96-871f766dabca)

**Comment by mark-dce** [comment]
Looked great at today's demo!
