### ISSUE TITLE
Two-step circulation request via API - more than one unique item

### ISSUE THREAD

**Issue by mark-dce** [emory-libraries/blacklight-catalog#682]
**ACCEPTANCE**
When unique* items exist in one or more holdings for a title and I click on "Request item/Request"
- [x] Take me an item-level selection page
    - [x] Show the call number and description for each item that is available to me based on circulation policy
- [x] When I selected a unique item, take me to the delivery location screen
- [x] Once I enter delivery info and click submit, 
    - [x] Use the common holding precedence to decide which item to request

**NOTE* we can determine an item's uniqueness by the presence of an item level description on any of the items

Sample Items:
990025817540302486 Letters of John James Audubon, 1826-1840 - Single holding with multiple volumes
990008529070302486 The divine comedy of Dante Alighieri - Multiple holdings with multiple volumes

**Comment by mark-dce** [comment]
This should take me to a page that asks me to select between multiple volumes - like kleene currently does

So, for **The divine comedy of Dante Alighieri** https://blackcat-test.library.emory.edu/catalog/990008529070302486, I should get a page that asks me which volume I want to check out.  (e.g. V1, V2, or V3)

**Comment by lovinscari** [comment]
I am not sure why the end user would not be able to select multiple items in this example. I am going to accept this as is as this was not specifically called out and I will put in a new ticket for an enhancement to this.
