### ISSUE TITLE
Deploying and testing on production [placeholder]

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/blacklight-catalog#683]
Before our DCE engagement ends, we should confirm that we can deploy and test functionality on our production environment.

TASKS
- [x] Deploy to production
- [x] Do an index/reindex

ACCEPTANCE
- [ ] Track and capture the total reindex time for production and compare to the total reindex time on test to determine if 
- [ ] Confirm that https://blackcat.library.emory.edu is running the most current release of the application
- [ ] Confirm that an open search on production returns the expected number of results (> 4.85M titles)

Note: the DLP Curate environment will be running a fixity check starting 6/20 and may continue for a week or more. We should avoid restarting SOLR in production while this is running if possible.

**Comment by mark-dce** [comment]
PROVISIONAL PLAN
* Wednesday 6/23 afternoon, get current release deployed to production 
* Thursday 6/24 morning, begin production reindex of full data set
* Monday 6/24 stand up, status-check-in, determine if we need to set aside any additional time to address newly discovered issues.
