### ISSUE TITLE
Login Revisions

### ISSUE THREAD

**Issue by rotated8** [emory-libraries/blacklight-catalog#685]
These are some punch list features to wrap up authentication.

- [ ] Create a login choice page. When a user clicks the login button, they should go to a page where they can choose to login with shibboleth or the affiliate login. If database login is enabled for developers, it should show up too.
- [ ] Setup affiliate login to take the user back to the page they were on before they stopped to log in.

**Comment by mark-dce** [comment]
merged these requirements into #680
