### ISSUE TITLE
One-step document (ILLiad) request via API - single item titles

### ISSUE THREAD

**Issue by mark-dce** [emory-libraries/blacklight-catalog#687]
**ACCEPTANCE**
When only one item exists for a title and I click on "Request item/Get Article or Chapter"
- [x] Take me directly to ILLIAD
- [x] Pre-fill the request form with the available metadata about the title

SAMPLE ITEMS
9937271562602486 Art is everything : a novel - Only one copy at Woodruff
990012931580302486 The practice of the presence of God - Only one copy at Pitts

**Comment by lovinscari** [comment]
I am unsure what the acceptance criteria was for this issue. I have confirmed Document Delivery Request is working for a physical item request.
