### ISSUE TITLE
Two-step document (ILLiad) request via API - more than one unique item

### ISSUE THREAD

**Issue by mark-dce** [emory-libraries/blacklight-catalog#688]
**ACCEPTANCE** 
When unique* items exist in one or more holdings for a title and I click on "Request item/Get Article or Chapter"
- [x] Take me an item-level selection page
    - [x] Show the call number and description for each item that is available to me based on circulation policy
- [x] When I selected a unique item, take me to ILLiad
- [x] The link to ILLiad request form should be populated with all the available title metadata

**NOTE* we can determine an item's uniqueness by the presence of an item level description on any of the items

Sample Items:
990025817540302486 Letters of John James Audubon, 1826-1840 - Single holding with multiple volumes
990008529070302486 The divine comedy of Dante Alighieri - Multiple holdings with multiple volumes

**Comment by alexBLR** [comment]
![Screen Shot 2021-07-13 at 8.37.31 AM.png](https://images.zenhubusercontent.com/5c488275c10ae96cd915967b/c54f28f6-e2b9-4ad8-85a7-08ff4ba29a6c)

![Screen Shot 2021-07-13 at 8.37.44 AM.png](https://images.zenhubusercontent.com/5c488275c10ae96cd915967b/52b629d3-c036-448e-ae08-4eeca181baad)

![Screen Shot 2021-07-13 at 8.38.33 AM.png](https://images.zenhubusercontent.com/5c488275c10ae96cd915967b/6c8ba370-fd0a-48ec-bb95-5933b7199d9f)

**Comment by lovinscari** [comment]
@alexBLR - When testing this against 990008529070302486, and selecting Volume 3 from Woodruff, I don't see the correct volume information populated in the Illiad request. ![TwoStepIlliad.png](https://images.zenhubusercontent.com/5c4a1fe1e9b5fb46bcedb9fc/86472466-14fa-4fa2-bbb8-3207227792aa).

I can't tell from Mark's acceptance criteria if this was specifically called out. Please let me know if you prefer I submit a new ticket for this? Thanks.

**Comment by alexBLR** [comment]
@lovinscari, I just finished reviewing this. We need to create a separate ticket for it.

**Comment by lovinscari** [comment]
Per Zo's comment, I am going to close this ticket and will create a new ticket documenting the expected behavior.
