### ISSUE TITLE
Style new UI CDI view

### ISSUE THREAD

**Issue by libah** [emory-libraries/blacklight-catalog#689]
Acceptance criteria:

- [x] Create new view
- [x] Style new view
   - [x] Header with Emory Logo
   ~~- [ ] Link back to Catalog (not applicable)~~
   ~~- [ ] Footer? ~~
   - [ ] Other styles to match pattern library

**Comment by norm0** [comment]
@CB987 @libah Can you schedule time to show me where these styles can be managed?

**Comment by norm0** [comment]
We had a scheduled meeting for 06/22/2021 and have a happy path forward.

**Comment by norm0** [comment]
Updates:

- Footer designs only would work on the homepage.

https://emory-primosb-alma.hosted.exlibrisgroup.com/primo-explore/search?query=any,contains,yacht&tab=default_tab&search_scope=cdi&vid=newuicdi&offset=0

![screencapture-emory-primosb-alma-hosted-exlibrisgroup-primo-explore-search-2021-06-24-16_17_18.png](https://images.zenhubusercontent.com/5f8492d49b473a0cef37940f/1552f869-99ef-414b-abe1-a6256e250d61)

**Comment by lovinscari** [comment]
@norm0, @libah, @CB987 - This looks pretty good and certainly understand the limitations. I think you said it is possible to create a link to return to Blacklight in the header?
