### ISSUE TITLE
Delivery Options for restricted Oxford items

### ISSUE THREAD

**Issue by mark-dce** [emory-libraries/blacklight-catalog#693]
**STORY**
As a collection manager, I only want to allow certain items to be requested and used by Oxford patrons

**ACCEPTANCE**
When I log in as an Oxford campus user and the item is restricted to Oxford use
- [x] Oxford is the only location that appears in the delivery list

NOTE: See #674 for music media specific overrides

**Comment by alexBLR** [comment]
This ticket has been done by @maxkadel : https://github.com/emory-libraries/blacklight-catalog/blob/main/app/models/hold_request.rb#L71-L72
