### ISSUE TITLE
SPIKE: CSS Refinements - Punchlist

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/blacklight-catalog#694]
Running list of CSS refinements will be collected here, and addressed later in Sprint 14.

- [Punchlist](https://docs.google.com/document/d/1TfiTa7wdHPcVA8uNbkrH2MtZDYbBI5SPLRV4Ka2yfq4/edit?usp=sharing)

**Comment by eporter23** [comment]
@norm0 @mark-dce I started a CSS punch list doc which is linked to this ticket.

**Comment by lovinscari** [comment]
@eporter23 - Can you please review the changes made to ensure completeness? thanks!

**Comment by eporter23** [comment]
@lovinscari there are a few items on the punchlist that can't be tested (blocked by the Bookmarks bug) and some haven't yet been implemented. I'll check with you about how we want to proceed.

**Comment by lovinscari** [comment]
I am going to close this large ticket and open new tickets with individual items based on results of the punchlist.
