### ISSUE TITLE
Item not in discovere is showing in blackcat-test

### ISSUE THREAD

**Issue by libdgg** [emory-libraries/blacklight-catalog#697]
This item is blackcat-test
https://blackcat-test.library.emory.edu/catalog/990015218550302486

Is not in our production discovere product
 
using the mmsid to try and find it: 990015218550302486

http://discovere.emory.edu/primo_library/libweb/action/search.do?fn=search&ct=search&initialSearch=true&mode=Basic&tab=emory_catalog&indx=1&dum=true&srt=rank&vid=discovere&frbg=&tb=t&vl%28freeText0%29=990015218550302486&scp.scps=scope%3A%28repo%29%2Cscope%3A%2801EMORY_ALMA%29%2CEmory_PrimoThirdNode&vl%28341573392UI1%29=all_items

**Comment by bwatson78** [comment]
@libdgg I just reindexed this item in test and can confirm that the indexer does not consider this record a deleted or suppressed record. I am guessing that the publishing job marking this as deleted/suppressed hasn't process yet.

**Comment by rotated8** [comment]
According to Laura: "Its location is XL:  Permanently Lost.  That is probably a suppressed location (ask Lisa).  It had an item, no indication of electronic location."

**Comment by lovinscari** [comment]
I have confirmed this item is no longer showing in Library Search
