### ISSUE TITLE
Catch-all exception/error handling 

### ISSUE THREAD

**Issue by mlooney** [emory-libraries/blacklight-catalog#700]
Current behavior for errors results in a blank page when an unhandled error occurs.  

Unhandled errors should render an appropriately styled & branded exception/outage page.

**ACCEPTANCE**
- [x] Display a success message ONLY WHEN we receive a specifically identifiable success condition;  
OTHERWISE
- [x] Display a general error message; UNLESS, we can identify and describe a more specific error condition - handled in #699

**Comment by norm0** [comment]
![screencapture-libraries-emory-edu-404-2021-06-23-13_41_59.png](https://images.zenhubusercontent.com/5f8492d49b473a0cef37940f/0e51bf17-18d3-46f4-9398-c7f3f54983bc)

**Comment by mlooney** [comment]
All the standard errors (500, 422 & 404) now look like this


![image.png](https://images.zenhubusercontent.com/5e5d3aa83ca793986edab47d/408c8a1a-31d0-45d5-a096-dafd3f929db7)


As the styling is already on the punch-list, we can probably close this

**Comment by norm0** [comment]
Updated content for 404, 422, 500

![screencapture-localhost-3000-404-2021-06-25-12_34_49](https://user-images.githubusercontent.com/8102/123464015-e0a88400-d5b1-11eb-848f-f873a9be1655.png)
![screencapture-localhost-3000-422-2021-06-25-12_35_00](https://user-images.githubusercontent.com/8102/123464036-e69e6500-d5b1-11eb-9b41-5f0342ccee35.png)
![screencapture-localhost-3000-500-2021-06-25-12_35_54](https://user-images.githubusercontent.com/8102/123464043-ea31ec00-d5b1-11eb-8eb0-ef7e9516b1a4.png)
