### ISSUE TITLE
Content Types in Index: Count Comparison 

### ISSUE THREAD

**Issue by tmiles2** [emory-libraries/blacklight-catalog#72]
As the product owner for the Blacklight Discovery Layer project, I would like a detailed report of the content types and counts of various resource types from the OAI-PMH data from Alma that are imported into to the Solr Index

The acceptance criteria will compare the report of Solr Data with reports for physical and electronic items provided by Lisa Hamlett in the following reports looking specifically at the Physical or Portfolio Material Type and the bibliographic record counts for each file. 

Physical Item Counts - https://emory.box.com/s/rmsglt0w6ccduosu4ak84ciaqfy9lqew
Electronic Item Counts - https://emory.box.com/s/4q0vrqvqm1d1zxfrnr4yoi1g2hrh7wln

User Acceptance Criteria
- [x] Update solr schema on arch
- [x] Run OAI-PMH Publishing Profile as currently configured by Lisa Hamlett into a SOLR instance that is linked to the Blacklight Application to determine if counts can be seen within Blacklight application.

**Comment by devanshu-m** [comment]
Meeting is setup for anyone who is interested in learning about mapping (we are all learning together) for Tuesday at 3: https://emory.zoom.us/j/94525466640

**Comment by devanshu-m** [comment]
Counts from SOLR updated in this doc:
https://emory.app.box.com/file/756293381506?s=g9knwk2ty5fxyk8stdex9wv1nj807xdz

I will meet with @lisahamlett tomorrow to compare counts and provide final report.

**Comment by lisahamlett** [comment]
I cannot meet today -- I've got to be on campus working on an issues.  I can meet with you Monday, anywhere my calendar is open.  @devanshu-m

**Comment by devanshu-m** [comment]
For @lovinscari :
**69066** items in ALMA did not get imported into SOLR. 
Full report is here: https://emory.app.box.com/file/756293381506?s=g9knwk2ty5fxyk8stdex9wv1nj807xdz

Our next steps (according to Lisa and I) should be:
- Priority number 1 should be get the total number of bib items same in ALMA and SOLR after second pass of mappings.
- Second priority should be correct number of physical and electronic records.
- Third on the list is getting as close to content type count as possible.

**Comment by lovinscari** [comment]
@devanshu-m and @lisahamlett - Thank you for all of your work on this. The report is very helpful and I will create a new ticket to address some of the steps that should be taken to get the counts as close as possible.
