### ISSUE TITLE
Load Services Page link from Blacklight into new tab/window

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/blacklight-catalog#724]
This ticket follows work to configure basic branding for the Services Page within Alma (#655). Related to that, we want the Services Page to load in a new tab, so that a user can more readily get back to Blacklight. Currently, it replaces the same window that is open.

![Screen Shot 2021-06-29 at 11.07.36 AM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/d109c14f-d600-49cd-9b46-a0aefdc37fc3)

From our View Single Item page, adjust the following:

- [ ]  Modify the existing Services Page link to open in a new tab, so that users can easily return to Blacklight.

**Comment by mark-dce** [comment]
Reviewed at today's demo
