### ISSUE TITLE
STORY: Test and document Solr Sync with Alma

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#73]
As the product owner of the Blacklight Discovery Layer product, this story contains various tasks about syncing the Blacklight Solr Index with Alma. The Solr Index should sync so that current bibliographic records, holdings, item records, and portfolios are showing in Blacklight including newly acquired materials and materials removed from the collection. 

Acceptance Criteria:

- [x] Complete task for Solr Sync Performance Test

- [x] Document standard operating process for Alma Sync

**Comment by tmiles2** [comment]
These could be under: Performance/Capacity - epic

**Comment by lisahamlett** [comment]
Added Alma info to #74.

**Comment by lisahamlett** [comment]
Brad added Solr info to #74 as well.
