### ISSUE TITLE
Implement Bookmark Page Citation button

### ISSUE THREAD

**Issue by norm0** [emory-libraries/blacklight-catalog#742]
Implement function for styles in ticket #569. 

**Goal:** 
 [style_bookmarks_citation_694 Branch](https://github.com/emory-libraries/blacklight-catalog/tree/style_bookmarks_citation_694) has the design implemented but is not functioning to load the citation modal 

**Acceptance:**
- [x] Click/select "cite" button to see citation notes for collected bookmarks.
- [x] Remove old "cite" tools/link

![screencapture-localhost-3000-bookmarks-2021-06-30-12_09_57.png](https://images.zenhubusercontent.com/5f8492d49b473a0cef37940f/baf5891e-d23e-4052-b7d1-eb4c42f6726a)

**Comment by eporter23** [comment]
FYI, to see an example of how the Cite feature should function on the Bookmarks page, you can go to https://digital.library.emory.edu/bookmarks. 

When a user clicks on the Cite button, it should launch the Cite modal with multiple selected records included.

Screenshot below:
![Screen Shot 2021-07-15 at 12.25.57 PM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/46a2fa15-6ba2-4553-beb7-35367f997048)

**Comment by bwatson78** [comment]
I just wanted to note that the only work I had to do was fix the logic--the styling was already merged with commit f24101a98ccf238af591f28a1a1c3a95a4f90001.

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/blacklight-catalog/pull/771

![Screen Shot 2021-07-21 at 3.15.47 PM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/512b93ec-283b-4b01-83b0-3633ae384278)

**Comment by lovinscari** [comment]
Looks great. Thanks @bwatson78
