### ISSUE TITLE
SPIKE: Determine a way to back up and reload Configs for the Service Page

### ISSUE THREAD

**Issue by tmiles2** [emory-libraries/blacklight-catalog#746]
Alma Sandbox was last synced with production on 2/13/21.  Any records created or updated in production after that date WILL NOT be reflected in Sandbox.
The next sync with production will be the Sunday after the Alma release on production environments in August.  (August 8, 2021)
https://knowledge.exlibrisgroup.com/Alma/Release_Notes/Release_and_Maintenance_Schedule

This means we need to have anything we've done for the services page documented and backed up by then because after the sync, I will have to have Ex Libris switch us back to Alma-Summon and replace everything we've done so far, including all those bloody norm rules for Atlas requesting.

**Comment by tmiles2** [comment]
Additional comments: 
- Ex Libris will not back or preserve the work when they do the sync.

**Comment by lisahamlett** [comment]
I have scheduled a reminder for Alex, Emily, and myself on 8/6 to make a last backup of any changes before the update.  I can forward to anyone else who might like to look at it.
