### ISSUE TITLE
SPIKE: Investigate what is needed to configure export to EndNote functionality 

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/blacklight-catalog#755]
Our Export to RIS feature produces what appears to be a valid RIS output, but it does not import into EndNote (tested on Macs only). The RIS output does, however, import into Zotero. @bwatson78 indicated the default Blacklight includes an "Export to Endnote" feature. 

To investigate:

- Endnote system requirements for importable formats
- Original blacklight/MARC export to Endnote capability

Results from the investigation should be documented within this ticket and a new ticket will be created for modifications to export to RIS and/or enabling export to Endnote based on findings from investigation.

**Comment by bwatson78** [comment]
@eporter23 The process would be very similar to how RIS exporting was set up. Currently, the method in place pulls from the marc record, so I'm guessing that we'd prefer to pull directly from our solr document mapping. Below is what is being pulled:
```
end_note_format = {
      "%A" => "100.a",
      "%C" => "260.a",
      "%D" => "260.c",
      "%E" => "700.a",
      "%I" => "260.b",
      "%J" => "440.a",
      "%@" => "020.a",
      "%_@" => "022.a",
      "%T" => "245.a,245.b",
      "%U" => "856.u",
      "%7" => "250.a"
}
```

There are Blacklight developer notes above the method that discuss problems with using Endnote:
```
  # Endnote Import Format. See the EndNote User Guide at:
  # http://www.endnote.com/support/enx3man-terms-win.asp
  # Chapter 7: Importing Reference Data into EndNote / Creating a Tagged “EndNote Import” File
  #
  # Note: This code is copied from what used to be in the previous version
  # in ApplicationHelper#render_to_endnote.  It does NOT produce very good
  # endnote import format; the %0 is likely to be entirely illegal, the
  # rest of the data is barely correct but messy. TODO, a new version of this,
  # or better yet just an export_as_ris instead, which will be more general
  # purpose.
```
Those comments make me feel that RIS is the way to go, so I'll look into what Endnote needs to digest an RIS file for the rest of this ticket. I'll check with Emily on Slack to make sure that's not a fool's errand.

**Comment by bwatson78** [comment]
@eporter23 I've discovered that Endnote wasn't digesting our RIS' because there is a spacing issue between the field key and the separating dash (i.e. `TY  - blah` good, `TY - blah` bad).

I will be able to address this bug within the estimation of this ticket.

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/blacklight-catalog/pull/768
No screenshot necessary.

**Comment by lovinscari** [comment]
@bwatson78 - thank you so much for fixing the export to RIS functionality to open with EndNote!
