### ISSUE TITLE
Setup production with new load balancer

### ISSUE THREAD

**Issue by libah** [emory-libraries/blacklight-catalog#757]
Production is not pointing to the new load balancer according to McClain who reached out to us.

**Comment by libah** [comment]
The environmental variables for production have been changed. The .env.production SOLR url has now been changed to point to the solr load balancer. 
New URL
SOLR_URL="http://internal-solr-prod-alb-1200081172.us-east-1.elb.amazonaws.com/solr/blackcat_collection"

**Comment by libah** [comment]
The documentation that needs to be updated (I don't have write permissions) is here:

https://emory-my.sharepoint.com/:w:/g/personal/cbrittl_emory_edu/EaE1CdzsQrxIqXloPaslImsBMUWxzRBRqDSDSyuNPD4P2g?e=4%3Atwcdvp&at=9&wdLOR=c2C819F95-C711-A844-A18D-9D77DAC5F59F

**Comment by rotated8** [comment]
The documentation referenced above has been superseded by placing our ENV vars in 1Password.
