### ISSUE TITLE
SPIKE: Review possible refinements to metadata with metadata subgroup

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#759]
A handful of "cataloging cleanup" items have been identified after some initial testing and feedback. These items should be reviewed with the Metadata Subgroup to determine if the cleanup should happen by revising the catalog records or if any development is needed to modify the data in Solr. 

Acceptance Criteria:

- [x] Ensure all information is current on [Cataloging Cleanup spreadsheet](https://docs.google.com/spreadsheets/d/1wEhOovQBYudZjFxLc6YQhbN9WDSLC3JHreqAQqAToPM/edit?usp=sharing) 

- [x] Schedule meeting with Sofia and any other members of the Metadata Subgroup who can attend to review the spreadsheet and devise an action plan including how any cleanup of the cataloging records should be communicated to associated stakeholders.

- [x] Create new issues for any cleanup that should be resolved by modifying data in Solr.

**Comment by eporter23** [comment]
@lovinscari Please see ticket #785 for some date-related refinements
