### ISSUE TITLE
Confirm alma harvest into solr instance is working

### ISSUE THREAD

**Issue by devanshu-m** [emory-libraries/blacklight-catalog#76]
This ticket is to make sure everyone has a working rake task to be able to harvest alma data into their local solr instance:

Instructions [here](https://wiki.emory.edu/display/BDL/Using+SolrMarc+to+harvest+data+from+Alma+into+Solr+Index) are in the wiki

- [x] Brad
- [x] Zo
- [x] McClain
- [x] Devanshu

**Comment by tmiles2** [comment]
The instructions for the solr sync are in the wiki, https://wiki.emory.edu/display/BDL/Using+SolrMarc+to+harvest+data+from+Alma+into+Solr+Index

**Comment by bwatson78** [comment]
It worked for me. Just a bit of advice: switching VPNs on the fly doesn't seem to work very well. You may have to completely quit the VPN application, reopen, and choose vpnproxy.

**Comment by bwatson78** [comment]
Will produce a PR for a README for these instructions within an hour.

**Comment by bwatson78** [comment]
The above-mentioned PR has already been deployed.
