### ISSUE TITLE
SPIKE: Determine work involved with implementing Blacklight gem that includes ArticlesPlus suggestion within search results

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#760]
As the product owner, I would like to explore the work involved with implementing a gem used by Stanford University Libraries Searchworks for showing results from ArticlesPlus within the catalog search results as shown on the screenshot ![ArticlesPlus_Stanford.png](https://images.zenhubusercontent.com/5c4a1fe1e9b5fb46bcedb9fc/48115bdd-7212-4408-8cd8-a78c789c4611)

For Emory University Libraries, the desired action would be to capture search results from the new Primo view that is being developed to search Central Discovery Index (CDI) and include highlights from the search results from CDI in a box after the top three results from the catalog. The information in the Articles Plus gem would provide high level results if the same search was performed in CDI including total number of results and counts according to each resource type. The counts (total and faceted) should be active links that take the user to those results within CDI (see Searchworks for example workflow).

The details of the work involved to implement this gem should be documented within this ticket and reviewed with the product owner if she has any questions.

**Comment by rotated8** [comment]
[Searchworks Gemfile](https://github.com/sul-dlss/SearchWorks/blob/master/Gemfile)

**Comment by alexBLR** [comment]
Here is the feature development for the bento-box:
https://github.com/sul-dlss/SearchWorks/commit/9f72da1a903524305f6039d8a05b877dd32ca3f4

The work needs to be divided into a couple of sections:
1) Create model to pull (fetch) data from CDI into a json object
2) Create controller to render data into the page
3) Create Javascript frontend to to dynamically populate the view
4) Create css to style the bento box
5) Write unit tests

**Comment by lovinscari** [comment]
Meeting scheduled with @eporter23 to develop wireframes and put a placeholder ticket into New Issues for application development tasks.
