### ISSUE TITLE
SPIKE: Determine work involved with implementing a bento box search results page

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#761]
As the product owner I would like to understand the work involved with implementing a bento box search results page similar to that on the screenshot from Temple University Libraries search results when the user selects to search "Everything"![TempleBentoBox.png](https://images.zenhubusercontent.com/5c4a1fe1e9b5fb46bcedb9fc/7a2f533f-3e3e-4094-b4c1-b4bb3eb12bcd)

This work will likely not be implemented until Phase II of the Blacklight project but I would like to understand

1. How our developers would implement the Bento Box search results for Emory's Blacklight instance

2. How the data source(s) would need to be configured to be included in the bento search results

3. If a Bento Box search results can be implemented with limited data sources and customized at a later date. For example, would it be possible to implement a Bento Box search for the Catalog (Alma records), Articles Plus (CDI View in Primo) and eJournals A-Z (Primo View) initially, and add the website and repositories data in the future.

Details of the proposed implementation and answers to the questions above should be documented within this ticket and reviewed with the product owner if she has any questions after reviewing the details.

**Comment by devanshu-m** [comment]
https://github.com/jrochkind/bento_search

**Comment by lovinscari** [comment]
Thanks @alexBLR for all of your work on this. The details are much appreciated.
