### ISSUE TITLE
SPIKE: Document work needed to fully implement services pages for requesting

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#762]
As the product owner, I believe the best approach for requesting in the immediate future is to use the Alma Services Page. I would like to understand the work remaining to implement the Services page and how the remaining work can/should be distributed among members of the team.

A meeting has been scheduled with the objective to review the work remaining to implement the Services page and any correlation or dependencies with real time availability that is currently configured on the single item view page. The details from the meeting will be linked within this ticket and new tickets will be created based on the work identified.

**Comment by lisahamlett** [comment]
I poked Ex Libris about the ticket regarding display logic for users for general electronic services not working:
[https://app.zenhub.com/files/295449627/09f8705f-b657-40c4-8d03-a949113b0aeb/download](https://app.zenhub.com/files/295449627/09f8705f-b657-40c4-8d03-a949113b0aeb/download)

**Comment by tmiles2** [comment]
pending final outcomes from the meeting

**Comment by lovinscari** [comment]
After the meeting on 7/19/21, Lisa was able to identify some of the additional work needed on the Ama services page including integration with any of the Atlas Products and looking at how the page is configured in the sandbox (currently configured with Summon) and ideally should be setup to use Alma sandbox and Primo sandbox. 

Reading and discussions around the link resolver led the group to believe exploring the work involved with the Primo services page should also be explored. Tickets have been added to look at this work and a decision will be made by the end of Sprint 16 if we will use the Primo Services page or the Alma Services Page.
