### ISSUE TITLE
Diagram and review current setup of Alma and Primo including production and sandbox instances

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#769]
As the product owner, I would like to gain a better understanding of the current configuration of the Alma and Primo instances for Emory Libraries as provided by ExLibris including production and sandbox environments. Diagrams were created by Emily Porter in the [Services Page Documentation](https://docs.google.com/presentation/d/1Mb2zufCP8dYxLhbaNO5KSiDuVSxpKOtmVzEgk2asrt4/edit?usp=sharing), however, it is unclear if either diagram presented depicts the entirety of our Alma/Primo ecosystem. 

According to Laura Ackerman, there is a persistent Primo sandbox but she does advise we consider refreshing the sandbox (requested in a new ticket) before making too many new configuration changes with the new Primo UI. 

Acceptance Testing:

- [ ] Request for members of Core Systems to work together to create a new diagram depicting the current state of the Alma / Primo environments similar to that shown in the Services Page document referenced above.

- [ ] Consult with Laura Ackerman as needed to confirm any specifics of Primo that are unknown to Core System.

- [ ] Link to the diagram within this ticket and place in team review to discuss during one of the sprint meetings (standup or demo) with information about the current configuration and any recommended changes as we look to sunset discoverE and create a new Primo UI to be used in conjunction with Blacklight.

**Comment by lovinscari** [comment]
@AGCooper and @libah - I sent a message in Basecamp providing Efi and Ben with a link to @lisahamlett demo of the services page so they can see the need for a sandbox that mirrors what we currently have in production.

**Comment by lovinscari** [comment]
This ticket also remains blocked until we get the sandbox and production environments created.

**Comment by libdgg** [comment]
This ticket also remains blocked until we get the sandbox and production environments created.

**Comment by libdgg** [comment]
Lisa emailed Efi yesterday with what we needed resynched. We have not heard anything back as of today.

**Comment by libdgg** [comment]
Efi responded on basecamp and to Lisa's ticket on 2021-09-20.
Unfortunately, we cannot change the time of the Alma Sandbox refresh and we will need to update the SB configurations manually. From my experience you can export the configurations to a list and compeer between the list and the SB environment. For the Configurations > Fulfillment > Discovery Interface Display Logic migrated > labels you don’t need to review all 515 lines. The only lines that changed from the OTB version are the lines with the “Last updated” time stamp. Please let me if you have any questions and I will be more than happy to assist.

**Comment by libdgg** [comment]
Lisa will proceed with the manual setup today.

**Comment by lisahamlett** [comment]
I have completed the manual setup including the Atlas integrations.

**Comment by libdgg** [comment]
Lisa may be looking at this and can move it into In Progress if able to start work on it.

**Comment by lisahamlett** [comment]
[https://app.zenhub.com/files/295449627/b30ba8e2-9a4a-4d3e-aa92-bab16cc63aa8/download](https://app.zenhub.com/files/295449627/b30ba8e2-9a4a-4d3e-aa92-bab16cc63aa8/download)

**Comment by lovinscari** [comment]
Thanks @lisahamlett for your document. I think this depicts a good overview of the interaction between Blacklight and the PrimoVE views. I was hoping to see a document that shows a higher level overview of the sandbox and production environments. I am going to put this back into backlog and we can discuss during sprint review/demo on Wednesday.
