### ISSUE TITLE
Develop and document a plan for development and testing of Primo and/or Alma Services pages without interrupting production instances of Alma or Primo 

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#770]
As the product owner, I would like for the Core Systems team to develop and document a plan for testing the new Primo UI features developed for the Blacklight project along with any Alma features (e.g., Alma Services Page) that will represent a production like environment without interrupting production instances of Alma or Primo. If sandbox instances of Alma and/or Primo are used, the sandboxes should represent a production like environment that include holdings and item level records needed to test the complete requesting process from seeing the item is available, to having the ability to place a hold or recall an item, to seeing the item I placed on hold appear in MyAccount. Additionally, new views of PrimoUI could possibly be constructed in this test environment such as the new CDI view where I can access the new view and conduct a search in CDI to determine any issues with the view and/or breadcrumbs associated with the view.

Expected items to be tested:

- Alma services page configuration that enables requesting (GetIT and ViewIT) , enabling electronic services, and viewing MyAccount.

- Primo services page configuration that that enables requesting (GetIT and ViewIT) , enabling electronic services, and viewing MyAccount.

- Testing Link Resolver redirects that would enable use to configure a link resolver redirect and test the functionality and determine if any manual configurations are needed

- Creating and testing new views with the new Primo UI

The documentation should be included within this ticket including any recommended changes to our test environments or changes that would be needed to our production environments before moving Blacklight to production. This work could be performed by either members of the  Core Systems or ExLibris.

**Comment by lisahamlett** [comment]
We will look at this when Alex gets back from vacation.

**Comment by libdgg** [comment]
Lisa, Ann and Alex plan to meet about this Monday 8/9

**Comment by lovinscari** [comment]
This ticket remains blocked until we get the sandbox environments completely setup. We are waiting to get the sandbox finalized until ExLibris support responds to see if they will sync our current production instance with sandbox.

**Comment by libdgg** [comment]
If Lisa does not hear back by middle or next week, will do rebuild. We have time to give ExL a few days after their holidays.

**Comment by libdgg** [comment]
ExL assigned the ticket for the resync to the project team (Efi, et al) this morning.

**Comment by libdgg** [comment]
ExL Case Number: 00988198
SAML metadata file for Primo VE service
Ann is in communication with ExL for [Step 2: Authentication](https://knowledge.exlibrisgroup.com/Primo/Product_Documentation/Go_VE/Step_2%3A_Authentication_Profiles) work for Primo VE

**Comment by libdgg** [comment]
Lisa emailed Efi yesterday with what we needed resynched. We have not heard anything back as of today.

**Comment by libdgg** [comment]
As of today, still no response from ExL on the Salesforce ticket [00990895](https://exlibrisgroup--c.visualforce.com/apex/VF_Case_WithoutJira?id=5004y00001fI3lZAAS) that Lisa submitted for the resync.
I posted on basecamp a request for a check-in meeting with Ophir and Efi next week.
The plan is to see about the ticket status and any response from them on Monday.

**Comment by lisahamlett** [comment]
I have completed the manual sync of sandbox with production.

**Comment by libdgg** [comment]
Lisa may be looking at this and can move it into In Progress if able to start work on it.

**Comment by AGCooper** [comment]
- [ ] Enable Primo VE / Services view in the Alma Sandbox

- [ ] Configure Primo VE CDI view

- [ ] Style Primo VE CDI view

- [ ] Configure Services view

- [ ] Configure custom integrations in the Services view

- [ ] Style the Services view

- [ ] Integrate the Alma sandbox with Blacklight

- [ ] SME testing

- [ ] Enhance / fix bugs as needed or time allows
