### ISSUE TITLE
Refine Cite in Bookmarks button

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#773]
In testing issue [#569](https://app.zenhub.com/workspaces/blacklight-catalog-5f5f84a8a6d29939a0bc5d78/issues/emory-libraries/blacklight-catalog/569), I believe Norm should have specified this is an action button therefore should have the blue background with the white text based on the action buttons of search or login. Please change the existing Cite within bookmarks to a blue background with white text to match search and login buttons.

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/blacklight-catalog/pull/775

Quicktime movie of changes are in PR.
