### ISSUE TITLE
SPIKE: Teach out on Primo and Alma Services Page Development 

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#782]
In an effort to distribute the work around any further Primo New UI and Alma Services Page development, it would be good for thee application developers to have a good understanding with how overall development would work in these areas.

Acceptance Criteria:

- [ ] @AGCooper and @rotated8 determine the format for the teach out (e.g., one longer session or multiple sessions) and schedule sessions accordingly. Sessions can be planned for Sprint 16 with the understanding @AGCooper will be on vacation 8/2 - 8/8 therefore any sessions requiring his attendance should be scheduled around his time out of office.

- [ ] Members of Core Systems prepare teach out session(s) to educate application developers with some of the basics where Primo new UI or Alma Services page application development is concerned. This should be a high-level review as there is an additional ticket to review specifics of Angular JS. 

- [ ] Per the conversation during standup on 8/6, the teachout should also include a review of Primo Studio. 

The outcome of the meeting should be a Team Review for the entire Scrum team on what was discussed. This can also be presented during Sprint Review/Demo.

**Comment by lisahamlett** [comment]
Alex, Ann, and I reviewed this today and we're ready to show Alma Service Page vs Primo New UI View whenever y'all wanna schedule a meeting.  A 1 hour meeting should suffice.  @rotated8
