### ISSUE TITLE
Revise header wireframe with Emory University Libraries logo and name

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#783]
Revise wireframes for header replacing the existing logo with the new logo and name. Different logo options have been presented to Rosalyn for review and for now the name of Blacklight will be replaced with the name of the application. 

Updates: Per Rosalyn, we will use the existing logo and link conventions from the Libraries website and Lux. The product name is "Library Search".

The following changes were identified.

- Utility navigation: change link text "About Catalog" to "About Library Search"
- The logo element that says "Library Catalog" should be changed to "Emory Libraries"
- The Emory Libraries link should point to https://libraries.emory.edu
- The shield link should point to the Blacklight homepage
- The Emory University link text should point to https://www.emory.edu

Tasks
- [x] Generate visual mockup
- [x] Update [Figma file(s)](https://www.figma.com/file/Z7y52FyJlYYjOx7QMAmnyz/Blacklight-Wireframes-v2?node-id=91%3A4720)
- [x] Write implementation ticket - #798

Mockup:

![Screen Shot 2021-07-29 at 1.36.09 PM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/c33794c8-0e12-4138-b282-163c144b68bf)

**Comment by eporter23** [comment]
@CB987, Cari and I confirmed all of the above with Rosalyn earlier today and so I went ahead and wrapped this one up.
