### ISSUE TITLE
URL and DNS Work

### ISSUE THREAD

**Issue by libdgg** [emory-libraries/blacklight-catalog#786]
We should plan for the time it takes to request setup and configuration of the DNS, url and F5 work to meet launch dates.
[INC03290687](https://emory.service-now.com/nav_to.do?uri=%2Fincident.do%3Fsys_id%3D0ed429481b714c50522e964ead4bcbf1%26sysparm_record_target%3Dtask%26sysparm_record_row%3D2%26sysparm_record_rows%3D6%26sysparm_record_list%3Dopened_by%3Djavascript:gs.getUserID()%5Esys_class_name!%3Dsc_request%5Esys_class_name!%3Dsc_req_item%5E123TEXTQUERY321%3DDNS%5EORDERBYDESCzztextsearchyy) is a ticket from January 2020 related to the DNS work for the launch of the libraries website in case it helps.

NOTE: new tickets have been created for the discreet parts of work needed for Certificate, F5, and AWS
Checklist:

- [x] The production url is  search.libraries.emory.edu

- [x] DNS request submitted

**Comment by libdgg** [comment]
@rotated8 @AGCooper Please review this ticket for any further editing or next steps.

**Comment by lovinscari** [comment]
@libdgg - I think I like the search DNS name instead of find.

**Comment by libah** [comment]
Requested dns for 'search.libraries.emory.edu' 7/29

**Comment by libah** [comment]
Working on F5, I have some questions and we are reaching out to the F5 folks. 
Also we will need a certificate for search.libraries.emory.edu

**Comment by libah** [comment]
Still have not heard back about F5.

**Comment by libdgg** [comment]
Closing this ticket as the URL and DNS work is complete. Three new tickets are now on the board for the Certificate, F5 and AWS work.
