### ISSUE TITLE
Alma Collection for Format Testing

### ISSUE THREAD

**Issue by rotated8** [emory-libraries/blacklight-catalog#79]
- [ ] Find out all of Alma's format types, and add them to this ticket
- [ ] Create a new Alma collection for publishing format examples. Add the name to this ticket.
- [ ] Find an example for each of Alma's formats, and add it to the collection
- [ ] Publish the collection for OAI-PMH harvesting.

This ticket is done when a developer can ingest the collection into Solr, and have all of Alma's format type examples.

**Comment by lisahamlett** [comment]
I created norm rule to include MMSIDs and only the LDR positions and MARC fields that indicate material types.  It is currently running on the entire database.
When it is finished, I will have a published list of all material type combinations along with MMSID and will be able to provide a full count.

From there, I will take several of each type and use them to set up a set that I will publish to an new OAI.

**Comment by lisahamlett** [comment]
Depending on Alma's temperament today, the list will be published at some point today or tomorrow.  From there, I should have it ready in a couple hours.

**Comment by lisahamlett** [comment]
Job started at 12/14/2020 13:47:27 EST.  Still running.  Can't do anything until that finishes.

**Comment by lisahamlett** [comment]
[https://app.zenhub.com/files/295449627/9902f3a3-54f6-4632-9ed6-c9f37d50f914/download](https://app.zenhub.com/files/295449627/9902f3a3-54f6-4632-9ed6-c9f37d50f914/download)
[https://app.zenhub.com/files/295449627/17549705-60f6-40f3-baeb-4efab1e80eb9/download](https://app.zenhub.com/files/295449627/17549705-60f6-40f3-baeb-4efab1e80eb9/download)
^^^ These are the totals for everything in the LDR positions 6 and 7

I am working on the OAI now.

**Comment by lisahamlett** [comment]
OAI: https://na03.alma.exlibrisgroup.com/view/oai/01GALI_EMORY/request?verb=ListRecords&set=blacklightmaterialtypetest&metadataPrefix=marc21

Item list in Excel format: [https://app.zenhub.com/files/295449627/4c678507-9cc4-4396-8e11-dff824e231f6/download](https://app.zenhub.com/files/295449627/4c678507-9cc4-4396-8e11-dff824e231f6/download)

**Comment by lovinscari** [comment]
The reports look good to me but want to make sure this passes @rotated8 acceptance test as detailed in the ticket.

**Comment by bwatson78** [comment]
Will test later today.

**Comment by mlooney** [comment]
I have successfully imported this set, resulting in 252 records (the spreadsheet above has some duplicates)

**Comment by bwatson78** [comment]
And I just got the same results.
