### ISSUE TITLE
Create wireframes and identify metadata fields for eJournals A-Z list (facet)

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#790]
As the product owner, I would like to replicate the eJournals A-Z feature currently in discoverE The screenshot ![ejournalsa-z.png](https://images.zenhubusercontent.com/5c4a1fe1e9b5fb46bcedb9fc/b95be2fa-2c76-404b-8691-42d4c84ee629) depicts the current view from discoverE. It has been determined this function will be a new facet view in Blacklight by querying resource type journals and access online. It will be necessary for this facet to function differently from the other facets in Blacklight and perform very similarly to the feature in discoverE. 

FOR METADATA:

- [ ] Identify the specific fields in Solr that should be queried to complete this facet including the list of ejournals.

- [ ] Metadata field that will be used to link the journal name to its provider (unsure of how this currently works in discoverE so some investigation might be needed with this).

- [ ] Metadata fields showing publisher name and beginning date of availability. - It looks like name of publisher and available dates are included below name of title but I am unsure why this does not appear for all titles. If able to figure this out, I believe this information would be helpful?

- [ ] If any updates are needed within Solr, updates should be made to the metadata model and new tickets submitted for the application developers to complete this work (add to backlog).

FOR WIREFRAMES:

- [ ] Create a new wireframe (or wireframes) showing the facet view that will display the electronic journals in alphabetical order. The new view should include:

- Navigation at the top of the view allowing users to navigate to groupings of journals by letter, those that begin with numbers (0-9) and others (for those beginning with punctuation or other characters). The letters should appear first, then the number grouping, then other.

- A search bar for searching eJournals by name.

- Navigation to return to the home page or "back to search"

- Grouping of ejournals by letter (or number or other) - it is not necessary to show all journals in the wireframes but rather how journals are grouped by letter.

- Name of journal title that will link to the journal or provider of the journal if multiple providers. Again, I am unsure how this works today when selecting the journal name as I am presented with a page showing multiple options for access. ![ejournalaccess.png](https://images.zenhubusercontent.com/5c4a1fe1e9b5fb46bcedb9fc/505d2c59-521b-476e-bc5f-e461401d1dc3).

- It looks like name of publisher and available dates are included below name of title but I am unsure why this does not appear for all titles. If able to figure this out, I believe this information would be helpful?

Once wireframes and metadata are completed, review with product owner with recommendation for implementation.

**Comment by eporter23** [comment]
Early [draft started here](https://docs.google.com/drawings/d/11ub-TuvpsKS-72ttkHo6GPnGck3XNcq7c8Yg5kmSkxk/edit).

**Comment by lovinscari** [comment]
Thanks @eporter23. These look great. Depending on what is found in the Spike tickets you added, I think we can discuss how to proceed during our next wireframes meeting.
