### ISSUE TITLE
Update content on About Page - Main Block

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#791]
Please update the content on the [About Page](https://blackcat-test.library.emory.edu/about) 

MAIN BLOCK

About Emory Libraries Search 

The NEW Emory Libraries Search Tool is the primary tool for searching Emory Libraries catalog including books, e-books, videos, journals, articles, and some digital media. Present the roadmap and differences between Primo and Blacklight. Might also look at this under technology.  

 

Technology 

The NEW Emory Libraries Search Tool is developed in Blacklight, which is an open-source Ruby on Rails "engine" that provides a basic discovery interface for searching an Apache Solr index. The product development is part of a multi-phase project that started in 2019.  

 

Accessibility 

Emory Libraries is committed to the principles of universal design and strives to provide equitable services online and in our spaces. We assess and enhance the usability and accessibility of our digital interfaces on an ongoing basis, and use Section 508 of the Rehabilitation Act and current WCAG AA standards as benchmarks. For further information, please use our feedback form or consult Emory’s Department of Accessibility Services. 

 

Questions, Help, and Feedback 

Please visit our Contact page for more information about Emory Libraries collections, catalog, electronic resources, and access.  You can also reach out via our feedback form or visit our project wiki.

**Comment by CB987** [comment]
![Screen Shot 2021-08-17 at 3.50.39 PM.png](https://images.zenhubusercontent.com/5d379c9d5221e52414fca85c/d17098c9-e019-46d6-974b-287a86d29351)

**Comment by lovinscari** [comment]
@CB987 - I opened a new ticket to fix my mistake. Apologies!
