### ISSUE TITLE
Update contact page - Main Block

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#792]
Please update the content on the main block of the Contact Page 

**Emory Library Search Points of Contact** 
Contact points for technical assistance and additional information about our Emory Libraries Catalog and Search

**Send Feedback or Report a Problem** 
Feedback send to the development team (link to https://emory.libwizard.com/f/blacklight)

**Assistance with Emory Libraries Services**
Request a purchase (link to https://libraries.emory.edu/services/purchase-request/index.html)
Ask a Librarian (link to https://emory.libanswers.com/)
Ask eJournals (link to https://libraries.emory.edu/tools/report-issues-with-ejournals.html)
Find a subject librarian (link to https://libraries.emory.edu/contact/subject-librarian-directory.html)
Access Course Reserves (link to https://libraries.emory.edu/services/access-course-reserves.html)
Submit an ILL Request (link to https://libraries.emory.edu/services/submit-ill-request.html)

**Comment by alexBLR** [comment]
@lovinscari 
![Screen Shot 2021-08-16 at 10.46.10 AM.png](https://images.zenhubusercontent.com/5c488275c10ae96cd915967b/69d88453-d84b-4a2f-a3db-2785fc374263)

**Comment by lovinscari** [comment]
@alexBLR - My mistake on the Send Feedback or Report a Problem - Can you change the body text to read "Send feedback to the development team" ? Totally my mistake. Other than that - everything looks good. Thanks!

**Comment by lovinscari** [comment]
Looks good.
