### ISSUE TITLE
Wireframe change to Cite Modal to include export to RIS function

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#794]
Before we look at the possibility of incorporating export to RIS function the cite modal from the bookmarks page, I would like to present the developers with a wireframe with what this would look like. The assumption is an end user might want the ability to export the citations from the cite modal that is launched when viewing bookmarks. I will leave the layout to your discretion. 

Wireframes:
[Export to RIS from Bookmarks Page](https://docs.google.com/drawings/d/1hRyc9mO9USBi1Nir4uSoIhqNqT982mVOdxKA42oMM0w/edit?usp=sharing)
[Export to RIS from View Item Detail Page](https://docs.google.com/drawings/d/1rmAwESNLSgYJhlAczgsa39Jav-k79LuQNhKiYDqhxoo/edit?usp=sharing)

Preferred treatments have been identified as option 1 in both wireframes (keeping Cite and Export as RIS distinct).

Tasks

- [x] Create wireframes
- [x] Identify preferred UI options
- [x] Write implementation ticket for Tools menu UI changes - #799
- [x] Write implementation ticket for Export to RIS from bookmarks page - ticket #800

**Comment by eporter23** [comment]
@CB987 this is another one Cari and I discussed on the fly today.
