### ISSUE TITLE
Resolve performance issues on Collection filter in Advanced Search

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/blacklight-catalog#796]
This ticket continues work in #619. After the new lookup method was introduced, we are experiencing issues with load time when trying to use the form field.

Ideas proposed:

- Suggestions include switching the lookup to use emory_collection_tesim (Emory-named collections only) 
- Only loading the first 100 or so titles in the drop box until a user starts typing.

**Comment by lovinscari** [comment]
Accepting this as work completed but noting a bug still exists which is documented in ticket #808.
