### ISSUE TITLE
Amend Shib setup for prod

### ISSUE THREAD

**Issue by rotated8** [emory-libraries/blacklight-catalog#797]
Since we are pointing prod to a new dns address, we need to update our shib config to also use the new address.

- [x] Create SN ticket for Gerry to update the shib config.

**Comment by CB987** [comment]
similar ticket for avalon: shibboleth add end point https://emory.service-now.com/nav_to.do?uri=task.do?sys_id=5acb1dc91b222094a8441f4ead4bcbe0

**Comment by libdgg** [comment]
Ticket to OIT has been submitted on 8/4. [INC03640588](https://emory.service-now.com/nav_to.do?uri=%2Fincident.do%3Fsys_id%3D80967bcd1bb57490e72ada4cbc4bcbdd%26sysparm_record_target%3Dincident%26sysparm_record_row%3D1%26sysparm_record_rows%3D6%26sysparm_record_list%3Dactive%3Dtrue%5E123TEXTQUERY321%3Dshib%5EORDERBYzztextsearchyy)

Waiting for assignment and a response as of 8/6

**Comment by libah** [comment]
Met with Gerry Hall and he is setting up his end. 8/9

**Comment by libah** [comment]
Worked with Gerry to get the Shib configuration successfully setup.

**Comment by eporter23** [comment]
Confirmed that I can login via Shibb on search.libraries.emory.edu.

**Comment by lovinscari** [comment]
I too can login via shib on search.libraries.emory.edu
