### ISSUE TITLE
Update header/logo elements for branding (link and text updates)

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/blacklight-catalog#798]
This ticket follows the related wireframe work (#783) to update the Blackcat header to more closely align with Emory Libraries logo conventions.

- [x] Utility navigation: change link text "About Catalog" to "About Library Search" (no change to href)
- [x] The logo element that currently says `Blacklight` should be changed to `Emory Libraries`
- [x] The renamed `Emory Libraries` link should point to https://libraries.emory.edu
- [x] The Emory shield SVG link should point to the Blacklight homepage (/) - no change needed
- [x] The `Emory University` link text should point to https://www.emory.edu - no change needed

![Screen Shot 2021-07-29 at 1.36.09 PM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/9e1a0477-9278-4ceb-bcac-d2fc3b4cb7a9)

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/blacklight-catalog/pull/804

![Screen Shot 2021-07-30 at 11.53.22 AM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/d011fa16-3477-478a-b68c-63f398e1545b)
![Screen Shot 2021-07-30 at 11.53.41 AM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/81cf7219-9977-4fa5-ad34-23cb46cf8c0f)

**Comment by lovinscari** [comment]
Looks great!
