### ISSUE TITLE
Revise order of Export as RIS link in Tools menu

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/blacklight-catalog#799]
This ticket implements changes made to the wireframe related to the Export as RIS feature on the single item view page (#794). After review of options, we determined it would be worth keeping these elements distinct.  

[Wireframe](https://docs.google.com/drawings/d/1rmAwESNLSgYJhlAczgsa39Jav-k79LuQNhKiYDqhxoo/edit)

Revisions needed

- [x] Change the order of the links in the Tools menu so that Export as RIS immediately follows the Cite link.

![Screen Shot 2021-07-29 at 4.21.05 PM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/aee10dee-642f-43ac-b6c9-773f397f3d91)

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/blacklight-catalog/pull/802

![Screen Shot 2021-07-30 at 10.50.22 AM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/edc11676-5c69-40bf-9ffe-c79f87a89c53)
