### ISSUE TITLE
Emory Login Service Request(Shibboleth): Initiate

### ISSUE THREAD

**Issue by tmiles2** [emory-libraries/blacklight-catalog#8]
Details into the Shibboleth Service can be found on the Wiki [https://wiki.service.emory.edu/display/integration/Shibboleth+Service#ShibbolethService-Purpose](url)

The Emory Login Service can be requested once the form is completed. You will need to confirm the following items before the form can be completed.
- [x] EntityID/test URL
- [x] Attributes to request 

_There are additional questions on the form to answer as well._ A draft of the form has been placed in Box so the information can be gathered before submitted. [https://emory.app.box.com/file/710176312172](url)

**Comment by lovinscari** [comment]
@tmiles2 I believe the attributes are PPID, NetID, Directory first, last and preferred name. This is what was requested for Curate and is in line with that currently in place for Primo.

**Comment by tmiles2** [comment]
The form has been updated but pending the following:
-  entityID
- confirmation of admins (specifically do we need to include someone from Core Systems)

**Comment by tmiles2** [comment]
@rotated8 @mprefer I filled in the request form based on the information I received. Take a look and let me know if there are any questions.

**Comment by tmiles2** [comment]
The document has been drafted but pending sign off.
