### ISSUE TITLE
Add ENV var for Alma collection in the ingest rake task

### ISSUE THREAD

**Issue by rotated8** [emory-libraries/blacklight-catalog#80]
- [x] Add a new ENV var to the dotenv.sample for the Alma collection. Add the name and default value to this ticket.
- [x] Configure the ingest rake task to use that ENV var instead of hardcoding "blacklighttest" as the `oai_set`

This is done when:
- [x] A developer can set the ENV var explicitly and run the rake task, and end up with that Alma collection's records in Solr
- [x] A developer can allow dotenv to set the ENV var and run the rake task, and end up with the "blacklighttest" collection's records in Solr.

**Comment by bwatson78** [comment]
dotenv.sample: `oai_set_name=blacklight_default_set`

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/blacklight-catalog/pull/88

**Comment by devanshu-m** [comment]
I was able to run the rake task with this new env variable on my local computer. Closing.
