### ISSUE TITLE
Add Export to RIS feature to the Bookmarks page

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/blacklight-catalog#800]
Story: _As an end user, I would like to export my bookmarks to a file, so that I can import multiple citations into a citation manager such as EndNote_

This ticket follows wireframe work in #794 and #779.

- [x] Add a button to the right of the existing Cite button
- [x] When a user clicks the button, Blacklight should generate an RIS file that contains records for all the bookmarks on the page

Additional notes
- [Wireframe](https://docs.google.com/drawings/d/1hRyc9mO9USBi1Nir4uSoIhqNqT982mVOdxKA42oMM0w/edit) (option 1 preferred)
- [RIS Format Reference](https://en.wikipedia.org/wiki/RIS_%28file_format%29#Tags).
- See also this[ archived documentation for generating RIS output](https://web.archive.org/web/20120526103719/http://refman.com/support/risformat_intro.asp).

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/blacklight-catalog/pull/810

![Screen Shot 2021-08-03 at 10.10.30 AM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/545bb6d4-4e43-40b0-b3f0-52f323463217)

**Comment by eporter23** [comment]
@bwatson78 @lovinscari this looks great! Exports and loads up multiple references in Endnote like a charm.

**Comment by lovinscari** [comment]
Great work @bwatson78!!!
