### ISSUE TITLE
Revise links in footer

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/blacklight-catalog#803]
This ticket implements changes to links in the footer as noted in #518:

- [x] About Catalog link

- Change link text to About Library Search
- No change to url

- [x] Copyright & Content link

- Change link text to Harmful Language in the Catalog
- Change link url to https://libraries.emory.edu/about/policies/statement-harmful-language.html

 

![Footer Revised.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/6e3cfd8b-3ead-41c8-b615-e104a05421dc)

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/blacklight-catalog/pull/807

![Screen Shot 2021-08-02 at 9.33.21 AM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/1592e871-51a1-4957-85ee-3749317ad5cc)
