### ISSUE TITLE
Advanced Search - Collection filter lookup sends searches with no matches

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/blacklight-catalog#808]
See also prior ticket to enhance performance/load time of the Collection filter on the Advanced Search form #796.

To reproduce:

1. Start a new advanced search.
2. Use the Collection filter option to search for Ted Hughes Library
3. Multiple options appear (due to inconsistent data entry)
4. Select one of these e.g. `Ted Hughes Library (Emory University. General Libraries.)`
5. Click Search

Search results show no matches and the search is only run against "Ted".

https://blackcat-test.library.emory.edu/catalog?utf8=✓&range%5Bpub_date_isim%5D%5Bbegin%5D=&range%5Bpub_date_isim%5D%5Bend%5D=&op=AND&all_fields_advanced=&title_advanced=&author_advanced=&subject_advanced=&title_series_advanced=&publisher_advanced=&identifier_advanced=&call_number_advanced=&f_inclusive%5Bcollection_ssim%5D%5B%5D=Ted&range%5Bpub_date_isim%5D%5Bbegin%5D=&range%5Bpub_date_isim%5D%5Bend%5D=&sort=score+desc%2C+pub_date_isim+desc%2C+title_si+asc&search_field=advanced&commit=Search

**Comment by bwatson78** [comment]
PR

**Comment by eporter23** [comment]
@bwatson78 @lovinscari looks great! I've tested against a few known collections (Ted Hughes Library, Danowski, Criterion Collection) and they are all working now. Page load time is also speedy.

**Comment by lovinscari** [comment]
I also tested in Advanced Search and everything seems to be working very well. Great job!!
