### ISSUE TITLE
Preliminary Advanced Search

### ISSUE THREAD

**Issue by mark-dce** [emory-libraries/blacklight-catalog#81]
**STORY**
As a graduate student, I'd like to be able to see all resources that have "Connecticut" in the title AND an author name that includes "Twain", so that I can find potentially interesting copies of a book I'm researching.

**ACCEPTANCE**
There is a form-like search option where I can enter specific
- [ ] Title words
- [ ] Author/Creator names
- [ ] Subject Keyword(s)
- [ ] ISBN
- [ ] ISSN

I can also choose the following options for a controlled list of options 
- [ ] Language
- [ ] Resource Type

I can choose to see matches that match
- [ ] Any of the filled fields
OR
- [ ] All of the filled fields

**Comment by lovinscari** [comment]
Advanced search was handled and refined through the Advanced Search gem.
