### ISSUE TITLE
Refine RIS output to omit duplicate entries across older vs newer RIS tags

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/blacklight-catalog#811]
Our revised RIS mapping includes older and newer tags which have turned out to produce duplicate entries in EndNote.

In the following example, when opened in EndNote, the (single) author is repeated twice and we can also see a geographic location code in addition to the publication place name.
https://blackcat-test.library.emory.edu/catalog/9937294718502486

![Screen Shot 2021-08-03 at 11.43.19 AM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/3df9b053-c002-43c2-b77b-ac63beeb16bb)

The following revisions are requested to address this, assuming that the tags to delete are older style tags:

> TY  - GEN
> A1  - Acuff, Jonathan M., author **// DELETE A1**
> AU  - Acuff, Jonathan M., author **//DELETE RELATOR TERM**
> CN  - JF1525.I6
> CN  - A28 2022
> CY  - cau **//DELETE GEO CODE**
> CY  - Thousand Oaks, California
> DA  - 2022
> LA  - English
> PB  - [CQ Press, an imprint of SAGE Publications, Inc]
> PP  - cau **// DELETE GEO CODE**
> PP  - Thousand Oaks, California
> PY  - 2022
> SN  - 9781544374673
> SN  - 1544374674
> T1  - Introduction to intelligence : institutions, operations, and analysis **// DELETE T1**
> TI  - Introduction to intelligence : institutions, operations, and analysis
> ER  - 

To be determined: it is unclear which tag EndNote is using for the place of publication, but once we remove the geographic code from displaying we may have a better sense of this.

**Comment by eporter23** [comment]
I'm guessing on which fields are read by EndNote [from this document](https://support.clarivate.com/Endnote/s/article/EndNote-Directions-for-implementing-EndNote-Direct-Export?language=en_US).

**Comment by eporter23** [comment]
@bwatson78 I also just noticed the author fields are including a relator term - we'd talked about removing that in the last ticket, is that possible?

**Comment by bwatson78** [comment]
@eporter23 That issue should've been resolved. Can you link me an example?

**Comment by bwatson78** [comment]
@eporter23 Checked the example from above--objections to using `author_ssim` for `AU`?

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/blacklight-catalog/pull/812

**Comment by eporter23** [comment]
@bwatson78 author_ssim should be good.

**Comment by bwatson78** [comment]
@eporter23 I assumed--current PR swaps to that field.

**Comment by lovinscari** [comment]
I will need to wait to test this after the reindexing finishes as the record @eporter23 referenced is not currently showing up in Test.

**Comment by eporter23** [comment]
@bwatson78 I'm noticing some odd behavior with AU vs A2 fields. A couple of examples:

https://blackcat-arch.library.emory.edu/catalog/9936989020102486
https://blackcat-test.library.emory.edu/catalog/990011265900302486

> TY  - GEN
> A2  - Gilbert, W. S. (William Schwenck), 1836-1911
> A2  - Simpson, Carl, 1955-
> A2  - Jones, Ephraim Hammett
> A2  - Clarke, Hamilton, 1840-1912
> AU  - Sullivan, Arthur, 1842-1900
> AU  - Gilbert, W. S. (William Schwenck), 1836-1911
> AU  - Simpson, Carl, 1955-
> AU  - Jones, Ephraim Hammett
> AU  - Clarke, Hamilton, 1840-1912
> CN  - M1500 .S95 M5 1999
> CY  - Mineola, N.Y.
> DA  - 1999
> ET  - New edition /
> ET  - In full score.
> LA  - English
> PB  - [Dover Publications]
> PP  - Mineola, N.Y.
> PY  - 1999
> SN  - 0486406261 :
> TI  - The Mikado
> ER  - 

When opened in EndNote:
![Screen Shot 2021-08-05 at 1.00.42 PM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/ff792bb3-b4f9-4f6f-bf37-00956cf23483)

In the MARC record, Sullivan, Arthur, 1842-1900 is the primary author (AU). The rest are 700s and should be A2s.

**Comment by eporter23** [comment]
@bwatson78 another note: if you'll be doing any adjustments on this, I'd also request that we remove the DA field from our export mapping. Now that I'm seeing it in more examples, it appears that DA is supposed to contain Month or Day and not years. When we populate both PY and DA with years, it repeats when exported back out of Endnote. Sorry for not catching this sooner.

https://blackcat-test.library.emory.edu/catalog/9937271572602486

> Schieder, Chelsea Szendi. "Co-Ed Revolution : The Female Student in the Japanese New Left." [Duke University Press], **2021 2021.** http://proxy.library.emory.edu/login?url=http://dx.doi.org/10.1215/9781478012979.

**Comment by bwatson78** [comment]
@eporter23 That's because `author_ssim` is catching `100abcdq:110abd:111acd:700abcdq:710abd:711acd` and is multivalued. Maybe we should switch this to `author_ssm` which captures only `100abcdq:110#{ATOZ}:111#{ATOZ}` or `author_tesim`, that pulls `100abcegqu:110abcdegnu:111acdegjnqu` (a little more restricted).

**Comment by eporter23** [comment]
@bwatson78 thanks - let's try author_tesim and see how that goes.

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/blacklight-catalog/pull/820

**Comment by eporter23** [comment]
Looks good @bwatson78 !
