### ISSUE TITLE
Preliminary Field Display

### ISSUE THREAD

**Issue by mark-dce** [emory-libraries/blacklight-catalog#82]
**STORY**
As a student, I'd like to see more information about the resource I'm looking for, so that I can choose the best item for my studying needs.

**ACCEPTANCE**
When I look at an the single item view for an item, I see the data for all of the fields below that are populated
- [ ] Title
- [ ] Author/Creator
- [ ] Subject Keyword(s)
- [ ] ISBN
- [ ] ISSN
- [ ] Language
- [ ] Resource Type

**Comment by lovinscari** [comment]
No longer needed as this as been addressed through other tickets.
