### ISSUE TITLE
Update content on About Page - Explore Block

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#823]
Please update the Explore Block on the About Library Search page [https://blackcat-test.library.emory.edu/about](url)

Explore

Information about Libraries Materials (link to https://libraries.emory.edu/materials/index.html)

Research Guides (link to https://guides.libraries.emory.edu/main)

Contact Us (link to https://blackcat-test.library.emory.edu/contact)

**Comment by CB987** [comment]
![Screen Shot 2021-08-17 at 9.43.56 AM.png](https://images.zenhubusercontent.com/5d379c9d5221e52414fca85c/91f4b2db-fc8c-4c8e-8c2e-ac1ca7410853)

**Comment by lovinscari** [comment]
@CB987 - This looks good. I forgot to include a couple of things which I will do in a new ticket. Thanks!
