### ISSUE TITLE
Update Contact Page Explore Block

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#824]
Update the Explore Block on the Contact Page

Explore (no change)

Library Policies (no change)

Using the Library (link to https://libraries.emory.edu/using-the-library/index.html)

Libraries Hours (link to https://libraries.emory.edu/hours/index.html)

Change "Contact Emory Libraries" to "Contact Library Staff and Departments" (link to https://libraries.emory.edu/contact/index.html)

**Comment by alexBLR** [comment]
@lovinscari 
![Screen Shot 2021-08-16 at 10.53.16 AM.png](https://images.zenhubusercontent.com/5c488275c10ae96cd915967b/01c3731c-cf7e-44fc-9203-dd170956ea95)

**Comment by lovinscari** [comment]
@alexBLR - This looks good. Thanks!

**Comment by lovinscari** [comment]
@alexBLR - I overlooked (or perhaps it recently changed) the fact the Visiting the Emory Libraries link is dead. I submitted a new ticket to have this removed. Apologies!
