### ISSUE TITLE
Document expected work/requirements on moving to Primo VE for validation with ExLibris

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#828]
Once the Spike ticket is completed in reviewing the interface of Primo VE, it will be necessary to document what we believe the work is around the CDI View, The Services Page, and moving to Primo VE so we can get clarification from ExLibris on what they will help with and what the Emory Team would be responsible for. I will add more details to this ticket. (CL).

**Comment by libah** [comment]
Work to be done for CDI view:
https://emory.primo.exlibrisgroup.com/discovery/search?vid=01GALI_EMORY:CDI

 1. Turn off extra functionality in view, such as Journal search, tags, etc. currently viewable in Primo VE CDI view
2. Same thing for Advanced search
3. same thing for brief view, full view
4. Design elements -
       a. adding footer
       b. enabling linking from Articles+ image to blacklight
       c. turn off or change wording in search box - currently says "search everything"
