### ISSUE TITLE
Homepage - preliminary facets

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/blacklight-catalog#83]
_As [any end user], I want to preview certain types and quantity of material from the homepage, so that I can get a sense of what the catalog contains without having to enter a specific search_

The homepage will show a subset of facets in order to support initial browse-based entry into the catalog, in addition to the search options shown on the homepage. There are a larger set of facets that display after a search has been executed (separate ticket #84).

_Note: some requirements for this ticket are not yet fully approved, so refinements are anticipated later:_
- Exact MARC mappings for these fields is not yet provided.
- Library/Location behavior for values is not fully confirmed
- Wireframes have not yet been approved.

**Set of homepage facets to display:**
- [ ] ~~Library / Location~~ (Unavailable in the mapping)
- [x] Resource Type
- [x] Language
- [ ] ~~Publication Date~~ (recommended to be separated into another ticket)
- this should be a date range slider such as offered in Emory Digital Collections
- [ ] ~~Recently Added~~ (recommended to be separated into another ticket)
- Within 90 days
- Within 60 days
- Within 30 days
- Within 15 days
- Within 7 days

**Preliminary wireframes:** 
- [Homepage Facets](https://www.figma.com/file/ocSo3KytI6GgwjalSVAmE1/Blacklight-Wireframes?node-id=80%3A92)
- [Facets: general](https://www.figma.com/file/ocSo3KytI6GgwjalSVAmE1/Blacklight-Wireframes?node-id=91%3A3765)
- [Facets: date slider](https://www.figma.com/file/ocSo3KytI6GgwjalSVAmE1/Blacklight-Wireframes?node-id=115%3A186)

**General facets acceptance criteria:**
- [x] Unless otherwise noted, facets should generally display and behave like the facets in [Emory Digital Collections](https://digital.library.emory.edu)
- [x] Facet heading displays like Lux: shows a right-facing arrow when collapsed, and a downward facing arrow when expanded
- [x] Facet values will initially display sorted in order of highest numerical value to lowest value.
- [x] The five tags with the highest values will be displayed when the facet heading is expanded, and if the number of tags exceeds five then “More Options” with a >> arrow will be displayed beneath the last facet tag indicating selecting the more options will produce an additional window.
- [x] If “more options” is clicked, a popup displays, similar to Emory Digital Collections, that includes additional facet matches. A total of 20 values with the associated item counts will be shown in the window, and if the number exceeds 20, pagination of <<Previous and Next>> will be included similar to Emory Digital Collections. If the “more options” popup appears, sort options of A-Z Sort and Numerical Sort will be included in the window similar to Emory Digital Collections.
- [ ] ~~Publication Date should behave like date slider in Emory Digital Collections~~

**Comment by rotated8** [comment]
- We do not yet have location data.
- Resource Type is Format currently
- Language is present
- Recommend splitting dates, date range slider work into a separate issue.
- What data do we currently use for Recently Added?
- Need to review indexing to see if current data supports faceting (we believe language and format do).
- Adding facets to homepage is a large change in homepage functionality
- Recommend working on indexing data first.

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/blacklight-catalog/pull/114

![Screen Shot 2020-12-22 at 12.44.15 PM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/d7b10b73-2764-47ec-9963-f5acd5422837)

**Comment by bwatson78** [comment]
Arch site is live again and above changes are evident. @mprefer believes the schema was going into the wrong directory and has decided to script the procedure to update the the schema so that it works correctly every time.
