### ISSUE TITLE
Preliminary extended facets (after a search is executed)

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/blacklight-catalog#84]
_As [any end user], I want to be able to refine my search results using additional metadata presented to me, so that I can more easily hone in on results that are the best match._

After a search has been executed, an expanded set of facets is displayed beyond what initially shows on the homepage.

_Note: some requirements for this ticket are not yet fully approved, so refinements are anticipated later:_

- **Exact MARC mappings for the values within each facet is not yet provided**.
- Library/Location behavior for values is not fully confirmed
- Wireframes have not yet been approved.

**Heading displayed above facets:**
- [x] "Limit your results"

**Extended facet set:**

- [x] Access 
-this will include online or physical items
- [ ] ~~Library~~
- [x] Resource Type
- [x] Language
- [ ] ~~Publication Date~~
- this should be a date range slider such as offered in Emory Digital Collections
- [ ] ~~Recently Added~~ 
- Within 90 days
- Within 60 days
- Within 30 days
- Within 15 days
- Within 7 days
- [x] Author/Creator
- [x] Subject
- [x] Collection
- [ ] ~~Call Number~~
- [ ] ~~Genre~~
- [ ] ~~Organization as Author~~
- [x] Region
- [x] Era

**Preliminary wireframes:** 
- [Facets: general](https://www.figma.com/file/ocSo3KytI6GgwjalSVAmE1/Blacklight-Wireframes?node-id=91%3A3765)
- [Facets: date slider](https://www.figma.com/file/ocSo3KytI6GgwjalSVAmE1/Blacklight-Wireframes?node-id=115%3A186)

**General facets acceptance criteria:**
- [x] Unless otherwise noted, facets should generally display and behave like the facets in [Emory Digital Collections](https://digital.library.emory.edu)
- [x] Facet heading displays like Lux: shows a right-facing arrow when collapsed, and a downward facing arrow when expanded
- [x] Facet values will initially display sorted in order of highest numerical value to lowest value.
- [x] The five tags with the highest values will be displayed when the facet heading is expanded, and if the number of tags exceeds five then “More Options” with a >> arrow will be displayed beneath the last facet tag indicating selecting the more options will produce an additional window.
- [x] If “more options” is clicked, a popup displays, similar to Emory Digital Collections, that includes additional facet matches. A total of 20 values with the associated item counts will be shown in the window, and if the number exceeds 20, pagination of <<Previous and Next>> will be included similar to Emory Digital Collections. If the “more options” popup appears, sort options of A-Z Sort and Numerical Sort will be included in the window similar to Emory Digital Collections.
- [ ] ~~Publication Date should behave like date slider in Emory Digital Collections~~

**Comment by rotated8** [comment]
- Is subject all the LCSH subjects?
- Is organization cataloged separate from author in MARC?
- Era and Region- may be in 6xx fields, may be present as subjects
- Collection, genre, and region are not yet indexed.
- Recommend splitting dates into a separate ticket.

**Comment by bwatson78** [comment]
Call Number isn't clear as far as what I should use to facet it. Below is what I have to work with:

```lc_1letter_facet = 050a[0], callnumber_map.properties, first
lc_alpha_facet = 050a, (pattern_map.lc_alpha), first
lc_b4cutter_facet = 050a, first```

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/blacklight-catalog/pull/115

[Uploading... Screen Shot 2020-12-23 at 9.54.42 AM.png ]
