### ISSUE TITLE
Update to About Page

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#841]
I forgot to update the text since I do not have the roadmap ready in a way we can easily show on the web. For now, please make the following changes to the About page...

- [ ] About Emory Library Search section - Please remove the text, "Present the roadmap and differences between Primo and Blacklight. Might also look at this under technology."

- [ ] Questions, Help, and Feedback section - Please include a link to the Contact page - https://blackcat-test.library.emory.edu/contact

Apologies for my oversight.

**Comment by CB987** [comment]
@lovinscari , which specific text do you want the contact page link connected with? My assumption would be "Contact page" in "visit our Contact page"? Thanks.

**Comment by lovinscari** [comment]
Looks good!
