### ISSUE TITLE
Add Blacklight footer element to Services page using Angular JS

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/blacklight-catalog#846]
This ticket follows work in spike #788 where options were identified for how modify ExLibris page views using Angular and the package files.

See also this placeholder footer prototype in the [blacklight-EP Alma services view](https://emory-psb.alma.exlibrisgroup.com/discovery/openurl?institution=01GALI_EMORY&vid=01GALI_EMORY:blacklightEP&rft.mms_id=990006792470302486). This view can also be used for development and testing as needed.

Suggested tasks:

- [ ] Identify necessary `<footer>` elements from Blacklight application
- [ ] Recreate `<footer>` elements using ExLibris' Angular JS options
- [ ] Recreate required CSS styles and add to the view's CSS
- [ ] Generate a new package file version
- [ ] Upload the new package to the Alma Services view

**Comment by tmiles2** [comment]
We are holding off on this ticket until we get the Primo VE sandbox in place.

**Comment by eporter23** [comment]
@lovinscari I think we confirmed we aren't going to add a footer at this time. I suggest we move this back to new issues.
