### ISSUE TITLE
Hide API requesting work

### ISSUE THREAD

**Issue by rotated8** [emory-libraries/blacklight-catalog#849]
Since we are going to use the Services Page at launch, we should hide the work we have done around API requesting. We don't want to remove it, but it should not be visible to the user.

**Comment by rotated8** [comment]
In my opinion, the easiest way to do this would be to wrap the code in an 
```<% if false %> ... <% end %>``` block.

@lovinscari - can you add a screenshot highlighting what you want removed?

**Comment by eporter23** [comment]
Looks great @alexBLR !

**Comment by lovinscari** [comment]
Thanks @alexBLR
