### ISSUE TITLE
Convert Title Starts With facet into navigation menu

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/blacklight-catalog#851]
**Story:** _As a searcher, I want to skip around in my results list alphabetically by title, because I am looking for a specific matches that start with a given letter or number_ 

This ticket follows work previously done to provide a Title Starts With facet. In order to present users with more continuity for browse-type searches in Primo, we want to adapt this facet into a visible navigation menu. 

[Wireframe - Title Starts With A-Z Menu](https://docs.google.com/drawings/d/1w2Fd0HMmWnTzdbCJpgIQkdRBRNc-1_Butiqiv-4JjlI/edit)

- The menu should be a persistent, visible UI element for the search results page whether it is actively selected or not.
- The menu should offer 0-9, the letters A-Z, and "All".
- See the wireframe for additional details and styling notes.

Note: we will probably need an alternate design for responsive views (separate wireframe and ticket).

**Comment by eporter23** [comment]
@bwatson78 I just confirmed with @devanshu-m related to bug ticket #880 that when we do a search from Advanced Search, the A-Z menu is not appearing above the results. We want that to be a consistent option for both basic and advanced search results.

**Comment by bwatson78** [comment]
Work to correct bug was included in PR https://github.com/emory-libraries/blacklight-catalog/pull/882/

**Comment by lovinscari** [comment]
@eporter23 - This looks good to me. Please review and if you accept, please move to To Deploy to Production pipeline. Thanks!

**Comment by lovinscari** [comment]
@bwatson78 - Based on the demonstration you provided, this looks great.
