### ISSUE TITLE
Update Search tips sidebar text for Advanced Search

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/blacklight-catalog#852]
Now that we have enabled wildcard searching on Advanced Search, we need to update the help text on that page. 

See revised text below for the last two bullets (highlighted in bold just for clarification, but should not be bold on the page).

**Search tips**

- Select "match all" to require all fields.
- Select "match any" to find at least one field.
- Combine keywords and attributes to find specific items.
- Use quotation marks to search as a phrase.
- Use "+" before a term to make it required. (Otherwise results matching only some of your terms may be included).
- Use "-" before a word or phrase to exclude.
- Use "OR", "AND", and "NOT" to create complex boolean logic. You can use parentheses in your complex expressions.
- **Truncation and wildcards are not supported unless specifically noted. Word-stemming is done automatically.**
- **View our [search guide](https://libraries.emory.edu/tools/discovere/search-discovere.html) for more search tips.**

**Comment by eporter23** [comment]
@lovinscari here is a starter ticket but feel free to revise it. I put in a placeholder link to the discovere search guide for now.

**Comment by eporter23** [comment]
Looks great @devanshu-m !

**Comment by lovinscari** [comment]
thanks @devanshu-m
