### ISSUE TITLE
Spike: investigate if 856s for print records can display on Services page/view

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/blacklight-catalog#853]
Scenario to research:

We have some print records for which there is also full text access added through 856 links on the records. This is often the case with locally digitized items. In this scenario, there is not an AVE/electronic holding or portfolio information: the 856 links provide the only online access.

Examples: 
https://blackcat-test.library.emory.edu/catalog/990017705390302486
https://blackcat-test.library.emory.edu/catalog/990021279710302486

Since we are routing users to all other requesting and viewing options through the Services page, if we can include those 856s on that page also, it would provide for a more consistent experience. We do have a workaround in mind if this is not possible, but want to confirm first.

Ticket goals:

1. Confirm if 856s on a print record can be added to the Services page view
2. If possible, prototype this display in a Services page view
3. Testing

**Comment by lisahamlett** [comment]
I have followed the instructions for turning on 856s according to the August 2018 release notes (https://knowledge.exlibrisgroup.com/Primo/Release_Notes/002Primo_VE/0982018/0052018_Release_Notes_for_Primo_VE) but it isn't showing.

> If the holdings record has an 856 u field and the second indicator is not 2, the View It service will appear and contain a link based on the 856 u field.

@eporter23 Have you disabled the View It service?  I see the outline of the box popping up but nothing is appearing in it.

Here's the link for one of your examples: https://emory-psb.alma.exlibrisgroup.com/discovery/openurl?institution=01GALI_EMORY&vid=01GALI_EMORY:blacklight&rft.mms_id=990017705390302486

**Comment by eporter23** [comment]
@lisahamlett I haven't disabled View It, only Send To. I'm not seeing what you describe, can you send a screenshot or walk me through it sometime? Thanks!

**Comment by lisahamlett** [comment]
I lied.  I'm not seeing it anywhere on any view.  Maybe ask on basecamp what this is supposed to look like?

**Comment by libdgg** [comment]
@lisahamlett and @eporter23 will get together
@libah check on adding Lisa to basecamp (so we can ask the question in the post above)

**Comment by libdgg** [comment]
Lisa and Emily will touch base. 
Ann put in the request to add Lisa to basecamp. Ann will also add Emily to basecamp as well.

**Comment by lisahamlett** [comment]
I emailed the basecamp about this issue.

**Comment by tmiles2** [comment]
Emily will respond in basecamp to ExLibris not comments
