### ISSUE TITLE
Add standard identifiers field to keyword search

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/blacklight-catalog#855]
As part of our functional testing of basic search, testers experienced problems while trying to search for DOIs specifically.

This is most likely due to people searching for a doi including the prefix "doi:". While the value of the doi is searchable in the full text of the MARC, the prefix is in a different subfield, so an exact phrase search will not match.

**Example:** 
1. _"doi: 10.1007/978-1-349-18209-1"_ fails in a keyword search
2. _doi: 10.1007/978-1-349-18209-1_ works in a keyword search
3. _10.1007/978-1-349-18209-1_ matches results in a keyword search

**SOLR/Indexing Recommendation:**
Add the `other_standard_ids_tesim` to the keyword search, which should provide better results for exact phrase searches. This is currently configured for the Advanced Search field for Identifiers.

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/blacklight-catalog/pull/874

No screenshots necessary.

**Comment by eporter23** [comment]
@bwatson78 @lovinscari looks good! searches for `"doi: 10.1007/978-1-349-18209-1" ` and `"10.1007/978-1-349-18209-1"` now match the correct, single record.

**Comment by lovinscari** [comment]
This looks great. Thank you @eporter23 and @bwatson78 for your work on this!
