### ISSUE TITLE
TASK: Remove Unnecessary extra vertical spacing on Sort and Per Page options in search results

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#857]
Per Item #5 on [CSS Punchlist ](https://docs.google.com/document/d/1TfiTa7wdHPcVA8uNbkrH2MtZDYbBI5SPLRV4Ka2yfq4/edit?usp=sharing)- Remove unnecessary extra vertical spacing on Sort and Per Page options in search results

**Comment by eporter23** [comment]
@CB987 looks great!
