### ISSUE TITLE
TASK: Fix irregular alignment of right-oriented elements on search results (Bookmark item option) 

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#859]
Per the [CSS Punchlist](https://docs.google.com/document/d/1TfiTa7wdHPcVA8uNbkrH2MtZDYbBI5SPLRV4Ka2yfq4/edit?usp=sharing) Item #1 - Fix irregular alignment of right-oriented elements on search results (Bookmark item option).

**Comment by eporter23** [comment]
@CB987 This is definitely much improved! I'm still seeing a little bit of an anomaly between the right edges ("h" in Advanced Search  and the "m" in Bookmark Item). I think we can probably close this and look at it again later if needed.  ![Screen Shot 2021-08-31 at 1.12.14 PM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/0e110ae9-51db-4107-913d-c53a658d3da6)
