### ISSUE TITLE
Complete wireframes for Services Pages

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#860]
Complete wireframes and styling requirements for services pages in an effort to match theming and branding standards on Blacklight site. Some of the desired theming and branding

- Incorporating basic header with some modifications including removal of links to static pages, bookmarks, history, and help but adding Return to Libraries Search instead of "Home"

- Incorporating existing footer if possible

- Incorporating any CSS styles including font and color

Once the wireframes and styling requirements are completed, please submit a new ticket to have the styling completed. 

Working notes:
[Final wireframe](https://docs.google.com/drawings/d/1FDLtuRjQWa-BvxMegUelgbykHYVDk_5XJopMXVkg4hE/edit)

**Comment by eporter23** [comment]
@lovinscari please see this finalized wireframe. I have confirmed with Core Systems various options for generating the search link for WorldCat.

**Comment by lovinscari** [comment]
@eporter23 and @libdgg - This looks great. Similar to the other wireframes ticket, I am going to close this ticket and assume that any work to implement this styling will be done as part of the subproject.
