### ISSUE TITLE
Create wireframes and styling requirements for My Library Card (My Account) page

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#861]
Please create new wireframes and styling requirements for the My Library Card (My Account Page) ![MyLibraryCard.png](https://images.zenhubusercontent.com/5c4a1fe1e9b5fb46bcedb9fc/fd44417b-6b8c-4a87-af9e-8764df33e3d9)

- [ ] The page is expected to add as a stand-alone page that can be linked from the Services Pages, and within the header in Blacklight. 

- [x] The header should be the same as the Services Pages

- [ ]  If possible, incorporate the standard footer 

- [x] Incorporate any styling standards including font and colors

Once the wireframes and styling standards are completed, please complete a new ticket for application developers to complete the work to update the My Account Page. 

**Work Notes**
[List of related UI reviews and restyled Alma view prototype](https://docs.google.com/document/d/1QsdtR6ydrZmD3kdo56Wzc5ILiZm4bFPdR8vVqmMRdkc/edit#heading=h.gy0uffid1ya2)

**Comment by eporter23** [comment]
@lovinscari please see the link to the wireframe review notes and Alma view prototype. I can continue the actual view styling as we move forward with setting up the view in Primo VE.

**Comment by eporter23** [comment]
Also, we will need to investigate how to get a footer into this "view" once we get set up for Primo VE.

**Comment by lovinscari** [comment]
@eporter23 and @libdgg - This looks great. I am going to close this ticket with the assumption the completion (implementation) of this work will be managed under the subproject.
