### ISSUE TITLE
Revise Home Page Wireframe

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#862]
Meet with product owner and revise wireframe and styling requirements for home page based on original layouts completed by Norm in ticket [562](https://app.zenhub.com/workspaces/blacklight-catalog-5f5f84a8a6d29939a0bc5d78/issues/emory-libraries/blacklight-catalog/562).

Once the new layout requirements are confirmed, finalize wireframes and submit new ticket for application developers to implement the changes to the home page.

A copy of the [most current wireframe is here](https://www.figma.com/file/PP4GdxNNZKIZX0BeHHAPTo/Homepage-Visual-Comp?node-id=0%3A1).

**Comment by eporter23** [comment]
@lovinscari I have added some annotations [to the wireframe here](https://www.figma.com/file/PP4GdxNNZKIZX0BeHHAPTo/Homepage-Visual-Comp?node-id=0%3A1). We should review some of the verbiage and links on the page related to Ask a Librarian, etc.
