### ISSUE TITLE
Add availability and links to services page from search results 

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/blacklight-catalog#864]
**Story:**  _As an end user, I want to see a brief summary of how I can access material in my search results, so that I know if an item is online or on-site and whether it is currently available_

Because we are directing users to the Services page for almost all access requests, we have opted to show a very minimal real time availability check and not show detailed holdings or electronic access options. These are presented as very brief badges + buttons within Blacklight.

When implementing this new display component, this should build on the previous logic we built to show brief tables for either At the Library and/or Online using the API, particularly the work we did prior to DCE's investigations. #461, #462.

We anticipate that 4 main combinations could be displayed to end users, depending on the type of holdings and real time availability of the item:

1. Online + Connect button (link to Services page)
2. Online + Connect button (link to 856s added to a print record, if the record does not have AVE/electronic holdings)
3. Available + Locate/Request (link to Services page)
4. Not Available + Request (link to Services page)

Note: some requirements are still pending related to whether or not we can display 856 links (fulltext) on the Services page. If we can’t display this from the MARC record, we need to add the modal option shown in wireframe 2 below.

Wireframes and Mockups

- [Search results with availability as badges and services page links as buttons](https://docs.google.com/drawings/d/1p8lsg3colLtehZaE-_S4LZlujTgVv0Lr77mkuugLHAQ/edit)
- [Search results with badges + buttons and modal for multiple 856s](https://docs.google.com/drawings/d/1gnw0hA1dT_lz9zMr6QxUfFRspc7IYVMz3JiXqQJWDy4/edit)
- [Button and badge styles](https://codepen.io/eporter23/pen/GREJqxw) 

SOLR and Indexing
These mockups assume we retrieve basic real time availability using the API checks that we have been using in earlier prototypes, but in some cases we may need to check SOLR also. 

- For print holdings, look for AVA.
- For online holdings, look for AVE.
- If  url_fulltext_ssm is populated and there is no AVE, we should use that for the Connect option as noted in the wireframes above.

**Comment by bwatson78** [comment]
This is taking longer than expected since my changes have made existing tests err and it's taking a long time to fix them.

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/blacklight-catalog/pull/882/

![Screen Shot 2021-09-01 at 1.05.37 PM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/7a8e4629-0e4a-4931-a3c4-3502290fc072)

**Comment by eporter23** [comment]
This is looking really good. Some minor styling issues: can we set the width of the badge to be the same as the action button. Also, the font size is slightly too large (should be ~11px for the action link and ~14 px for the badge status). Please see the [codepen example](https://codepen.io/eporter23/pen/GREJqxw) for more details and let me know if I can clarify.

**Comment by eporter23** [comment]
I also noticed this item shows the Not Available badge from the results list, but there is more than 1 copy and 1 copy is available. Do we need to refine the availability status with more rules? https://blackcat-test.library.emory.edu/catalog/9937311240802486

**Comment by bwatson78** [comment]
@eporter23 Starting on those changes now.

**Comment by bwatson78** [comment]
@eporter23 Checking on the Availability response for that one in particular.

**Comment by eporter23** [comment]
Thanks @bwatson78 : another hopefully minor issue. On items with the modals for multiple 856s, can we please display those on separate lines? 

![Screen Shot 2021-09-07 at 10.19.11 AM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/a9cbcbc0-e93f-4c45-bb2d-cfd686e63ff4)

**Comment by bwatson78** [comment]
@eporter23 Will do. Can you share the mms_id on that one?

**Comment by eporter23** [comment]
Here's that one: https://blackcat-test.library.emory.edu/catalog/990021279710302486

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/blacklight-catalog/pull/888

![Screen Shot 2021-09-07 at 12.33.38 PM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/d87034d7-a320-417d-9a91-8dc552b57203)
![Screen Shot 2021-09-07 at 1.35.37 PM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/f0d58bae-1e31-46d1-aa30-95d7984957fb)![Screen Shot 2021-09-07 at 1.37.29 PM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/ba841b87-67a5-451d-8592-c64de9c0b94b)

**Comment by bwatson78** [comment]
One more PR: https://github.com/emory-libraries/blacklight-catalog/pull/889

**Comment by eporter23** [comment]
@bwatson78 revisions look great! @lovinscari we also found this weird behavior, and we may want to look at it in another ticket. If you search for this ID, it shows nothing for availability. 990002044110302486. Confirmed that it has no holdings info or an 856. You can see info in the Services page, however. We should probably create additional tickets to address this kind of situation.

**Comment by lovinscari** [comment]
@eporter23 and @bwatson78 - Thanks for the great work on this. I am also seeing a few weird records (based on the demo today) we'll want to look at. I suspect more like these will come up in acceptance testing so I'll note this as a known issue for now we will look at post-beta.
