### ISSUE TITLE
Add real time availability and services page links to Single Item View page

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/blacklight-catalog#865]
Story: As an end user, I want to see options to access a specific resource I am viewing in detail, so that I can quickly connect to the appropriate service for viewing online or requesting a physical item 

This ticket implements the real time availability and service page connection options documented in ticket #864. Please refer to that ticket for additional details. When implementing this new display component, this should build on the previous logic we built to show brief tables for either At the Library and/or Online using the API, particularly the work we did prior to DCE's investigations. #461, #462.

Wireframes and Mockups

- [Wireframe for single item view page with buttons and badges](https://docs.google.com/drawings/d/1yzKv3SctWrvlYha5aKGxuAn8KRC52mMIveOa8OfAAOg/edit)
- [Section headings and badges + buttons mockup ](https://codepen.io/eporter23/pen/vYZOJeq)

SOLR and indexing

- See ticket #864 for details about use of API and SOLR fields

**Comment by alexBLR** [comment]
![Screen Shot 2021-09-10 at 6.42.02 AM.png](https://images.zenhubusercontent.com/5c488275c10ae96cd915967b/8bb2b0af-3a1e-4417-8326-72dcaf244260)

**Comment by lovinscari** [comment]
@eporter23 - this looks good to me but I would like you to review before moving to To Deploy to Prod pipeline. I did get a 502 Bad Gateway error (issue Laura brought up) so I will try to replicate again and see if there is a bug that needs to be fixed. If you approve this ticket, please move to next pipeline. Thanks!

**Comment by eporter23** [comment]
Looks great! I tested against known complex examples and they all look good to me. @lovinscari we should also write up a ticket for what to display if no availability is returned. here is an example: https://blackcat-test.library.emory.edu/catalog/990024839780302486
