### ISSUE TITLE
Placeholder: Work on PrimoVE during Sprint 18

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#866]
Work with ExLibris to implement PrimoVE with the primary view of CDI which will be used as part of the Blacklight application. Report out on progress during mid-sprint review and sprint demo. Actual tasks are completed in BaseCamp. Ann will serve as primary point of contact and call on others from the team as needed.

**Comment by libdgg** [comment]
@libah @AGCooper @CB987 Since we have met with Ex Libris and now have a Primo VE implementation plan, Epic with tickets, and the Ex Libris basecamp site I propose this ticket is closed. Please let me know if you agree or there is still work to be done on this ticket. Thanks. -DG
