### ISSUE TITLE
SPIKE: Investigate work needed and desired approach for a domain name. for Primo VE

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#875]
Based on conversation with ExLibris today,  we should investigate configuring a new domain name for the PrimoVE instance.  Some considerations that should factor into the conversation:

- [ ] Classic UI for Primo (discovere.emory.edu) will continue to operate when search.libraries.emory.edu is in production for the purpose of sending Emory's Primo records to Georgia Tech. If we did move the discovere domain, I would like to understand the work needed by Georgia Tech.

- [ ] We might consider moving the discovere domain to PrimoVE is there would be any reduction in work on Emory's part to the link resolver work. Details about this should be explored as part of this ticket to uncover what the work would be if creating a new domain for PrimoVE or moving the discoverE to PrimoVE.

- [ ] Work involved and time needed for setting up a new domain for PrimoVE.

**Comment by AGCooper** [comment]
- [ ] Decide on a domain name

- [ ] Inform ExL of the new domain

- [ ] Get the csr file from ExL

- [ ] Request an Incommon cert for the domain

- [ ] Provide cert information to ExL

- [ ] Once ExL confirms the cert is active test the new domain

**Comment by AGCooper** [comment]
This is the url the findit@Emory button appears to be currently pointing to http://emory-primoprod.hosted.exlibrisgroup.com/openurl/01EMORY/01EMORY_services_page?&vid=01EMORY_services_page&sid=Entrez:PubMed&id=pmid:28244479

**Comment by lovinscari** [comment]
Team is meeting this afternoon to review how we should handle this work moving forward. I will update ticket(s) accordingly.

**Comment by lovinscari** [comment]
@libdgg and @AGCooper - I am going to put a note in Basecamp for Efi to see if the ExLibris team can provide some direction especially around link resolver. I will have that note in before sprint planning tomorrow.
