### ISSUE TITLE
Update Help Link on Tools Menu on production instance

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#876]
The link for the Help Page on the Tools Menu on Single Item View needs to be updated. The link should go to https://search.libraries.emory.edu/help and currently directs me to the home page.

**Comment by bwatson78** [comment]
@lovinscari This link hasn't changed since empty links were initialized for Print, Direct Link, Help, and Feedback on 04/16/2021 for ticket #428. It just seems we've never had a ticket calling out the proper endpoint for this Tools choice.
