### ISSUE TITLE
Adjust Resource Type labels to help with text wrapping

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/blacklight-catalog#884]
In order to help with some of the word breaks (#858) we have proposed changing some of the Resource Type values which are coming from metadata. 

Labels to change for `format_ssim` field:

Video/Visual Material: change to **Video or Visual Material**
Archival Material/Manuscripts: change to **Archival Material or Manuscripts**

**Comment by bwatson78** [comment]
PR made: ﻿https://github.com/emory-libraries/blacklight-catalog/pull/886

![Screen Shot 2021-09-03 at 9.07.37 AM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/95c024f6-05d2-42f6-9bc1-6f2b5c5c3515)

**Comment by lovinscari** [comment]
@eporter23 - This looks good to me. If acceptable to you, please move to To Deploy to Production. Thanks!

**Comment by lovinscari** [comment]
@bwatson78 - I think this looks great and am satisfied. I believe @eporter23 has reviewed but perhaps has not had a chance to respond. I am moving to To Deploy to Prod.
