### ISSUE TITLE
Update OAIs

### ISSUE THREAD

**Issue by AGCooper** [emory-libraries/blacklight-catalog#887]
Update Alma OAIs to match Blemily:
998
Library subfield: c
Available for Library subfield: d

**Comment by AGCooper** [comment]
Update Alma OAIs to match Blemily:

Library subfield: c
Available for Library subfield: d

**Comment by libdgg** [comment]
Blocked due to Primo VE and capacity for Core Systems in general (hiring, etc.)

**Comment by lisahamlett** [comment]
Done

![image.png](https://images.zenhubusercontent.com/5d379bd44943b962f4d2105c/786dca12-3b68-47d7-8b24-3a8e732c9023)
