### ISSUE TITLE
Bug: Choosing a Title Starts With letter wipes out the previous facets chosen

### ISSUE THREAD

**Issue by bwatson78** [emory-libraries/blacklight-catalog#890]
When one or more other facets are already chosen, and the user chooses a letter from the Title Starts With nav menu, the resulting page clears out the already chosen facets. The expected behavior should be the addition of the Title Starts With facet, not the removal of the previous options.

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/blacklight-catalog/pull/891

No screenshots necessary.

**Comment by lovinscari** [comment]
Tested on blackcat-test selected two facets and then title starts with letter. Facets remained.
