### ISSUE TITLE
Implement CDI view within PrimoVE Sandbox 

### ISSUE THREAD

**Issue by libdgg** [emory-libraries/blacklight-catalog#895]
Search Profiles Configuration - We only need CDI search profile.

**Comment by libdgg** [comment]
Lisa has a ticket in with ExL for this.

**Comment by libdgg** [comment]
ExL Case Number: 00990895
Request to Resynch Alma Sandbox with Production
Efi responded to the ticket this morning 9-13-2021 to get more info from Lisa

**Comment by libdgg** [comment]
Per mid-sprint check-in:
If ExL does not respond on Monday or are unable to do the sync we will.
Ann and Lisa need to plan time Monday and Tuesday to do work and will block their calendars.

**Comment by eporter23** [comment]
@libah recreated this manually in sandbox today.

**Comment by libdgg** [comment]
Styling for this is now in ticket #621. 
NOTE: we should create tickets for doing this work in Production since this is only sandbox.
