### ISSUE TITLE
Implement and configure the PrimoVE Services View for physical requesting and viewing electronic items 

### ISSUE THREAD

**Issue by libdgg** [emory-libraries/blacklight-catalog#897]
- [x] Configure the services associated with PrimoVE to facilitate requesting of physical materials  
- [x] Configure the services page associated with PrimoVE to facilitate viewing electronic items that are part of a portfolio and included in Alma. 
- [x] Remove Primo specific elements (e.g., browse search) for the journal view that would enable users to further their search in Primo as opposed to Blacklight. 
- [ ] Test

**Comment by lisahamlett** [comment]
Physical items requesting example:
https://emory-psb.alma.exlibrisgroup.com/discovery/openurl?institution=01GALI_EMORY&vid=01GALI_EMORY:blacklight&rft.mms_id=990022009440302486

![image.png](https://images.zenhubusercontent.com/5d379bd44943b962f4d2105c/2eca8815-44ae-4ed1-87dc-9e6e11e1a878)

Electronic items through a service is also ready to go:
https://emory-psb.alma.exlibrisgroup.com/discovery/openurl?institution=01GALI_EMORY&vid=01GALI_EMORY:blacklight&rft.mms_id=9936526097302486

![image.png](https://images.zenhubusercontent.com/5d379bd44943b962f4d2105c/cf859aa0-f652-4c45-bd7f-9fb3e6ff8f6b)

**Comment by lisahamlett** [comment]
Journals requesting is also ready:
https://emory-psb.alma.exlibrisgroup.com/discovery/openurl?institution=01GALI_EMORY&vid=01GALI_EMORY:blacklight&rft.mms_id=990027512140302486

![image.png](https://images.zenhubusercontent.com/5d379bd44943b962f4d2105c/affadd22-e71c-49f8-93fc-abf589e74ca9)

**Comment by lisahamlett** [comment]
I hid "Request Other Issue" on the Journals view.  This is now ready to be reviewed.

**Comment by libdgg** [comment]
Alex started testing. Aeon requesting is going to prod. Hopper (the request server) has an expired cert and Beth is working on that. This is not a show stopper. People just need to know not to put in a request.
So far it is looking good. Keep in review until at least Monday for final review.

**Comment by libdgg** [comment]
There is no test page for ILLiad. Aeon test server is behind VPN. ILLiad and Aeon have to be on prod.
Testers should be told not to submit the forms since those are live requests.
Ares goes to Ares test (Lisa has control of that server).
Closing this ticket per Alex Cooper.
