### ISSUE TITLE
Emory Login Service Request(Shibboleth): Review and Request Approval 

### ISSUE THREAD

**Issue by tmiles2** [emory-libraries/blacklight-catalog#9]
The Identity and Access Management team will review the service request form and seek approval of the requested attributes from the data stewards. If there are no additional questions or concerns the request will be approved.

**Comment by mprefer** [comment]
Installed the shibboleth SP client package.

**Comment by tmiles2** [comment]
SeviceNow ticket is assigned to the Identity Management team

**Comment by tmiles2** [comment]
Anne Marie had some questions to clarify our needs around the preferred name. After speaking with Collin and Solomon, I provided answers to Anne Marie's questions. I also requested an additional attribute Collin identified during our discussion, preferred name in one field(displayName).

**Comment by tmiles2** [comment]
The attributes have been approved by HR and Student data stewards.  The SN ticket has been transferred to the Web team.

**Comment by mprefer** [comment]
Attached shibboleth2.xml to the SN INC03495097 per request from Gerry Hall of the Web Hosting team.

**Comment by tmiles2** [comment]
@mprefer The configuration has been added (message from Gerry). Where you able to complete testing?

**Comment by mprefer** [comment]
Tested browsing to 'http://blackcat-arch.library.emory.edu'. Apache with the mod_shib_24.so module loaded redirected to http://login.emory.edu, presented the log in page, and accepted and authorized my credentials.
So, I'd proffer that Shibboleth is working on blackcat-arch.
