### ISSUE TITLE
Update Wiki with new `oai_set_name` variable.

### ISSUE THREAD

**Issue by bwatson78** [emory-libraries/blacklight-catalog#90]
Change instructions to reflect the need for `oai_set_name` to be set in the following situations.

1. A different set name besides the default name assigned in the ENV variable is to be used.
2. The ENV variable of `oai_set_name` is vacant or missing in this environment.

Note: at this moment, the agreed-upon default `oai_set_name` value will be `blacklighttest`. This, however, has not been set in the lone Arch environment.

**Comment by bwatson78** [comment]
[Confluence site](https://wiki.emory.edu/display/BDL/Using+SolrMarc+to+harvest+data+from+Alma+into+Solr+Index) updated.

**Comment by lovinscari** [comment]
I added @norm0 to the Blacklight Wiki and requested access for @mlooney who is not currently listed as a Confluence user. I believe someone from the software engineering team should review the Wiki and accept this issue?
