### ISSUE TITLE
TASK: Implement Domain Name for PrimoVE

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#910]
Message sent to ExLibris - [basecamp ticket](https://3.basecamp.com/3765443/buckets/23697781/messages/4134164204) - asking for advice based on following criteria:

I am hoping to get some advice from the ExLibris team on considerations we need to make in determining the domain we should use for PrimoVE based on the following criteria.

1. Our instance of Primo Classic UI (discovere.emory.edu) will continue to operate until Georgia Tech moves to PrimoVE. We do not necessarily need for users to access this domain (directly) after February 2022. However, I am concerned with re-using this domain now for PrimoVE since we will not be building out the full discovery interface for PrimoVE until later this year.

2. If possible, we would like to avoid having to update all link resolver information, including our links for "FindIT at Emory." Currently, the links from FindIT at Emory point to http://emory-primoprod.hosted.exlibrisgroup.com/openurl/01EMORY/01EMORY_services_page?&vid=01EMORY_services_page&sid=Entrez:PubMed&id=pmid:28244479 (e.g.)

We would appreciate any insight you have around this subject and possibly suggest how we might proceed in order to get a new domain developed as quickly as possible to move forward with PrimoVE setup while being minimally disruptive to current production environments.

**Comment by tmiles2** [comment]
Pending a response from Ex Libris team on considerations, we need to make in determining the domain.

**Comment by libdgg** [comment]
Moving to blocked as we are waiting on ExL to respond to the basecamp ticket to help us settle on the domain name.

**Comment by libdgg** [comment]
Updated from Efi on Basecamp as of 9-12-2021
In Primo VE we have the option to re-direct the old Primo URL’s to the Primo VE environment, this also includes the OpenURL URL’s.

This mean that we have the option to point the hostname “emory-primoprod.hosted.exlibrisgroup.com” that use the “01EMORY_services_page” view to the new Primo VE hostname + view.

For more information regarding this option, please review the following web page:
https://knowledge.exlibrisgroup.com/Primo/Product_Documentation/020Primo_VE/Primo_VE_(English)/120Other_Configurations/Configuring_Redirection_for_Primo_VE_Deep_Links

**Comment by libdgg** [comment]
NOTE: ExL response addresses Cari's #2 question but not #1 about impact to GaTech.

**Comment by libdgg** [comment]
Doug will schedule a working meeting to walk through this question and what our approach will be.
-Ann, Beth, Cari, Doug

**Comment by libdgg** [comment]
For our view names may want to use "services" instead of "blacklight" and "articles" instead of "CDI". This decision will lock us in and it will be more difficult to rename later.

**Comment by libdgg** [comment]
Per the [Primo VE working meeting ](https://emory-my.sharepoint.com/:w:/r/personal/rmetz_emory_edu/_layouts/15/Doc.aspx?sourcedoc=%7BD095D23A-7A69-4FC2-89F8-035C93D12A8A%7D&file=2021-09-15-Primo-VE-Working-Meeting-Domain-Redirects.docx&action=default&mobileredirect=true)- we will not be pursuing a vanity domain but instead use ExL provided urls.
As such, we will not need to perform domain or cert work at this time. We are requesting check-in meetings with ExL to go over our linking/redirection topics. If the domain decisions is reversed we will create new tickets on this board as needed.
