### ISSUE TITLE
Bug: Selecting "All" option on A-Z menu causes homepage content to load

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/blacklight-catalog#912]
This occurs when a search is performed, facets are cleared out, and Title Starts with "All" is selected. Here is an example query URL that is generated:

https://blackcat-test.library.emory.edu/?sort=title_ssort+asc%2C+pub_date_isim+desc

To reproduce:

1. Start a new, blank search 
2. Select a Library from the facet
3. Select any letter (not All) from the Title Starts With Menu
4. Remove the starts with letter facet
5. Remove the Library facet
6. Homepage block will appear

![Screen Shot 2021-09-09 at 10.56.38 AM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/46fd12d1-6134-40b1-b109-a233973f988f)

**Comment by lovinscari** [comment]
@alexBLR - I am no longer able to replicate the behavior @eporter23 and I saw during our wireframes meeting last week. I am not sure if @eporter23 is able to replicate? If not, I would say let's close this for now and we can create a new ticket if we find the behavior again.

**Comment by eporter23** [comment]
@lovinscari @alexBLR I'm not seeing it either using the steps noted above. Let's close this and write up a new ticket if we see it recurring.
