### ISSUE TITLE
Style Blacklight Services/Default View for Primo VE in Sandbox

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/blacklight-catalog#913]
This ticket focuses specifically on look and feel customizations/customization package needed for the "Services" view that Blacklight users will see for connecting to resources or requesting.

See prior work for [Services Page wireframe](https://docs.google.com/drawings/d/1FDLtuRjQWa-BvxMegUelgbykHYVDk_5XJopMXVkg4hE/edit) (#860)

This ticket does not include the General Electronic Services configurations for requesting or viewing electronic items or other Alma back-end configurations.

- [x] Confirm view name to use in Sandbox: **services**
- [x] Implement existing CSS to restyle or hide specified Services-related elements
- [x] Implement header elements using JS
- [x] Implement footer elements using JS
- [x] Adjust Links section content
- [x] Remove left nav menu
- [x] Remove Send to Section
- [x] Remove Journal Search section 
- [ ] Update GitHub Services Page repository with revised package files, if applicable

Work notes:
- Working prototype is now on the ["blacklight" view](https://emory-psb.alma.exlibrisgroup.com/discovery/openurl?institution=01GALI_EMORY&vid=01GALI_EMORY:blacklight&rft.mms_id=9936498254502486) as linked to Blacklight currently
- These styles and configurations have also been added to the ["services" view](https://emory-psb.alma.exlibrisgroup.com/discovery/openurl?institution=01GALI_EMORY&vid=01GALI_EMORY:services&rft.mms_id=9936498254502486) which will be linked to blacklight
- Some elements previously hidden by CSS can be disabled at the View > General settings including Enable QR code on top

**Comment by libdgg** [comment]
This is largely done but there are some final steps to roll it into production.

**Comment by libdgg** [comment]
The footer is complicated and we are not sure how much value it will add right away. The footer may be an enhancement. Emily may talk to Cari about the footer.

**Comment by libdgg** [comment]
Emily will talk to Cari Wed.

**Comment by libdgg** [comment]
Emily will add "links" specs to this ticket for Lisa to work on.

**Comment by eporter23** [comment]
For the "Links" section in the "services"/blacklight view and "articles" view, we want to: 

1. Remove the WorldCat identities link
2. Add a link to Search This Item in WorldCat (see wireframe notes about desired functionality; if nothing else, just add link to the WorldCat homepage)

**Comment by lisahamlett** [comment]
@eporter23 
I have turned off Worldcat Identities in both production and sandbox.

I tried to create an OpenURL from the Alma Link Resolver that would do what you're asking with the query, but I couldn't get it to work due to the fact that there is so much crap in our ISBN and ISSN fields.  I DID, however, create a link that will search WorldCat IF the record has an OCLC number.  Otherwise, it will just go to the search box.  That's the best I can do because WorldCat's search parameters are not flexible enough to allow our crap data to return results.

![image.png](https://images.zenhubusercontent.com/5d379bd44943b962f4d2105c/d3cad5a5-0d2a-47ba-a1fe-7cec91f7d2eb)

**Comment by lisahamlett** [comment]
Oh, I also set ProQuest dissertations to only show for dissertations...  Been meaning to do that for a while.

**Comment by eporter23** [comment]
@lisahamlett links look great, thanks! And thanks for the Worldcat stuff - that's a good compromise.

**Comment by libdgg** [comment]
This all seems done except for the footer. Check back on Monday with Cari.

**Comment by libdgg** [comment]
Emily has wireframe meeting with Cari on Wednesday and can go over this ticket at that time.

**Comment by eporter23** [comment]
@lovinscari and I decided to remove the footer for now. This also has the benefit of the page loading faster.

**Comment by lovinscari** [comment]
Looks great. Thanks @eporter23 and @lisahamlett
