### ISSUE TITLE
Primo VE Go Live - putting it into production for beta use by users

### ISSUE THREAD

**Issue by libdgg** [emory-libraries/blacklight-catalog#915]
- [ ] Ensure all other prerequisite zenhub tickets or dependencies are closed or not blocking our ability to "go live" with Primo VE for users
- [ ] Review and complete the[ Ex Libris Go Live Checklist](https://emory-my.sharepoint.com/:w:/r/personal/rmetz_emory_edu/Documents/LTDS%20Shared%20Documentation/Projects/Project%20Documentation/Blacklight%20Discovery%20Layer%20Phase%201/PrimoVE%20Implementation/Supporting%20Documents/Primo%20VE%20Go%20Live%20Checklist%20from%20ExLibris.docx?d=w010f7ff267574d6ea5889b10047a337b&csf=1&web=1&e=rW4UWb)

- [ ] Initiate the [Go Live Process with Ex libris](https://knowledge.exlibrisgroup.com/Primo/Product_Documentation/Go_VE/Step_4%3A_Go_Live#Initiating_the_Go_Live_Process)
- [ ] [Redirect Permalinks in Primo to Primo VE](https://knowledge.exlibrisgroup.com/Primo/Product_Documentation/Go_VE/Step_4%3A_Go_Live#Redirect_Permalinks_in_Primo_to_Primo_VE)

On the scheduled day of the switch, Ex Libris will perform the following tasks for you:

- DNS switch will be deployed.
- E-Shelf saved records will be copied from Primo to Primo VE. Saved searches are not copied.
- Primo APIs will be routed to point at Primo VE instead of Primo (Production and SB).
- Primo Analytics data will be copied to Primo VE Analytics in Alma. Saved reports can be copied over per request.
- Primo VE will be activated on Alma Sandbox. Alma Premium sandboxes will receive a copy of Primo VE configuration during the coming Sandbox Refresh (February and August).

When the above tasks are complete, you will receive a final notification via your Support case to let you know that traffic is being redirected from your old Primo environment to your new Primo VE environment.

Once you receive the switch-over notification, perform the following tasks:

- Test the redirection.
- Test authentication and verify that E-shelf saved records are available.
- Test Primo VE Analytics and verify that Primo Analytics data is available.

Source: https://knowledge.exlibrisgroup.com/Primo/Product_Documentation/Go_VE/Step_4%3A_Go_Live

**Comment by libdgg** [comment]
Vendor meeting on 2021-10-6
Follow up vendor meeting scheduled for 2021-11-11
The team should review this ticket after 11/11 to confirm the ticket is closed or if follow up ticket(s) need to be created.

**Comment by lovinscari** [comment]
@libdgg - I think we can close this ticket but would like to explore what new tickets are needed to actually initiate the work of the DNS redirects.

**Comment by lovinscari** [comment]
I am closing this ticket as other individual tickets have been created.
