### ISSUE TITLE
Configure MARC Fields for Title Search

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#92]
Based on feedback from the SEND Team (stakeholder group), the following MARC Fields should be associated with Title Search when utilizing the header search drop down selection "Title".

[Link to figma](https://www.figma.com/file/ocSo3KytI6GgwjalSVAmE1/Blacklight-Wireframes?node-id=1%3A119)

- 245 - Title Statement
- 210 - Abbreviated Title (R) Full
- 222 - Key Title
- 130, 240, 243, 700 $t (etc.), 710 $t (etc.), 711 $t (etc.), 730 - Main Entry Uniform Title, Uniform Title (author/title), Collective Uniform Title, Added entry (name/uniform title), Added entry uniform title
- 773 $t /774 $t - Host Item Entry/Issued With Entry
- 76X/78X - Preceding Entry/Succeeding Entry
- 242, 505 (t), 740 - Translation of Title, Varying Form of Title, Former Title, Formatted Contents, Added entry Uncontrolled Related/Analytical Title
- 246 - Varying Form of Title
- 247 - Former Title
- 440, 490, 800, 810, 811, 830, 840 - Title of Series, Series Added Entry-Personal Name, Series Added Entry-Corporate Name, Series Added Entry-Conference Name, and Series Added Entry-Uniform Title
- 505 $t (if 2d indicator $2 is 0) - Formatted Contents Note - Enhanced - Title
- 880 (with $6 linking to one of the above tags)- Alternate Graphic Representation

**Comment by rotated8** [comment]
Are these in order of relevance?

**Comment by devanshu-m** [comment]
![image.png](https://images.zenhubusercontent.com/5c12bc2dd3542818d52aa3a0/3faeb02c-6eaa-454e-9472-dc7c4d59618d)

Title seems to be working. Searched for string in tag 245.
