### ISSUE TITLE
Update services page links to use new view name for beta launch

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/blacklight-catalog#922]
In order to make these names more meaningful if exposed to end users, the following Primo VE views will be renamed:

The following urls refer to the sandbox. We will use the same Primo VE view names in production also when we link up to the production environment.

**blacklight** view has been duplicated and renamed to **services**
Example link: https://emory-psb.alma.exlibrisgroup.com/discovery/openurl?institution=01GALI_EMORY&vid=01GALI_EMORY:services&rft.mms_id=9936498254502486

This will impact any links we have in the Blacklight application which point to these views, including our links to the Services page, e.g.:

> https://emory-psb.alma.exlibrisgroup.com/discovery/openurl?institution=01GALI_EMORY&vid=01GALI_EMORY:blacklight&rft.mms_id=990031856940302486

Suggested tasks:

- [x] VE team will duplicate and rename new views
- [x] SE team will update any links to the services page (Search Results, Single Item View)

**Comment by libdgg** [comment]
Need to make sure everything is duplicated correctly. Some tickets may need to be created for software engineering. Discuss this in mid-sprint.
