### ISSUE TITLE
Revise mapping and extraction for local_call_number_tesim

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/blacklight-catalog#923]
As part of our first round of user acceptance testing, some users reported issues with searching by call number.

For more details, see the[ Search Testing Review notes](https://docs.google.com/document/d/1IkVs3q5rqM2qx50xoKXuZrRubf4h-xnUzcXlux7g5fA/edit#heading=h.t5cnyqo9qys3) here (Call Number Search section)

On closer investigation, it seems that in some cases, the sections of a call number are being split and stored as separate values in the SOLR local_call_number_tesim field, which can cause problems when searching:

9937345159302486
`"local_call_number_tesim":["F2272", ".R83 2020"],`
^ in this example, the call number should be stored as one entry "F2272 .R83 2020", not split into two.

990022253520302486
`"local_call_number_tesim":["LSC","RSTORM","MSS1061","MARBL","MSSTK","MSS1061"],`

^ in this example, the call number appears to contain library and location information in addition to the call number itself.  It is probably supposed to be 2 entries, but it is unclear from the stored value.

Desired outcome would be: "MSS1061" (omitting exact duplicate from second holding) 

**SOLR and Indexing Notes**

- Our indexer should concatenate all the mapped subfields into a single value for each HOL852 instead of storing each subfield as a separate value
- See revised mapping requirements for the `local_call_number_tesim` field in the [metadata worksheet](https://docs.google.com/spreadsheets/d/1jSqgNd6HnVJdJMrrShAofkmK8uGgHGdlKODmZOL5NfY/edit#gid=1979033236) related to the second example above.
- If feasible, if exact duplicate call numbers exist for a record, do not store duplicates

**Comment by eporter23** [comment]
@lovinscari fyi, adding this based on past discussions.

**Comment by eporter23** [comment]
@lovinscari I'm putting this in blocked temporarily while I confirm a few mapping revisions with the MD subgroup. There are other aspects of the ticket that could get worked on if we need to split this up, but the SOLR field mapping needs a couple of adjustments too.

**Comment by lovinscari** [comment]
@eporter23 - can you please test and accept this? If acceptable please move to Deploy to Prod. Thanks!
