### ISSUE TITLE
SPIKE: Investigate issue with exporting RIS citations with Zotero

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#927]
As part of the User Acceptance Testing, users have reported issues with the export as RIS function on the Tools Menu and the Bookmarks Cite menu in that the file does not appear to import properly in Zotero. We initially tested this function only on Endnote but have heard from SEND Team members that Zotero is needed just as much as Endnote. According to the SEND Team, most users prefer the web version of Zotero so configuring the RIS file based on this functionality is preferred.

The functionality should perform as it does for Endnote where the RIS file can be opened or imported into Zotero and appear as a list of cited references. I can provide more details if needed for Zotero. 

Once it is determined what work is needed to resolve this issue, please document within the ticket and I will create a new ticket with the work to be done. I am timeboxing this at a 5 so if it is too difficult to find a solution, we can just remove the feature for now.

**Comment by alexBLR** [comment]
Zotero implementation in Blacklight: https://github.com/ualbertalib/discovery/issues/429

Blacklight: https://github.com/projectblacklight/blacklight/blob/7c11785b4345174ac30790c0d2d25d5d897c7aeb/app/views/catalog/_show_main_content.html.erb#L8-L15

**Comment by alexBLR** [comment]
Here is what we currently have for Zotero as an overwrite of the original method: https://github.com/emory-libraries/blacklight-catalog/blob/d087727cc61999e728b8f39e1eb8b3ec77ba879e/app/models/concerns/blacklight/solr/document/marc_export.rb#L52

What we inherit from Blacklight Project: https://github.com/projectblacklight/blacklight/blob/7c11785b4345174ac30790c0d2d25d5d897c7aeb/app/views/catalog/_show_main_content.html.erb#L8-L15

It looks like the support for Zotero exists. We need to modify our export_as_openurl_ctx_kev method for it to display correctly.
