### ISSUE TITLE
Mobile testing and styling on all ExLibris Primo VE views 

### ISSUE THREAD

**Issue by libdgg** [emory-libraries/blacklight-catalog#928]
For all ExLibris views that will be user-facing, conduct testing on the responsive views CSS.

- [x] Test [Services page view](https://emory-psb.alma.exlibrisgroup.com/discovery/openurl?institution=01GALI_EMORY&vid=01GALI_EMORY:services&rft.mms_id=990021158010302486)
- [x] Test [Articles+ (CDI) view](https://emory-psb.primo.exlibrisgroup.com/discovery/search?vid=01GALI_EMORY:articles)
- [x] Test my library card from either of the above views
- [x] Add any issues to the [Exlibris CSS punchlist](https://docs.google.com/document/d/1_cD4xp6NQN8kl8y_tAmToKCqewUyp4_7o04dnxZWdM8/edit#heading=h.r3vjkjxmn8ci)
- [x] Write additional tickets for significant bug fixes (#950)

Priority device families to test:
- [x] iphone
- [x] iPad
- [x] Google Pixel
- [x] Samsung Galaxy

Report from discovere's analytics:
[Top 50 mobile devices - August 2021](https://docs.google.com/spreadsheets/d/1YBGU8HUF97SL4ZV8AQf_-oO8iA1Gm1CWEjA6_gfzX2I/edit#gid=1855093532)
[Overview of mobile vs desktop usage - August 2021](https://docs.google.com/spreadsheets/d/15QhzwVtG11UvlSLHU4i4SghKhIdVLCtJ5lHPfNAtPzA/edit#gid=1774640244)

NOTE: possible think of ways to automate, or tools, to do this type of testing for future projects/products.

Resolved issues to re-test:

- [x] Smallest breakpoint: black screen on Sign in/"Menu" modal
- [x] "homepage" on services ("blacklight") view obscures login
- [x] Gray background color on single record view on iPad

**Comment by AGCooper** [comment]
CDI view on Samsung Galaxy looks a little wonky:

![image.png](https://images.zenhubusercontent.com/5c75948e37910a45fad7cb77/e458e8ca-439a-4ecd-9282-e15bcf63de58)

There's a gray box, like a menu box next to the logo, and when I click on that I get a black screen. Also I don't see a way to access My Library Card.

**Comment by eporter23** [comment]
@AGCooper thanks - I think I have resolved the black screen issue on the Menu if you want to retest. I will also add the gray button styling to the punchlist.

**Comment by libah** [comment]
Testing Articles view on iPhone 12, iPhone 10 - Both Affliate and Emory login working, My Library card looks ok. Brief display looks ok, full display looks ok.

**Comment by libah** [comment]
Testing Services Page view (blacklight). ![IMG_0200.PNG](https://images.zenhubusercontent.com/5f452c7a13fd993154acf9b9/0da0e83f-990a-4eb9-a5f1-b6e390104ce9)

**Comment by libah** [comment]
Top page - logo is cut off, can't login. Text is to the left.

**Comment by eporter23** [comment]
@libah thanks. I put in a fix for this which is to remove the search box. This is an odd page because users shouldn't ever see it, but in the event that they get there, I'll make a note to add some content here.

**Comment by libah** [comment]
@eporter23 I realized that after I sent that. Does it make sense to wait to test the servicess view? or is it ready now do you think?

**Comment by libdgg** [comment]
Emily fixed the items that were reported. Alex and Ann will test.

**Comment by AGCooper** [comment]
Looking good!

**Comment by libah** [comment]
Tested with iPhone:

- CDI view. 
- Services page view
- My library 
All looking good!

**Comment by eporter23** [comment]
Thank you @AGCooper and @libah!

**Comment by eporter23** [comment]
iPad (portrait mode) shows gray background on Articles + when viewing a single record. This does not occur when viewing it in horizontal mode. Services view on iPad looks fine in both modes.

**Comment by eporter23** [comment]
^ the above issue for iPad is now resolved.

**Comment by eporter23** [comment]
@CB987 do you have a Google pixel we could use for testing?

**Comment by CB987** [comment]
**pixel** 
services view:
- (p) three dots login menu, bottom border of box is cut off
- (p) underlining of the availability is even weirder than on desktop
- (p+l) able to log in
- (p) icon to the right of request/ place on reserves is cut off
- (p+l) able to get to my library card
- (p+l) on my library card > loans, the numbers on the checkboxes are not centered (i say we don't need numbers in the checkboxes)

articles view:
- (p) background of three dots menu is light gray and there looks like there's a margin or padding to the right of it. looks weird above the blue spyglass
- (p) when scrolling up an individual item, the title scrolls over the "back to results list" button and you can't select it -- in (l) the title scrolls behind. the back to results button header. (p) it's *just* the title and description; once it gets down to Send to it goes behind it.
- (p) in My Favorites, a double spyglass, one in light gray next to the dots menu. (l) that plus a big white space to the right of the blue spyglass in the search bar

these are all pretty minor, style stuff only. no issues with functionality![Screenshot_20211004-204448.png](https://images.zenhubusercontent.com/5d379c9d5221e52414fca85c/1283ee7a-c3f0-432b-94eb-e5d04f2a00c3)![Screenshot_20211004-210706.png](https://images.zenhubusercontent.com/5d379c9d5221e52414fca85c/0bac7ec4-f087-4604-8a9c-4605152d5fdb)![Screenshot_20211004-205649.png](https://images.zenhubusercontent.com/5d379c9d5221e52414fca85c/7a0a3149-33b2-45d1-995d-160547d77392)![Screenshot_20211004-210140.png](https://images.zenhubusercontent.com/5d379c9d5221e52414fca85c/a5ab8f0d-03ac-4ec3-890f-742bf95f6f43)![Screenshot_20211004-210820.png](https://images.zenhubusercontent.com/5d379c9d5221e52414fca85c/cd394aa4-33da-48d9-891e-61db614540b6)![Screenshot_20211004-133940.png](https://images.zenhubusercontent.com/5d379c9d5221e52414fca85c/0715642e-20fe-48b0-8db2-1a9b63ed5845).
