### ISSUE TITLE
SPIKE: Investigate how we can change message when user logs in

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#933]
Currently within Blacklight, when the user logs into the application, they receive a message stating "You are already signed in." The preferred behavior is that when a user logs in, they are presented with a message similar to that with Emory Digital Collections "Successfully authenticated from Emory Account" or perhaps could just present something like "Successfully logged in" which would apply to both Shibboleth and Affiliate logins. 

If work is a simple fix, please proceed with making the change as part of this ticket. If the work is more substantial, please document the work needed within this ticket so a new ticket can be created.

**Comment by abelemlih** [comment]
PR ready for review: https://github.com/emory-libraries/blacklight-catalog/pull/951

**Comment by eporter23** [comment]
@abelemlih @lovinscari looks great! I tested this and the related ticket by logging in while viewing a single item detail page. 

![Screen Shot 2021-10-13 at 4.29.18 PM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/34a9f663-4e14-4045-ab96-7f768a3935a4)
