### ISSUE TITLE
Bug: next/previous options sometimes disappear when viewing single items after a search

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/blacklight-catalog#934]
[Uploading... NoNavigationBug_SingleItemView.jpg]

**Comment by bwatson78** [comment]
Unable to recreate this behavior on my local environment. Moving to Test, where I will watch the rails traceback while clicking around.

**Comment by bwatson78** [comment]
@lovinscari, @eporter23, and @rotated8 An additional clue as to why this behavior is uncommon to us is that our other Blacklight application, Lux, is setup to eliminate users' sessions after 24 hours, while Blacklight is currently set to expire after 40 minutes. Knowing that this application will be primarily used at our libraries, I'm not sure if we should extend that session to the same length.

**Comment by lovinscari** [comment]
@bwatson78 - I would like to discuss this with the team during Sprint Planning tomorrow just to make sure there will not be any adverse consequences if changing the timeout to 24 hours.
