### ISSUE TITLE
Finding aids/special collections

### ISSUE THREAD

**Issue by libah** [emory-libraries/blacklight-catalog#936]
When you search for a special collections item in blackcat-test.library.emory.edu that is not requestable through Aeon, but is requestable through Finding Aids, you are taken to a screen that says the item is unrequestable. In DiscoverE you are taken to the Finding Aid for that collection. We need to setup blacklight so that it behaves the same way and you are taken to the collectionfinding aids page. Possibly this can be setup in Alma.  

Examples are below:

Office of Lesbian/Gay/Bisexual/Transgender Life records, 1979-2012
https://libapiproxyprod1.library.emory.edu/cgi-bin/booking_findingaids?doc_id=990031606370302486&user_id=0
Old South miscellany collection, 1792-1861
https://libapiproxyprod1.library.emory.edu/cgi-bin/booking_findingaids?doc_id=990022243120302486&user_id=0
Alice walker papers
https://libapiproxyprod1.library.emory.edu/cgi-bin/booking_findingaids?doc_id=990022253520302486&user_id=0
Salman Rushdie papers
https://libapiproxyprod1.library.emory.edu/cgi-bin/booking_findingaids?doc_id=990022136540302486&user_id=0

**Comment by lisahamlett** [comment]
I have updated Special Collections requesting to refer to the finding aids instead of Aeon.

**Comment by lisahamlett** [comment]
https://emory-psb.alma.exlibrisgroup.com/discovery/openurl?institution=01GALI_EMORY&vid=01GALI_EMORY:blacklight&rft.mms_id=990031606370302486
emory-psb.alma.exlibrisgroup.com/discovery/openurl?institution=01GALI_EMORY&vid=01GALI_EMORY:blacklight&rft.mms_id=990022243120302486
https://emory-psb.alma.exlibrisgroup.com/discovery/openurl?institution=01GALI_EMORY&vid=01GALI_EMORY:blacklight&rft.mms_id=990022253520302486
https://emory-psb.alma.exlibrisgroup.com/discovery/openurl?institution=01GALI_EMORY&vid=01GALI_EMORY:blacklight&rft.mms_id=990022136540302486

**Comment by lisahamlett** [comment]
This is complete and ready for acceptance.

**Comment by libah** [comment]
I also tested the links and they are now resolving to Finding Aids as expected.
