### ISSUE TITLE
Increase CPU size on Blacklight Solr EC2's

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#937]
Per the investigation regarding the home page load time for the test and production instances of Blacklight, it was found the load on the solr instances during load to be fairly high (> 2 for 2 vcpu instances ) loads on the solr ec2s. These are small t3 large ec2 instances and that should likely be increased.

I am unsure what size the CPU's should be but would ask @jcrompton42 and @rotated8 to work together and identify and implement the improvements believed to resolve some of the performance issues.

**Comment by jcrompton42** [comment]
All prod solr instances are now t3 xlarge. Observed load averages during an apache benchmark run of 100 tests show usage is now within capacity.
