### ISSUE TITLE
Modify behavior of application if all facets are cleared without starting new search

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#939]
SEND Team Members reported confusion when testing the Blacklight application and using facets. When selecting facets and then clearing all of the facets, users reported getting non-sensical results. They did not understand that by clearing all facets but not selecting the Start Over button, they were essentially getting results from an empty search. 

To avoid confusion of the future, please modify the behavior of the application so if all facets are removed, the user is returned to the home page just as if they have selected the Start Over button.

**Comment by tmiles2** [comment]
Cari will create a help article to address this.
