### ISSUE TITLE
Configure MARC Fields associated with Subject Search in header search box

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#94]
The feedback received from the SEND Team includes MARC Fields that should be associated when users execute the Subject selection used as part of the header search box.

[Link to figma](https://www.figma.com/file/ocSo3KytI6GgwjalSVAmE1/Blacklight-Wireframes?node-id=1%3A119)

- 600 - Subject Added Entry - Personal Name
- 610 - Subject Added Entry - Corporate Name
- 611 - Subject Added Entry - Meeting Name
- 630 - Subject Added Entry - Uniform Title
- 647 - Subject Added Entry - Named Event
- 648 - Subject Added Entry - Chronological Term
- 650 - Subject Added Entry - Topical Term
- 651 - Subject Added Entry - Geographic Name
- 653 - Index Term - Uncontrolled
- 654 - Subject Added Entry - Faceted Topical Terms
- 655 - Index Term--Genre/Form

**Comment by rotated8** [comment]
Are these in order of relevancy?

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/blacklight-catalog/pull/120

![Screen Shot 2021-01-11 at 9.18.49 AM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/dbe7f1cd-0989-4fbe-a064-e4a158d3a9d7)

**Comment by bwatson78** [comment]
@lovinscari There is one field that incorporates exactly all of the tags listed above into a multivalued variable. I have utilized this for the search option.

**Comment by devanshu-m** [comment]
![image.png](https://images.zenhubusercontent.com/5c12bc2dd3542818d52aa3a0/e836191c-26b2-4609-b67f-d6b802188094)

Subjects seem to be working
