### ISSUE TITLE
Modify application to return user to the page they were on prior to logging in

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#940]
As the product owner, I would like for the Blacklight application to be modified so a user is returned to the page they were on prior to logging in. For example, if a user begins using the application not logged in, conducts a search, and selects an item record and logs into the Blacklight application at that point - they should be returned to the page they were on at the point just prior to logging in. In this example, the user would be returned to the single item view page. The current behavior is to return the user to the home page after logging in. 
This behavior was also modified in Lux so code should be available there.

**Comment by eporter23** [comment]
@abelemlih @lovinscari looks great! I tested this while viewing a single item detail page. 

![Screen Shot 2021-10-13 at 4.29.18 PM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/34a9f663-4e14-4045-ab96-7f768a3935a4)

**Comment by lovinscari** [comment]
Looks great!
