### ISSUE TITLE
Revise header links and homepage links for beta launch

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/blacklight-catalog#946]
- [x] **Add new `My Library Card` link (sandbox view)**
url: https://emory-psb.primo.exlibrisgroup.com/discovery/account?vid=01GALI_EMORY:services&section=overview&lang=en
link behavior: open in new tab

- [x] **Add new `eJournals A-Z` link to header and homepage card**
url: placeholder until we build this feature
link behavior: open in same tab

- [x] **Add url to `Articles +` link (sandbox view) to header and homepage card**
url:  https://emory-psb.primo.exlibrisgroup.com/discovery/search?vid=01GALI_EMORY:articles
link behavior: open in new tab

- [x] **Update Databases at Emory link in header and homepage card**
link behavior: to open in new tab 

- [ ] **Update all accordion menu links to open links to the additional research resources in new tabs** (e.g. Research Guides, Emory Digital Collections etc)

See the wireframe below for header link placement:

![Screen Shot 2021-10-01 at 3.13.55 PM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/17a0828d-a7bd-41f6-b29a-d88989307968)

**Comment by eporter23** [comment]
@lovinscari fyi, I created this based on our last wireframe meeting but let me know if this isn't ready for Backlog.

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/blacklight-catalog/pull/977

![Screen Shot 2021-10-13 at 9.37.14 AM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/ccb65c56-f97f-497b-a148-3aa37868161f)
