### ISSUE TITLE
Configure MARC Fields associated with Keyword Search in header search bar

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#95]
According to the SEND Team, the attached MARC Fields should be associated with a Keyword Search when selected as part of the header search box.

Standard numbers (ISBN, ISSN, UPC, EAN, LCCN, OCLC#, MMSid) see use case below
- 020 – ISBN
- 022 – ISSN
- 010 – LCCN
- 001 – MMSid
- 019, 035 – OCLC #
- 024 – Other Standard Identifier (UPC, ISMN, etc.)
- 028 – publisher number
- 5xx (all note fields are important, but the ones below are essentials)
- 505 – unformatted table of content (2d indicator blank) provides additional topical terms, titles and names that are not included in title or subject fields
- 520 – Summary – provides additional topical terms that are not included in title or subject fields 
- 511 -  Participant or Performer Note (used in media cataloging for actors, etc., not all names are traced in 7xx)
- 508 - Creation/Production Credits Note (used in media cataloging for directors, producers, directors of photography, etc., not all names are traced in 7xx)
- 590 Local note 

See notes 1,2, and 3 in [the figma wireframe](https://www.figma.com/file/ocSo3KytI6GgwjalSVAmE1/Blacklight-Wireframes?node-id=1%3A119)

**Comment by rotated8** [comment]
Do we really want all of the table of contents indexed into a facet? It seems like there'd be a bunch of junk in there.

**Comment by rotated8** [comment]
Are these in order of relevance?

**Comment by eporter23** [comment]
@lovinscari if I'm reading this correctly, if a user executes a keyword search, they cannot search by title, author or subjects? Since "keyword" is the default search option,it seems like there ought to be some other commonly searched fields in this list? I would imagine most users would simply enter a title or author and then hit search (and may not even notice the drop down options).

**Comment by bwatson78** [comment]
@eporter23 I noticed the same thing. The only reason I didn't bring this up is because the 5xx fields seem to contain alot of the title, author and subject details.

**Comment by eporter23** [comment]
@lovinscari @bwatson78 I would assume that keyword search is like "Common Fields" in Lux (a set of commonly searched fields but not exhaustive), but also contains the specific list of fields in this ticket. But if that is not the case, it would be good to confirm with stakeholders.

**Comment by bwatson78** [comment]
Every option in the search bar relies on a list of fields it should search from.

**Comment by bwatson78** [comment]
PR for the stated configuration: https://github.com/emory-libraries/blacklight-catalog/pull/117

If you'd like me to update the fields, just let me know and I'll put a hold on anyone approving/merging this work until it's updated.

Proof that Keyword is now the option in the search bar:
![Screen Shot 2021-01-07 at 10.39.47 AM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/56d8db8e-fac7-44fa-ad48-8dc5a5f8adb1)

@lovinscari A separate ticket to change the option's label isn't necessary. No front-end work is needed to alter the labels (unless we're talking about size, color, position on page, etc.). It can all be done in the back-end.

**Comment by devanshu-m** [comment]
![image.png](https://images.zenhubusercontent.com/5c12bc2dd3542818d52aa3a0/509617a5-5e9c-4662-a8bc-54042d2ac2c6)


Keyword seems to be working. I searched with a specific ISBN.
