### ISSUE TITLE
Implement new eJournals A-Z search/browse form page

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/blacklight-catalog#955]
Story: as a faculty researcher, I want to jump quickly into a search or browse interface focused on e-journals, so that I can get to the online title I want without a lot of additional clicks or search refinements.

The SEND team reviewed multiple options related to browsing and browse search and the majority of feedback received indicated this type of eJournals-centric interface is heavily used in Primo. This was also corroborated with an analytics review.

This mockup builds on our existing Title Starts With A-Z menu.

Wireframe:
- [eJournals A-Z static form page](https://docs.google.com/drawings/d/1XAwee6kNSqJCQ96LJQottCxv0VWTLxIffHrO-cDaAkE/edit)

Note: for the title field being searched, we may need to identify a much narrower set of title fields or a single field to search against compared to our basic title search fields. Short e-journal titles such as _Blood_, _Vaccine_, _Gut_, _Cell_, and _Nature_ are requiring a lot of wading through results to get to even if the exact phrase is searched by title and wrapped in quotes.  

Example of basic Title search for online journal "Nature" (poor result matching) :
https://blackcat-test.library.emory.edu/?f%5Bformat_ssim%5D%5B%5D=Journal%2C+Newspaper+or+Serial&f%5Bmarc_resource_ssim%5D%5B%5D=Online&q=%22Nature%22&search_field=title&sort=title_ssort+asc%2C+pub_date_isim+desc

SOLR and Indexing
- Implement new field `title_precise_tesim` ([see metadata worksheet for mapping notes](https://docs.google.com/spreadsheets/d/1jSqgNd6HnVJdJMrrShAofkmK8uGgHGdlKODmZOL5NfY/edit#gid=1979033236))

**Comment by lovinscari** [comment]
Emily has created a new ticket for revisions.
