### ISSUE TITLE
Converting Primo Search Scopes to Primo VE

### ISSUE THREAD

**Issue by libdgg** [emory-libraries/blacklight-catalog#956]
Confirm the mapping work that Ex Libris said (in the 2021-10-06 meeting) we could start at any time, is part of [the Primo VE, Go VE documentation.](https://knowledge.exlibrisgroup.com/Primo/Product_Documentation/Go_VE/Step_3%3A_Configuration/020Go_VE%3A_Converting_Primo_Scopes_to_Primo_VE).

See also [Go VE: Converting Views in Primo to Primo VE](https://knowledge.exlibrisgroup.com/Primo/Product_Documentation/Go_VE/Step_3%3A_Configuration/030Go_VE%3A_Moving_Views_in_Primo_to_Primo_VE/010Go_VE%3A_Converting_Views_in_Primo_to_Primo_VE)

Diagram the two distinct flows we have been talking about (services vs CDI).

Identify and implement the mapping work (detail this further when the ticket is assigned).

**Comment by libah** [comment]
There are two views now, entitled services and articles. The searcg scope for the services view is the library catalog, the searcg scope for the articles view is CDI only. 

articles: https://emory.primo.exlibrisgroup.com/discovery/search?vid=01GALI_EMORY:articles
services: https://emory.primo.exlibrisgroup.com/discovery/search?vid=01GALI_EMORY:services

**Comment by eporter23** [comment]
@libah @lovinscari after the meeting with ExLibris, did we also want to add the search cope of CDI to the services view in case of misc. redirects, saved searches, bookmarks etc?

**Comment by lovinscari** [comment]
@eporter23 - I think that is a good point. I will submit a new ticket for this work.
