### ISSUE TITLE
Journal Title Search - Search Results

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#96]
As an end user, I would like to see all related journal titles when conducting a Title Search as part of a Global Search entry and entering part of a journal title such as "Science."

**Comment by lovinscari** [comment]
@laura-ake - Can you please provide better examples of similar journal titles and perhaps detail how the search would take place? For example, if the user selects title, and entered the word science, I am assuming there would be results beyond Journal Titles so we might need to change this to a faceted search instead of basic search?

**Comment by laura-ake** [comment]
@lovinscari Just to let you know, I'm still working on this.  "Related journal titles" is very complex, and we may need more stakeholder and cataloging input on what we would try to accomplish.  I've written the "article" about it, I'm just looking for examples ("Science" is an amazing case but you want more),  I think having the Resource Type facet available and choosing "journal" before (or after) entering the basic search will need to be a first step.

**Comment by laura-ake** [comment]
@lovinscari looks like this was linked to wrong STORY?

Here's link to long writeup - in OneDrive https://emory-my.sharepoint.com/:w:/g/personal/liblna_emory_edu/Ec_kBKv7p3VLjW8i3NUMQEsB-_c53JTkZ980kDyNhj44uw?e=xOvUCz

**Comment by lovinscari** [comment]
I believe this has been addressed through other search related tickets and single item display. We can also test this as part of functional testing.
