### ISSUE TITLE
Display call numbers on search results and single item view pages

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/blacklight-catalog#960]
_As a keyword searcher, I want to see the call number for an item that I have searched for, so that I can be sure my call number search has matched the right records_

Mockups:

[Search results](https://docs.google.com/drawings/d/17cIxKSd7U0sj2eAg6JdngRwSAUBxBnDMYBNJJDqBml8/edit)

- Display the local_call_number_tesim field with a label of "Call Number" as shown in the mockup
- If multiple call numbers exist, sort them ascending and list each on a new line

[Single Item view](https://docs.google.com/drawings/d/1EsDxlPDB9tpV7Oa6fh9Zeg6krYn5vf3pSmKuL64nIoc/edit)

- Display the local_call_number_tesim field with a label of "Call Number" as shown in the mockup
- If multiple call numbers exist, sort them ascending and list each on a new line

**Comment by eporter23** [comment]
@lovinscari creating as a placeholder

**Comment by eporter23** [comment]
@bwatson78 @lovinscari I think this looks great. My test case is this one: https://blackcat-arch.library.emory.edu/?utf8=✓&search_field=title&q=%22walking+with+the+wind%22

**Comment by lovinscari** [comment]
Looks great!
