### ISSUE TITLE
Add Chicago citation style to "Cite" options

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/blacklight-catalog#961]
This ticket follows work already completed for adding MLA and APA styles to the "Cite" option on the single record view page. 

Notes from Cari:
The [notes and bibliography system](https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.chicagomanualofstyle.org%2Ftools_citationguide%2Fcitation-guide-1.html&data=04%7C01%7Ceporter%40emory.edu%7C494eee9a09e546cb3fa708d9833ebc16%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637685127727540381%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=ANNG0pzQkyy%2BhosvK%2BZ4hrP%2BWU8HVRdkSue8m7iiT3U%3D&reserved=0) is preferred by many working in the humanities—including literature, history, and the arts. In this system, sources are cited in numbered footnotes or endnotes. Each note corresponds to a raised (superscript) number in the text. Sources are also usually listed in a separate bibliography. The notes and bibliography system can accommodate a wide variety of sources, including unusual ones that don’t fit neatly into the author-date system.

**Style guides:**

Chicago Manual of Style: https://www.chicagomanualofstyle.org/tools_citationguide/citation-guide-1.html

Book: https://owl.purdue.edu/owl/research_and_citation/chicago_manual_17th_edition/cmos_formatting_and_style_guide/books.html

Journal: 
https://owl.purdue.edu/owl/research_and_citation/chicago_manual_17th_edition/cmos_formatting_and_style_guide/periodicals.html

**Examples:**
Last name, First name. _Title of Book_. Place of publication: Publisher, Year of publication.

**Book:**
Kerouac, Jack. _The Dharma Bums_. New York: Viking Press, 1958.

**eBook:**
Melville, Herman. _Moby-Dick; or, The Whale._ New York: Harper & Brothers, 1851. http://mel.hofstra.edu/moby-dick-the-whale-proofs.html.

**Thesis/dissertation:**
Rutz, Cynthia Lillian. “King Lear and Its Folktale Analogues.” PhD diss., University of Chicago, 2013.

**SOLR fields to use (as used in other Cite styles, e.g. MLA):**

- `author_ssim` [Author]
- `title_citation_ssi` [documented as used for citations; confirm if this is used vs. title_tesim]
- `title_tesim` [also documented for citation usage; confirm which one is used]
- `published_tesim` [Publisher Name]
- `publisher_location_ssm` [Publisher Location]
- `pub_date_isim` [Publication Date]
- `other_standard_ids_tesim` [for DOIs]

**Comment by eporter23** [comment]
@lovinscari writing this up as a placeholder

**Comment by lovinscari** [comment]
Moving back to new issues as an enhancement for now.

**Comment by abelemlih** [comment]
Deployed in v1.6.0

**Comment by eporter23** [comment]
@abelemlih I did some testing on this using various examples from this page: https://www.chicagomanualofstyle.org/tools_citationguide/citation-guide-1.html
In general, the formatting looks good but we seem to have some mapping/data issues in a few places.

This record has a DOI but the citation also includes another type of identifier (we only want the DOI component). The author entry also shows ", and author".  https://blackcat-test.library.emory.edu/catalog/9937313645402486

Here is another example of the ", and author" being added. It looks like the $e relator term is getting included, which we don't want. https://blackcat-test.library.emory.edu/catalog/990035853090302486 

This record is missing the publication information: https://blackcat-test.library.emory.edu/catalog/990018128730302486

This record omits the publication year. It's populated in SOLR and the other two styles are including it. https://blackcat-test.library.emory.edu/catalog/9937307669402486

**Comment by abelemlih** [comment]
@eporter23 thank you for your feedback! I will look into the issues above and add fixes in a new PR.

**Comment by abelemlih** [comment]
@eporter23 I opened a new PR with fixes for all the issues above: https://github.com/emory-libraries/blacklight-catalog/pull/1295

Once approved and merged, I will release the changes to the testing instance.

**Comment by abelemlih** [comment]
@eporter23 these enhancements were released to Test (v1.8.0) and are ready for testing!

**Comment by eporter23** [comment]
Changes look great @abelemlih!

**Comment by tclayton33** [comment]
Deployed Dec 15, 2022
