### ISSUE TITLE
Update "services" view styling and configs in Production Primo VE

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/blacklight-catalog#962]
Since we have been working in sandbox, we need to ensure the production view is in sync.

- [x] Create a view named services if it does not already exist
- [x] Upload current CSS package
- [x] Test view functionality in production

**Comment by eporter23** [comment]
@libdgg @lovinscari adding this ticket to ensure we refresh the production views. Should we target this work for the current sprint?

**Comment by libah** [comment]
There is now a "services" view in production, which has been updated with the styling from the services view in sandbox. Just started testing.
