### ISSUE TITLE
BUG: More Options on show page is broken 

### ISSUE THREAD

**Issue by bwatson78** [emory-libraries/blacklight-catalog#968]
Since updating the verbiage of Marc Resource Type, the logic behind delivering More Options on the show page are broken since the mapping isn't finding the new values.

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/blacklight-catalog/pull/970

No screenshots necessary.

**Comment by eporter23** [comment]
@bwatson78 @lovinscari This looks good so far in test. I checked all the values that have an "or" in them which used to be a slash.

**Comment by lovinscari** [comment]
Looks good!
