### ISSUE TITLE
SPIKE: Produce preliminary report for outliers in publication date field

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#97]
As a product owner, I would like to see a report  once all data has been harvested into Solr to determine any outliers or inconsistencies in the creation date field to determine any corrections needed in the data before work on Facets and a possible date slider begins.

- [x] Outliers for creation date would be looking at MARC Fields 008, 260, 264 that have the year in any format other than a three digit or four digit format.  

- [ ] The report should be human readable as it will be shared with members of the SEND Team and CATACOM so that data can be corrected in Alma. 

Discussed at planning - we will timebox. 
See also [OCLC 008 reference about dates](https://www.oclc.org/bibformats/en/fixedfield/dates.html) and [Laura's notes about 008 dates](https://app.zenhub.com/workspaces/blacklight-catalog-5f5f84a8a6d29939a0bc5d78/issues/emory-libraries/blacklight-catalog/102) which appear to be more uniformly formatted.

> "Dates of production, publication, distribution, manufacture, or copyright, as specified by the code in DtSt. Dates represents two MARC 21 fixed-field elements: Date 1 and Date 2. Each date has four positions usually coded with digits..."

**Comment by lovinscari** [comment]
@rotated8 - Can you please review the acceptance criteria to see if this aligns with your expectations from our discussion during Ops Meeting on 12/14?

**Comment by eporter23** [comment]
@cari we are assuming this is focused on publication date ("creation" was causing some confusion) and that this relates to the Publication Date facet.

**Comment by eporter23** [comment]
Discussed on 12/17 - we will work on the current Blacklight Test Set initially and then create another ticket for a full run later.

**Comment by eporter23** [comment]
Note from Laura A: "Generally, 008 entries will be better than 260 or 264 which only semi-formatted.  I'll try to fish out the exceptions and note them in the ticket.  I think Primo has a routine "Format Date" ...

**Comment by mlooney** [comment]
report available here:

https://emory.box.com/s/nqt44bv0s9twe0zobd4qqj7tw3p1ie1n


Summary: 

Lisa produced a list of all available 008 , 260c, 264c & 263c fields in the Alma

008 field: was able to parse a surprising proportion of 008 fields, but did find a few bad records which have been forwarded to cataloging

260c, 264c, 263:  biggest issue was missing or empty data, but was able to get around some of the more common strangeness to produce EDTF compatible dates. some work was done to convert invalid EDTF dates to valid dates i.e [198-?] (invalid combination of determinacy indicators etc)

**Comment by lisahamlett** [comment]
McClain's report looks good.  I will run those MMSIDs back through Alma and see what user-friendly info I can get for the catalogers to evaluate.

**Comment by lisahamlett** [comment]
Here is the user-friendly report for the catalogers.  Each field issue is in a different tab.
[https://app.zenhub.com/files/295449627/79d8bb4c-eab1-483c-9675-c4d84420f38d/download](https://app.zenhub.com/files/295449627/79d8bb4c-eab1-483c-9675-c4d84420f38d/download)

I'm also working on the full list of 008 errors because I think there are a bunch of false positives in there.

**Comment by lisahamlett** [comment]
Of the 132,316 008 errors, 105,187 are brief, suppressed, or deleted records.
The first tab lists the 27,129 active records with problematic 008s.  I dumped everything else into the second tab.
[https://app.zenhub.com/files/295449627/327336ae-cf7e-4461-b07d-0102a4b350c0/download](https://app.zenhub.com/files/295449627/327336ae-cf7e-4461-b07d-0102a4b350c0/download)

**Comment by lisahamlett** [comment]
This ticket is ready to be reviewed and closed.
