### ISSUE TITLE
Change eJournals A-Z link in Services view: Links section: sandbox only

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/blacklight-catalog#983]
We need to update the eJournals A-Z link in the Services view so that it no longer points to Primo. This ticket is for the sandbox only.

![Screen Shot 2021-10-13 at 2.49.44 PM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/6b9df609-4aa4-47ad-8250-eefca2b2ae17)

Separate ticket #984 exists for production, because we don't want to change anything that would impact discovery prematurely.

**Comment by libah** [comment]
I changed the link to ejournals to now go to: https://search.libraries.emory.edu/ejournals
