### ISSUE TITLE
Change link to ejournals A-Z from services and articles views: production 

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/blacklight-catalog#984]
We need to update the eJournals A-Z link in the Services view so that it no longer points to Primo.

**To discuss before building:** we need to make sure this link does not change production behavior until we want it too.

![Screen Shot 2021-10-13 at 2.49.44 PM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/6b9df609-4aa4-47ad-8250-eefca2b2ae17)

**Comment by kairosmix** [comment]
Changed the link this morning around 10:00 am.
