### ISSUE TITLE
Draft of the Blacklight change request to Change Advisory Board

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#992]
Per @libdgg  slack message - we will need to submit a change request to the Change Advisory Board. 

Review the [[change draft](https://emory-my.sharepoint.com/:w:/r/personal/rmetz_emory_edu/Documents/LTDS%20Shared%20Documentation/Projects/Project%20Documentation/Blacklight%20Discovery%20Layer%20Phase%201/Scrum%20Team/Work%20Planning/2021-Blacklight-CAB-Request-Planning.docx?d=w4f0de80a6c004f68b92a66456dfcaf3b&csf=1&web=1&e=xspd6y)] and check the box next to your user id indicating your approval by 7 am EST, 10/25/22

https://emory-my.sharepoint.com/:w:/r/personal/rmetz_emory_edu/Documents/LTDS%20Shared%20Documentation/Projects/Project%20Documentation/Blacklight%20Discovery%20Layer%20Phase%201/Scrum%20Team/Work%20Planning/2021-Blacklight-CAB-Request-Planning.docx?d=w4f0de80a6c004f68b92a66456dfcaf3b&csf=1&web=1&e=xspd6y

- [x] @rotated8 
- [x] @AGCooper 
- [x] @jcrompton42 
- [x] @tmiles2 
- [x] @lovinscari  

Once approved, @libdgg will submit to the CAB in order to receive approval for production launch at least 3 weeks prior to launch. Target date to submit to CAB is no later than 12/1/2021 in order to meet the CAB deadlines.

This ticket has been updated to cover only the draft of the document. A new ticket will be used for internal approval of the draft for me to submit to CAB.

**Comment by libdgg** [comment]
@tmiles2 @lovinscari closing this with an update to the scope of the ticket for drafting the change request only. I will create a new ticket for approving the change request with this team which will indicate it is ready for CAB.
