### ISSUE TITLE
Spike/Placeholder - Review navigation and wording of "Return to Library Search" on Services Page View

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/blacklight-catalog#997]
Some users from UAT #3 reported confusion about the expectation of "Return to Library Search" from the Services Page View as they assumed it would take them back to their search as opposed to the Library Search Home Page. This will be discussed in the next wireframes meeting.

**Comment by eporter23** [comment]
[Mockup approved](https://docs.google.com/drawings/d/1MI58w6gKpWBubguY2KoyZy0MJXHfA8sZq-K3oHq8L-A/edit) and changes implemented on Services and Articles views.
